### ISSUE TITLE
cannot use schematics on latest plotsquared

### ISSUE THREAD

**Issue by Twi5TeD** [IntellectualSites/PlotSquared#1005]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: http://hastebin.com/hujenudire plotsquared version 3.2.26
http://hastebin.com/uleboheraf plotsquared version 3.3.1

**Description of the problem:**
when claiming a plot i get a message saying failed to generate  schematic but if i go back to an older version of plotsquared it works fine

**How to replicate**:
use version 3.3.1 and paste a schematic it will work fine try version 3.2.26 it will give the message
Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
> when claiming a plot i get a message saying failed to generate schematic but if i go back to an older version of plotsquared it works fine
--> It doesnt work in 3.3.1 but it does work in 3.2.26

> use version 3.3.1 and paste a schematic it will work fine try version 3.2.26 it will give the message
--> It works in 3.3.1 but it does not work in 3.2.26

Would you mind to elaborate a little bit more, your statements seem to stultify oneself.
Also, what message do you get when it fails?

**Comment by Twi5TeD** [comment]
[15:01:57 INFO]: F64_Rx issued server command: /plot auto
[15:01:57 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotSquared v3.3.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[prison.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[prison.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[prison.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [prison.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [prison.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [prison.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [prison.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [prison.jar:git-Spigot-e4d4710-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [prison.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [prison.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [prison.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [prison.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [prison.jar:git-Spigot-e4d4710-e1ebe52]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
at com.intellectualcrafters.plot.object.Plot.claim(Plot.java:1313) ~[?:?]
at com.intellectualcrafters.plot.commands.Auto.onCommand(Auto.java:193) ~[?:?]
at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:47) ~[?:?]
at com.plotsquared.general.commands.Command.execute(Command.java:343) ~[?:?]
at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:226) ~[?:?]
at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:159) ~[?:?]
at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:26) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[prison.jar:git-Spigot-e4d4710-e1ebe52]
... 15 more
also when doing plot claim on a plot the schematics does get pasted https://gyazo.com/a2b13c999f0b8189b5e0bed2fbede22b 
https://gyazo.com/aea14f8273d301b047cbe1eb26ea1332
debug
http://hastebin.com/raw/emaposonon

**Comment by manuelgu** [comment]
Please update to [3.3.3](https://github.com/IntellectualSites/PlotSquared/releases/tag/v3.3.3) and see if it still occurs.

**Comment by Twi5TeD** [comment]
when i do plot auto on the newest version of plots the schematic doesn't paste
 if i go back  3.2.26 it works fine i tried 3.3.3 this morning still was the same

**Comment by MattBDev** [comment]
Generate a new error log using 3.3.3 so I can traceback the error in my IDE and find a fix

**Comment by Twi5TeD** [comment]
when i get on pc ill re add the new one and try

**Comment by Twi5TeD** [comment]
latest update 3.3.3

when doing plot auto 

/plot auto
[17:58:27 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotSquared v3.3.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
        at com.intellectualcrafters.plot.object.Plot.claim(Plot.java:1304) ~[?:?]
        at com.intellectualcrafters.plot.commands.Auto.onCommand(Auto.java:172) ~[?:?]
        at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27) ~[?:?]
        at com.plotsquared.general.commands.Command.execute(Command.java:332) ~[?:?]
        at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:207) ~[?:?]
        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:140) ~[?:?]
        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:27) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        ... 15 more

when doing plot claim on a plot i get failed to paste  the schematic

http://hastebin.com/raw/welukihute
latest debugpaste

**Comment by boy0001** [comment]
Duplicate / Fixed

**Comment by Twi5TeD** [comment]
is there a link to a fixed  version?

**Comment by manuelgu** [comment]
@Twi5TeD http://ci.xephi.fr/job/PlotSquared/

**Comment by Twi5TeD** [comment]
https://gyazo.com/0b6ee289dc330d5ef3d50ff808b44764 still getting the same message
debug http://hastebin.com/uxoyibeqob

**Comment by boy0001** [comment]
>     schematic:
      file: PlotWorld
      on_claim: true
      specify_on_claim: false
      schematics: []

Can you try specifying the whole filename? e.g. PlotWorld.schematic

**Comment by Twi5TeD** [comment]
schematic:
      file: PlotWorld
      on_claim: true
      specify_on_claim: false
      schematics: []

https://gyazo.com/bdb9e8aea9b6c9ab940817babf3ce94f

**Comment by manuelgu** [comment]
```
schematic:
  file: PlotWorld.schematic
  on_claim: true
  specify_on_claim: false
  schematics: []
```
Try this

**Comment by Twi5TeD** [comment]
didnt work same message

**Comment by manuelgu** [comment]
@Twi5TeD How do you reload the plugin?

**Comment by Twi5TeD** [comment]
plot reload

**Comment by Twi5TeD** [comment]
also tried restarting the server still the same

**Comment by boy0001** [comment]
```YML
schematics:
  save_path: /var/www/schematics
```
Change to
```YML
schematics:
  save_path: schematics
```

**Comment by Twi5TeD** [comment]
thanks that worked
