### ISSUE TITLE
error on clear

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1006]
using dev build from today
```
[23:51:52 INFO]: [ExpireManager] Deleted expired plot: plotme_default;-5;-5 : 47 - 47
[23:51:52 INFO]:  - Area: plotme_default
[23:51:52 INFO]:  - Owner: CaptainHorrible
[23:51:52 WARN]: java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.List
[23:51:52 WARN]:        at com.plotsquared.bukkit.util.block.FastQueue_1_9.execute(FastQueue_1_9.java:156)
[23:51:52 WARN]:        at com.plotsquared.bukkit.util.block.SlowQueue.next(SlowQueue.java:71)
[23:51:52 WARN]:        at com.intellectualcrafters.plot.util.SetQueue$1.run(SetQueue.java:28)
[23:51:52 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58)
[23:51:52 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[23:51:52 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:819)
[23:51:52 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404)
[23:51:52 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720)
[23:51:52 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619)
[23:51:52 WARN]:        at java.lang.Thread.run(Thread.java:745)
[23:51:52 WARN]: java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.List
[23:51:52 WARN]:        at com.plotsquared.bukkit.util.block.FastQueue_1_9.execute(FastQueue_1_9.java:156)
[23:51:52 WARN]:        at com.plotsquared.bukkit.util.block.SlowQueue.next(SlowQueue.java:71)
[23:51:52 WARN]:        at com.intellectualcrafters.plot.util.SetQueue$1.run(SetQueue.java:28)
[23:51:52 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58)
[23:51:52 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[23:51:52 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:819)
[23:51:52 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404)
[23:51:52 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720)
[23:51:52 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619)
[23:51:52 WARN]:        at java.lang.Thread.run(Thread.java:745)
[23:51:52 WARN]: java.lang.ClassCastException: java.util.HashSet cannot be cast to java.util.List
[23:51:52 WARN]:        at com.plotsquared.bukkit.util.block.FastQueue_1_9.execute(FastQueue_1_9.java:156)
[23:51:52 WARN]:        at com.plotsquared.bukkit.util.block.SlowQueue.next(SlowQueue.java:71)
[23:51:52 WARN]:        at com.intellectualcrafters.plot.util.SetQueue$1.run(SetQueue.java:28)
[23:51:52 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58)
[23:51:52 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[23:51:52 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:819)
[23:51:52 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404)
[23:51:52 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720)
[23:51:52 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619)
[23:51:52 WARN]:        at java.lang.Thread.run(Thread.java:745)

```

**Comment by boy0001** [comment]
Fixed
