### ISSUE TITLE
Error - execute command

### ISSUE THREAD

**Issue by piesio98** [IntellectualSites/PlotSquared#1044]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: 
http://hastebin.com/sepebayisa

**Description of the problem:**

When i type command for expample /p add , in the console and in the game i see an error
(without selecting a player). When i select a player, command works fine. I want to see something like this when i don't type player:

Usage /p add <player>

ERROR:
```
[21:08:10] [Server thread/INFO]: piesio98 issued server command: /p add
[21:08:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'p' in plugin PlotSquared v3.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.intellectualcrafters.plot.commands.Add.onCommand(Add.java:67) ~[?:?]
	at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:47) ~[?:?]
	at com.plotsquared.general.commands.Command.execute(Command.java:343) ~[?:?]
	at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:226) ~[?:?]
	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:159) ~[?:?]
	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:26) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[fixspigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	... 13 more
```

**Comment by manuelgu** [comment]
Please update to plugin to version 3.3.3 and see if it still occurs.

**Comment by MattBDev** [comment]
Fixed already. not sure when it was fixed but when testing 3.4.0 it was fixed.

**Comment by EvilOlaf** [comment]
Just noticed this exception at `p unlink n`
```
[16:12:23] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotSquared v3.3.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.intellectualcrafters.plot.commands.Unlink.onCommand(Unlink.java:46) ~[?:?]
        at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27) ~[?:?]
        at com.plotsquared.general.commands.Command.execute(Command.java:332) ~[?:?]
        at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:207) ~[?:?]
        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:140) ~[?:?]
        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:27) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        ... 15 more
```
with version 3.3.3

As you stated this should be fixed already it is purely FYI.

**Comment by MattBDev** [comment]
@EvilOlaf I'm not gonna re-open but I did make a note of this. ;)

**Comment by EvilOlaf** [comment]
That's all I wanted :P
