### ISSUE TITLE
SCHEMATIC NOT PASTING!

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [IntellectualSites/PlotSquared#1087]
```
org.bukkit.command.CommandException: Unhandled exception executing command 'p' in plugin PlotSquared v3.3.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-ccb6016-f92e01b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-ccb6016-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot.jar:git-Spigot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot.jar:git-Spigot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-ccb6016-f92e01b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-ccb6016-f92e01b]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
        at com.intellectualcrafters.plot.object.Plot.claim(Plot.java:1304) ~[?:?]
        at com.intellectualcrafters.plot.commands.Auto.onCommand(Auto.java:172) ~[?:?]
        at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27) ~[?:?]
        at com.plotsquared.general.commands.Command.execute(Command.java:332) ~[?:?]
        at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:207) ~[?:?]
        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:140) ~[?:?]
        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:27) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-ccb6016-f92e01b]
        ... 15 more
```

I can paste the schematic with /p paste islandv3, but island is not pasting when a player claim a plot
Here is my config:

```
version: 3.3.3
platform: Bukkit
clear:
  'on':
    ban: false
  auto:
    calibration:
      variety: 0
      changes_sd: 1
      faces: 0
      data_sd: 0
      air: 0
      air_sd: 0
      faces_sd: 0
      data: 0
      variety_sd: 0
      changes: 1
    days: 7
    clear-interval-seconds: 120
    threshold: 1
    enabled: true
    confirmation: false
  fastmode: false
confirmation:
  clear: true
  delete: true
  unlink: true
  setowner: true
UUID:
  offline: false
  force-lowercase: false
cache:
  permissions: true
  ratings: true
chunk-processor:
  auto-trim: false
  auto-unload: false
  enabled: false
  max-blockstates: 4096
  experimental-fast-async-worldedit: false
  max-entities: 512
  disable-physics: false
worldedit:
  require-selection-in-mask: true
  max-volume: 500000
  enable-for-helpers: false
  queue-commands: false
  max-iterations: 1000
  blacklist:
  - cs
  - .s
  - restore
  - snapshot
  - delchunks
  - listchunks
schematics:
  save_path: schematics/
web:
  url: http://empcraft.com/plots/
  server-ip: your.ip.here
approval:
  done:
    required-for-download: false
    restrict-building: false
    counts-towards-limit: false
  ratings:
    require-done: false
chat:
  fancy: true
console:
  color: true
kill_road_mobs: true
merge:
  remove-terrain: true
mob_pathfinding: true
plotme-alias: false
plotme-convert:
  enabled: true
  cache-uuids: false
global_limit: false
update-notifications: true
metrics: true
comments:
  notifications:
    enabled: false
protection:
  redstone:
    disable-unoccupied: false
    disable-offline: false
  piston:
    falling-blocks: true
teleport:
  on_login: false
  delay: 0
claim:
  max-auto-area: 4
uuid:
  use_sqluuidhandler: false
  read-from-disk: false
max_plots: 127
bo3:
  save_path: BO3
kill_road_vehicles: false
debug: true
clusters:
  enabled: false
titles: true
worlds:
  MyIsland:
    plot:
      height: 63
      size: 91
      filling:
      - '8:0'
      floor:
      - '8:0'
      bedrock: true
      biome: FOREST
      auto_merge: false
      create_signs: false
    wall:
      block: 0:0
      block_claimed: 0:0
      filling: '166:0'
      height: 62
    road:
      width: 10
      height: 62
      block: 0:0
    event:
      pve: false
      pvp: false
      spawn:
        egg: false
        breeding: false
        custom: true
    home:
      default: side
      allow-nonmembers: false
    schematic:
      specify_on_claim: false
      on_claim: true
      file: islandv3
      schematics: []
    economy:
      prices:
        merge: 100.0
        sell: 75.0
        claim: 100.0
      use: false
    chat:
      enabled: false
    limits:
      max-members: 128
    world:
      max_height: 256
      gamemode: survival
      min_height: 1
      border: false
    natural_mob_spawning: true
    flags: {}
    mob_spawner_spawning: false
```

**Comment by QUIQUELHAPPY** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1035
