### ISSUE TITLE
Custom flag with new flag system

### ISSUE THREAD

**Issue by diecode** [IntellectualSites/PlotSquared#1096]
This is not a bug, just a developer question.

Can I create custom flags with new Flag system? If yes, can you write to me a short example please? Unfortunately I must modify my plugin which hooking PlotSquared, because Flag system changed.

Thanks.

**Comment by MattBDev** [comment]
I'll get back to you on this when I have time to write a detailed explanation.

**Comment by diecode** [comment]
Great, I am waiting then :)

**Comment by MattBDev** [comment]
I should have time at the end of this week to write up on it.

**Comment by MattBDev** [comment]
Currently not implemented but will be ready for v3.4.0

**Comment by MattBDev** [comment]
@diecode it would be awesome if you showed me the code you currently have for a custom flag, that way I can try to test out the new system and make sure it works.

**Comment by boy0001** [comment]
https://gist.github.com/MattBDev/78746f19f0613f3151c0526de6c98d74

**Comment by diecode** [comment]
I used the AbstractFlag class, but it removed. My plugin is broken, I tested.

**Comment by MattBDev** [comment]
The new Flag system is based around the `FlagManager` and the `Flag` object. All flags such as `BooleanFlag` or `IntegerFlag` extend from the `Flag` object. The `Flag` object can be thought of as an enum but it's different than an Enum because it allows you to parse data with it. I am writing javadocs for the FlagManager, Flags, and Flag classes. Once those are finished it should be really straight forward.

**Comment by diecode** [comment]
I tried this:

1. `LongFlag DONE_FLAG = new LongFlag("hdone");`
2. `Flags.registerFlag(DONE_FLAG);`
3. `plot.setFlag(DONE_FLAG, System.currentTimeMillis() / 1000);`

It is working, but when I restart the server, then my custom flag is losing, not saved.

Is it my fault?

**Comment by MattBDev** [comment]
It isn't your fault. It is my fault. I need to add the code in the database stuff to make sure custom flags will save or even be created before registered.

**Comment by diecode** [comment]
Ok, then please tell me if you committed the changes :) Thanks

**Comment by MattBDev** [comment]
try the newest dev build and let me know if it works

**Comment by MattBDev** [comment]
I made the changes. let me know if it is fixed.

**Comment by diecode** [comment]
I get this:

`java.lang.NullPointerException
        at com.intellectualcrafters.plot.flag.FlagManager.toString(FlagManager.java:107) ~[?:?]
        at com.intellectualcrafters.plot.database.SQLManager.setFlags(SQLManager.java:1964) ~[?:?]
        at com.intellectualcrafters.plot.database.DBFunc.setFlags(DBFunc.java:249) ~[?:?]
        at com.intellectualcrafters.plot.flag.FlagManager.addPlotFlag(FlagManager.java:153) ~[?:?]
        at net.diecode.Architecture.SchematicManager.saveSchematicFile(SchematicManager.java:181) ~[?:?]
        at net.diecode.Architecture.SchematicManager$1$1.run(SchematicManager.java:124) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-8a048fe-5ff377a]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
`

The `net.diecode.Architecture.SchematicManager.saveSchematicFile(SchematicManager.java:181) ` line: `plot.setFlag(SCHEMATIC_FLAG, playerName + "_" + hash + ".zip");`

I registered flag with this in onEnable():

`private static final StringFlag SCHEMATIC_FLAG = new StringFlag("schematic")
`Flags.registerFlag(SCHEMATIC_FLAG);
FlagManager.reserveFlag(SCHEMATIC_FLAG);`

**Comment by MattBDev** [comment]
@diecode Do you think you can come on the IRC so we can chat?

**Comment by diecode** [comment]
Yes, of course. Where?

**Comment by MattBDev** [comment]
@diecode http://webchat.esper.net/?nick=&channels=IntellectualCrafters&fg_color=000&fg_sec_color=000&bg_color=FFF

**Comment by MattBDev** [comment]
Finished custom flags. @diecode has reported that everything is functional in regards to them.
