### ISSUE TITLE
Bug "Could not pass event [...]"

### ISSUE THREAD

**Issue by ChoukiMe** [IntellectualSites/PlotSquared#1106]
Hi !
When I install PlotSquared, I type : /pl and the name "PlotSquared" is in green (enabled). But, when I type : / plot world : this error message appear : "An internal error occured while attempting to perform this command".
I look for a similary error in yours issues messages but I don't fin.
Please help me.
I'm in Spigot 1.9.
(Sorry for my english, I'm french.)

**- Steps :**
- [] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin
```
`[14:26:26 ERROR]: Could not pass event InventoryCloseEvent to PlotSquared v3.3.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-bc01c3a-55b0def]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-bc01c3a-55b0def]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:858) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityPlayer.closeInventory(EntityPlayer.java:853) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityPlayer.die(EntityPlayer.java:457) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity(EntityLiving.java:890) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityHuman.damageEntity(EntityHuman.java:762) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityPlayer.damageEntity(EntityPlayer.java:513) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityMonster.B(EntityMonster.java:68) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityZombie.B(EntityZombie.java:236) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.PathfinderGoalMeleeAttack.e(SourceFile:122) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.PathfinderGoalZombieAttack.e(SourceFile:28) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.PathfinderGoalSelector.a(SourceFile:129) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityInsentient.doTick(EntityInsentient.java:642) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityLiving.n(EntityLiving.java:1903) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityInsentient.n(EntityInsentient.java:487) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityMonster.n(EntityMonster.java:24) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityZombie.n(EntityZombie.java:175) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1759) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityMonster.m(EntityMonster.java:28) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.EntityZombie.m(EntityZombie.java:232) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1605) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.World.g(World.java:1580) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1420) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:628) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
        at com.intellectualcrafters.plot.util.UUIDHandler.getPlayer(UUIDHandler.java:107) ~[?:?]
        at com.plotsquared.bukkit.util.BukkitUtil.getPlayer(BukkitUtil.java:64) ~[?:?]
        at com.plotsquared.bukkit.listeners.PlayerEvents.onInventoryClose(PlayerEvents.java:1809) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-bc01c3a-55b0def]
        ... 32 more
[14:26:26 ERROR]: Could not pass event PlayerMoveEvent to PlotSquared v3.3.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-bc01c3a-55b0def]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-bc01c3a-55b0def]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:579) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-bc01c3a-55b0def]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
        at com.intellectualcrafters.plot.util.UUIDHandler.getPlayer(UUIDHandler.java:107) ~[?:?]
        at com.plotsquared.bukkit.util.BukkitUtil.getPlayer(BukkitUtil.java:64) ~[?:?]
        at com.plotsquared.bukkit.listeners.PlayerEvents.playerMove(PlayerEvents.java:471) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-bc01c3a-55b0def]
        ... 15 more
```
Thanks for your future answer,
Ch.

**Comment by MattBDev** [comment]
Rerun BuildTools. Your server is 157 versions out of date.
