### ISSUE TITLE
/plot claim and /plot auto not working

### ISSUE THREAD

**Issue by Permanently** [IntellectualSites/PlotSquared#1115]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: http://hastebin.com/oxojeyuhel
I'm currently running Spigot 1.9. 

I tried using /plot move once (which didn't work) and now whenever I type /plot auto or /plot claim, this happens:
[09:57:09] [Server thread/INFO]: Permanently issued server command: /plot claim
[09:57:09] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
[09:57:09] [Server thread/WARN]:     at java.lang.String.substring(String.java:1931)
[09:57:09] [Server thread/WARN]:     at com.intellectualcrafters.plot.object.Plot.guessOwner(Plot.java:1950)
[09:57:09] [Server thread/WARN]:     at com.intellectualcrafters.plot.object.Plot.canClaim(Plot.java:1927)
[09:57:09] [Server thread/WARN]:     at com.intellectualcrafters.plot.commands.Claim.onCommand(Claim.java:67)
[09:57:09] [Server thread/WARN]:     at com.intellectualcrafters.plot.commands.Claim.onCommand(Claim.java:34)
[09:57:09] [Server thread/WARN]:     at com.intellectualcrafters.plot.commands.MainCommand.handle(MainCommand.java:450)
[09:57:09] [Server thread/WARN]:     at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:303)
[09:57:09] [Server thread/WARN]:     at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:37)
[09:57:09] [Server thread/WARN]:     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[09:57:09] [Server thread/WARN]:     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[09:57:09] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[09:57:09] [Server thread/WARN]:     at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302)
[09:57:09] [Server thread/WARN]:     at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137)
[09:57:09] [Server thread/WARN]:     at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[09:57:09] [Server thread/WARN]:     at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[09:57:09] [Server thread/WARN]:     at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[09:57:09] [Server thread/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:57:09] [Server thread/WARN]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:57:09] [Server thread/WARN]:     at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[09:57:09] [Server thread/WARN]:     at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716)
[09:57:09] [Server thread/WARN]:     at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[09:57:09] [Server thread/WARN]:     at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655)
[09:57:09] [Server thread/WARN]:     at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554)
[09:57:09] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:745)

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Update PlotSquared
Latest stable dev build:
http://ci.xephi.fr/job/PlotSquared/115/changes
Releases:
https://github.com/IntellectualSites/PlotSquared/releases
