### ISSUE TITLE
Dev Build #115 failing to work

### ISSUE THREAD

**Issue by Permanently** [IntellectualSites/PlotSquared#1119]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: Can not provide, all the commands do not work.

**Description of the problem:**
So I was told to use a dev build since /plot claim and /plot auto didn't work for me, like in my last report. I was linked to dev build #115 (I'm using Spigot 1.9.0) and when loaded, I get these errors:
`[14:13:34] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to PlotSquared v3.4.0-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:568) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at com.intellectualcrafters.plot.util.UUIDHandler.getPlayer(UUIDHandler.java:107) ~[?:?]
	at com.plotsquared.bukkit.util.BukkitUtil.getPlayer(BukkitUtil.java:64) ~[?:?]
	at com.plotsquared.bukkit.listeners.PlayerEvents.playerMove(PlayerEvents.java:480) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	... 15 more
[14:13:34] [Server thread/INFO]: Permanently issued server command: /plot
[14:13:34] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to PlotSquared v3.4.0-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1294) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at com.intellectualcrafters.plot.util.UUIDHandler.getPlayer(UUIDHandler.java:107) ~[?:?]
	at com.plotsquared.bukkit.util.BukkitUtil.getPlayer(BukkitUtil.java:64) ~[?:?]
	at com.plotsquared.bukkit.listeners.worldedit.WEListener.onPlayerCommand(WEListener.java:167) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	... 16 more
[14:13:34] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to PlotSquared v3.4.0-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1294) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at com.intellectualcrafters.plot.util.UUIDHandler.getPlayer(UUIDHandler.java:107) ~[?:?]
	at com.plotsquared.bukkit.util.BukkitUtil.getPlayer(BukkitUtil.java:64) ~[?:?]
	at com.plotsquared.bukkit.listeners.PlayerEvents.playerCommand(PlayerEvents.java:366) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	... 16 more
[14:13:34] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotSquared v3.4.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at com.intellectualcrafters.plot.util.UUIDHandler.getPlayer(UUIDHandler.java:107) ~[?:?]
	at com.plotsquared.bukkit.util.BukkitUtil.getPlayer(BukkitUtil.java:64) ~[?:?]
	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	... 15 more`

**How to replicate**:
Just install dev build #115 on Spigot 1.9 and there you go.

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Can you do a `/plot debugpaste`?

**Comment by boy0001** [comment]
*Can you provide a startup log?

**Comment by Permanently** [comment]
This is what I'm seeing on startup:
`[15:41:34] [Server thread/INFO]: [PlotSquared] Enabling PlotSquared v3.4.0-SNAPSHOT
[15:41:34] [Server thread/INFO]: $1PlotSquared is now enabled
[15:41:34] [Server thread/INFO]: $3[$1P2$3] $2&6Debug Mode Enabled (Default). Edit the config to turn this off.
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: greeting
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: farewell
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: feed
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: heal
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: notify-enter
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: notify-leave
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: item-drop
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: invincible
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: instabreak
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: drop-protection
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: forcefield
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: titles
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: pve
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: pvp
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: no-worldedit
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: redstone
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: misc-cap
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: entity-cap
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: mob-cap
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: animal-cap
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: hostile-cap
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: vehicle-cap
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: music
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: done
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: analysis
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: disable-physics
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: fly
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: explosion
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: mob-place
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: hostile-interact
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: hostile-attack
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: animal-interact
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: animal-attack
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: tamed-interact
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: tamed-attack
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: player-interact
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: misc-interact
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: misc-place
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: misc-break
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: hanging-interact
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: hanging-place
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: hanging-break
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: vehicle-use
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: vehicle-place
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: vehicle-break
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: device-interact
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: place
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: break
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: use
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: blocked-cmds
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: ice-melt
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: block-ignition
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: block-burn
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: fire-spread
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: snow-melt
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: keep
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: gamemode
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: price
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: time
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: weather
[15:41:34] [Server thread/INFO]: [P2]  - Adding flag: description
[15:41:36] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/event/entity/LingeringPotionSplashEvent
[15:41:36] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.registerPlayerEvents(BukkitMain.java:356)
[15:41:36] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:188)
[15:41:36] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:127)
[15:41:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[15:41:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[15:41:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:41:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[15:41:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[15:41:36] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202)
[15:41:36] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522)
[15:41:36] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:41:36] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.event.entity.LingeringPotionSplashEvent
[15:41:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[15:41:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[15:41:36] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[15:41:36] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[15:41:36] [Server thread/WARN]: 	... 11 more`

**Comment by boy0001** [comment]
Try updating spigot.

You are using a very early version of spigot 1.9. LingeringPotionSplashEvent was introduced in spigot 1.9, but you appear to be using a version which doesn't have this yet, which is causing PlotSquared to fail to load.

**Comment by Permanently** [comment]
It's working, thanks! :+1:
