### ISSUE TITLE
Non criticial errors with last few dev versions and 1.9.4  (UUID related)

### ISSUE THREAD

**Issue by frizzbee30** [IntellectualSites/PlotSquared#1122]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

**Description of the problem:**

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

Hi, very minor as the plugin and latest builds seem to be working fairly well with 1.9.4, just been getting an error upon boot up with the builds, and the latest commit of spigot.

More to make you aware, if you aren't already :)

Thanks for a fantastic plugin!!

[09:26:19] [Craft Scheduler Thread - 11/WARN]: Exception in thread "Craft Scheduler Thread - 11" 
[09:26:19] [Craft Scheduler Thread - 11/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.4.0-SNAPSHOT generated an exception while executing task 1951
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.plotsquared.bukkit.uuid.FileUUIDHandler$1.run(FileUUIDHandler.java:187)
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[09:26:20] [Craft Scheduler Thread - 17/INFO]: [Autorank] Config files have been correctly setup!

**Comment by frizzbee30** [comment]
currently using #154

**Comment by MattBDev** [comment]
@frizzbee30 from which website? There is no official dev-build download site and it is important to so we know which commit you are running.

**Comment by boy0001** [comment]
I would guess http://ci.athion.net/job/PlotSquared/ since the build numbers seem to match the timeframe.

**Comment by frizzbee30** [comment]
It is :)

**Comment by boy0001** [comment]
Error doesn't look to be related to any recent changes. It's likely from a corrupt player.dat file.
