### ISSUE TITLE
Deluxe Chat

### ISSUE THREAD

**Issue by random1167** [IntellectualSites/PlotSquared#1184]
updated to 1.10 and deluxe chat 1.10
```

[12:54:30 ERROR]: Could not pass event AsyncPlayerChatEvent to DeluxeChat v1.10.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.jar:git-Spigot-e50d38c-02f4218]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.jar:git-Spigot-e50d38c-02f4218]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar:git-Spigot-e50d38c-02f4218]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.10.jar:git-Spigot-e50d38c-02f4218]
        at net.minecraft.server.v1_10_R1.PlayerConnection.chat(PlayerConnection.java:1273) [spigot-1.10.jar:git-Spigot-e50d38c-02f4218]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1211) [spigot-1.10.jar:git-Spigot-e50d38c-02f4218]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.10.jar:git-Spigot-e50d38c-02f4218]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_77]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NoSuchMethodError: com.intellectualcrafters.plot.object.Plot.getOwners()Ljava/util/HashSet;
        at me.clip.deluxechat.hooks.PlotSquaredHook$1.onPlaceholderRequest(PlotSquaredHook.java:51) ~[?:?]
        at me.clip.deluxechat.placeholders.PlaceholderHandler.setPlaceholders(PlaceholderHandler.java:485) ~[?:?]
        at me.clip.deluxechat.placeholders.PlaceholderHandler.setPlaceholders(PlaceholderHandler.java:434) ~[?:?]
        at me.clip.deluxechat.DeluxeChat.getFancyChatFormat(DeluxeChat.java:993) ~[?:?]
        at me.clip.deluxechat.listeners.AsyncPlayerChatListener.onChat(AsyncPlayerChatListener.java:83) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.jar:git-Spigot-e50d38c-02f4218]
        ... 11 more
```
is that suppose to be Ljava ?

**Comment by manuelgu** [comment]
This is an issue with DeluxeChat. Please contact their authors.

> DeluxeChat expects  HashSet, PlotSquared however returns a Set<UUID> for the Plot#getOwners() method
