### ISSUE TITLE
players dont own there plots anymore

### ISSUE THREAD

**Issue by random1167** [IntellectualSites/PlotSquared#1185]
players dont own there plots anymore
```
 PLOT 4402 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[13:29:39 INFO]: ENTRY 4402 in `plot_helpers` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[13:29:39 INFO]: ENTRY 4402 in `plot_helpers` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[13:29:39 INFO]: ENTRY 4402 in `plot_trusted` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[13:29:39 INFO]: ENTRY 4402 in `plot_trusted` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[13:29:39 INFO]: ENTRY 4402 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[13:29:39 INFO]: [WARNING] Found 313 plots in DB for non existent world; 'vip'.
[13:29:39 INFO]: [WARNING] Found 3233 plots in DB for non existent world; 'plots'.
[13:29:39 INFO]: [WARNING] - Please create the world/s or remove the plots using the purge command
[13:29:39 INFO]: [P2] Metrics enabled.
[13:29:39 INFO]: [P2]  PlotSquared is using online UUIDs
[13:29:39 WARN]: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.server.v1_9_R2.PacketPlayOutMapChunk.<init>(net.minecraft.server.v1_9_R2.Chunk, boolean, int)
[13:29:39 WARN]:        at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getConstructor(ReflectionUtils.java:335)
[13:29:39 WARN]:        at com.plotsquared.bukkit.util.SendChunk.<init>(SendChunk.java:53)
[13:29:39 WARN]:        at com.plotsquared.bukkit.BukkitMain.initPlotQueue(BukkitMain.java:407)
[13:29:39 WARN]:        at com.intellectualcrafters.plot.PS.<init>(PS.java:253)
[13:29:39 WARN]:        at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:127)
[13:29:39 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:29:39 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[13:29:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:29:39 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362)
[13:29:39 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322)
[13:29:39 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:201)
[13:29:39 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
[13:29:39 WARN]:        at java.lang.Thread.run(Thread.java:745)
[13:29:39 WARN]: Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_9_R2.PacketPlayOutMapChunk.<init>(net.minecraft.server.v1_9_R2.Chunk, boolean, int)
[13:29:39 WARN]:        at java.lang.Class.getConstructor0(Class.java:3082)
[13:29:39 WARN]:        at java.lang.Class.getDeclaredConstructor(Class.java:2178)
[13:29:39 WARN]:        at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getConstructor(ReflectionUtils.java:332)
[13:29:39 WARN]:        ... 12 more
[13:29:39 INFO]: [P2] Key: API Location, Value: http://www.intellectualsites.com/minecraft.php
[13:29:39 INFO]: [P2] Key: Kill Road Mobs, Value: false
[13:29:39 INFO]: [P2] Key: Use Metrics, Value: true
[13:29:39 INFO]: [P2] Key: Delete Plots On Ban, Value: false
[13:29:39 INFO]: [P2] Key: DB SQLite Enabled, Value: false
[13:29:39 INFO]: [P2] Key: DB Mysql Enabled, Value: true
[13:29:39 INFO]: [P2] Key: Auto Clear Enabled, Value: true
[13:29:39 INFO]: [P2] Key: Auto Clear Days, Value: 7
[13:29:39 INFO]: [P2] Key: Schematics Save Path, Value: schematics

```
tried updating to 1.10 with great failure...reverting back to 1.9.4 and now plots are sooooo messed up..i got no answers, plots don't below to the owners and some plots are just not claimed when they are ment to be

**Comment by random1167** [comment]
http://hastebin.com/ojoficufiw
plots dp

**Comment by random1167** [comment]
checked my database and there is no other worlds defined only the plots world..when i have "had" others ...this is the second time this has happened we cannot reset our creative server again its just to mean..its nearly 5 my time i will check back in a few hours and i hope someone has a solution

**Comment by manuelgu** [comment]
You upgraded to 3.4.1 of PlotSquared and reverted back to 3.3.3 now.

3.4.1 of PlotSquared completely changed the way the configuration is built. All the world configuration is now in a `worlds.yml`.

Easy fix if you keep backups: Also revert your configuration file to one with the old layout.

**Comment by MattBDev** [comment]
You cannot upgrade to 3.4.1 and revert.

**Comment by random1167** [comment]
what about the players plots?

**Comment by EvilOlaf** [comment]
Restore your backup.
