### ISSUE TITLE
Jar does not contain plugin.yml

### ISSUE THREAD

**Issue by DreamPhreak** [IntellectualSites/PlotSquared#1186]
**Debug paste link**:
Cant post a debug with /plot debugpaste because the plugin breaks on startup. However I do have this from console:
`[15:10:24] [Server thread/ERROR]: Could not load 'plugins/PlotSquared-Core-3.4.1-ae5e15e.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
... 6 more`

**Description of the problem:**
By the looks of it, "Jar does not contain plugin.yml"

**How to replicate**:
Started a new Spigot server (trying to do 1.9.4) (This server is running CraftBukkit version git-Spigot-798f32d-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT))

The first and only plugin I installed was PlotSquared-Core-3.4.1-ae5e15e.jar, got this error message and can't load up the plugin.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
You need to install PlotSquared-Bukkit instead of Core
