### ISSUE TITLE
Error with command alias

### ISSUE THREAD

**Issue by rErEaT** [IntellectualSites/PlotSquared#1206]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

http://hastebin.com/yilefelavi

**Description of the problem:**

[13:56:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotSquared v3.4.1-f5e7d08
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at com.intellectualcrafters.plot.commands.MainCommand$1.run(MainCommand.java:161) ~[?:?]
	at com.intellectualcrafters.plot.commands.MainCommand$1.run(MainCommand.java:132) ~[?:?]
	at com.intellectualcrafters.plot.commands.Trust.execute(Trust.java:63) ~[?:?]
	at com.plotsquared.general.commands.Command.execute(Command.java:336) ~[?:?]
	at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:218) ~[?:?]
	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:132) ~[?:?]
	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	... 15 more

**How to replicate**:

use the command alias

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
Using outdated PlotSquared version, please update.

**Comment by rErEaT** [comment]
lol I updated to 3.4.1 release today

**Comment by manuelgu** [comment]
@rErEaT 3.4.2 is the latest version

https://github.com/IntellectualSites/PlotSquared/releases

**Comment by rErEaT** [comment]
oh, it does not uploaded to spigot
