### ISSUE TITLE
Console spam (ChunkUnloadEvent)

### ISSUE THREAD

**Issue by RikoDEV** [IntellectualSites/PlotSquared#1212]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: sorry, j can't use command

**Description of the problem:**
When I run I see the server console
```
[08:06:21] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to PlotSquared v3.4.3-56000d6
java.lang.StackOverflowError
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_91]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_91]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_91]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_91]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_91]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_91]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_91]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:114) ~[patched_1.10.jar:git-Paper-797]
	at org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:90) ~[patched_1.10.jar:git-Paper-797]
	at org.apache.logging.log4j.core.impl.DefaultLogEventFactory.createEvent(DefaultLogEventFactory.java:49) ~[patched_1.10.jar:git-Paper-797]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:365) ~[patched_1.10.jar:git-Paper-797]
	at org.apache.logging.log4j.core.Logger.log(Logger.java:110) ~[patched_1.10.jar:git-Paper-797]
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:609) ~[patched_1.10.jar:git-Paper-797]
	at org.bukkit.craftbukkit.v1_10_R1.util.ForwardLogHandler.publish(ForwardLogHandler.java:33) ~[patched_1.10.jar:git-Paper-797]
	at java.util.logging.Logger.log(Logger.java:738) ~[?:1.8.0_91]
	at java.util.logging.Logger.doLog(Logger.java:765) ~[?:1.8.0_91]
	at java.util.logging.Logger.log(Logger.java:875) ~[?:1.8.0_91]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:534) ~[patched_1.10.jar:git-Paper-797]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.10.jar:git-Paper-797]
	at net.minecraft.server.v1_10_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:326) ~[patched_1.10.jar:git-Paper-797]
	at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.unloadChunk0(CraftWorld.java:222) ~[patched_1.10.jar:git-Paper-797]
	at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.unloadChunk(CraftWorld.java:212) ~[patched_1.10.jar:git-Paper-797]
	at org.bukkit.craftbukkit.v1_10_R1.CraftChunk.unload(CraftChunk.java:137) ~[patched_1.10.jar:git-Paper-797]
	at com.plotsquared.bukkit.listeners.ChunkListener.unloadChunk(ChunkListener.java:110) ~[?:?]
	at com.plotsquared.bukkit.listeners.ChunkListener.onChunkUnload(ChunkListener.java:146) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor68.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.jar:git-Paper-797]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.jar:git-Paper-797]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.jar:git-Paper-797]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.10.jar:git-Paper-797]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.10.jar:git-Paper-797]
	at net.minecraft.server.v1_10_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:326) ~[patched_1.10.jar:git-Paper-797]
```

**Comment by boy0001** [comment]
Disable auto-trim in the settings.yml
