### ISSUE TITLE
Bugs /p confirm

### ISSUE THREAD

**Issue by IAlekseyI22** [IntellectualSites/PlotSquared#1214]
[Server thread/INFO]: gasp issued server command: /p confirm
[Server thread/WARN]: [PlotSquared] Task #1516062 for PlotSquared v3.4.1-f5e7d08 generated an exception
java.lang.NullPointerException
	at com.intellectualcrafters.plot.commands.MainCommand$1$1.run(MainCommand.java:143) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by MattBDev** [comment]
Use the issue template in the future to report bugs. Also make sure you are using the most up to date PlotSquared version since this issue has been fixed already.
