### ISSUE TITLE
 /plots tp And /plots home  ，The number of cross-border

### ISSUE THREAD

**Issue by yyeerai** [IntellectualSites/PlotSquared#1219]
`[11:07:21] [Server thread/INFO]: lapin_boy issued server command: /plots tp 55555555555
[11:07:21] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plots' in plugin PlotSquared v3.4.3-9fa28e1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.4.jar:git-Paper-773]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-773]
at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-773]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-773]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NumberFormatException: For input string: "55555555555"
at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_91]
at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_91]
at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_91]
at com.intellectualcrafters.plot.commands.Visit.onCommand(Visit.java:47) ~[?:?]
at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27) ~[?:?]
at com.plotsquared.general.commands.Command.execute(Command.java:336) ~[?:?]
at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:220) ~[?:?]
at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:133) ~[?:?]
at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.4.jar:git-Paper-773]
... 15 more

[11:08:10] [Server thread/INFO]: lapin_boy issued server command: /plots home 5555555555555
[11:08:10] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plots' in plugin PlotSquared v3.4.3-9fa28e1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.4.jar:git-Paper-773]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-773]
at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-773]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-773]
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-773]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NumberFormatException: For input string: "5555555555555"
at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_91]
at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_91]
at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_91]
at com.intellectualcrafters.plot.commands.Visit.onCommand(Visit.java:47) ~[?:?]
at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27) ~[?:?]
at com.plotsquared.general.commands.Command.execute(Command.java:336) ~[?:?]
at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:220) ~[?:?]
at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:133) ~[?:?]
at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.4.jar:git-Paper-773]
... 15 more`

**Comment by boy0001** [comment]
> lapin_boy issued server command: /plots tp 55555555555

Isn't a valid location (it's outside the world). Anywho, an error message should now sent to the player.
