### ISSUE TITLE
Merging Plots creates Road bug / NullPointer when claiming

### ISSUE THREAD

**Issue by pedroo21** [IntellectualSites/PlotSquared#1222]
# FIRST BUG - Merging not clearing a part of the road

**Debug paste link**:
![bug](https://cloud.githubusercontent.com/assets/12183954/16358316/662afa40-3b07-11e6-85f6-0ede0606b416.png)

**Description of the problem:**

**How to replicate**:
**(This is how players explained me, apparently it doesn't happen everytime)**
**(It happened to me on the second time I did it)**
(Do this steps in the same circle direction clock-wise or counter-clock-wise)
1. Claim 4 plots one by one
2. Merge two like this:
![bug4](https://cloud.githubusercontent.com/assets/12183954/16358290/004194b4-3b07-11e6-9718-087bc2262985.png)
3. Merge the big one with a 3rd one
![bug5](https://cloud.githubusercontent.com/assets/12183954/16358296/0e31357a-3b07-11e6-8c2e-685bf8862272.png)
4. This is where the bug generally happens, sometime it fails, sometimes it works. 
4.1 Place yourself facing the remaining road, not pointing to the center, but front
4.2 Merge the big one with the last remaining one
![bug](https://cloud.githubusercontent.com/assets/12183954/16358301/32d73a78-3b07-11e6-8ea9-68079a0accad.png)
After disposing:
![bug8](https://cloud.githubusercontent.com/assets/12183954/16358309/44a75814-3b07-11e6-96af-b739468914a3.png)

# SECOND BUG - Null exception after disposing plots (Right after doing the first bug)

**Description of the problem:**

``[20:05:22] [Server thread/INFO]: ImTedzi issued server command: /p dispose
[20:05:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'p' in plugin PlotSquared v3.4.4-SNAPSHOT;-3a97334
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at com.intellectualcrafters.plot.object.PlotArea$2.run(PlotArea.java:471) ~[?:?]
	at com.intellectualcrafters.plot.object.PlotArea$2.run(PlotArea.java:468) ~[?:?]
	at com.intellectualcrafters.plot.object.PlotArea.foreachPlotAbs(PlotArea.java:625) ~[?:?]
	at com.intellectualcrafters.plot.object.PlotArea.getPlotsAbs(PlotArea.java:468) ~[?:?]
	at com.intellectualcrafters.plot.object.PlotPlayer.getPlotCount(PlotPlayer.java:176) ~[?:?]
	at com.intellectualcrafters.plot.commands.Delete.onCommand(Delete.java:44) ~[?:?]
	at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27) ~[?:?]
	at com.plotsquared.general.commands.Command.execute(Command.java:336) ~[?:?]
	at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:226) ~[?:?]
	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:133) ~[?:?]
	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	... 15 more``

**How to replicate**:
1. Do exactly all the steps in the first bug
2. After, dispose the big plot
3. All the plots will seem disposed, but one of them will remain claimed with your name in the SIGN. If you try to dispose that plot, it will dispose it again (not supposed) or give this error:

(Also happened NullPointer everytime I claim or dispose afterwards)
![bug7](https://cloud.githubusercontent.com/assets/12183954/16358302/3b1eff40-3b07-11e6-8c12-9eb373187c89.png)

``[20:05:44] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotSquared v3.4.4-SNAPSHOT;-3a97334
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-f928e7a-e91aed8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException``

I will attempt to test this further and find out the causes.

**Comment by MattBDev** [comment]
Can you provide a debugpaste link so we can also have the latest.log of these errors? Thank you.

**Comment by pedroo21** [comment]
Sorry, I forgot that.

http://hastebin.com/eyegibahid

I wasn't able to provide this report right after the time it happened, I had to restart the server.
But I'm available to provide extra info or server logs to fix this issue.

**Comment by pedroo21** [comment]
I'm open to help in solving this issue!

I have plot merging disabled while this bug is around, please try to fix it as soon as possible 😃

**Comment by pedroo21** [comment]
Road bug confirmed as not fixed. 

http://prntscr.com/bt39xm
