### ISSUE TITLE
Clearing a plot throws an error, does not clear

### ISSUE THREAD

**Issue by c0wg0d** [IntellectualSites/PlotSquared#1264]
```
[01:56:01 WARN]: [PlotSquared] Task #419716 for PlotSquared v3.4.1-f5e7d08 generated an exception
java.lang.NullPointerException
        at com.intellectualcrafters.plot.commands.MainCommand$1$1.run(MainCommand.java:143) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[creative.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [creative.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [creative.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [creative.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [creative.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [creative.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

```

A player types /plot clear, it asks if they are sure, they type /plot confirm, then the above error is thrown and nothing happens.

http://hastebin.com/imuborinaj

**Comment by manuelgu** [comment]
Update PlotSquared to the latest version.

**Comment by c0wg0d** [comment]
I only see a 3.4.4-dev version.  Is there a more current stable release than what I have?  /plot update does not work.

**Comment by manuelgu** [comment]
`/plot update` is currently broken. Dev releases should be considered stable.

**Comment by c0wg0d** [comment]
I do not agree with that.  Commands and permissions are changed willy-nilly with no warning or notice on dev versions.  When I download the 3.4.2 version from SpigotMC, it is not actually 3.4.2, but is 3.4.1.

**Comment by manuelgu** [comment]
Someone messed up there then. Nevertheless, dev version is considered stable at this point. If you fear it, then you have to wait for a next release.
