### ISSUE TITLE
Schematics containing blocks don't work?

### ISSUE THREAD

**Issue by EthanRPro** [IntellectualSites/PlotSquared#1268]
[11:20:35] [Server thread/INFO]: EthanRAdmin issued server command: /plot schematic paste desutest
[11:20:35] [Craft Scheduler Thread - 16/WARN]: Exception in thread "Craft Scheduler Thread - 16" 
[11:20:35] [Craft Scheduler Thread - 16/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.4.4-SNAPSHOT-cf5d2a5 generated an exception while executing task 1211
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.plotsquared.bukkit.object.schematic.StateWrapper.restoreTag(StateWrapper.java:56)
	at com.plotsquared.bukkit.util.BukkitSchematicHandler.restoreTile(BukkitSchematicHandler.java:308)
	at com.intellectualcrafters.plot.util.SchematicHandler$2$1.run(SchematicHandler.java:335)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by MattBDev** [comment]
Please follow the issue template in the future. Please resubmit this issue and include the schematic if needed.
