### ISSUE TITLE
my sponge server just cant use this plugin and make issue :(

### ISSUE THREAD

**Issue by linyuzhe210** [IntellectualSites/PlotSquared#1298]
hello great work plotsquared builder ：
I‘m a chinese server owner who is interested in this plugin and i m now planing to build a good pixelmon 1.89 mod server and this plugin must be a very important part of it，but when i add this plugin on the mods folder and start the server，i get the error like this：
Could not pass FMLServerAboutToStartEvent to org.spongepowered.mod.plugin.SpongeModPluginContainer@5e501909
java.lang.NoSuchMethodError: org.spongepowered.api.GameRegistry.register(Ljava/lang/Class;Lorg/spongepowered/api/CatalogType;)Lorg/spongepowered/api/CatalogType;
	
at com.plotsquared.sponge.SpongeMain.onServerAboutToStart(SpongeMain.java:139) ~[SpongeMain.class:?]
at org.spongepowered.common.event.listener.GameAboutToStartServerEventListener_SpongeMain_onServerAboutToStart47.handle(Unknown Source) ~[?:?]
	
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1620]
	
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1620]
	
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:242) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1620]
	
at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:185) [SpongeMod.class:1.8.9-1890-4.2.0-BETA-1620]
	
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.9.jar:?]
	
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.9.jar:?]
	
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.9.jar:?]
	
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.9.jar:?]
	
at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.9.jar:?]
	
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) [LoadController.class:?]
	
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) [LoadController.class:?]
	
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.9.jar:?]
	
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.9.jar:?]
	
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.9.jar:?]
	
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.9.jar:?]
	
at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.9.jar:?]
	
at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53) [LoadController.class:?]
	
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	
at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:857) [Loader.class:?]
	
at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
	
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:252) [ko.class:?]
	
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
	
at java.lang.Thread.run(Unknown Source)
i tested the plugin on the environmrnt:sponge 1.8.9-1890-4.2.0-BETA-1620]
froge 11.15.1.1902
could you please give me some advise where i did it wrong or is it a plugin bug?hope for your early
reply :) and other people who know how to deal with it are welcome

**Comment by MattBDev** [comment]
We will not be supporting Sponge running Minecraft version 1.8 or 1.9
