### ISSUE TITLE
Plot Setup fails on Sponge 1.10

### ISSUE THREAD

**Issue by lasercar** [IntellectualSites/PlotSquared#1321]
**Debug paste link**: http://hastebin.com/omovakucil

**Description of the problem:**

When finishing `/plot setup`, this error happens:
```
[01:14:53] [Server thread/INFO] [nucleus]: Server ran the command: /plots setup plots
[01:14:53] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task plotsquared-S-21 owned by Plugin{id=plotsquared, name=PlotSquared, version=3.3.3, description=Easy, yet powerful Plot World generation and management., url=https://github.com/IntellectualSites/PlotSquared, source=/minecraft/mods/PlotSquared-Sponge.jar}, but an error occured.
java.lang.ClassCastException: com.plotsquared.sponge.generator.SpongePlotGenerator cannot be cast to org.spongepowered.api.world.WorldArchetype
	at com.plotsquared.sponge.util.SpongeSetupUtils.setupWorld(SpongeSetupUtils.java:143) ~[SpongeSetupUtils.class:?]
	at com.intellectualcrafters.plot.commands.Setup.onCommand(Setup.java:273) ~[Setup.class:?]
	at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27) ~[SubCommand.class:?]
	at com.plotsquared.general.commands.Command.execute(Command.java:336) ~[Command.class:?]
	at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:220) ~[MainCommand.class:?]
	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:133) ~[MainCommand.class:?]
	at com.plotsquared.sponge.util.SpongeCommand.lambda$process$6(SpongeCommand.java:40) ~[SpongeCommand.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) ~[SyncScheduler.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) ~[SchedulerBase.class:1.10.2-2052-5.0.0-BETA-1680]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_92-internal]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) [SchedulerBase.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) [SyncScheduler.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:252) [SpongeMod.class:1.10.2-2052-5.0.0-BETA-1680]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:131) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:100) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92-internal]
``` 

**How to replicate**:

`PlotSquared v3.3.3`

```
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-c7b2063
    SpongeForge: 1.10.2-2052-5.0.0-BETA-1680
    Minecraft Forge: 12.18.1.2052
```

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by lasercar** [comment]
Then when I restart the server, I get this in addition to the previous error:

```
[01:29:07] [Server thread/INFO]: `plots` was not properly loaded - PlotSquared will now try to load it properly:
[01:29:07] [Server thread/INFO]:  - Are you trying to delete this world? Remember to remove it from the settings.yml, bukkit.yml and multiverse worlds.yml
[01:29:07] [Server thread/INFO]:  - Your world management plugin may be faulty (or non existent)
```

Same thing happens whether I have Project Worlds (0.10.4) installed or not.

**Comment by boy0001** [comment]
Try updating PlotSquared:
http://ci.athion.net/job/PlotSquared/

**Comment by lasercar** [comment]
Okay, with `v3.5.0-SNAPSHOT` I get Unknown Command for `/plot`

**Comment by manuelgu** [comment]
Startup errors in console?

**Comment by lasercar** [comment]
```
[08:43:51] [Server thread/ERROR] [Sponge]: Could not pass FMLServerAboutToStartEvent to Plugin{id=plotsquared, name=PlotSquared, version=3.5.0-SNAPSHOT, description=Easy, yet powerful Plot World generation and management., url=https://github.com/IntellectualSites/PlotSquared, source=/minecraft/mods/PlotSquared-Sponge-3.4.6-SNAPSHOT-61d00e5.jar}
java.lang.NumberFormatException: For input string: "0-SNAPSHOT"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_92-internal]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_92-internal]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_92-internal]
	at com.plotsquared.sponge.SpongeMain.getPluginVersion(SpongeMain.java:175) ~[SpongeMain.class:?]
	at com.intellectualcrafters.plot.PS.<init>(PS.java:138) ~[PS.class:?]
	at com.plotsquared.sponge.SpongeMain.onServerAboutToStart(SpongeMain.java:137) ~[SpongeMain.class:?]
	at org.spongepowered.common.event.listener.GameAboutToStartServerEventListener_SpongeMain_onServerAboutToStart23.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:349) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:390) [SpongeModEventManager.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:215) [SpongeMod.class:1.10.2-2052-5.0.0-BETA-1680]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92-internal]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92-internal]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:908) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:264) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92-internal]
```
