### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by renzotom** [IntellectualSites/PlotSquared#1322]
Link to debug: http://hastebin.com/pitobeqafe

There is error, when it start. 
`[20:54:10] [Server thread/WARN]: [PlotSquared] Task #24 for PlotSquared v3.4.6-SNAPSHOT-7d11147 generated an exception
java.lang.NullPointerException
	at com.khorn.terraincontrol.bukkit.TCPlugin.onWorldInit(TCPlugin.java:176) ~[?:?]
	at com.khorn.terraincontrol.bukkit.generator.TCChunkGenerator.makeSureWorldIsInitialized(TCChunkGenerator.java:40) ~[?:?]
	at com.khorn.terraincontrol.bukkit.generator.TCChunkGenerator.getDefaultPopulators(TCChunkGenerator.java:66) ~[?:?]
	at com.plotsquared.bukkit.generator.BukkitPlotGenerator.<init>(BukkitPlotGenerator.java:192) ~[?:?]
	at com.plotsquared.bukkit.util.BukkitSetupUtils.updateGenerators(BukkitSetupUtils.java:43) ~[?:?]
	at com.plotsquared.bukkit.util.BukkitSetupUtils.setupWorld(BukkitSetupUtils.java:53) ~[?:?]
	at com.plotsquared.bukkit.BukkitMain.setGenerator(BukkitMain.java:601) ~[?:?]
	at com.intellectualcrafters.plot.PS$3.run(PS.java:289) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-a9631d2-56813c7]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-a9631d2-56813c7]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:728) [spigot.jar:git-Spigot-a9631d2-56813c7]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-a9631d2-56813c7]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot.jar:git-Spigot-a9631d2-56813c7]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot.jar:git-Spigot-a9631d2-56813c7]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

**Comment by manuelgu** [comment]
You have a world called `<world>`, probably not supposed to be like that.

The plugin TerrainControl is causing the issue.

Please attach the worlds.yml of Multiverse

**Comment by renzotom** [comment]
`[11:03:50] [Server thread/INFO]: Renzotom issued server command: /plots setup IslandWorld
[11:03:50] [Server thread/INFO]: [TerrainControl] Starting to enable world ''CheckingPlotSquaredGenerator''...
[11:03:50] [Server thread/INFO]: [TerrainControl] 0 world custom objects loaded.
[11:03:50] [Server thread/INFO]: [TerrainControl] 62 biomes Loaded
[11:03:50] [Server thread/INFO]: BukkitPlotGenerator does not fully support: com.khorn.terraincontrol.bukkit.generator.TCChunkGenerator@34f17bbc[m
[11:03:50] [Server thread/WARN]: java.lang.NullPointerException
[11:03:50] [Server thread/WARN]: 	at com.khorn.terraincontrol.bukkit.TCPlugin.onWorldInit(TCPlugin.java:176)
[11:03:50] [Server thread/WARN]: 	at com.khorn.terraincontrol.bukkit.generator.TCChunkGenerator.makeSureWorldIsInitialized(TCChunkGenerator.java:40)
[11:03:50] [Server thread/WARN]: 	at com.khorn.terraincontrol.bukkit.generator.TCChunkGenerator.getDefaultPopulators(TCChunkGenerator.java:66)
[11:03:50] [Server thread/WARN]: 	at com.plotsquared.bukkit.generator.BukkitPlotGenerator.<init>(BukkitPlotGenerator.java:192)
[11:03:50] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.BukkitSetupUtils.updateGenerators(BukkitSetupUtils.java:43)
[11:03:50] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.Setup.onCommand(Setup.java:53)
[11:03:50] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27)
[11:03:50] [Server thread/WARN]: 	at com.plotsquared.general.commands.Command.execute(Command.java:337)
[11:03:50] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:227)
[11:03:50] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:133)
[11:03:50] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
[11:03:50] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:03:50] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:03:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[11:03:50] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
[11:03:50] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
[11:03:50] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:03:50] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:03:50] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[11:03:50] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11:03:50] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11:03:50] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[11:03:50] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[11:03:50] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[11:03:50] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[11:03:50] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[11:03:50] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)`
TerrarianControl also block IslandWorld :/ You can fix it please?

**Comment by renzotom** [comment]
And why TerrarianControl doesn´t work? And also IslandPlots :/ I don´t see them in /plot setup.

**Comment by boy0001** [comment]
@renzotom Your config is invalid. You can use a YML parser to find any errors and correct them:
http://yaml-online-parser.appspot.com/

**Comment by renzotom** [comment]
Config of what? PlotSquared? Beacuse in IslandPlots and TerrarianControl I don´t set anything.

**Comment by EvilOlaf** [comment]
Check all of them anyways.
