### ISSUE TITLE
Error in PlotRankup

### ISSUE THREAD

**Issue by renzotom** [IntellectualSites/PlotSquared#1343]
Hello, in your addon PlotRankup is problem. I am using 1.10.2 version and latest version of PlotSquared and error is:
```
[14:32:19] [Server thread/ERROR]: Could not load 'plugins/PlotRankup (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/flag/AbstractFlag
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-455072c-2f5bda8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-455072c-2f5bda8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-455072c-2f5bda8]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot.jar:git-Spigot-455072c-2f5bda8]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-Spigot-455072c-2f5bda8]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-455072c-2f5bda8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/flag/AbstractFlag
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_72]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-455072c-2f5bda8]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-455072c-2f5bda8]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.flag.AbstractFlag
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-455072c-2f5bda8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-455072c-2f5bda8]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_72]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-455072c-2f5bda8]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-455072c-2f5bda8]
	... 6 more
```

**Comment by SupremeMortal** [comment]
The plugin hasn't been updated in quite a while. It explains this at the top of the resource.

**Comment by renzotom** [comment]
And it can be updated?

**Comment by MattBDev** [comment]
This is not the place for PlotRankup errors.
