### ISSUE TITLE
Thermos-1.7.10-1614-57-server  ERROR

### ISSUE THREAD

**Issue by azbh111** [IntellectualSites/PlotSquared#1347]
[17:23:23] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[17:23:23] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:23:23] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[17:23:23] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[17:23:23] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[17:23:23] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.QueueProvider$1.getNewQueue(QueueProvider.java:15)
[17:23:23] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue.getNewQueue(GlobalBlockQueue.java:69)
[17:23:23] [Server thread/WARN]: 	at com.plotsquared.bukkit.generator.BukkitPlotGenerator$1.populate(BukkitPlotGenerator.java:59)
[17:23:23] [Server thread/WARN]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:460)
[17:23:23] [Server thread/WARN]: 	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1201)
[17:23:23] [Server thread/WARN]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:77)
[17:23:23] [Server thread/WARN]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
[17:23:23] [Server thread/WARN]: 	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
[17:23:23] [Server thread/WARN]: 	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
[17:23:23] [Server thread/WARN]: 	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
[17:23:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917)
[17:23:23] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[17:23:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[17:23:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[17:23:23] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[17:23:23] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/Block
[17:23:23] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[17:23:23] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[17:23:23] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.ReflectionUtils.getRefClass(ReflectionUtils.java:215)
[17:23:23] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.block.BukkitLocalQueue_1_7.<init>(BukkitLocalQueue_1_7.java:24)
[17:23:23] [Server thread/WARN]: 	... 19 more

**Comment by azbh111** [comment]
version is 3.4.5

**Comment by MattBDev** [comment]
Resubmit this following the proper bug report guidelines.
