### ISSUE TITLE
Error Running on Nukkit

### ISSUE THREAD

**Issue by CRBairdUSA** [IntellectualSites/PlotSquared#1356]
```
[ALERT] java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.util.regex.Matcher.reset(Unknown Source)
        at java.util.regex.Matcher.<init>(Unknown Source)
        at java.util.regex.Pattern.matcher(Unknown Source)
        at java.util.regex.Pattern.matches(Unknown Source)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:189)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:133)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:125)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:121)
        at cn.nukkit.Server.<init>(Server.java:380)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

Help a brother out!

**Comment by MattBDev** [comment]
Not a Plotsquared issue.

**Comment by CRBairdUSA** [comment]
Sorry about that. I suppose you're right.

**Comment by boy0001** [comment]
@CRBairdUSA 
One of your jar files doesn't have a valid description. Remove the invalid jar.
