### ISSUE TITLE
NullPointerException - saveConfiguration

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#1377]
PlotSquared dev 357
FAWE dev 332
Paper dev 881 (Spigot 1.10.2)

Settings
http://paste.ubuntu.com/23253696/

Removed a plot world from the worlds.yml manually. Then tried to reload the plugin.

```
[17:49:35] [Server thread/INFO]: player issued server command: /ps reload
```
```
[17:49:35] [Server thread/WARN]: java.lang.NullPointerException
[17:49:35] [Server thread/WARN]: 	at com.intellectualcrafters.plot.object.PlotArea.saveConfiguration(PlotArea.java:353)
[17:49:35] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.Reload$1.run(Reload.java:35)
[17:49:35] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.Reload$1.run(Reload.java:30)
[17:49:35] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.foreachPlotArea(PS.java:2015)
[17:49:35] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.Reload.onCommand(Reload.java:30)
[17:49:35] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27)
[17:49:35] [Server thread/WARN]: 	at com.plotsquared.general.commands.Command.execute(Command.java:337)
[17:49:35] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:228)
[17:49:35] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:134)
[17:49:35] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
[17:49:35] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:49:35] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[17:49:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:672)
[17:49:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1396)
[17:49:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1201)
[17:49:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:49:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:49:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[17:49:35] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:49:35] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:49:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[17:49:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:804)
[17:49:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[17:49:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734)
[17:49:35] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633)
[17:49:35] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by boy0001** [comment]
Well, you probably shouldn't have deleted the section from the config, but whatever. Fixed now.

**Comment by mibby** [comment]
I removed that world from the config manually because I had deleted the test world and didn't see a command to remove that world's plot settings. So figured I'd manually remove it and force a reload.

**Comment by boy0001** [comment]
- Stop the server:
 - Remove from PlotSquared worlds.yml
 - Remove from bukkit.yml
 - Remove from multiverse (or multiworld) worlds.yml

**Comment by mibby** [comment]
To clarify; a config reload not a server ```/reload``` (since that breaks things). 

I had just ```/mv delete <world>``` and was wanting to remove it from the PlotSquared config without restarting. :P
