### ISSUE TITLE
Nukkit issue

### ISSUE THREAD

**Issue by NycuRO** [IntellectualSites/PlotSquared#1414]
I don't know ,i'm not use Hybrid Generator and plugin show this in load: @boy0001 

15:16:41 [INFO] PlotSquared is now enabled
15:16:41 [INFO] [P2] Metrics enabled.
15:16:41 [NOTICE] Level "bridge" not found
15:16:41 [INFO] Preparing level "bridge"
15:16:41 [INFO] [P2] Detected world load for 'bridge'
15:16:41 [INFO] [P2]  - generator: PlotSquared>PlotSquared
15:16:41 [INFO] [P2]  - plotworld: com.intellectualcrafters.plot.generator.HybridPlotWorld
15:16:41 [INFO] [P2]  - manager: com.plotsquared.nukkit.NukkitMain
15:16:41 [ERROR] Could not generate level "bridge": java.lang.reflect.InvocationTargetException
15:16:41 [ALERT] java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at cn.nukkit.level.Level.initLevel(Level.java:358)
        at cn.nukkit.Server.generateLevel(Server.java:1622)
        at cn.nukkit.Server.<init>(Server.java:415)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at cn.nukkit.level.Level.initLevel(Level.java:356)
        ... 3 more
Caused by: java.lang.NullPointerException
        at com.intellectualcrafters.plot.config.Configuration$8.parseString(Configuration.java:161)
        at com.intellectualcrafters.plot.config.Configuration$8.parseString(Configuration.java:117)
        at com.intellectualcrafters.plot.generator.ClassicPlotWorld.loadConfiguration(ClassicPlotWorld.java:60)
        at com.intellectualcrafters.plot.generator.HybridPlotWorld.loadConfiguration(HybridPlotWorld.java:151)
        at com.intellectualcrafters.plot.object.PlotArea.loadDefaultConfiguration(PlotArea.java:303)
        at com.intellectualcrafters.plot.PS.loadWorld(PS.java:1454)
        at com.plotsquared.nukkit.generator.NukkitPlotGenerator.<init>(NukkitPlotGenerator.java:89)
        at com.plotsquared.nukkit.util.block.NukkitHybridGen.<init>(NukkitHybridGen.java:11)
        ... 8 more

**Comment by NycuRO** [comment]
And i'm deleted all configs and other world and show in load:

15:18:46 [INFO] Loading Pokkit v0.5-SNAPSHOT
15:18:46 [INFO] [Pokkit] This server is running Nukkit version v0.15.10 alpha (Implementing API version 1.10.2-R0.1-SNAPSHOT)
15:18:46 [INFO] [Pokkit] Server permissions file /root/creative/plugins/Pokkit/permissions.yml is empty, ignoring it
15:18:46 [INFO] Loading PlotSquared v3.4.6-SNAPSHOT-1d7cdde
15:18:46 [INFO] Enabling PlotSquared v3.4.6-SNAPSHOT-1d7cdde
> java.lang.IllegalAccessError: class org.sqlite.SQLiteConfig$TransactionMode cannot access its superinterface org.sqlite.SQLiteConfig$PragmaValue
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44)
        at cn.nukkit.plugin.JavaPluginLoader.getClassByName(JavaPluginLoader.java:146)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:40)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.sqlite.core.CoreConnection.<clinit>(CoreConnection.java:46)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at com.intellectualcrafters.plot.database.SQLite.openConnection(SQLite.java:47)
        at com.intellectualcrafters.plot.database.SQLManager.<init>(SQLManager.java:104)
        at com.intellectualcrafters.plot.PS.setupDatabase(PS.java:1846)
        at com.intellectualcrafters.plot.PS.<init>(PS.java:162)
        at com.plotsquared.nukkit.NukkitMain.onEnable(NukkitMain.java:101)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:456)
        at cn.nukkit.Server.enablePlugin(Server.java:618)
        at cn.nukkit.Server.enablePlugins(Server.java:607)
        at cn.nukkit.Server.<init>(Server.java:382)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by NycuRO** [comment]
Issue is caused by Pokkit , plugin : https://github.com/rutgerkok/Pokkit

You can fix?

**Comment by boy0001** [comment]
What PlotSquared are you running?
Can you attach your PlotSquared settings.yml and worlds.yml?

**Comment by NycuRO** [comment]
# These first 4 aren't configurable
issues: "https://github.com/IntellectualSites/PlotSquared/issues"
wiki: "https://github.com/IntellectualSites/PlotSquared/wiki"
version: "3.4.6"
platform: "Nukkit"
# Show additional information in console
debug: true
# The big annoying text that appears when you enter a plot
# For a single plot: `/plot flag set titles false`
# For just you: `/plot toggle titles`
titles: true

# Enable or disable part of the plugin
# Note: A cache will use some memory if enabled
enabled-components:
  # The database stores all the plots
  database: true
  # Events are needed to track a lot of things
  events: true
  # Commands are used to interact with the plugin
  commands: true
  # The UUID cacher is used to resolve player names
  uuid-cache: true
  # Notify players of updates
  updater: true
  # Stores user metadata in a database
  persistent-meta: true
  # Optimizes permission checks
  permission-cache: true
  # Optimizes block changing code
  block-cache: true
  # Getting a rating won't need the database
  rating-cache: true
  # The converter will attempt to convert the PlotMe database
  plotme-converter: true
  # Allow WorldEdit to be restricted to plots
  worldedit-restrictions: true
  # Allow economy to be used
  economy: true
  # Send anonymous usage statistics. Bukkit only setting.
  metrics: true
  # Expiry will clear old or simplistic plots
  plot-expiry: false
  # Processes chunks (trimming, or entity/tile limits) 
  chunk-processor: false
  # Kill mobs or vehicles on roads
  kill-road-mobs: false
  kill-road-vehicles: false
  # Notify a player of any missed comments upon plot entry
  comment-notifier: false
  # Actively purge invalid database entries
  database-purger: false
  # Delete plots when a player is banned
  ban-deleter: false

ratings:
  categories: []

claim:
  # The max plots claimed in a single `/plot auto <size>` command
  max-auto-area: 4

redstone:
  # Disable redstone in unoccupied plots
  disable-unoccupied: false
  # Disable redstone when all owners/trusted/members are offline
  disable-offline: false

teleport:
  # Teleport to your plot on death
  on-death: false
  # Teleport to your plot on login
  on-login: false
  # Add a teleportation delay to all commands
  delay: 0

# Switching from PlotMe?
plotme:
  # Cache the uuids from the PlotMe database
  cache-uuds: false

# Relating to how many plots someone can claim  
limit:
  # Should the limit be global (over multiple worlds)
  global: false
  # The range of permissions to check e.g. plots.plot.127
  max-plots: 127

chat:
  # Sometimes console color doesn't work, you can disable it here
  console-color: true
  # Should chat be interactive
  interactive: true

done:
  # Require a done plot to download
  required-for-download: false
  # Only done plots can be rated
  required-for-ratings: false
  # Restrict building when a plot is done
  restrict-building: false
  # The limit being how many plots a player can claim
  counts-towards-limit: true

web:
  # We are already hosting a web interface for you:
  url: "http://empcraft.com/plots/"
  # The ip that will show up in the interface
  server-ip: "your.ip.here"

# Configure the paths that will be used
paths:
  schematics: "schematics"
  bo3: "bo3"
  scripts: "scripts"
  templates: "templates"
  translations: "translations"

uuid:
  # Force using offline UUIDs (it usually detects the right mode)
  offline: false
  # Force using lowercase UUIDs
  force-lowercase: false
  # Use a database to store UUID/name info
  use-sqluuidhandler: false

chunk-processor:
  # Auto trim will not save chunks which aren't claimed
  auto-trim: false
  # Max tile entities per chunk
  max-tiles: 4096
  # Max entities per chunk
  max-entities: 512
  # Disable block physics
  disable-physics: false

# This is an auto clearing task called `task1`
auto-clear:
  task1:
    threshold: 1
    required-plots: -1
    confirmation: true
    days: 7
    worlds: 
    - "*"
    # See: https://github.com/IntellectualSites/PlotSquared/wiki/Plot-analysis
    calibration:
      variety: 0
      variety-sd: 0
      changes: 0
      changes-sd: 1
      faces: 0
      faces-sd: 0
      data-sd: 0
      air: 0
      air-sd: 0
      data: 0

**Comment by NycuRO** [comment]
worlds:
  bridge:
    generator:
      plugin: PlotSquared
    plot:
      height: 64
      floor:
      - '2:0'
      biome: FOREST
      size: 50
      bedrock: true
      create_signs: true
      filling:
      - '1:0'
      auto_merge: false
    event:
      spawn:
        breeding: false
        egg: false
        custom: true
      pvp: false
      pve: false
    economy:
      use: false
      prices:
        claim: 100.0
        sell: 75.0
        merge: 100.0
    home:
      allow-nonmembers: true
      default: center
    wall:
      height: 64
      filling: '1:0'
      block: '44:0'
      block_claimed: '44:5'
    road:
      block: '155:0'
      height: 64
      width: 12
    world:
      border: false
      gamemode: creative
      max_height: 256
      min_height: 1
    schematic:
      file: 'null'
      on_claim: false
      specify_on_claim: false
    limits:
      max-members: 128
    chat:
      enabled: false
    flags: {}
    natural_mob_spawning: false
    mob_spawner_spawning: false

**Comment by NycuRO** [comment]
@boy0001 Ready

**Comment by boy0001** [comment]
@NycuRO 
When I said attach, I didn't mean paste it as a wall of text in a comment. Second error your posted is with your sql driver. 

Use the driver from dblib: nukkit.ru/resources/dblib.14/

**Comment by NycuRO** [comment]
@boy0001 Cause is pokkit plugin man..
