### ISSUE TITLE
PlotSquared fails to regenerate roads in 1.7.10

### ISSUE THREAD

**Issue by MrPowerGamerBR** [IntellectualSites/PlotSquared#1418]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/dehelumero

**Description of the problem:**
When using "/plot regenallroads", the console is flooded with errors. (Not using FAWE)

```
[20:41:55 WARN]: java.lang.NullPointerException¢P
[20:41:55 WARN]:        at com.plotsquared.bukkit.util.block.BukkitLocalQueue_1_7.setBlocks(BukkitLocalQueue_1_7.java:115)
[20:41:55 WARN]:        at com.plotsquared.bukkit.util.block.BukkitLocalQueue.setComponents(BukkitLocalQueue.java:66)
[20:41:55 WARN]:        at com.intellectualcrafters.plot.util.block.BasicLocalBlockQueue.execute(BasicLocalBlockQueue.java:67)
[20:41:55 WARN]:        at com.intellectualcrafters.plot.util.block.BasicLocalBlockQueue.next(BasicLocalBlockQueue.java:53)
[20:41:55 WARN]:        at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:48)
[20:41:55 WARN]:        at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:44)
[20:41:55 WARN]:        at com.intellectualcrafters.plot.object.RunnableVal2.run(RunnableVal2.java:16)
[20:41:55 WARN]:        at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$2.run(GlobalBlockQueue.java:109)
[20:41:55 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[20:41:55 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[20:41:55 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:701)
[20:41:55 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307)
[20:41:55 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643)
[20:41:55 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549)
[20:41:55 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
```

**How to replicate**:
1. Create a custom road
2. Use "/plot regenallroads"

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an up-to-date version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by piesio98** [comment]
the same here

**Comment by RedstoneFuture** [comment]
Currently `/plot debugpaste` works fine.
