### ISSUE TITLE
NPE com.plotsquared.bukkit.util.BukkitHybridUtils

### ISSUE THREAD

**Issue by L4BORG** [IntellectualSites/PlotSquared#1419]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

**Description of the problem:**
```
[03:07:59 WARN]: Exception in thread "Craft Scheduler Thread - 7"
[03:07:59 WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.4.6-SNAPSHOT-1d7cdde generated an exception while executing task 1494
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.plotsquared.bukkit.util.BukkitHybridUtils$1$2$2$1.run(BukkitHybridUtils.java:176)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**How to replicate**:
It just show up after server startup...

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an up-to-date version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by L4BORG** [comment]
This is still an issue with PlotSquared-Bukkit-3.4.6-SNAPSHOT-3070557.
