### ISSUE TITLE
/P i NPE

### ISSUE THREAD

**Issue by L4BORG** [IntellectualSites/PlotSquared#1426]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

**Description of the problem:**
```
[12:20:36] [Server thread/INFO]: Player issued server command: /P i
[12:20:36] [Server thread/WARN]: java.lang.NullPointerException
[12:20:36] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.MainUtil.format(MainUtil.java:733)
[12:20:36] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.Info.onCommand(Info.java:123)
[12:20:36] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27)
[12:20:36] [Server thread/WARN]: 	at com.plotsquared.general.commands.Command.execute(Command.java:337)
[12:20:36] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:259)
[12:20:36] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:134)
[12:20:36] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
[12:20:36] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:20:36] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[12:20:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[12:20:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194)
[12:20:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006)
[12:20:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:20:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:20:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[12:20:36] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:20:36] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:20:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[12:20:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[12:20:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[12:20:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[12:20:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[12:20:36] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**How to replicate**:
I think /p i is bugged for some players or is it plots?

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an up-to-date version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
Bug report template not followed. This error shouldn't exist based on the information given (which is very little).
