### ISSUE TITLE
error on /plot info

### ISSUE THREAD

**Issue by frizzbee30** [IntellectualSites/PlotSquared#1440]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:http://imgur.com/a/q5Rbk

getting this error for /plot debugpaste so could only include a summary /plot debug image sorry
 java.io.IOException: Server returned HTTP response code: 503 for URL: http://hastebin.com/documents

**Description of the problem:**
intitally landing in home plot gives the expected result on running /p info

moving to another players plot which correctly displays the owner, running /p info gives an error of 'an error occured: %s

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an up-to-date version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

error paste

[10:56:52] [Server thread/INFO]: frizzbee30 issued server command: /p info
[10:56:52] [Server thread/WARN]: java.lang.NullPointerException
[10:56:52] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.MainUtil.format(MainUtil.java:733)
[10:56:52] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.Info.onCommand(Info.java:123)
[10:56:52] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27)
[10:56:52] [Server thread/WARN]: 	at com.plotsquared.general.commands.Command.execute(Command.java:337)
[10:56:52] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:259)
[10:56:52] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:134)
[10:56:52] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
[10:56:52] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[10:56:52] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[10:56:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[10:56:52] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335)
[10:56:52] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170)
[10:56:52] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[10:56:52] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[10:56:52] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[10:56:52] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[10:56:52] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[10:56:52] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[10:56:52] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[10:56:52] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[10:56:52] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[10:56:52] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[10:56:52] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[10:57:01] [Craft Scheduler Thread - 12/WARN]: [SurvivalGames] [SurvivalGames] c

version version: 3.4.6-SNAPSHOT-e126054
spigot version 1.11 16c940b0677

using an external MySQL db for storage

**Comment by frizzbee30** [comment]
possibly error 1426 is identical, closed without sufficient information?

**Comment by frizzbee30** [comment]
Just to add, running /p info on any unclaimed plot gives the expected response, only claimed plots are affected.

**Comment by MattBDev** [comment]
I'll look into this. thanks for the extra information. Now I know this is an issue.

**Comment by MattBDev** [comment]
@frizzbee30 did you have plot expiry enabled?

**Comment by frizzbee30** [comment]
Hi, we do have plot expiry enabled.  Thanks
