### ISSUE TITLE
Error with Chunk generation Nukkit

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1442]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/ihuzezaxup
nukkit as of https://github.com/Nukkit/Nukkit/commit/77c13335d1f1c9933025adcf1afdd64991f2a0cd
FAWE build 376 - http://ci.athion.net/job/FastAsyncWorldEdit/376/
PlotSquared build 386 http://ci.athion.net/job/PlotSquared/386/

**Description of the problem:**
I created a brand new world and it appears the generator is causing corruption. 

The initial error is found here: http://pastebin.com/raw/u0VekxCm

Eventually there will be crashes with
```
2016-11-23 12:03:49 [CRITICAL] Could not tick level "pocket": cn.nukkit.utils.ChunkException: Invalid Chunk Sent^M
2016-11-23 12:03:49 [ALERT] cn.nukkit.utils.ChunkException: Invalid Chunk Sent
    at cn.nukkit.level.format.mcregion.McRegion.requestChunkTask(McRegion.java:121)
    at cn.nukkit.level.Level.processChunkRequest(Level.java:2308)
    at cn.nukkit.level.Level.doTick(Level.java:785)
    at cn.nukkit.Server.checkTickUpdates(Server.java:922)
    at cn.nukkit.Server.tick(Server.java:997)
    at cn.nukkit.Server.tickProcessor(Server.java:793)
    at cn.nukkit.Server.start(Server.java:772)
    at cn.nukkit.Server.<init>(Server.java:463)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

**How to replicate**:
Make a new world and then do /plot auto

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an up-to-date version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
I wish I knew how to fix this. I can't even figure out how to setup a nukkit server that will run with Minecraft Win10

**Comment by boy0001** [comment]
Error is from FAWE. Should be fixed in latest version.

@MattBDev 
Run it like you would a spigot jar:
 - http://ci.regularbox.com/job/Nukkit/
 - https://www.youtube.com/watch?v=ivyJTaC5ixE
