### ISSUE TITLE
error with doing worldedit on nukkit

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1450]
I was standing in my plot doing a worldedit on the full plot and got this

```
2016-11-28 02:01:11 [CRITICAL] Could not tick level "pocket": java.lang.NullPointerException^M
2016-11-28 02:01:11 [ALERT] java.lang.NullPointerException
    at cn.nukkit.level.Level.getBlock(Level.java:1367)
    at cn.nukkit.level.Level.getBlock(Level.java:1351)
    at cn.nukkit.entity.Entity.getBlocksAround(Entity.java:1406)
    at cn.nukkit.Player.checkBlockCollision(Player.java:1202)
    at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:940)
    at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:187)
    at cn.nukkit.Player.onUpdate(Player.java:1536)
    at cn.nukkit.level.Level.doTick(Level.java:732)
    at cn.nukkit.Server.checkTickUpdates(Server.java:922)
    at cn.nukkit.Server.tick(Server.java:997)
    at cn.nukkit.Server.tickProcessor(Server.java:793)
    at cn.nukkit.Server.start(Server.java:772)
    at cn.nukkit.Server.<init>(Server.java:463)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)
```
I dont know if this is a nukkit or FAWE issue

**Comment by MattBDev** [comment]
It looks to me like it has to do with Nukkit but if you use FAWE then I'm not sure.

**Comment by boy0001** [comment]
Fixed in https://github.com/Nukkit/Nukkit/pull/1306
