### ISSUE TITLE
Disposing Merged plots doesn't regen roads right and /p debugpaste error [1.11]

### ISSUE THREAD

**Issue by Bobcatsss** [IntellectualSites/PlotSquared#1482]
# Bug report template 

**Debug paste link:** 
Error when running "/p debugpaste" 
`[09:08:48] [Server thread/INFO]: CatsCraftDotCom issued server command: /p debugpaste
[09:08:48] [Craft Scheduler Thread - 11/WARN]: [PlotSquared] Plugin PlotSquared v3.5.1-SNAPSHOT-a843203 generated an exception while executing task 87
java.lang.RuntimeException: Couldn't read response!
	at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43) ~[?:?]
	at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60) ~[?:?]
	at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-aad97c4-4602331]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-aad97c4-4602331]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[09:10:06]`

**Description of the problem:** 
If i dispose of a merged plot the roads that it needs to regenerate don't fully regenerate it misses like 5 - 8 layers of quartz and the bedrock layer at the bottom. 

Picture Link: (Under the four plots after using /p dispose)
Link: http://i.imgur.com/FkTXeCx.png

**How to replicate:** 
Claim 4 plots.
Merge them together.
Type "/p dispose"
Go into gamemode 3 and look under the roads it had to regenerate.

**Checklist**:

- [ ] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
PlotSquared Version: PlotSquared v3.5.1-SNAPSHOT-a843203
Server Version: spigot-1.11-R0.1-SNAPSHOT

- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by L4BORG** [comment]
I can confirm this with latest PS and TacoSpigot 1.8.8

```
>plot debugpaste
[02:51:06 WARN]: Exception in thread "Craft Scheduler Thread - 19"
[02:51:06 WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.5.1-SNAPSHOT-a843203 generated an exception while executing task 29497
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Couldn't read response!
        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43)
        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60)
        at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by RedstoneFuture** [comment]
The debugpaste error is fixed.

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
