### ISSUE TITLE
 Could not pass event PlayerInteractEvent/PlayerJoinEvent/EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by L4BORG** [IntellectualSites/PlotSquared#1487]
```
[02:40:21] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to PlotSquared v3.5.1-SNAPSHOT-a843203
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:626) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_111]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_111]
	at com.intellectualcrafters.plot.object.Plot.isOwner(Plot.java:345) ~[?:?]
	at com.intellectualcrafters.plot.object.Plot.isAdded(Plot.java:396) ~[?:?]
	at com.intellectualcrafters.plot.util.EventUtil.checkPlayerBlockEvent(EventUtil.java:116) ~[?:?]
	at com.plotsquared.bukkit.listeners.PlayerEvents.onInteract(PlayerEvents.java:1408) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	... 19 more
```

Latest TacoSpigot 1.8.8

**Debug paste link:** 
Debug paste is bugged at the moment.

**Description of the problem:** 
Exception spamming console.

**How to replicate:** 
Not sure.

**Checklist**:
- [] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by L4BORG** [comment]
Also there one more exception there:

```
[02:40:22] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to PlotSquared v3.5.1-SNAPSHOT-a843203
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1112) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:748) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.EntityWolf.damageEntity(EntityWolf.java:213) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1086) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1387) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_111]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_111]
	at com.intellectualcrafters.plot.object.Plot.isOwner(Plot.java:345) ~[?:?]
	at com.intellectualcrafters.plot.object.Plot.isAdded(Plot.java:396) ~[?:?]
	at com.plotsquared.bukkit.listeners.PlayerEvents.entityDamage(PlayerEvents.java:2288) ~[?:?]
	at com.plotsquared.bukkit.listeners.PlayerEvents.onEntityDamageByEntityEvent(PlayerEvents.java:2182) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	... 25 more
```

**Comment by L4BORG** [comment]
And this:

```
[13:58:18] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to PlotSquared v3.5.1-SNAPSHOT-a843203
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_111]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_111]
	at com.intellectualcrafters.plot.object.Plot.getBasePlot(Plot.java:510) ~[?:?]
	at com.intellectualcrafters.plot.object.PlotArea.getPlot(PlotArea.java:547) ~[?:?]
	at com.intellectualcrafters.plot.object.PlotArea.getPlot(PlotArea.java:410) ~[?:?]
	at com.plotsquared.bukkit.listeners.PlayerEvents.onConnect(PlayerEvents.java:464) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	... 15 more
```

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
