### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by Xayanix** [IntellectualSites/PlotSquared#1497]
[18:42:06] [Server thread/WARN]: java.lang.NullPointerException
[18:42:06] [Server thread/WARN]: java.lang.RuntimeException: java.lang.IllegalArgumentException: java.lang.ClassCastException@3bf300d5
[18:42:06] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:573)
[18:42:06] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.block.BukkitLocalQueue_1_7.fixChunkLighting(BukkitLocalQueue_1_7.java:90)
[18:42:06] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.block.BukkitLocalQueue_1_7.setBlocks(BukkitLocalQueue_1_7.java:123)
[18:42:06] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.block.BukkitLocalQueue.setComponents(BukkitLocalQueue.java:66)
[18:42:06] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.BasicLocalBlockQueue.execute(BasicLocalBlockQueue.java:67)
[18:42:06] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.BasicLocalBlockQueue.next(BasicLocalBlockQueue.java:53)
[18:42:06] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:48)
[18:42:06] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:44)
[18:42:06] [Server thread/WARN]: 	at com.intellectualcrafters.plot.object.RunnableVal2.run(RunnableVal2.java:16)
[18:42:06] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$2.run(GlobalBlockQueue.java:109)
[18:42:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[18:42:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[18:42:06] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641)
[18:42:06] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[18:42:06] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[18:42:06] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[18:42:06] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[18:42:06] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@3bf300d5
[18:42:06] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
[18:42:06] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:42:06] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:42:06] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:571)
[18:42:06] [Server thread/WARN]: 	... 16 more

**Comment by Xayanix** [comment]
kek

**Comment by RedstoneFuture** [comment]
Hello. Have you still a problem with this? We need more informations, please. Can you try it with the last version? When you get this error?

**Comment by Xayanix** [comment]
No, i dont have it anymore but i got many more issues. I can post them tommorow.

**Comment by RedstoneFuture** [comment]
Ok. :)
