### ISSUE TITLE
PaperSpigot  java.lang.IllegalStateException: Asynchronous Async Chunk Load!

### ISSUE THREAD

**Issue by helptiger** [IntellectualSites/PlotSquared#1501]
Error on latest Paperspigot (1.11.2) with latest CI-Build. Does not happen on Spigot 1.11.2

[20:06:59 WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[20:06:59 WARN]: 	at net.minecraft.server.v1_11_R1.MCUtil.ensureMain(MCUtil.java:51)
[20:06:59 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[20:06:59 WARN]: 	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[20:06:59 WARN]: 	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[20:06:59 WARN]: 	at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[20:06:59 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getChunkAt(CraftWorld.java:171)
[20:06:59 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getBlockAt(CraftWorld.java:115)
[20:06:59 WARN]: 	at com.plotsquared.bukkit.object.schematic.StateWrapper.restoreTag(StateWrapper.java:65)
[20:06:59 WARN]: 	at com.plotsquared.bukkit.util.BukkitSchematicHandler.restoreTile(BukkitSchematicHandler.java:308)
[20:06:59 WARN]: 	at com.intellectualcrafters.plot.util.SchematicHandler$2$1.run(SchematicHandler.java:335)
[20:06:59 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[20:06:59 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:06:59 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:06:59 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[20:06:59 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[20:06:59 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
