### ISSUE TITLE
import storage.db to mysql

### ISSUE THREAD

**Issue by tg95** [IntellectualSites/PlotSquared#1542]
Hello, i have some problem on import storage.db to mysql i do plot database mysql host etc etc and dont import, and dont say any error only do change on "config" mysql to true, some one can help me on import for mysql?

sorry for my bad english and thanks for help.

**Comment by boy0001** [comment]
`/plots database import storage.db`

**Comment by tg95** [comment]
hi, say convert finish but dont create folder on config and dont upload to mysql some problem? thanks for help

**Comment by boy0001** [comment]
The import is for when you already have MySQL configured.

**Comment by tg95** [comment]
i have configuration and dont upload nothing i need put mysql true?

**Comment by tg95** [comment]
hi, i try and say this error:

`[17:30:10] [Craft Scheduler Thread - 607/INFO]: [0;30;1m[[0;33;22mP2[0;30;1m] [0;37;22m[0;33;22mStarting player data caching for: world[m
[17:30:10] [Craft Scheduler Thread - 607/INFO]: [0;32;1mFast mode UUID caching enabled![m
[17:30:10] [Craft Scheduler Thread - 607/INFO]: [0;30;1m[[0;33;22mP2[0;30;1m] [0;37;22m[0;33;22mCached a total of: 40 UUIDs[m
[17:30:11] [Server thread/INFO]: tg95 issued server command: /p h
[17:30:15] [Server thread/INFO]: [0;30;1m[[0;33;22mP2[0;30;1m] [0;37;22m[0;33;22mStarting...[m
[17:30:15] [Server thread/WARN]: java.lang.NullPointerException
[17:30:15] [Server thread/WARN]: 	at com.intellectualcrafters.plot.object.Plot.create(Plot.java:1364)
[17:30:15] [Server thread/WARN]: 	at com.intellectualcrafters.plot.object.Plot.create(Plot.java:1308)
[17:30:15] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.Database.onCommand(Database.java:107)
[17:30:15] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27)
[17:30:15] [Server thread/WARN]: 	at com.plotsquared.general.commands.Command.execute(Command.java:337)
[17:30:15] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:259)
[17:30:15] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:134)
[17:30:15] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:34)
[17:30:15] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:30:15] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:30:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[17:30:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[17:30:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[17:30:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[17:30:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[17:30:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[17:30:15] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[17:30:15] [Server thread/INFO]: [0;30;1m[[0;33;22mP2[0;30;1m] [0;37;22m[0;37;22mAn error occurred: %s[m`

**Comment by CuzImWeed** [comment]
> hi, i try and say this error:
> [17:30:10] [Craft Scheduler Thread - 607/INFO]: �[0;30;1m[�[0;33;22mP2�[0;30;1m] �[0;37;22m�[0;33;22mStarting player data caching for: world�[m [17:30:10] [Craft Scheduler Thread - 607/INFO]: �[0;32;1mFast mode UUID caching enabled!�[m [17:30:10] [Craft Scheduler Thread - 607/INFO]: �[0;30;1m[�[0;33;22mP2�[0;30;1m] �[0;37;22m�[0;33;22mCached a total of: 40 UUIDs�[m [17:30:11] [Server thread/INFO]: tg95 issued server command: /p h [17:30:15] [Server thread/INFO]: �[0;30;1m[�[0;33;22mP2�[0;30;1m] �[0;37;22m�[0;33;22mStarting...�[m [17:30:15] [Server thread/WARN]: java.lang.NullPointerException [17:30:15] [Server thread/WARN]: 	at com.intellectualcrafters.plot.object.Plot.create(Plot.java:1364) [17:30:15] [Server thread/WARN]: 	at com.intellectualcrafters.plot.object.Plot.create(Plot.java:1308) [17:30:15] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.Database.onCommand(Database.java:107) [17:30:15] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27) [17:30:15] [Server thread/WARN]: 	at com.plotsquared.general.commands.Command.execute(Command.java:337) [17:30:15] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:259) [17:30:15] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:134) [17:30:15] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:34) [17:30:15] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [17:30:15] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [17:30:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [17:30:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [17:30:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [17:30:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [17:30:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [17:30:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [17:30:15] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745) [17:30:15] [Server thread/INFO]: �[0;30;1m[�[0;33;22mP2�[0;30;1m] �[0;37;22m�[0;37;22mAn error occurred: %s�[m

Do you have fixed the error? I got the same error
