### ISSUE TITLE
Auto-clear task does not work.

### ISSUE THREAD

**Issue by wasder** [IntellectualSites/PlotSquared#1562]
https://hastebin.com/vomucowome

I can't make auto-clear task to work at all. It never asks for a confirmation. Total plots >4200 many of them are expired.
I also tried with `confirmation: false` and got no luck.
I guess it does not detect expired plots. Could the reason be in 512*512 plots?

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
You should change the threshold, with your current settings it would only consider completely empty plots. A value of `-1` will have all plots older than 7 days expired.

**Comment by wasder** [comment]
How does it check the last player login?

**Comment by boy0001** [comment]
From the playerdata files.

**Comment by wasder** [comment]
What if there is no any playerdata files?

**Comment by wasder** [comment]
I am trying to make it work. Now I switched from online UUIDs to offline, made uuidconvert and now I got this.
```
[02:30:55] [Craft Scheduler Thread - 4/WARN]: Exception in thread "Craft Scheduler Thread - 4" 
[02:30:55] [Craft Scheduler Thread - 4/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.5.1-SNAPSHOT-478ad96 generated an exception while executing task 20
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: value already present: 5d6e9bf9-f2fc-3b7f-a9c1-f0f2a455a790
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
	at com.plotsquared.bukkit.uuid.SQLUUIDHandler$1.run(SQLUUIDHandler.java:82)
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```
https://hastebin.com/gamawecido

**Comment by boy0001** [comment]
Disable the SQLUUIDHandler with offline mode.

**Comment by wasder** [comment]
Did it. Still the same.

**Comment by wasder** [comment]
Also, I failed to mention, that we have our own unique player's UUIDs on server.
We changed the way players get their UUIDs on Bungeecord level. So players have unique UUIDs it's not online or offline ones.
We need it for our own authentication system.
