### ISSUE TITLE
Plot Home Error

### ISSUE THREAD

**Issue by CosmicPyrex** [IntellectualSites/PlotSquared#1571]
**Debug paste link:** 

```
02.04 21:13:36 [Server] ERROR Could not pass event ServerCommandEvent to Commandspy v3.2.0
02.04 21:13:36 [Server] INFO org.bukkit.event.EventException
02.04 21:13:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:36 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:36 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:432) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:36 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:36 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:36 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
02.04 21:13:36 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
02.04 21:13:36 [Server] INFO at net.korikisulda.commandspy3.EventListener.onServerCommandEvent(EventListener.java:66) ~[?:?]
02.04 21:13:36 [Server] INFO at sun.reflect.GeneratedMethodAccessor246.invoke(Unknown Source) ~[?:?]
02.04 21:13:36 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
02.04 21:13:36 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
02.04 21:13:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:36 [Server] INFO ... 8 more
02.04 21:13:36 [Server] WARN Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 218157
02.04 21:13:36 [Server] INFO java.lang.RuntimeException: Couldn't read response!
02.04 21:13:36 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43) ~[?:?]
02.04 21:13:36 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60) ~[?:?]
02.04 21:13:36 [Server] INFO at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29) ~[?:?]
02.04 21:13:36 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:36 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:36 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
02.04 21:13:36 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
02.04 21:13:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
02.04 21:13:47 [Server] ERROR Could not pass event ServerCommandEvent to Commandspy v3.2.0
02.04 21:13:47 [Server] INFO org.bukkit.event.EventException
02.04 21:13:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:47 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:47 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:432) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:47 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:47 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:47 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
02.04 21:13:47 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
02.04 21:13:47 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
02.04 21:13:47 [Server] INFO at net.korikisulda.commandspy3.EventListener.onServerCommandEvent(EventListener.java:66) ~[?:?]
02.04 21:13:47 [Server] INFO at sun.reflect.GeneratedMethodAccessor246.invoke(Unknown Source) ~[?:?]
02.04 21:13:47 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
02.04 21:13:47 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
02.04 21:13:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot_v1.11.2.jar:git-Spigot-4741400-c1aa859]
```
**Description of the problem:** 
When you do /plot h it says; *[P2] An error occured: %s*

**Console Log**
```
02.04 21:06:58 [Server] WARN java.lang.NullPointerException
02.04 21:06:58 [Server] WARN at com.plotsquared.bukkit.util.BukkitUtil.getHighestBlock(BukkitUtil.java:182)
02.04 21:06:58 [Server] WARN at com.intellectualcrafters.plot.object.Plot.getSide(Plot.java:1122)
02.04 21:06:58 [Server] WARN at com.intellectualcrafters.plot.object.Plot.getDefaultHome(Plot.java:1186)
02.04 21:06:58 [Server] WARN at com.intellectualcrafters.plot.object.Plot.getHome(Plot.java:1133)
02.04 21:06:58 [Server] WARN at com.intellectualcrafters.plot.object.Plot.teleportPlayer(Plot.java:2565)
02.04 21:06:58 [Server] WARN at com.intellectualcrafters.plot.commands.Visit$1.run(Visit.java:149)
02.04 21:06:58 [Server] WARN at com.intellectualcrafters.plot.commands.MainCommand$1.run(MainCommand.java:175)
02.04 21:06:58 [Server] WARN at com.intellectualcrafters.plot.commands.MainCommand$1.run(MainCommand.java:134)
02.04 21:06:58 [Server] WARN at com.intellectualcrafters.plot.commands.Visit.execute(Visit.java:146)
02.04 21:06:58 [Server] WARN at com.plotsquared.general.commands.Command.execute(Command.java:337)
02.04 21:06:58 [Server] WARN at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:259)
02.04 21:06:58 [Server] WARN at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:134)
02.04 21:06:58 [Server] WARN at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
02.04 21:06:58 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
02.04 21:06:58 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
02.04 21:06:58 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
02.04 21:06:58 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
02.04 21:06:58 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
02.04 21:06:58 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
02.04 21:06:58 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
02.04 21:06:58 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
02.04 21:06:58 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
02.04 21:06:58 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02.04 21:06:58 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
02.04 21:06:58 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
02.04 21:06:58 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
02.04 21:06:58 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
02.04 21:06:58 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
02.04 21:06:58 [Server] WARN at java.lang.Thread.run(Thread.java:745)
```
**How to replicate:** 
Just literally do /plot h

**Checklist**:

- [ ] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Can you see if updating fixes the issue?
 - http://ci.athion.net/job/PlotSquared/

If the problem persists:
 - Include a `/plot debugpaste`
 - Ensure that the world is loaded
