### ISSUE TITLE
I can´t create a road schematic

### ISSUE THREAD

**Issue by Agnl** [IntellectualSites/PlotSquared#1575]
# Bug report template 
**Debug paste link**
**https://hastebin.com/kohuxafutu** 

**Description of the problem:** 
I use the comand "/plot createroadschematic" and i get error "An error ocurred %s"
![s](https://cloud.githubusercontent.com/assets/27027146/24822987/44ad120e-1bd0-11e7-9eca-2a7aede9e94e.png)

**Checklist**:
I included a `/plot debugpaste` link
I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
I made sure I am using an up-to-date version of PlotSquared
I Made sure the bug/error is not caused by any other plugin

**Comment by loveyanbei** [comment]
encountering NullPointerException in HybridUtils.java
s.MainCommand:execute:263]: 	at java.lang.Thread.run(Thread.java:745)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: java.lang.NullPointerException
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at com.intellectualcrafters.plot.generator.HybridUtils.get_ey(HybridUtils.java:365)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at com.intellectualcrafters.plot.generator.HybridUtils.setupRoadSchematic(HybridUtils.java:331)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at com.intellectualcrafters.plot.commands.CreateRoadSchematic.onCommand(CreateRoadSchematic.java:32)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at com.plotsquared.general.commands.Command.execute(Command.java:337)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:259)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:134)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at com.plotsquared.sponge.util.SpongeCommand.lambda$process$10(SpongeCommand.java:41)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:81)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:51)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:271)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[15:59:41] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.commands.MainCommand:execute:263]: 	at java.lang.Thread.run(Thread.java:745)
>

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
