### ISSUE TITLE
cannot claim plots

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1585]
```
[16:56:49] [Server thread/INFO]: PhanaticD issued server command: /plot auto
[16:56:49] [Craft Scheduler Thread - 4/INFO]: ============ DATABASE ERROR ============
[16:56:49] [Craft Scheduler Thread - 4/INFO]: There was an error updating the database.
[16:56:49] [Craft Scheduler Thread - 4/INFO]:  - It will be correct on shutdown
[16:56:49] [Craft Scheduler Thread - 4/INFO]: ========================================
[16:56:49] [Craft Scheduler Thread - 4/WARN]: java.lang.IllegalStateException: Asynchronous chunk load!
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.loadChunk(CraftWorld.java:305)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at org.bukkit.craftbukkit.v1_11_R1.CraftChunk.load(CraftChunk.java:126)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at com.plotsquared.bukkit.util.BukkitChunkManager.loadChunk(BukkitChunkManager.java:376)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at com.boydti.fawe.regions.general.plot.FaweChunkManager.loadChunk(FaweChunkManager.java:32)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at com.intellectualcrafters.plot.object.Plot.guessOwner(Plot.java:2035)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at com.intellectualcrafters.plot.object.Plot.canClaim(Plot.java:2018)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at com.intellectualcrafters.plot.object.PlotArea.getNextFreePlot(PlotArea.java:690)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at com.intellectualcrafters.plot.commands.Auto.autoClaimSafe(Auto.java:197)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at com.intellectualcrafters.plot.commands.Auto$2.run(Auto.java:207)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at com.intellectualcrafters.plot.database.SQLManager$13.addBatch(SQLManager.java:1053)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:358)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at com.intellectualcrafters.plot.database.SQLManager$1.run(SQLManager.java:148)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[16:56:49] [Craft Scheduler Thread - 4/WARN]:   at java.lang.Thread.run(Thread.java:745)
[16:56:49] [Craft Scheduler Thread - 4/INFO]: ========================================
```

using build 477 https://github.com/IntellectualSites/PlotSquared/commit/b616951e2353f4eb0eb67e36a8285cb4c94105fc

**Comment by PhanaticD** [comment]
also when standing on an empty plot and typing /plot claim it just says plot not claimed

**Comment by frizzbee30** [comment]
latest build 477 seems to fix the p auto, but I am also having issues with basic p claim in test with this build.

**Comment by mibby** [comment]
Still not working according to my testing. See; https://github.com/IntellectualSites/PlotSquared/commit/3c110bb125ca9fb4a719e37174bbdf360576d927#commitcomment-21828990

**Comment by frizzbee30** [comment]
Hi, we also lost /p auto in latest build with 'no plots available' or similar.

**Comment by frizzbee30** [comment]
latest build appears to have resolved the issue. Thanks
