### ISSUE TITLE
setweather issue

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1588]
```
16:56:42 [CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerMoveEvent' to 'PlotSquared v3.5.1-SNAPSHOT-7eb7cd9': null on com.plotsquared.nukkit.listeners.PlayerEvents
16:56:42 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.Player.processMovement(Player.java:1441)
        at cn.nukkit.Player.onUpdate(Player.java:1572)
        at cn.nukkit.level.Level.doTick(Level.java:762)
        at cn.nukkit.Server.checkTickUpdates(Server.java:946)
        at cn.nukkit.Server.tick(Server.java:1021)
        at cn.nukkit.Server.tickProcessor(Server.java:808)
        at cn.nukkit.Server.start(Server.java:787)
        at cn.nukkit.Server.<init>(Server.java:472)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.UnsupportedOperationException: Not implemented yet: setWeather
        at com.plotsquared.nukkit.object.NukkitPlayer.setWeather(NukkitPlayer.java:148)
        at com.plotsquared.listener.PlotListener.plotEntry(PlotListener.java:123)
        at com.plotsquared.nukkit.listeners.PlayerEvents.playerMove(PlayerEvents.java:528)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 11 more

```

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
