### ISSUE TITLE
Terrain generating from specific location

### ISSUE THREAD

**Issue by Ishidres** [IntellectualSites/PlotSquared#1601]
**Debug paste link:** 
**Failure!** If I execute /p debugpaste nothing happens. I just get this error:
```
[15:58:06] [Server thread/INFO]: Ishidres issued server command: /p debugpaste
[15:58:06] [Craft Scheduler Thread - 254/WARN]: Exception in thread "
[15:58:06] [Craft Scheduler Thread - 254/WARN]: Craft Scheduler Thread - 254
[15:58:06] [Craft Scheduler Thread - 254/WARN]: " 
[15:58:06] [Craft Scheduler Thread - 254/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 27276
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Couldn't read response!
        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43)
        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60)
        at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Description of the problem:** 
The problem is that at a specifiy position of the world, it starts generating terrain. I also tried removing and reimporting the world in Multiverse, but it's still the same.

![2017-05-06_15 55 31](https://cloud.githubusercontent.com/assets/17363426/25773064/531e9822-3277-11e7-8df8-2c85e238dfaa.png)
![2017-05-06_15 55 26](https://cloud.githubusercontent.com/assets/17363426/25773065/5322e6a2-3277-11e7-9a29-661cbc20125c.png)

**How to replicate:** 
The terrain starts generating from 0 0 -509 and goes infinite far into the negative (e.g. at 0 0 -700 there is still terrain).

**Checklist**:
- [] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report _(there are a few, but their problem gets produced in an other way)_
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**More**:
Multiverse world configuration:
```
  Creative:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: EASY
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.0
      y: 65.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '7896754200908962778'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'
```

PlotSquared world configuration:
```
worlds:
  Creative:
    generator:
      plugin: PlotSquared
    plot:
      height: 64
      size: 32
      filling:
      - '1:0'
      floor:
      - '2:0'
      bedrock: true
      biome: FOREST
      auto_merge: false
      create_signs: true
    wall:
      block: '44:5'
      block_claimed: '44:4'
      filling: '1:0'
      height: 64
    road:
      width: 7
      height: 64
      block: '5:2'
    home:
      default: side
      allow-nonmembers: false
    schematic:
      specify_on_claim: false
      on_claim: false
      file: 'null'
      schematics: []
    economy:
      prices:
        merge: 100
        sell: 100
        claim: 100
      use: false
    chat:
      enabled: false
    limits:
      max-members: 128
    world:
      max_height: 256
      gamemode: creative
      min_height: 1
      border: false
    event:
      spawn:
        egg: false
        breeding: false
        custom: true
    natural_mob_spawning: false
    mob_spawner_spawning: false
    flags: {}
```

**Comment by Ishidres** [comment]
nobody? really? :cry:

**Comment by boy0001** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Manual-generator-setting

**Comment by Ishidres** [comment]
It's still happening :(

**Comment by dordsor21** [comment]
are you using the latest versions of P2 and MV? http://ci.athion.net/job/PlotSquared/ for P2 (you're the only one with this issue)

**Comment by Ishidres** [comment]
I've got the latest version of MV an I just installed the 3.5.1 version of P² (PlotSquared-Bukkit-3.5.1-SNAPSHOT-355e16f).
But it's still happening. :(
Any other idea?

**Comment by dordsor21** [comment]
is it after server restarts?

**Comment by Ishidres** [comment]
Yes, I already restarted the server with the plugin, but it's still happening.
