### ISSUE TITLE
Plot schematic paste error.

### ISSUE THREAD

**Issue by download042** [IntellectualSites/PlotSquared#1619]
**Debug paste link:** 

> [19:16:34 WARN]: Exception in thread "Craft Scheduler Thread - 3" 
> [19:16:34 WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 697
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Couldn't read response!
at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43)
at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60)
at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

**Description of the problem:** 

Plot schematic is not pasting, but the schematic is correct.

**How to replicate:** 

I builded some plots, and is saved theese, into schematics:  /plot sch save
After the schematic is saved, i try to paste.
1-2 paste was successfully, but once the command did not work.
I checked the console, and for errors, and i received this:

[19:19:48] [Craft Scheduler Thread - 20/WARN]: Exception in thread "Craft Scheduler Thread - 20" 
[19:19:48] [Craft Scheduler Thread - 20/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 1671
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Asynchronous entity world add!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
	at net.minecraft.server.v1_8_R3.World.b(World.java:2633)
	at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:820)
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115)
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97)
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:126)
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90)
	at com.plotsquared.bukkit.object.schematic.StateWrapper.restoreTag(StateWrapper.java:65)
	at com.plotsquared.bukkit.util.BukkitSchematicHandler.restoreTile(BukkitSchematicHandler.java:308)
	at com.intellectualcrafters.plot.util.SchematicHandler$2$1.run(SchematicHandler.java:335)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

After this error,I tried to paste it again, and i received this error in chat: "Task is already running."
No more errors in console, the paste command is crashed, the server need restart to work.

Thank you in advance for your answer

**Comment by Zarpez0** [comment]
Did you fix the problem ?

**Comment by download042** [comment]
No. :/
