### ISSUE TITLE
/p kick [ign] teleporting players into the void under the plot spawn?

### ISSUE THREAD

**Issue by James126788** [IntellectualSites/PlotSquared#1621]
****Debug paste link:**** 
[20:17:36 WARN]: Exception in thread "Craft Scheduler Thread - 2120"
[20:17:36 WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.5.0 generated an exception while executing task 2873939
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Couldn't read response!
        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43)
        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60)
        at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
****Description of the problem:**** 
I help to manange a Opprison server that has a free rank (includes creative plots) and than there are survival plots. When another player is on your plot or you are on another plot and they decide to use the command /p kick it sends that kicked player under the plot world spawn which than they go and fall into the void and loose their items.

**How to replicate:** 
1. another player on someone's plot
2. the player is kicked by the plot owner
3. they are teleported under spawn and die

**Comment by RedstoneFuture** [comment]
Can you test it with the last version?
