### ISSUE TITLE
Error loading the plugin

### ISSUE THREAD

**Issue by DaragonOne** [IntellectualSites/PlotSquared#1626]
[17:10:59] [Server thread/INFO]: [PlotSquared] Enabling PlotSquared v3.5.0-SNAPSHOT-95f8aaa
[17:11:00] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/sqlite/NativeDB
[17:11:00] [Server thread/WARN]: 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[17:11:00] [Server thread/WARN]: 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
[17:11:00] [Server thread/WARN]: 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
[17:11:00] [Server thread/WARN]: 	at java.lang.Runtime.load0(Runtime.java:809)
[17:11:00] [Server thread/WARN]: 	at java.lang.System.load(System.java:1086)
[17:11:00] [Server thread/WARN]: 	at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:272)
[17:11:00] [Server thread/WARN]: 	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:308)
[17:11:00] [Server thread/WARN]: 	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64)
[17:11:00] [Server thread/WARN]: 	at org.sqlite.core.NativeDB.load(NativeDB.java:56)
[17:11:00] [Server thread/WARN]: 	at org.sqlite.core.CoreConnection.open(CoreConnection.java:211)
[17:11:00] [Server thread/WARN]: 	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
[17:11:00] [Server thread/WARN]: 	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26)
[17:11:00] [Server thread/WARN]: 	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
[17:11:00] [Server thread/WARN]: 	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
[17:11:00] [Server thread/WARN]: 	at org.sqlite.JDBC.createConnection(JDBC.java:114)
[17:11:00] [Server thread/WARN]: 	at org.sqlite.JDBC.connect(JDBC.java:88)
[17:11:00] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
[17:11:00] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:270)
[17:11:00] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLite.openConnection(SQLite.java:47)
[17:11:00] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.<init>(SQLManager.java:105)
[17:11:00] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.setupDatabase(PS.java:1846)
[17:11:00] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:162)
[17:11:00] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:183)
[17:11:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[17:11:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[17:11:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[17:11:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
[17:11:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
[17:11:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205)
[17:11:00] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
[17:11:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[17:11:00] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.sqlite.NativeDB
[17:11:00] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[17:11:00] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:11:00] [Server thread/WARN]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
[17:11:00] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:11:00] [Server thread/WARN]: 	... 31 more

Somebody know the solution for this?

**Comment by dordsor21** [comment]
are you using the latest version of P2 from http://ci.athion.net/job/PlotSquared/ ?

**Comment by DaragonOne** [comment]
I update it now but still the same problem

**Comment by dordsor21** [comment]
has this been happening for the entire time you've had P2 installed?

**Comment by DaragonOne** [comment]
No, the problem start today...

**Comment by dordsor21** [comment]
can you include a /ps debugpaste and have you tried updating SQLite drivers?

**Comment by DaragonOne** [comment]
/ps debugpaste does't work... Generally some plugins dont load correctly. How I can update the SQLite drivers?... I have the same problem with WorldGuard and others

**Comment by dordsor21** [comment]
what OS are you using?

**Comment by DaragonOne** [comment]
I have a hosted server... I think is CentOS. I recently talk to the provider for Java 8 Update because some plugins need it

**Comment by dordsor21** [comment]
You'll need to do the same here then

**Comment by DaragonOne** [comment]
What do you mean?
