### ISSUE TITLE
can only build on half my plot?

### ISSUE THREAD

**Issue by Junior1544** [IntellectualSites/PlotSquared#1637]
Good day!

I have gotten my server mostly up and running...  
I seem to be having an odd problem...  I have a plot, i can only build on half of it..

I don't understand what's going on there, but it's weird.  when I try one one half everything works as expected.  when I go to the otherside of my plot it doesn't work, it start to looks like it works and about 1/4 of a second later it returns to how it was.

I have another user and they said that they can't build (or break blocks) on their plot at all.

There's no error or permission issue, it just goes back to how it was.  I can't build or break blocks.

There is nothing showing up when I do this on the console, or in game.

`/plot debugpaste` info:

[09:08:08] [Server thread/INFO]: Junior1544 issued server command: /plot debugpaste
[09:08:08] [Craft Scheduler Thread - 7/WARN]: [PlotSquared] Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 38
java.lang.RuntimeException: Couldn't read response!
	at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43) ~[?:?]
	at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60) ~[?:?]
	at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-8cbfc85-ec47e79]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-8cbfc85-ec47e79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

[I didn't see any similar issues when I searched the issues area]
[I am using the most up to date version of spigot and the plugin I can find]
[I remost all plugins except multiverse to see if it was one of them and it still happened, actually was worse without the permissions plugin, with out my permissions plugin (PEX) I couldn't break or build anything at all]

**Comment by dordsor21** [comment]
Is your plot right near the spawn for the world, and do you have spawn-protection enabled (is the radius greater than 0)
