### ISSUE TITLE
Errors on schematic resuming on claiming

### ISSUE THREAD

**Issue by l89669** [IntellectualSites/PlotSquared#1646]
Exception happens on claiming a plot.
I've set a schematic but nothing appear on claiming.
Server: Thermos 58, 1.7.10, Java 8, PlotSq 3.5.0u2

Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.plotsquared.bukkit.object.schematic.StateWrapper.restoreTag(StateWrapper.java:56)
        at com.plotsquared.bukkit.util.BukkitSchematicHandler.restoreTile(BukkitSchematicHandler.java:308)
        at com.intellectualcrafters.plot.util.SchematicHandler$2$1.run(SchematicHandler.java:335)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
