### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by juzhijian** [IntellectualSites/PlotSquared#1663]
[22:54:15 WARN]: java.lang.reflect.InvocationTargetException
[22:54:15 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:54:15 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[22:54:15 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:54:15 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.util.block.QueueProvider$1.getNewQueue(QueueProvider.java:15)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.util.block.GlobalBlockQueue.getNewQueue(GlobalBlockQueue.java:69)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.object.PlotArea.getQueue(PlotArea.java:113)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.generator.HybridPlotManager.clearPlot(HybridPlotManager.java:166)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.object.Plot$1.run(Plot.java:795)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.object.Plot.clear(Plot.java:807)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.commands.Clear$1.run(Clear.java:44)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand$1.run(MainCommand.java:175)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand$1.run(MainCommand.java:134)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.commands.Clear.execute(Clear.java:40)
[22:54:15 WARN]:        at com.plotsquared.general.commands.Command.execute(Command.java:337)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:259)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:134)
[22:54:15 WARN]:        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
[22:54:15 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:54:15 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[22:54:15 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740)
[22:54:15 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370)
[22:54:15 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107)
[22:54:15 WARN]:        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[22:54:15 WARN]:        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[22:54:15 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[22:54:15 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
[22:54:15 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
[22:54:15 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[22:54:15 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[22:54:15 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[22:54:15 WARN]:        at java.lang.Thread.run(Thread.java:748)
[22:54:15 WARN]: Caused by: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/Block
[22:54:15 WARN]:        at java.lang.Class.forName0(Native Method)
[22:54:15 WARN]:        at java.lang.Class.forName(Class.java:264)
[22:54:15 WARN]:        at com.intellectualcrafters.plot.util.ReflectionUtils.getRefClass(ReflectionUtils.java:215)
[22:54:15 WARN]:        at com.plotsquared.bukkit.util.block.BukkitLocalQueue_1_7.<init>(BukkitLocalQueue_1_7.java:24)
[22:54:15 WARN]:        ... 32 more

**Comment by dordsor21** [comment]
when do you get this? And do you still get this?
