### ISSUE TITLE
I think its conflic on other plugins please fix sir

### ISSUE THREAD

**Issue by juliu123** [IntellectualSites/PlotSquared#1699]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

```
RPGItems Error
[02:34:41] [Server thread/INFO]: [RPGItems] Enabling RPGItems v3.5.231
[02:34:41] [Server thread/WARN]: [RPGItems] Could not save en_GB.lang to plugins\RPGItems\locale\en_GB.lang because en_GB.lang already exists.
[02:34:41] [Server thread/INFO]: [RPGItems] WorldGuard version 6.1.3 : 6.1.3-SNAPSHOT;c904242 found
[02:34:41] [Server thread/ERROR]: Error occurred while enabling RPGItems v3.5.231 (Is it up to date?)
java.lang.NullPointerException
	at think.rpgitems.support.WGHandler.registerHandler(WGHandler.java:76) ~[?:?]
	at think.rpgitems.support.WorldGuard.init(WorldGuard.java:88) ~[?:?]
	at think.rpgitems.Plugin.onEnable(Plugin.java:54) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]

CratesPlus Error
[02:34:41] [Server thread/INFO]: [CratesPlus] Enabling CratesPlus v4.4.2
[02:34:41] [Server thread/ERROR]: Error occurred while enabling CratesPlus v4.4.2 (Is it up to date?)
java.lang.NullPointerException
	at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at plus.crates.CratesPlus.loadMetaData(CratesPlus.java:443) ~[?:?]
	at plus.crates.CratesPlus.onEnable(CratesPlus.java:212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]

ProBedwars Error
[02:34:41] [Server thread/INFO]: [ProBedwars] Enabling ProBedwars v2.6
[02:34:42] [Server thread/INFO]: [[0;36;1mBedWars[0;37;22m] Loaded [0;36;1m0[0;37;22m Sign(s)![m
[02:34:43] [Server thread/ERROR]: Error occurred while enabling ProBedwars v2.6 (Is it up to date?)
java.lang.NullPointerException
	at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at io.gabbo200.github.Bedwars.gamemanager.Arena.loadSigns(Arena.java:294) ~[?:?]
	at io.gabbo200.github.Bedwars.gamemanager.Arena.<init>(Arena.java:250) ~[?:?]
	at io.gabbo200.github.Bedwars.Main.loadArenas(Main.java:790) ~[?:?]
	at io.gabbo200.github.Bedwars.Main.onEnable(Main.java:257) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]

ProSkywars Error
[02:34:43] [Server thread/INFO]: [ProSkyWars] Enabling ProSkyWars v1.0
[02:34:48] [Server thread/INFO]: [[0;36;1mSkyWars[0;37;22m] Loaded [0;36;1m5[0;37;22m Sign(s)![m
[02:34:48] [Server thread/ERROR]: Error occurred while enabling ProSkyWars v1.0 (Is it up to date?)
java.lang.NullPointerException
	at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at com.mineorigin.minigame.gamemanager.Arena.verifyChests(Arena.java:501) ~[?:?]
	at com.mineorigin.minigame.gamemanager.Arena.<init>(Arena.java:207) ~[?:?]
	at com.mineorigin.minigame.Main.loadArenas(Main.java:746) ~[?:?]
	at com.mineorigin.minigame.Main.onEnable(Main.java:262) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
```

I hope you can fix it
if i remove your plugin my server runs fine
thank you in advance <3

**Comment by boy0001** [comment]
Please include a `/plot debugpaste`

**Comment by juliu123** [comment]
/plot debugpaste: https://hastebin.com/efopivifac

here sir.

**Comment by boy0001** [comment]
First error occurs because you have the wrong version of WorldGuard. The build failed, and it was for 1.10 anyway. Error occurs without PlotSquared installed. Update the plugin.

Second error occurs because the plugin never checks if the world is loaded (or exists) when reading the locations from the config. Clearing the `CratesPlus` config would probably fix it. Doesn't seem to be related to PlotSquared being installed. 

The rest are premium, and closed source, so I can't help you there. Get the author to fix the issue.
