### ISSUE TITLE
java.lang.IllegalArgumentException: value already present

### ISSUE THREAD

**Issue by L4BORG** [IntellectualSites/PlotSquared#1702]
# Bug report template 
**Debug paste link:** 

**Description of the problem:** 
```
[20:15:02] [Craft Scheduler Thread - 1/WARN]: Exception in thread "Craft Scheduler Thread - 1" 
[20:15:02] [Craft Scheduler Thread - 1/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v17.08.18-17154ef-1907 generated an exception while executing task 17
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: value already present: c99e8ea0-ab4f-3804-9ae4-555add2cc272
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
	at com.plotsquared.bukkit.uuid.SQLUUIDHandler$1.run(SQLUUIDHandler.java:82)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

**How to replicate:** 
Looks like crashing or some other issue caused DB to have dupliate UUIDs

**Checklist**:

- [] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
