### ISSUE TITLE
Disposing or clearing of plots does not work properly

### ISSUE THREAD

**Issue by Marcy135** [IntellectualSites/PlotSquared#1705]
**Debug paste link:** 
Debug does not working:
`org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 185
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Couldn't read response!
        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43)
        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60)
        at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more`

**Description of the problem:**
If I have a plot claime and then dispose or cleare, I get instead of my schematic a piece of the normal world on the plot. I have already tried to delete the world from the Config and re-create but that does not help.
I have installed the following plugins: AreaShop, AutoRestart, Bungee, BungeeServerSelector, Chairs, ChatEx, Chestshop, chatlog, ChopTree, CleanroomGenerator, ColoredSigns, ColoredTags, CommandAlias, CS-CoreLib, CustomJoinItems, CustomTab, Trash, EssentialsX, EssentialswarpGui, Holograms, iConomy , Jobs, Jails, LogBlock, LWC, MinePacks, Multiverse, MyCommand, OpenInv, PlotSquared, Portallink, RealTime, RemoteToolKit, TitleManager, Towny, ViaVersion, Votifier, Worldedit, Worldguard

**How to replicate:** 
Just claim a Plot and then clear it ore dispose it. Then you have the piece of normal world.

**Checklist**:
- [X] I included a `/plot debugpaste` link (Does not work, see above)
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin
I have so far checked whether it comes from another plugin. But I'm not sure if it really is.

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
