### ISSUE TITLE
Problem with excavation peaks (3x3 or 3x2) with plot walls

### ISSUE THREAD

**Issue by DanielTravi** [IntellectualSites/PlotSquared#1714]
**Description of the problem:** 

When I peak using a 3x3 peak of the plugin SlimeFun and EnchantsPlus and break the block before the wall of the plot also breaks the protected part out off the plot

SlimeFun: https://dev.bukkit.org/projects/slimefun
EnchantPlus: https://www.spigotmc.org/resources/enchantsplus.3396/

**How to replicate:** 

![2017-09-05_02 56 30](https://user-images.githubusercontent.com/26859457/30040951-fdefd450-91e5-11e7-9da1-914a3e265529.png)

![2017-09-05_02 56 36](https://user-images.githubusercontent.com/26859457/30040968-2df109ee-91e6-11e7-8c88-2c26a18b4994.png)

![2017-09-05_02 56 41](https://user-images.githubusercontent.com/26859457/30040982-4fd5a538-91e6-11e7-8b77-b5d80c34c436.png)

![2017-09-05_02 59 02](https://user-images.githubusercontent.com/26859457/30040991-62800b92-91e6-11e7-896e-a220159dd691.png)

**Checklist**:

>ps debugpaste
[02:46:42 WARN]: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
[02:46:42 WARN]:        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[02:46:42 WARN]:        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
[02:46:42 WARN]:        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
[02:46:42 WARN]:        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
[02:46:42 WARN]:        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[02:46:42 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[02:46:42 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[02:46:42 WARN]:        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[02:46:42 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[02:46:42 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
[02:46:42 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
[02:46:42 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
[02:46:42 WARN]:        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:24)
[02:46:42 WARN]:        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60)
[02:46:42 WARN]:        at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29)
[02:46:42 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[02:46:42 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[02:46:42 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[02:46:42 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[02:46:42 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by DanielTravi** [comment]
?¿
