### ISSUE TITLE
Failed to tab complete

### ISSUE THREAD

**Issue by guuslieben** [IntellectualSites/PlotSquared#1768]
**Debug paste link:**
https://hastebin.com/arogiteqas

**Description of the problem:** 
Whenever both in-game or console users try to tab complete anything within the PlotSquared provided commands, nothing happens except for this output in the console : https://gist.github.com/guuslieben/c847a2e9caead33d18fc3501351bb32a

Using PlotSquared-Sponge-17.11.14-734c4bb-1937.jar

**How to replicate:** 
Execute /p2, /plots, /plot and use [Tab] to autocomplete, error messages occur in console.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)]
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Tollainmear** [comment]
I have the same problem with p2.
[gist](https://gist.github.com/Tollainmear/97e07b1fbf08eee2fca3474cc4952ebc)

Using version=17.12.09-59557cf-1945

**Comment by lurr** [comment]
Please note: Your hastebin link is invalid.

**Comment by guuslieben** [comment]
@lurr To be expected as I recieved no reponse for over 2 months. Here is an updated link https://hastebin.com/quwoqusocu

**Comment by RedstoneFuture** [comment]
Hello. Have you still this problem with a currently PlotSquared version?

**Comment by guuslieben** [comment]
@RedstoneFuture I am still experiencing this issue. We recently updated to 1.12.2 (coming from 1.10.2) yet the issue persists.

**Comment by BrainStone** [comment]
I am also experiencing this issue.

StackTrace:

```
> [21:26:39] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error occured while tab completing 'plot visit worl'
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_161]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_161]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:277) [SpongeImplHooks.class:1.12.2-2655-7.1.0-BETA-3065]
at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3975) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.RuntimeException: Error occured while tab completing 'plot visit worl'
at org.spongepowered.common.command.SpongeCommandManager.getSuggestions(SpongeCommandManager.java:404) ~[SpongeCommandManager.class:1.12.2-2655-7.1.0-BETA-3065]
at net.minecraft.server.MinecraftServer.redirect$onGetTabCompletionOptions$zjg000(MinecraftServer.java:3743) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:918) ~[MinecraftServer.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1347) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[kz.class:?]
at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[kz.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:150) ~[PacketUtil.class:1.12.2-2655-7.1.0-BETA-3065]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539) ~[hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
... 7 more
Caused by: java.lang.NullPointerException
at java.util.ArrayList.<init>(ArrayList.java:178) ~[?:1.8.0_161]
at org.spongepowered.common.command.SpongeCommandManager.getSuggestions(SpongeCommandManager.java:390) ~[SpongeCommandManager.class:1.12.2-2655-7.1.0-BETA-3065]
at net.minecraft.server.MinecraftServer.redirect$onGetTabCompletionOptions$zjg000(MinecraftServer.java:3743) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:918) ~[MinecraftServer.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1347) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[kz.class:?]
at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[kz.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:150) ~[PacketUtil.class:1.12.2-2655-7.1.0-BETA-3065]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539) ~[hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
... 7 more
```

**Comment by guuslieben** [comment]
c7a1526 does not fix the issue. So far it only keeps the console clean by not throwing the stacktrace, but tab completion still does not work. This is best noticed by using the /plot trust {player} command where tab-completion takes place to fill out the player variable.
