### ISSUE TITLE
There are some mistakes after receiving the territory

### ISSUE THREAD

**Issue by cocomine** [IntellectualSites/PlotSquared#1797]
# Bug report template 

**Debug paste link:** 
https://hastebin.com/qatazeheho

**Description of the problem:** 
There are some mistakes after receiving the territory
Error:
[21:17:07 WARN]: [PlotSquared] Task #2004 for PlotSquared v17.12.07-6c06e48-1944 generated an exception
java.lang.RuntimeException: Could not create schematic parent directory
	at com.intellectualcrafters.plot.util.SchematicHandler.getSchematic(SchematicHandler.java:449) ~[?:?]
	at com.intellectualcrafters.plot.object.Plot.claim(Plot.java:1359) ~[?:?]
	at com.intellectualcrafters.plot.commands.Auto$1$1.run(Auto.java:226) ~[?:?]
	at com.intellectualcrafters.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.intellectualcrafters.plot.util.TaskManager.sync(TaskManager.java:27) ~[?:?]
	at com.intellectualcrafters.plot.util.TaskManager.sync(TaskManager.java:22) ~[?:?]
	at com.intellectualcrafters.plot.commands.Auto$1.run(Auto.java:220) ~[?:?]
	at com.intellectualcrafters.plot.commands.Auto$1.run(Auto.java:217) ~[?:?]
	at com.intellectualcrafters.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**How to replicate:** 
He did not generate what I set up to receive the territory
Config:
schematic:
      specify_on_claim: false
      on_claim: true
      file: 'plots'
      schematics: []

**Comment by cocomine** [comment]
ok i fix it
