### ISSUE TITLE
This error completely occupy the background output!

### ISSUE THREAD

**Issue by cocomine** [IntellectualSites/PlotSquared#1801]
Hello this not bug
This error completely occupy the background output!
My server is 1.8.8

```
[23:40:06 WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/Shulker
[23:40:06 WARN]:     at com.plotsquared.bukkit.BukkitMain$4$1.run(BukkitMain.java:489)
[23:40:06 WARN]:     at com.plotsquared.bukkit.BukkitMain$4$1.run(BukkitMain.java:327)
[23:40:06 WARN]:     at com.intellectualcrafters.plot.PS.foreachPlotArea(PS.java:1801)
[23:40:06 WARN]:     at com.plotsquared.bukkit.BukkitMain$4.run(BukkitMain.java:327)
[23:40:06 WARN]:     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[23:40:06 WARN]:     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[23:40:06 WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[23:40:06 WARN]:     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[23:40:06 WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[23:40:06 WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[23:40:06 WARN]:     at java.lang.Thread.run(Thread.java:745)
```

edit, dordsor21: fix formatting

**Comment by cocomine** [comment]
這個令我非常之困擾

**Comment by cocomine** [comment]
This is very disturbing to me

**Comment by cocomine** [comment]
https://hastebin.com/wifozuvami

**Comment by boy0001** [comment]
Fixed, please update.
