### ISSUE TITLE
start-up error spam

### ISSUE THREAD

**Issue by xXIOSCARIXx** [IntellectualSites/PlotSquared#1827]
[13:54:58 WARN]: java.lang.NullPointerException
[13:54:58 WARN]:        at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[13:54:58 WARN]:        at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[13:54:58 WARN]:        at java.lang.reflect.Field.get(Field.java:393)
[13:54:58 WARN]:        at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:388)
[13:54:58 WARN]:        at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[13:54:58 WARN]:        at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[13:54:58 WARN]:        at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[13:54:58 WARN]:        at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[13:54:58 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[13:54:58 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:54:58 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:54:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[13:54:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[13:54:58 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by SteveDog1** [comment]
Same problem is happening to me, would like if we got a response to the problem. If you ended up finding how to fix it, please say how.

**Comment by RedstoneFuture** [comment]
Is this the full error "Stacktrace"? Have you still this problem?

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
