### ISSUE TITLE
NukkitX NPE with buckets

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1853]
Not sure if this is a nukkit issue or a plotsquared issue, let me know if its nukkit fault ill report it there

```
10:46:14 [CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerBucketEmptyEvent' to 'PlotSquared v18.01.10-02b3581-1953': null on com.plotsquared.nukkit.listeners.PlayerEvents
10:46:14 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.block.BlockCauldron.onActivate(BlockCauldron.java:108)
        at cn.nukkit.level.Level.useItemOn(Level.java:1953)
        at cn.nukkit.level.Level.useItemOn(Level.java:1917)
        at cn.nukkit.Player.handleDataPacket(Player.java:2770)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:1979)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1004)
        at cn.nukkit.Server.tickProcessor(Server.java:807)
        at cn.nukkit.Server.start(Server.java:786)
        at cn.nukkit.Server.<init>(Server.java:473)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)
Caused by: java.lang.NullPointerException
        at cn.nukkit.math.Vector3.getSide(Vector3.java:140)
        at cn.nukkit.level.Position.getSide(Position.java:75)
        at cn.nukkit.block.Block.getSide(Block.java:969)
        at cn.nukkit.block.Block.getSide(Block.java:964)
        at com.plotsquared.nukkit.listeners.PlayerEvents.onBucketEmpty(PlayerEvents.java:1026)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 19 more
```

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
