### ISSUE TITLE
Cannot delete plots

### ISSUE THREAD

**Issue by Deliphin** [IntellectualSites/PlotSquared#1867]
**Debug paste link:** 
[/plot debugpaste output](https://hastebin.com/eziriwidiy).
[config.yml](https://hastebin.com/yocabatige.yml).
[worlds.yml](https://hastebin.com/vesisoqijo.yml).
I have not modified commands.yml or storage.yml.
Console output:
```java
[19:38:37 INFO]: Aria_S issued server command: /plotsquared:plot confirm [19:38:37 WARN]: [PlotSquared] Task #4365 for PlotSquared v18.02.02-73d0068-1961 generated an exception java.lang.NullPointerException: null at com.intellectualcrafters.plot.util.block.LocalBlockQueue.setBlock(LocalBlockQueue.java:48) ~[?:?] at com.intellectualcrafters.plot.util.block.LocalBlockQueue.setCuboid(LocalBlockQueue.java:97) ~[?:?] at com.intellectualcrafters.plot.generator.ClassicPlotManager.createRoadEast(ClassicPlotManager.java:304) ~[?:?] at com.intellectualcrafters.plot.generator.HybridPlotManager.createRoadEast(HybridPlotManager.java:55) ~[?:?] at com.intellectualcrafters.plot.object.Plot.unlinkPlot(Plot.java:877) ~[?:?] at com.intellectualcrafters.plot.object.Plot.clear(Plot.java:769) ~[?:?] at com.intellectualcrafters.plot.object.Plot.deletePlot(Plot.java:1006) ~[?:?] at com.intellectualcrafters.plot.commands.Delete$1.run(Delete.java:53) ~[?:?] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-1c40a81] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```
**Description of the problem:** 
If I try to delete a plot I own that I'm in, then do /plot info, it shows I still own the plot. I checked the console log and found the above output right after.
I have some custom roads already set up, I don't think that matters, though.
I don't believe any other plugins would be causing issues. We do have one command overlap, both Towny and PlotSquared take up /plot, however I've been using /plotsquared:plot to force using Plotsquared's commands.

**How to replicate:** 
  Claim a plot, delete the plot, do /plot info to show you still have the plot.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [ ] I Made sure the bug/error is not caused by any other plugin

**Comment by Deliphin** [comment]
I just thought to test it in a new world. It works perfectly fine in a new plot world. Something has gone wrong with my specific world and I don't know what.

**Comment by boy0001** [comment]
Change `wooden_slab:6` to `step:6` in the `worlds.yml`.
