### ISSUE TITLE
Worlds being randomly purged??

### ISSUE THREAD

**Issue by vorcazm** [IntellectualSites/PlotSquared#1869]
# Bug report template 

**Debug paste link:** 

[06:13:34] [Server thread/INFO]: vorcazm issued server command: /plot debugpaste

[06:13:34] [Craft Scheduler Thread - 25/WARN]: Exception in thread "Craft Scheduler Thread - 25" 

[06:13:34] [Craft Scheduler Thread - 25/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.3.0 generated an exception while executing task 628

	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

	at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.RuntimeException: Couldn't read response!

	at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:46)

	at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:59)

	at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:32)

	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)

	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)

	... 3 more

**Description of the problem:** 
The plots are being removed from the world without any warning.  I have no idea why this is happening.  I log on one day and the world that was once recognized as a plot world is now no longer a plot world.  Doing /plot info returns "you are not in a plot" and players can break the road.   

**How to replicate:** 

There doesn't seem to be any way to replicate it.  I just get on and the world is wiped.  It has happened 3 times in the course of a month.  I generate a new plot world and start to claim some plots in it then I get on a few days later and it's no longer a plot world.  It's worth noting that this only happens in the plot world I'm using for my server.  I have several plot worlds that I used to test stuff out but are inactive and no ops/players access them.  They are still fine.  All 3 of the times that the plots have been removed from the world it has been the world that is actively used by players.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Update PlotSquared
