### ISSUE TITLE
nukkit Error

### ISSUE THREAD

**Issue by Cobwebster** [IntellectualSites/PlotSquared#1921]
[20:12:30] at cn.nukkit.entity.Entity.addMovement(Entity.java:1202)

[20:12:30] at cn.nukkit.entity.Entity.updateMovement(Entity.java:1189)

[20:12:30] at cn.nukkit.entity.Entity.setMotion(Entity.java:1863)

[20:12:30] at cn.nukkit.Player.setMotion(Player.java:1573)

[20:12:30] at cn.nukkit.entity.Entity.teleport(Entity.java:1915)

[20:12:30] at cn.nukkit.Player.teleport(Player.java:4061)

[20:12:30] at cn.nukkit.entity.Entity.teleport(Entity.java:1895)

[20:12:30] at com.plotsquared.nukkit.object.NukkitPlayer.teleport(NukkitPlayer.java:123)

[20:12:30] at com.intellectualcrafters.plot.object.Plot.teleportPlayer(Plot.java:2614)

[20:12:30] at com.intellectualcrafters.plot.object.Plot.claim(Plot.java:1353)

[20:12:30] at com.intellectualcrafters.plot.commands.Auto$1$1.run(Auto.java:226)

[20:12:30] at com.intellectualcrafters.plot.object.RunnableVal.run(RunnableVal.java:14)

[20:12:30] at com.intellectualcrafters.plot.util.TaskManager.sync(TaskManager.java:27)

[20:12:30] at com.intellectualcrafters.plot.util.TaskManager.sync(TaskManager.java:22)

[20:12:30] at com.intellectualcrafters.plot.commands.Auto$1.run(Auto.java:220)

[20:12:30] at com.intellectualcrafters.plot.commands.Auto$1.run(Auto.java:217)

[20:12:30] at com.intellectualcrafters.plot.object.RunnableVal.run(RunnableVal.java:14)

[20:12:30] at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)

[20:12:30] at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:295)

[20:12:30] at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:276)

[20:12:30] at cn.nukkit.Server.tick(Server.java:1082)

[20:12:30] at cn.nukkit.Server.tickProcessor(Server.java:848)

[20:12:30] at cn.nukkit.Server.start(Server.java:825)

[20:12:30] at cn.nukkit.Server.<init>(Server.java:508)

[20:12:30] at cn.nukkit.Nukkit.main(Nukkit.java:99)

Latest nukkit and plotsquared

**Comment by RedstoneFuture** [comment]
When get you this error?

**Comment by Cobwebster** [comment]
Not sure, although it seems disabling entities via config doesn't actually do it. Same with default gamemodes within the settings file.

I just made a custom plugin which disables mob-spawning and forces gamemode so i haven't seen this error in awhile.

**Comment by boy0001** [comment]
This isn't the full stacktrace. I can't debug it properly without steps to reproduce or the full exception.
