### ISSUE TITLE
Error (fast issue) ;)

### ISSUE THREAD

**Issue by xCraftRayX** [IntellectualSites/PlotSquared#1951]
I have not free time but I can only paste error which displayed me in console:

`Caused by: java.lang.NullPointerException
>       at com.intellectualcrafters.plot.object.Plot.isOwner(Plot.java:342) ~[?:?]
>       at com.plotsquared.bukkit.listeners.PlayerEvents.entityDamage(PlayerEvents.java:2459) ~[?:?]
>       at com.plotsquared.bukkit.listeners.PlayerEvents.onEntityDamageByEntityEvent(PlayerEvents.java:2308) ~[?:?]
>       at sun.reflect.GeneratedMethodAccessor392.invoke(Unknown Source) ~[?:?]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
>       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
>       ... 32 more
`

**Comment by RedstoneFuture** [comment]
When you get this error?

**Comment by xCraftRayX** [comment]
@RedstoneFuture mb after this action:
`[13:04:12] [Server thread/INFO]: prosiak69 issued server command: /butcher
[13:04:42] [Server thread/INFO]: prosiak69 issued server command: /butcher
[13:06:27] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to PlotSquared v18.05.13-ecf94b8-1991
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
	at org.bukkit.p`

**Comment by RedstoneFuture** [comment]
Okay. Get you every time this error? In the plotworld, right?

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1487

**Comment by xCraftRayX** [comment]
No every time and yes, this error was displayed only in plotworld.

**Comment by RedstoneFuture** [comment]
And if you create for the test a second plotworld?

**Comment by xCraftRayX** [comment]
@RedstoneFuture  I test it in another plotworld and I have not error. I don't know why I get this error... I only notificated you about this problem. I can't find core of this problem.

**Comment by RedstoneFuture** [comment]
I thinks its wrong entitie or a chunk in your world.

**Comment by RedstoneFuture** [comment]
You can use the "/kill" command of minecraft.
