### ISSUE TITLE
Plot regenerating to vanilla instead of flat land

### ISSUE THREAD

**Issue by LemADEC** [IntellectualSites/PlotSquared#1962]
**Debug paste link:** 
https://hastebin.com/veluramora
```
15:21:18 INFO]: LemADEC issued server command: /plot clear
[15:21:18 WARN]: java.lang.reflect.InvocationTargetException
[15:21:18 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:21:18 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:21:18 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:21:18 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.util.block.QueueProvider$1.getNewQueue(QueueProvider.java:15)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.util.block.GlobalBlockQueue.getNewQueue(GlobalBlockQueue.java:69)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.object.PlotArea.getQueue(PlotArea.java:117)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.generator.HybridPlotManager.clearPlot(HybridPlotManager.java:163)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.object.Plot$1.run(Plot.java:800)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.object.Plot.clear(Plot.java:803)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.commands.Clear$1.run(Clear.java:44)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand$1.run(MainCommand.java:176)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand$1.run(MainCommand.java:135)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.commands.Clear.execute(Clear.java:40)
[15:21:18 WARN]:        at com.plotsquared.general.commands.Command.execute(Command.java:337)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:260)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:135)
[15:21:18 WARN]:        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
[15:21:18 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:21:18 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[15:21:18 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740)
[15:21:18 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370)
[15:21:18 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107)
[15:21:18 WARN]:        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[15:21:18 WARN]:        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[15:21:18 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[15:21:18 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
[15:21:18 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
[15:21:18 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[15:21:18 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[15:21:18 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[15:21:18 WARN]:        at java.lang.Thread.run(Thread.java:748)
[15:21:18 WARN]: Caused by: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/Block
[15:21:18 WARN]:        at java.lang.Class.forName0(Native Method)
[15:21:18 WARN]:        at java.lang.Class.forName(Class.java:264)
[15:21:18 WARN]:        at com.intellectualcrafters.plot.util.ReflectionUtils.getRefClass(ReflectionUtils.java:228)
[15:21:18 WARN]:        at com.plotsquared.bukkit.util.block.BukkitLocalQueue_1_7.<init>(BukkitLocalQueue_1_7.java:24)
[15:21:18 WARN]:        ... 32 more
```
The server is running with Thermos-1.7.10-1614.57-server.jar

**Description of the problem:** 
When doing a plot clear, there's an exception reported in console and the central chunks of the plots are regenerated to vanilla instead of flat land.

**How to replicate:** 
Clear a plot or release it

**Checklist**:
- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by LemADEC** [comment]
![image](https://user-images.githubusercontent.com/4776032/40447010-298d2280-5e9f-11e8-92ea-018822d45aa9.png)

**Comment by MinisBett** [comment]
Try to use FAWE(FastAsyncWorldEdit)

**Comment by LemADEC** [comment]
Can we get an update on this?

**Comment by boy0001** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Manual-generator-setting

**Comment by LemADEC** [comment]
already done

**Comment by MattBDev** [comment]
We no longer support thermos
