### ISSUE TITLE
possible crash from plotsquared or fawe

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1967]
using plotsquared 597 and fawe 1122 and paper 1398

thought it was suspicious it crashed immediately after someone did plot auto, if this is not related in any way i apologize

```
[17:49:27] [Server thread/INFO]: IV100 issued server command: /plot auto
[17:49:28] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Exception ticking world
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:909) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1416]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IndexOutOfBoundsException: writerIndex(49468) + minWritableBytes(8) exceeds maxCapacity(49471): UnpooledHeapByteBuf(ridx: 0, widx: 49468, cap: 49471/49471)
    at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:276) ~[patched_1.12.2.jar:git-Paper-1416]
    at io.netty.buffer.AbstractByteBuf.writeLong(AbstractByteBuf.java:1014) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PacketDataSerializer.writeLong(PacketDataSerializer.java:840) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PacketDataSerializer.a(PacketDataSerializer.java:112) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.DataPaletteBlock.b(DataPaletteBlock.java:139) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.DataPaletteBlock.writeBlocks(DataPaletteBlock.java:125) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PacketPlayOutMapChunk.a(PacketPlayOutMapChunk.java:146) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PacketPlayOutMapChunk.writeChunk(PacketPlayOutMapChunk.java:135) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PacketPlayOutMapChunk.<init>(PacketPlayOutMapChunk.java:46) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PlayerChunk.b(PlayerChunk.java:145) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:214) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:328) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:898) ~[patched_1.12.2.jar:git-Paper-1416]
    ... 4 more
[17:49:28] [Server thread/ERROR]:   Cause of unexpected exception was
java.lang.IndexOutOfBoundsException: writerIndex(49468) + minWritableBytes(8) exceeds maxCapacity(49471): UnpooledHeapByteBuf(ridx: 0, widx: 49468, cap: 49471/49471)
    at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:276) ~[patched_1.12.2.jar:git-Paper-1416]
    at io.netty.buffer.AbstractByteBuf.writeLong(AbstractByteBuf.java:1014) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PacketDataSerializer.writeLong(PacketDataSerializer.java:840) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PacketDataSerializer.a(PacketDataSerializer.java:112) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.DataPaletteBlock.b(DataPaletteBlock.java:139) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.DataPaletteBlock.writeBlocks(DataPaletteBlock.java:125) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PacketPlayOutMapChunk.a(PacketPlayOutMapChunk.java:146) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PacketPlayOutMapChunk.writeChunk(PacketPlayOutMapChunk.java:135) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PacketPlayOutMapChunk.<init>(PacketPlayOutMapChunk.java:46) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PlayerChunk.b(PlayerChunk.java:145) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:214) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:328) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:898) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) ~[patched_1.12.2.jar:git-Paper-1416]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1416]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by RedstoneFuture** [comment]
Can you included a `/plot debugpaste` link, please?

**Comment by PhanaticD** [comment]
settings: https://hastebin.com/mofuyobuma.bash
worlds: https://hastebin.com/egezabehik.sql

**Comment by RedstoneFuture** [comment]
And in which world you have this problem?

**Comment by Patsnflfan54** [comment]
I seem to be having the same problem.

**Comment by Sauilitired** [comment]
Has anyone experienced this issue with newer versions of the plugin(s)?

**Comment by Sauilitired** [comment]
It is unclear whether or not this was actually caused by PlotSquared. If anyone encounters this in the future, we'll investigate it further.
