### ISSUE TITLE
Moving plots cause NullPointerException

### ISSUE THREAD

**Issue by StiegeRobin** [IntellectualSites/PlotSquared#1971]
# Bug report template 

**Debug paste link:** https://hastebin.com/oqusecamen

**Description of the problem:** If you try to move or swap a plot, it'll cause the following error:
`[22:30:22 INFO]: Rasre issued server command: /p move -3;0
[22:30:22 WARN]: java.lang.NullPointerException
[22:30:22 WARN]:        at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:363)
[22:30:22 WARN]:        at com.intellectualcrafters.plot.database.SQLManager$1.run(SQLManager.java:148)
[22:30:22 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[22:30:22 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:30:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:30:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:30:22 WARN]:        at java.lang.Thread.run(Thread.java:748)`

**How to replicate:** Claim a plot and try to move/swap it.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by StiegeRobin** [comment]
Update:
`[22:48:45 INFO]: Rasre issued server command: /p move -5;0
[22:48:46 INFO]: (FAWE) Running 1.12 registry dumper!
[22:48:46 INFO]: (FAWE) Using adapter: com.boydti.fawe.bukkit.v1_12.FaweAdapter_1_12@530e196a
[22:48:46 INFO]: (FAWE) =========================================
[22:48:46 WARN]: java.lang.NullPointerException
[22:48:46 WARN]:        at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:363)
[22:48:46 WARN]:        at com.intellectualcrafters.plot.database.SQLManager$1.run(SQLManager.java:148)
[22:48:46 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[22:48:46 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:48:46 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:48:46 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:48:46 WARN]:        at java.lang.Thread.run(Thread.java:748)
`

**Comment by dordsor21** [comment]
Should be fixed in 825baf4
