### ISSUE TITLE
Error on shutdown

### ISSUE THREAD

**Issue by L4BORG** [IntellectualSites/PlotSquared#2019]
**Debug paste link:** 

**Description of the problem:** 
```
[03:50:25 INFO]: [PlotSquared] Disabling PlotSquared v18.07.06-ae1e58c-2021
[03:50:30 WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[03:50:30 WARN]:        at com.intellectualcrafters.plot.database.SQLManager.getPlots(SQLManager.java:1952)
[03:50:30 WARN]:        at com.intellectualcrafters.plot.database.SQLManager.validateAllPlots(SQLManager.java:3074)
[03:50:30 WARN]:        at com.intellectualcrafters.plot.database.DBFunc.validatePlots(DBFunc.java:79)
[03:50:30 WARN]:        at com.intellectualcrafters.plot.PS.disable(PS.java:1583)
[03:50:30 WARN]:        at com.plotsquared.bukkit.BukkitMain.onDisable(BukkitMain.java:292)
[03:50:30 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
[03:50:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359)
[03:50:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:423)
[03:50:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:416)
[03:50:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:332)
[03:50:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:475)
[03:50:30 WARN]:        at org.spigotmc.RestartCommand.restart(RestartCommand.java:61)
[03:50:30 WARN]:        at org.spigotmc.RestartCommand.restart(RestartCommand.java:35)
[03:50:30 WARN]:        at org.spigotmc.RestartCommand.lambda$0(RestartCommand.java:28)
[03:50:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:803)
[03:50:30 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:376)
[03:50:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:726)
[03:50:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:629)
[03:50:30 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**How to replicate:** 
Not sure.

**Checklist**:
- [] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Please reopen with required information if there is still the issue.
