### ISSUE TITLE
Crash in 1.13 when deleting plot + 1.12 when deleting plot (1.12 spigot)

### ISSUE THREAD

**Issue by BBoyJD10** [IntellectualSites/PlotSquared#2037]
# Bug report template 

**Debug paste link:** 
```
[02:59:57 WARN]: EntityPlayer['BBoyJD10'/197, uuid='347250c4-c09a-4e8a-8280-01f4b364128b', l='Plots', x=274.83, y=129.74, z=-235.94, cx=17, cd=-15, tl=358010, v=true, d=false](BBoyJD10 at 274.83071348777514,129.73690997343036,-235.93960470166797) is still in another ChunkSection! Report this to https://github.com/PaperMC/Paper/issues/1223
[02:59:57 WARN]: EntityPlayer['BBoyJD10'/197, uuid='347250c4-c09a-4e8a-8280-01f4b364128b', l='Plots', x=274.83, y=129.74, z=-235.94, cx=17, cd=-15, tl=358010, v=true, d=false](BBoyJD10 at 274.83071348777514,129.73690997343036,-235.93960470166797) was in another chunk at that! 16,-15
[02:59:57 WARN]: java.lang.Throwable
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:705)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1826)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.World.h(World.java:1758)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:706)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1531)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:683)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:920)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[02:59:57 WARN]:        at java.lang.Thread.run(Thread.java:748)
[02:59:57 WARN]: EntityPlayer['BBoyJD10'/197, uuid='347250c4-c09a-4e8a-8280-01f4b364128b', l='Plots', x=281.27, y=125.84, z=-236.06, cx=17, cd=-15, tl=358013, v=true, d=false](BBoyJD10 at 281.2678448605767,125.83726145009967,-236.0630479635825) is still in another ChunkSection! Report this to https://github.com/PaperMC/Paper/issues/1223
[02:59:57 WARN]: java.lang.Throwable
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:705)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1826)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.World.h(World.java:1758)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:706)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1531)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:683)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:920)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773)
[02:59:57 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[02:59:57 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Description of the problem:** 

**How to replicate:** 
delete a plot in 1.13 will cause server to crash as it will paste stone block everywhere anmd in 1.12 causes above error

**Comment by dordsor21** [comment]
Please reopen with required information if there is still the issue.
