### ISSUE TITLE
PlotSquared MySQL database error: All DB transactions during this session are being validated

### ISSUE THREAD

**Issue by A1Gaming** [IntellectualSites/PlotSquared#2047]
**Debug paste link:** 
[23:56:24] [Server thread/INFO]: [PlotSquared] Disabling PlotSquared v18.07.27-cd9d22c-2026
[23:56:24] [Server thread/INFO]: All DB transactions during this session are being validated (This may take a while if corrections need to be made)
[23:56:24] [Server thread/WARN]: java.lang.NullPointerException
[23:56:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.validateAllPlots(SQLManager.java:3080)
[23:56:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.DBFunc.validatePlots(DBFunc.java:79)
[23:56:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.disable(PS.java:1583)
[23:56:24] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onDisable(BukkitMain.java:292)
[23:56:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[23:56:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
[23:56:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422)
[23:56:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415)
[23:56:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:349)
[23:56:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465)
[23:56:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:613)
[23:56:24] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:56:24] [Server thread/INFO]: Could not close database connection!

**Description of the problem:** 
 I have a MultiVerse Creative Plots server, using the latest version of PlotSquared (PlotSquared-Bukkit-18.07.27-cd9d22c-2026) in MC version 1.12.2. There are 2 worlds on this server: 1. Creative Plots and 2. Staff Plots. I have a MySQL database error, which has resulted in PlotSquared to 1. Disable the claimed plots in the Staff Plots server. The land on Staff Plots is not registered as having any plots any longer. When i try to claim a new plot, it says there is not a registered plot in the region. 2. Plotsquared will not generate new land in new chunks in the Staff Plots world. It generates default land (ie seed land, no roads, etc). This issue is not affecting any plot generation or plot function on the Creative Plots world, only Staff Plots.

**How to replicate:** 
This error populates on every server shutdown.

**Comment by Sauilitired** [comment]
Has this issue been resolved since? I’m sorry that no one ever responded to it. It got lost in the middle of everything else.

**Comment by AeSix** [comment]
@A1Gaming If this issue is still occurring with newer builds, please update the ticket with relevant information.  It's been nearly 8 months since you were asked for an update.  

Additionally, newer issues have been opened up with other db connection issues. I will be tagging this issue with that one as it contains addtional information.
