### ISSUE TITLE
NullPointerException: Updated PlotSquared, now throws error in console.

### ISSUE THREAD

**Issue by FrozenBeard** [IntellectualSites/PlotSquared#2056]
I did some maintenance on my creative server today as it was very outdated, plotsquared now throws this error in console.

Paper version git-Paper-1534 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Wordledit: 6.1.10-SNAPSHOT;3807-e6c6a2c
FastAsyncWorldEdit version 18.08.03-e6128ec-1169-20.7.3
FastAsyncVoxelSniper version 18.08.06-60d07b5-1170-20.7.4
PlotSquared version 18.07.27-cd9d22c-2026

```
[14:45:09] [Craft Scheduler Thread - 14/INFO]: [Vault] Checking for Updates ... 
[14:45:10] [Craft Scheduler Thread - 10/INFO]: [PlaceholderAPI] 123 placeholder expansions are available on the cloud.
[14:45:10] [Craft Scheduler Thread - 10/INFO]: [PlaceholderAPI] 3 installed expansions have updates available.
[14:45:10] [Craft Scheduler Thread - 14/INFO]: [Vault] No new version available
[14:45:10] [Server thread/INFO]: Starting UUID caching
[14:45:10] [Craft Scheduler Thread - 13/INFO]: [P2] Starting player data caching for: Hub
[14:45:10] [Craft Scheduler Thread - 13/INFO]: Fast mode UUID caching enabled!
[14:45:10] [Craft Scheduler Thread - 20/WARN]: java.lang.NullPointerException
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.getHandle(TitleManager_1_11.java:422)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:387)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: java.lang.NullPointerException
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at java.lang.reflect.Field.get(Field.java:393)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:388)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:45:10] [Craft Scheduler Thread - 20/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: java.lang.NullPointerException
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.getHandle(TitleManager_1_11.java:422)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:387)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: java.lang.NullPointerException
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at java.lang.reflect.Field.get(Field.java:393)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:388)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:45:10] [Craft Scheduler Thread - 18/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: java.lang.NullPointerException
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.getHandle(TitleManager_1_11.java:422)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:387)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: java.lang.NullPointerException
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at java.lang.reflect.Field.get(Field.java:393)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:388)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:45:10] [Craft Scheduler Thread - 23/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: java.lang.NullPointerException
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.getHandle(TitleManager_1_11.java:422)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:387)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: java.lang.NullPointerException
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at java.lang.reflect.Field.get(Field.java:393)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:388)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:45:10] [Craft Scheduler Thread - 12/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:45:10] [Craft Scheduler Thread - 13/INFO]: [P2] Cached a total of: 336 UUIDs
[14:45:10] [Craft Scheduler Thread - 13/INFO]: Failed to cache: 2 uuids - slowly processing all files
[14:45:10] [Craft Scheduler Thread - 13/INFO]: [P2] Cached a total of: 1281 UUIDs
[14:45:36] [User Authenticator #1/INFO]: UUID of player swiftkids is d5ff76e3-71d2-48e8-bb79-5108a9dced27
[14:45:36] [Server thread/INFO]: swiftkids[/84.13.158.158:44133] logged in with entity id 243 at ([Hub]-292.5, 85.0, 537.5)
[14:45:36] [Server thread/INFO]: > Avast ye! Buccaneer swiftkids » has come aboard!
```

**Comment by dordsor21** [comment]
Please reopen with required information if there is still the issue.

**Comment by HeroCC** [comment]
I am having this issue as well, so here's the same (I think) issue with the proper issue template.

# Bug report template 



**[REQUIRED] PlotSquared Version Number:** 4.277

**[REQUIRED] Spigot/Paper Version Number:** git-Paper-624 (MC: 1.13.2)

**[REQUIRED] Minecraft Version Number:** 1.13.2

**Links to worlds.yml file and settings.yml file:** 
Worlds.yml: https://pastebin.com/issFtKfs
Settings.yml: https://pastebin.com/tUZZjuHC

**[REQUIRED] Description of the problem:** 
Running analysis tools generates Null Pointer Exception, fails to complete.

**Any relevant console output or screenshots:**
![image](https://user-images.githubusercontent.com/2124489/57586823-6992fd00-74c9-11e9-828f-bff9b86576e3.png)

**Plugins being used on the server:**
![image](https://user-images.githubusercontent.com/2124489/57586827-8f200680-74c9-11e9-936c-fcba5afa0196.png)

**How to replicate:** 
* Rate several plots (to get data)
* run `/plot debugexec generate-analysis 7` (same as in docs) or `/plot debugexec analyze`
* Command output will claim process is starting, console will print Null Pointer Exception


**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
