### ISSUE TITLE
Clearing plot duplicates player entity.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#2074]
Paper dev 1547 (Spigot 1.12.2)
PlotSquared dev 631 (Bukkit-18.08.12-4b8c434-2035)
FastAsyncWorldEdit dev 1174 (bukkit-18.08.18-39ef1d7-1185-21.1.2)

RE: https://github.com/PaperMC/Paper/issues/1302#issuecomment-414133151

https://github.com/IntellectualSites/PlotSquared/blob/77281017d4a6e597244cb563be6f16279cd7c939/Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitChunkManager.java#L692

When someone clears their plot, th eir player entity is duplicated.

```
[01:58:06] [Server thread/INFO]: Mr_Bullet issued server command: /plot clear
[01:58:08] [Server thread/INFO]: Mr_Bullet issued server command: /plot confirm
[01:58:08] [Server thread/INFO]: (FAWE) Having `parallel-threads` > 1 interferes with the timings.
[01:58:10] [Server thread/WARN]: EntityPlayer['Mr_Bullet'/1381449, uuid='18cd8997-f161-437d-91c8-7bce64a64ea2', l='build1', x=-608.35, y=83.75, z=-508.19, cx=-39, cd=-32, tl=13632419, v=true, d=false](Mr_Bullet at -608.3482150230061,83.75061483615866,-508.1883158448097) is still in another ChunkSection! Report this to https://github.com/PaperMC/Paper/issues/1223
[01:58:10] [Server thread/WARN]: EntityPlayer['Mr_Bullet'/1381449, uuid='18cd8997-f161-437d-91c8-7bce64a64ea2', l='build1', x=-608.35, y=83.75, z=-508.19, cx=-39, cd=-32, tl=13632419, v=true, d=false](Mr_Bullet at -608.3482150230061,83.75061483615866,-508.1883158448097) was in another chunk at that! -38,-32
[01:58:10] [Server thread/WARN]: java.lang.Throwable
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:705)
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1832)
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.Entity.recalcPosition(Entity.java:990)
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:846)
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:628)
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126)
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[01:58:10] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:58:10] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[01:58:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[01:58:10] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

[02:04:09] [Server thread/INFO]: Mr_Bullet issued server command: /plot clear
[02:04:11] [Server thread/INFO]: Mr_Bullet issued server command: /plot confirm
[02:04:12] [Server thread/WARN]: EntityPlayer['Mr_Bullet'/1381449, uuid='18cd8997-f161-437d-91c8-7bce64a64ea2', l='build1', x=-624.37, y=74.02, z=-506.50, cx=-40, cd=-32, tl=13639675, v=true, d=false](Mr_Bullet at -624.3652363354345,74.02421072241441,-506.4952093001268) is still in another ChunkSection! Report this to https://github.com/PaperMC/Paper/issues/1223
[02:04:12] [Server thread/WARN]: EntityPlayer['Mr_Bullet'/1381449, uuid='18cd8997-f161-437d-91c8-7bce64a64ea2', l='build1', x=-624.37, y=74.02, z=-506.50, cx=-40, cd=-32, tl=13639675, v=true, d=false](Mr_Bullet at -624.3652363354345,74.02421072241441,-506.4952093001268) was in another chunk at that! -39,-32
[02:04:12] [Server thread/WARN]: java.lang.Throwable
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:705)
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1832)
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.Entity.recalcPosition(Entity.java:990)
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:846)
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:628)
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126)
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[02:04:12] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[02:04:12] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[02:04:12] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[02:04:12] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
```
[06:49:21] [Server thread/INFO]: xEllie issued server command: /plot clear
[06:49:21] [Server thread/INFO]: (FAWE) Having `parallel-threads` > 1 interferes with the timings.
[06:49:31] [Server thread/WARN]: EntityPlayer['xEllie'/87542, uuid='4aa3f740-6a54-4e75-be90-85105fafb39e', l='build1', x=-512.06, y=79.12, z=-775.79, cx=-33, cd=-49, tl=141206166, v=true, d=false](xEllie at -512.06435500055,79.11700280587691,-775.7933479369399) is still in another ChunkSection! Report this to https://github.com/PaperMC/Paper/issues/1223
[06:49:31] [Server thread/WARN]: EntityPlayer['xEllie'/87542, uuid='4aa3f740-6a54-4e75-be90-85105fafb39e', l='build1', x=-512.06, y=79.12, z=-775.79, cx=-33, cd=-49, tl=141206166, v=true, d=false](xEllie at -512.06435500055,79.11700280587691,-775.7933479369399) was in another chunk at that! -32,-49
[06:49:31] [Server thread/WARN]: java.lang.Throwable
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:705)
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1832)
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.Entity.recalcPosition(Entity.java:990)
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:846)
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:628)
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126)
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[06:49:31] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[06:49:31] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[06:49:31] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[06:49:31] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by aikar** [comment]
FYI I think mibby has a misunderstanding about the error message, it's not duplicating as far as I know, just warning that the Entity was being added to a Chunk before it was removed from the previous chunk.

**Comment by dordsor21** [comment]
Please reopen with required information if there is still the issue @mibby
