### ISSUE TITLE
NullPointerException on join (sometimes)

### ISSUE THREAD

**Issue by Sprax2013** [IntellectualSites/PlotSquared#2090]
# Bug report template

**Debug paste link:**
https://hastebin.com/osaxofevol

**Description of the problem:**
Sometimes when I connect 2/4 NullPointerExceptions are thrown. I can not see anything not working as it should but the exception is thrown.

```
[12:40:59 INFO]: UUID of player StormStormy is 91f04fe9-0f36-43b5-8f20-e3375f86d39e
[12:40:59 INFO]: UUID of player Sprax2013 is 407b28ed-e7bd-4516-93d9-3361fecb7889
[12:40:59 INFO]: Sprax2013[/89.13.25.7:50805] logged in with entity id 1 at ([world]-111.5197163049126, 61.0, -39.39211648059391)
[12:40:59 INFO]: StormStormy[/89.13.25.7:33905] logged in with entity id 2 at ([world]-113.55172284715115, 63.123463131341026, -40.76531826202827)
[12:41:00 WARN]: java.lang.NullPointerException
[12:41:00 WARN]:        at com.plotsquared.bukkit.titles.TitleManager_1_11.getHandle(TitleManager_1_11.java:422)
[12:41:00 WARN]:        at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:387)
[12:41:00 WARN]:        at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[12:41:00 WARN]:        at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[12:41:00 WARN]:        at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[12:41:00 WARN]:        at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[12:41:00 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[12:41:00 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[12:41:00 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:41:00 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:41:00 WARN]:        at java.lang.Thread.run(Thread.java:748)
[12:41:00 WARN]: java.lang.NullPointerException
[12:41:00 WARN]:        at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[12:41:00 WARN]:        at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[12:41:00 WARN]:        at java.lang.reflect.Field.get(Field.java:393)
[12:41:00 WARN]:        at com.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:388)
[12:41:00 WARN]:        at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:232)
[12:41:00 WARN]:        at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[12:41:00 WARN]:        at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[12:41:00 WARN]:        at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[12:41:00 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[12:41:00 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[12:41:00 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:41:00 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:41:00 WARN]:        at java.lang.Thread.run(Thread.java:748)
[12:41:00 WARN]: java.lang.NullPointerException
[12:41:00 WARN]:        at com.plotsquared.bukkit.titles.TitleManager_1_11.getHandle(TitleManager_1_11.java:422)
[12:41:00 WARN]:        at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:235)
[12:41:00 WARN]:        at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[12:41:00 WARN]:        at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[12:41:00 WARN]:        at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[12:41:00 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[12:41:00 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[12:41:00 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:41:00 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:41:00 WARN]:        at java.lang.Thread.run(Thread.java:748)
[12:41:00 WARN]: java.lang.NullPointerException
[12:41:00 WARN]:        at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[12:41:00 WARN]:        at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[12:41:00 WARN]:        at java.lang.reflect.Field.get(Field.java:393)
[12:41:00 WARN]:        at com.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:236)
[12:41:00 WARN]:        at com.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:25)
[12:41:00 WARN]:        at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[12:41:00 WARN]:        at com.plotsquared.listener.PlotListener$2.run(PlotListener.java:170)
[12:41:00 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[12:41:00 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[12:41:00 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:41:00 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:41:00 WARN]:        at java.lang.Thread.run(Thread.java:748)

```

**How to replicate:**

There is no 100%-chance to replicate but I use `/send current Event` to join the server. `current` could be read as 'all players that are currently connected to my server' and `Event` is the server where PlotSquared is running. (It is a BungeeCord-Command that connects one or a couple of players with a specific server)

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
hastebin is not loading (expired?)
Is this even still an issue? Have you tried to update your plugins?

This is my creative server (with P2, and Spigot 1.12.2 on bungee)
>version
[12:38:54 INFO]: This server is running CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
>version PlotSquared
[12:38:59 INFO]: PlotSquared version 18.11.15-0252cf7-2052

BungeeCord-Bootstrap:1.13-SNAPSHOT:9a2acc8:1390 

I could not reproduce this issue. 

Please update if needed, and report success/failure :)
(A new debugpaste would probably be good if it fails when you update)

**Comment by Sprax2013** [comment]
Yeah probably expired. Maybe pastebin would be a better alternative with expiration date set to 1 year (or never).

I can't reproduce the issue. I don't know what caused it or fixed it.

**Comment by Sauilitired** [comment]
`Maybe pastebin would be a better alternative with expiration date set to 1 year (or never).` Not necessary. We're using a custom paste service now.

**Comment by Sprax2013** [comment]
> Not necessary. We're using a custom paste service now.
Even better!
