### ISSUE TITLE
Error in KillRoadMobs on Sponge (work to do there...)

### ISSUE THREAD

**Issue by Husky110** [IntellectualSites/PlotSquared#2091]
# Bug report template 

**Debug paste link:** 
[20:48:22] [Server thread/INFO] [STDOUT]: [com.intellectualcrafters.plot.PS:setupConfig:1680]: Version is PlotSquared-18.8.23-f5a981f-2037
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: java.lang.UnsupportedOperationException: NOT IMPLEMENTED YET
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.plotsquared.sponge.util.KillRoadMobs.run(KillRoadMobs.java:6)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.plotsquared.sponge.SpongeMain.runEntityTask(SpongeMain.java:290)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:169)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.plotsquared.sponge.SpongeMain.onServerAboutToStart(SpongeMain.java:145)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at org.spongepowered.common.event.listener.GameAboutToStartServerEventListener_SpongeMain_onServerAboutToStart2.handle(Unknown Source)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:231)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:271)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:864)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:291)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:268)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[20:48:23] [Server thread/INFO] [STDERR]: [com.intellectualcrafters.plot.PS:<init>:303]: 	at java.lang.Thread.run(Thread.java:748)
[20:48:23] [Server thread/INFO] [plotsquared]: §6PlotSquared is now enabled

**Description of the problem:** 
Using the most recent build from Jenkins and setting kill-road-mobs: true in the settings.yml results in the error stated above. The server states that PS is enabled, but it's not. plot-commands do not work at all.

**How to replicate:** 

see Description
Sponge-Version: spongeforge-1.12.2-2705-7.1.0-BETA-3361
Other Plugins enabled: ProjectCore, ProjectWorlds
**Checklist**:

- [x] I included a `/plot debugpaste` link -> (well... logfile...)
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by BrainStone** [comment]
Over 6 months later and still not implemented...

**Comment by AeSix** [comment]
@Husky110  Is this still going on?
You should be able to update the docs and/or a PR for the config.  I don't use Sponge and so can't exactly test this myself.  

As you seem to have found a fix, it would be wonderful for you to update the appropriate places, if at all possible (I know the P2 wiki is publicly editable, or was)  As for the config change, I can't see the devs not merging it if it's legible and clear. 

I can't promise it will be addressed otherwise, but if it has been, it would be nice to close the ticket. 

This is almost a year old, and as far as I know, no one has picked up PlotSquared development for Sponge.

**Comment by Husky110** [comment]
@AeSix I don't know. The project where I used PS is discontinued due to a lack of time. Please check yourself. Downloading and installing Sponge is pretty easy.

**Comment by AeSix** [comment]
closing issue.
