### ISSUE TITLE
Errors com.plotsquared.listener.WEManager

### ISSUE THREAD

**Issue by x1p** [IntellectualSites/PlotSquared#2122]
**Bug report template **
https://hastebin.com/igukuzebuf

**Description of the problem:** 
Even the most simpel WE commands generate numerous errors
Examples:
https://hastebin.com/xenovunoru.sql
https://hastebin.com/itejamujak.sql
I had filed an issue at Worledit, but they say it is Plotsquared who is responsible for this.

**How to replicate:** 
Simple commands on a plot that is from the one executing commands like:
/thru
//set 1

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by x1p** [comment]
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.plotsquared.listener.WEManager
at com.plotsquared.listener.WESubscriber.onEditSession(WESubscriber.java:54) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
... 45 more
```

**Comment by x1p** [comment]
I am completely up to date

**Comment by N0tMyFaultOG** [comment]
Once fawe runs smooth on 1.13 with PlotSquared I suggest to switch, as it uses some methods he normal worldedit doesn't have iirc

**Comment by x1p** [comment]
Tried FAWE, but it is not yet stable enough. The plot border did not change when (un) claiming.

**Comment by Sauilitired** [comment]
Solved in PlotSquared 4.
