### ISSUE TITLE
NullPointerException: null - ClassicPlotManager.claimPlot

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#2133]
PlotSquared dev 641
Paper dev 368 (Spigot 1.13.3)

```
[21:44:00] [Server thread/WARN]: [PlotSquared] Task #95754 for PlotSquared v18.10.13-b6d4872-2048 generated an exception
java.lang.NullPointerException: null
	at com.intellectualcrafters.plot.generator.ClassicPlotManager.claimPlot(ClassicPlotManager.java:469) ~[?:?]
	at com.intellectualcrafters.plot.object.Plot.claim(Plot.java:1408) ~[?:?]
	at com.intellectualcrafters.plot.commands.Claim$1$1.run(Claim.java:96) ~[?:?]
	at com.intellectualcrafters.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.intellectualcrafters.plot.util.TaskManager.sync(TaskManager.java:27) ~[?:?]
	at com.intellectualcrafters.plot.util.TaskManager.sync(TaskManager.java:22) ~[?:?]
	at com.intellectualcrafters.plot.commands.Claim$1.run(Claim.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-368]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-368]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Sauilitired** [comment]
This has probably been resolved by the P² 4 pre-release.
