### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1 on startup

### ISSUE THREAD

**Issue by L4BORG** [IntellectualSites/PlotSquared#2138]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
Exception on startup

```
[04:27:37] [Server thread/INFO]: [PlotSquared] Enabling PlotSquared v18.10.13-b6d4872-2048
[04:27:37] [Server thread/INFO]: Version is PlotSquared-18.10.13-b6d4872-2048
[04:27:37] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[04:27:37] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.getPlots(SQLManager.java:1952)
[04:27:37] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.DBFunc.getPlots(DBFunc.java:283)
[04:27:37] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.setupDatabase(PS.java:1621)
[04:27:37] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:163)
[04:27:37] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:193)
[04:27:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[04:27:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:331)
[04:27:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[04:27:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:353)
[04:27:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:312)
[04:27:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:201)
[04:27:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:575)
[04:27:37] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[04:27:37] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[04:27:37] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.getPlots(SQLManager.java:1952)
[04:27:37] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.DBFunc.getPlots(DBFunc.java:283)
[04:27:37] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.setupDatabase(PS.java:1621)
[04:27:37] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:163)
[04:27:37] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:193)
[04:27:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[04:27:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:331)
[04:27:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[04:27:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:353)
[04:27:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:312)
[04:27:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:201)
[04:27:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:575)
[04:27:37] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
