### ISSUE TITLE
NoSuchFieldError on interact with WorldEdit 7

### ISSUE THREAD

**Issue by MegaNarwhal** [IntellectualSites/PlotSquared#2141]
# Bug report template 

**Debug paste link:** https://hastebin.com/upekacijom

**Description of the problem:** NoSuchFieldError in console every time a player with WorldEdit permission interacts with a block.
```
[07:33:30 ERROR]: Could not pass event PlayerInteractEvent to PlotSquared v18.10.20-302051a-2049
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:251) ~[spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:452) ~[spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1242) ~[spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchFieldError: wandItem
        at com.plotsquared.bukkit.listeners.PlayerEvents.onInteract(PlayerEvents.java:1582) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-a1ba5fe-3359cb1]
        ... 17 more
```

**How to replicate:**
1. Put latest PlotSquared and WorldEdit 7.0 on a 1.13.x server
2. Op yourself
3. Interact with a block

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by MegaNarwhal** [comment]
Duplicate of #2119
