### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2146]
I have the Following Configuration

use-sqluuidcache = true
Stoarge mysql

i become this error on shutdown 

============ DATABASE ERROR ============[m
[19:48:24] [Server thread/INFO]: There was an error updating the database.[m
[19:48:24] [Server thread/INFO]:  - It will be corrected on shutdown[m
[19:48:24] [Server thread/INFO]: ========================================[m
[19:48:24] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[19:48:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:400)
[19:48:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:141)
[19:48:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:115)
[19:48:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:98)
[19:48:24] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.BukkitTaskManager.taskAsync(BukkitTaskManager.java:28)
[19:48:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.TaskManager.runTaskAsync(TaskManager.java:90)
[19:48:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$52.addBatch(SQLManager.java:2638)
[19:48:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:411)
[19:48:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.validateAllPlots(SQLManager.java:3063)
[19:48:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.DBFunc.validatePlots(DBFunc.java:79)
[19:48:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.disable(PS.java:1589)
[19:48:24] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onDisable(BukkitMain.java:292)
[19:48:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
[19:48:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
[19:48:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[19:48:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[19:48:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336)
[19:48:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460)
[19:48:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:593)
[19:48:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[19:48:24] [Server thread/INFO]: ========================================[m

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
