### ISSUE TITLE
Exception when deleting plot

### ISSUE THREAD

**Issue by Bobcat00** [IntellectualSites/PlotSquared#2154]
CraftBukkit 1.8.8
PlotSquared 18.10.25-40e7df8-2050

Plots are large, 101 x 101 blocks.  Claimed a plot, placed a couple dozen grass blocks spanning more than one chunk, then did /plot delete.  Got the following exception.  This is in the trim entities code, but there are no entities in the plot.  Sometimes blocks are left in the plot.

```
2018-11-02 15:12:11 [INFO] Bobcat00 issued server command: /p delete
2018-11-02 15:12:12 [WARN] java.lang.UnsupportedOperationException
2018-11-02 15:12:12 [WARN] 	at com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:43)
2018-11-02 15:12:12 [WARN] 	at java.util.AbstractCollection.clear(AbstractCollection.java:436)
2018-11-02 15:12:12 [WARN] 	at com.plotsquared.bukkit.util.block.BukkitLocalQueue_1_8_3.setBlocks(BukkitLocalQueue_1_8_3.java:320)
2018-11-02 15:12:12 [WARN] 	at com.plotsquared.bukkit.util.block.BukkitLocalQueue.setComponents(BukkitLocalQueue.java:66)
2018-11-02 15:12:12 [WARN] 	at com.intellectualcrafters.plot.util.block.BasicLocalBlockQueue.execute(BasicLocalBlockQueue.java:67)
2018-11-02 15:12:12 [WARN] 	at com.intellectualcrafters.plot.util.block.BasicLocalBlockQueue.next(BasicLocalBlockQueue.java:53)
2018-11-02 15:12:12 [WARN] 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:48)
2018-11-02 15:12:12 [WARN] 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:44)
2018-11-02 15:12:12 [WARN] 	at com.intellectualcrafters.plot.object.RunnableVal2.run(RunnableVal2.java:16)
2018-11-02 15:12:12 [WARN] 	at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$2.run(GlobalBlockQueue.java:109)
2018-11-02 15:12:12 [WARN] 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
2018-11-02 15:12:12 [WARN] 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
2018-11-02 15:12:12 [WARN] 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:680)
2018-11-02 15:12:12 [WARN] 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335)
2018-11-02 15:12:12 [WARN] 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629)
2018-11-02 15:12:12 [WARN] 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537)
2018-11-02 15:12:12 [WARN] 	at java.lang.Thread.run(Thread.java:748)
2018-11-02 15:12:13 [INFO] Deleting plot... Id: -12;2 World: plotworld Owner: 661348e9-56b6-4c4f-ad2b-7874683cf1d4 Index: 493
```
Your debugpaste doesn't work. Here's one I made by hand and put on PasteBin:
https://pastebin.com/rD5q66Rh

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Bobcat00** [comment]
Since your pastedebug doesn't work, I made my own by hand and put it on PasteBin:

https://pastebin.com/rD5q66Rh

**Comment by Bobcat00** [comment]
Same exception with 1.12.2:

```
14:33:20 [INFO] Bobcat00 issued server command: /p delete
14:33:21 [WARN] java.lang.UnsupportedOperationException
14:33:21 [WARN]         at com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:46)
14:33:21 [WARN]         at java.util.AbstractCollection.clear(Unknown Source)
14:33:21 [WARN]         at com.plotsquared.bukkit.util.block.BukkitLocalQueue_1_9.setBlocks(BukkitLocalQueue_1_9.java:293)
14:33:21 [WARN]         at com.plotsquared.bukkit.util.block.BukkitLocalQueue.setComponents(BukkitLocalQueue.java:66)
14:33:21 [WARN]         at com.intellectualcrafters.plot.util.block.BasicLocalBlockQueue.execute(BasicLocalBlockQueue.java:67)
14:33:21 [WARN]         at com.intellectualcrafters.plot.util.block.BasicLocalBlockQueue.next(BasicLocalBlockQueue.java:53)
14:33:21 [WARN]         at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:48)
14:33:21 [WARN]         at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$1.run(GlobalBlockQueue.java:44)
14:33:21 [WARN]         at com.intellectualcrafters.plot.object.RunnableVal2.run(RunnableVal2.java:16)
14:33:21 [WARN]         at com.intellectualcrafters.plot.util.block.GlobalBlockQueue$2.run(GlobalBlockQueue.java:109)
14:33:21 [WARN]         at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
14:33:21 [WARN]         at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:360)
14:33:21 [WARN]         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:690)
14:33:21 [WARN]         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371)
14:33:21 [WARN]         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651)
14:33:21 [WARN]         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555)
14:33:21 [WARN]         at java.lang.Thread.run(Unknown Source)
14:33:22 [INFO] Deleting plot... Id: -12;2 World: plotworld Owner: 661348e9-56b6-4c4f-ad2b-7874683cf1d4 Index: 493

version
14:33:44 [INFO] This server is running CraftBukkit version git-Bukkit-d7bebef (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

**Comment by N0tMyFaultOG** [comment]
Debugpaste works now again.

**Comment by Bobcat00** [comment]
Here you go - https://hastebin.com/ufecevupam

**Comment by N0tMyFaultOG** [comment]
>CraftBukkit 

Are you actually using CraftBukkit?

**Comment by Bobcat00** [comment]
Yes I am using CraftBukkit.  No I don't want to use Spigot.

**Comment by Sauilitired** [comment]
I can't currently get the legacy version to build and I don't really have time to mess around with it. However, a potential fix would be to add
```java
// We need to update entities to make it mutable
for (int i = 0; i < entities.length; i++) {
     final ArrayList<?> list = new ArrayList<>(entities[i]);
     entities[i] = list;
}
// Force update the field. This shouldn't be necessary, but weird stuff happened
entitySlices.set(c, entities);
```

To BukkitLocalQueue_1_8_3\#setBlocks to make the collections mutable. If anyone manages to get it working, then a PR is more than welcome.

**Comment by MattBDev** [comment]
We will no longer be supporting CraftBukkit because it is not receiving proper support from the Spigot Developers.

**Comment by Bobcat00** [comment]
> We will no longer be supporting CraftBukkit because it is not receiving proper support from the Spigot Developers.

All they did was remove a copy command from their build script.

**Comment by MattBDev** [comment]
"The two different jars exist for a variety of (primarily development-related) reasons, however it must be made clear that Spigot is the supported product on SpigotMC.org"
On a 1.8.8 server spigot should work a lot better than CraftBukkit although 1.8.8 is really old.

**Comment by Bobcat00** [comment]
I'm using 1.12.2 now. But the problem is that Spigot breaks things, and none of the Spigot developers can say definitively how to make Spigot run the same as CraftBukkit (or Vanilla).  From the standpoint of a plugin developer, unless the plugin is specifically using the Spigot API, it shouldn't matter if the server is running Spigot or CraftBukkit.

**Comment by MattBDev** [comment]
@Bobcat00 we are now using paper API in our code. Spigot changes some behavior but almost all of it can be fixed by using the configs or Paper.
