### ISSUE TITLE
Error in console when plot expiry enabled

### ISSUE THREAD

**Issue by MegaNarwhal** [IntellectualSites/PlotSquared#2159]
# Bug report template 

**Debug paste link:** https://hastebin.com/elunodoqil

**Description of the problem:** 
The following error is displayed shortly after the server finishes starting up with plot expiry enabled.
```
[07:40:27 INFO]: Adding new expiry task!
[07:40:42 WARN]: [PlotSquared] Task #173 for PlotSquared v18.11.05-ae2869a-2051 generated an exception
java.lang.NoSuchMethodError: org.bukkit.generator.ChunkGenerator.generateExtBlockSections(Lorg/bukkit/World;Ljava/util/Random;IILorg/bukkit/generator/ChunkGenerator$BiomeGrid;)[[S
        at com.plotsquared.bukkit.util.BukkitHybridUtils$1$2$1.run(BukkitHybridUtils.java:93) ~[?:?]
        at com.plotsquared.bukkit.util.BukkitHybridUtils$1$2$1.run(BukkitHybridUtils.java:87) ~[?:?]
        at com.intellectualcrafters.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
        at com.intellectualcrafters.plot.util.ChunkManager$3.run(ChunkManager.java:182) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-2474d93-ca22de3]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot.jar:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-2474d93-ca22de3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```
**How to replicate:** 

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
This should have been resolved in PlotSquared 4. It was because PlotSquared didn't fully support 1.13. Re-open if this is still an issue in PlotSquared 4.
