### ISSUE TITLE
low priority | command "/plot generatebiome help" generates a biome when "help" isn't an actual biome

### ISSUE THREAD

**Issue by Dad3** [IntellectualSites/PlotSquared#2186]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
/plot generatebiome help 
generates a biome but "help" is not an actual biome, very wierd 

**How to replicate:** 

stand on plot and type /plot generatebiome help 
**Checklist**:

- [-] I included a `/plot debugpaste` link
not working for some reason 
`[22:29:14 WARN]: java.io.IOException: Server returned HTTP response code: 503 for URL: https://hastebin.com/documents
[22:29:14 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[22:29:14 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[22:29:14 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[22:29:14 WARN]:        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:30)
[22:29:14 WARN]:        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60)
[22:29:14 WARN]:        at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29)
[22:29:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[22:29:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:29:14 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:29:14 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:29:14 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:29:14 WARN]:        at java.lang.Thread.run(Unknown Source)`
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
Hey, thanks for reporting this. BiomeGenerator uses the same string matcher as plotsquared, and `help` was probably matched to `hell` which is the old name for the nether biome. BiomeGenerator isn't maintained, and it isn't compatible with the new PlotSquared API. I might update it to the new API, if anyone actually wants me to. However, I do not have an extreme amount of free time on my hands and I have to prioritize the main plugin (and real life work, apparently you can't pay rent with plots :man_shrugging:)

**Comment by MattBDev** [comment]
@Dad3 Is there any reason why you aren't using FAWE like the plugin page recommends? I'm just trying to understand if there is a need for this add-on or if FAWE can provide everything this add-on offered.

**Comment by AeSix** [comment]
@MattBDev Shouldn't this issue be closed as he is using unsupported plugins which functions are supported in a supported plugin now?

**Comment by MattBDev** [comment]
@AeSix That's why I asked the question. If I don't get a reply in a couple of days, I'll close the issue.

**Comment by Dad3** [comment]
I am not using add-ons and I am using FAWE. I never heard of biomegenerator

**Comment by MattBDev** [comment]
@Dad3 I didn't realize that FAWE added this command. I made a mistake

**Comment by Sauilitired** [comment]
I didn’t know Jesse added the command to FAWE. But my explanation above still applies :P
