### ISSUE TITLE
Plot music menu not accessible on 1.13

### ISSUE THREAD

**Issue by alchemistmatt** [IntellectualSites/PlotSquared#2194]
# Bug report template 

**Debug paste link:** 
Using `/plot debugpaste` results in error `javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure` so I cannot include that.  I will instead include a portion of the stack trace below.

Versions:
 `Paper version git-Paper-470 (MC: 1.13.2)` 
`PlotSquared v18.12.21-03ad8eb-2059`

**Description of the problem:** 
Typing `/p music` should bring up a GUI to allow you to choose the plot music.  On Paper 1.13.2 it instead reports an ItemStack error, specifically
`org.bukkit.inventory.ItemStack.<init>(IIS)V`

**How to replicate:** 
Happens every time I use `/p music`.  I realize PlotSquared support for 1.13 is still a work in progress; just wanted to document this bug.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Stack Trace Excerpt**
```
java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.<init>(IIS)V
       at com.plotsquared.bukkit.util.BukkitInventoryUtil.getItem(BukkitInventoryUtil.java:26)
       at com.plotsquared.bukkit.util.BukkitInventoryUtil.open(BukkitInventoryUtil.java:56)
       at com.intellectualcrafters.plot.object.PlotInventory.openInventory(PlotInventory.java:36)
       at com.intellectualcrafters.plot.commands.Music.onCommand(Music.java:63)
       at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27)
       at com.plotsquared.general.commands.Command.execute(Command.java:337)
```

**Comment by Sauilitired** [comment]
This issue has been fixed in the new pre-release.
