### ISSUE TITLE
Could not pass event VehicleMoveEvent to PlotSquared

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#2195]
Paper dev 488 (Spigot 1.13.2)
PlotSquared-Breaking dev 57

@Sauilitired Noticed this error spamming my logs. :(

```
[01:35:36] [Server thread/ERROR]: Could not pass event VehicleMoveEvent to PlotSquared v4.18.12.26-f137801-2106
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-488]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityMinecartAbstract.tick(EntityMinecartAbstract.java:328) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.EntityMinecartHopper.tick(SourceFile:105) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1554) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1521) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1328) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:615) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1104) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:458) ~[?:?]
	at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.vehicleMove(PlayerEvents.java:647) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor141.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-488]
	... 14 more
```

**Comment by Sauilitired** [comment]
Yeah, I can confirm this. I solved it locally by just removing the exception, but that doesn't feel like a very complete solution. I'll see what I can do.

**Comment by mibby** [comment]
Thanks. Let me know if you need any help tested. :) The exception is quite obnoxious.
