### ISSUE TITLE
PlotSquared not working with FAWE

### ISSUE THREAD

**Issue by Xayanix** [IntellectualSites/PlotSquared#2206]
```
[19:09:01] [Server thread/ERROR]: Could not pass event BlockFromToEvent to PlotSquared v4.18.12.28-3156741-2126
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
	at com.github.intellectualsites.plotsquared.plot.object.Location.<init>(Location.java:26) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.Location.<init>(Location.java:34) ~[?:?]
	at com.github.intellectualsites.plotsquared.bukkit.util.BukkitUtil.getLocation(BukkitUtil.java:200) ~[?:?]
	at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onChange(PlayerEvents.java:1275) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor25.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[ps1.13.jar:git-Paper-453]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[ps1.13.jar:git-Paper-453]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[ps1.13.jar:git-Paper-453]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[ps1.13.jar:git-Paper-453]
	at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:196) ~[ps1.13.jar:git-Paper-453]
	at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:167) ~[ps1.13.jar:git-Paper-453]
	at net.minecraft.server.v1_13_R2.FluidTypeFlowing.a(FluidTypeFlowing.java:512) ~[ps1.13.jar:git-Paper-453]
	at net.minecraft.server.v1_13_R2.Fluid.a(SourceFile:56) ~[ps1.13.jar:git-Paper-453]
	at net.minecraft.server.v1_13_R2.WorldServer.a(WorldServer.java:681) ~[ps1.13.jar:git-Paper-453]
	at net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:85) ~[ps1.13.jar:git-Paper-453]
	at net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:673) ~[ps1.13.jar:git-Paper-453]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:313) ~[ps1.13.jar:git-Paper-453]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1088) ~[ps1.13.jar:git-Paper-453]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[ps1.13.jar:git-Paper-453]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[ps1.13.jar:git-Paper-453]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[ps1.13.jar:git-Paper-453]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]```

**Comment by Sauilitired** [comment]
Install WorldEdit 7.
