### ISSUE TITLE
Error when running scrips addsigns

### ISSUE THREAD

**Issue by x1p** [IntellectualSites/PlotSquared#2208]
# Bug report template 
**Debug paste link:** 
https://hastebin.com/tufogukitu

**Description of the problem:** 
```
plot debugexec run addsigns.js=> [00:17:27 WARN]: [WorldEdit] Failed to find properties for minecraft:AIR
[00:17:27 INFO]: Setting sign for: plot;2;0
[00:17:27 INFO]: Setting sign for: plot;1;0
[00:17:27 INFO]: Setting sign for: plot;1;1
[00:17:27 INFO]: Setting sign for: plot;0;1
[00:17:27 INFO]: Setting sign for: plot;0;0
[00:17:27 WARN]: java.lang.NullPointerException
[00:17:27 WARN]: at java.util.regex.Matcher.appendReplacement(Matcher.java:804)
[00:17:27 WARN]: at java.util.regex.Matcher.replaceAll(Matcher.java:955)
[00:17:27 WARN]: at java.lang.String.replaceAll(String.java:2223)
[00:17:27 WARN]: at com.github.intellectualsites.plotsquared.plot.object.Plot.setSign(Plot.java:967)
[00:17:27 WARN]: at com.github.intellectualsites.plotsquared.plot.object.Plot.setSign(Plot.java:1389)
[00:17:27 WARN]: at jdk.nashorn.internal.scripts.Script$3$\^eval\_.:program(<eval>:8)
[00:17:27 WARN]: at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
[00:17:27 WARN]: at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
[00:17:27 WARN]: at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
[00:17:27 WARN]: at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
[00:17:27 WARN]: at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
[00:17:27 WARN]: at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
[00:17:27 WARN]: at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
[00:17:27 WARN]: at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
[00:17:27 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.DebugExec.onCommand(DebugExec.java:422)
[00:17:27 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.execute(SubCommand.java:29)
[00:17:27 WARN]: at com.github.intellectualsites.plotsquared.commands.Command.execute(Command.java:332)
[00:17:27 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.execute(MainCommand.java:257)
[00:17:27 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.onCommand(MainCommand.java:126)
[00:17:27 WARN]: at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
[00:17:27 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:17:27 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[00:17:27 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732)
[00:17:27 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:694)
[00:17:27 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:483)
[00:17:27 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440)
[00:17:27 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[00:17:27 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[00:17:27 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**How to replicate:** 
just run plot debugexec run addsigns.js
PlotSquared-Bukkit-4.18.12.28-6292bff-2124

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Thanks for the excellent report. I'll look into this.

**Comment by dordsor21** [comment]
the scripts won't work with P2 breaking due to the API changes
