### ISSUE TITLE
Error in log with WorldEdit from latest build

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/PlotSquared#2220]
# Bug report template 
**Debug paste link:** 
https://hastebin.com/ebavisiqaw

**Description of the problem:** 
I don't see problem in-game
I have some bug log
```
[23:26:36] [Server thread/INFO]: jewome62 issued server command: /plot claim
[23:26:37] [Server thread/WARN]: [PlotSquared] Task #57 for PlotSquared v19.01.03-b288a2d-2044 generated an exception
java.lang.NullPointerException: null
	at com.intellectualcrafters.plot.generator.ClassicPlotManager.claimPlot(ClassicPlotManager.java:469) ~[?:?]
	at com.intellectualcrafters.plot.object.Plot.claim(Plot.java:1408) ~[?:?]
	at com.intellectualcrafters.plot.commands.Claim$1$1.run(Claim.java:96) ~[?:?]
	at com.intellectualcrafters.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.intellectualcrafters.plot.util.TaskManager.sync(TaskManager.java:27) ~[?:?]
	at com.intellectualcrafters.plot.util.TaskManager.sync(TaskManager.java:22) ~[?:?]
	at com.intellectualcrafters.plot.commands.Claim$1.run(Claim.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:888) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[23:26:50] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to PlotSquared v19.01.03-b288a2d-2044
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:299) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:266) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1162) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchFieldError: wandItem
	at com.plotsquared.bukkit.listeners.PlayerEvents.onInteract(PlayerEvents.java:1585) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	... 18 more
[23:26:51] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to PlotSquared v19.01.03-b288a2d-2044
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:299) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:266) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1162) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchFieldError: wandItem
	at com.plotsquared.bukkit.listeners.PlayerEvents.onInteract(PlayerEvents.java:1585) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	... 18 more
```

**How to replicate:** 
I use lastest build from master because i have a bug with AsyncWorldEdit (with load https://github.com/SBPrime/AsyncWorldEdit-Premium/issues/159)

**Checklist**:
- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update p2 
https://ci.athion.net/job/PlotSquared-Breaking/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-4.88.jar

**Comment by SBPrime** [comment]
@Sauilitired I never said anyone is wrong. I said that this was not the point of the issue.

**Comment by Sauilitired** [comment]
@SBPrime which is wrong, considering @N0tMyFaultOG was correct in saying that WE 7 isn't supported on that version.

**Comment by Sauilitired** [comment]
To clarify:
```yaml
PlotSquared:
    version: '19.01.03-b288a2d-2044'
    enabled: true
```
he was using a legacy version together with WorldEdit 7. That won't work. Separate issue. Now let this issue rest in peace.

**Comment by DarkEyeDragon** [comment]
Just stop playing Minecraft.
