### ISSUE TITLE
NullPointerException - BukkitPlotGenerator.getDefaultPopulators

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#2260]
Paper dev 513 (Spigot 1.13.2)
PlotSquared-Breaking dev 132
http://ci.athion.net/job/PlotSquared-Breaking/
Multiverse-Core dev 760
https://ci.onarandombox.com/job/Multiverse-Core

Updated from breaking dev 124 to 132. Now noticing this exception at start-up. @MattBDev Possibly caused here? https://github.com/IntellectualSites/PlotSquared/commit/8ac9b862f8610b02947bf25435024b2a58c30725#diff-76a04c61bf0b616bcb711485eb04ce4eR810

```
[00:18:54] [Server thread/INFO]: [P2] Detected world load for 'creative'
[00:18:54] [Server thread/INFO]: [P2]  - generator: PlotSquared>PlotSquared
[00:18:54] [Server thread/INFO]: [P2]  - plotworld: com.github.intellectualsites.plotsquared.plot.generator.HybridPlotWorld
[00:18:54] [Server thread/INFO]: [P2]  - plotAreaManager: com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager
[00:18:54] [Server thread/WARN]: java.lang.NullPointerException
[00:18:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.Plot.setArea(Plot.java:436)
[00:18:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.PlotSquared.addPlotArea(PlotSquared.java:446)
[00:18:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.PlotSquared.loadWorld(PlotSquared.java:1143)
[00:18:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.generator.BukkitPlotGenerator.getDefaultPopulators(BukkitPlotGenerator.java:199)
[00:18:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldServer.i_(WorldServer.java:121)
[00:18:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createWorld(CraftServer.java:1002)
[00:18:54] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:499)
[00:18:54] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[00:18:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[00:18:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448)
[00:18:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423)
[00:18:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728)
[00:18:54] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310)
[00:18:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[00:18:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[00:18:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:18:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[00:18:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[00:18:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[00:18:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[00:18:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[00:18:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[00:18:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[00:18:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[00:18:54] [Server thread/INFO]: [P2] Detected world load for 'creative'
[00:18:54] [Server thread/INFO]: [P2]  - generator: PlotSquared>PlotSquared
[00:18:54] [Server thread/INFO]: [P2]  - plotworld: com.github.intellectualsites.plotsquared.plot.generator.HybridPlotWorld
[00:18:54] [Server thread/INFO]: [P2]  - plotAreaManager: com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager
```

**Comment by AeSix** [comment]
Try updating to build 136 and testing.  There was some pretty major issues in 131 through 135.  If the issue persists, update the ticket with a new debugpaste please. 

If it's resolved, also update the ticket, and close it :)   Thanks!
