### ISSUE TITLE
Mega Issue on PlotSquared for 1.8.8 

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2308]
When i build a Road Shematic and generate all Roads and go to the Worldborder then the server crashes. 
```
`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 3/24/19 4:15 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property BlockStateDirection{name=facing, clazz=class net.minecraft.server.v1_8_R3.EnumDirection, values=[north, south, west, east]} as it does not exist in BlockStateList{block=minecraft:air, properties=[]}
	at net.minecraft.server.v1_8_R3.BlockStateList$BlockData.get(SourceFile:112)
	at net.minecraft.server.v1_8_R3.BlockCocoa.updateShape(BlockCocoa.java:55)
	at net.minecraft.server.v1_8_R3.BlockCocoa.a(BlockCocoa.java:49)
	at net.minecraft.server.v1_8_R3.Block.a(Block.java:274)
	at net.minecraft.server.v1_8_R3.World.getCubes(World.java:1204)
	at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:483)
	at net.minecraft.server.v1_8_R3.EntityItem.t_(EntityItem.java:74)
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607)
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582)
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425)
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.server.v1_8_R3.BlockStateList$BlockData.get(SourceFile:112)
	at net.minecraft.server.v1_8_R3.BlockCocoa.updateShape(BlockCocoa.java:55)
	at net.minecraft.server.v1_8_R3.BlockCocoa.a(BlockCocoa.java:49)
	at net.minecraft.server.v1_8_R3.Block.a(Block.java:274)
	at net.minecraft.server.v1_8_R3.World.getCubes(World.java:1204)
	at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:483)
	at net.minecraft.server.v1_8_R3.EntityItem.t_(EntityItem.java:74)
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607)
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582)

-- Entity being ticked --
Details:
	Entity Type: Item (net.minecraft.server.v1_8_R3.EntityItem)
	Entity ID: 344
	Entity Name: item.item.dyePowder.brown
	Entity's Exact location: 30000007.67, 73.56, 29999905.34
	Entity's Block location: 30000007.00,73.00,29999905.00 - World: (30000007,73,29999905), Chunk: (at 7,4,1 in 1875000,1874994; contains blocks 30000000,0,29999904 to 30000015,255,29999919), Region: (58593,58593; contains chunks 1874976,1874976 to 1875007,1875007, blocks 29999616,0,29999616 to 30000127,255,30000127)
	Entity's Momentum: -0.01, 0.16, 0.04
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425)
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597)

-- Affected level --
Details:
	Level name: plotjungle
	All players: 1 total; [EntityPlayer['JoeyPlayzTV'/342, l='plotjungle', x=29999999.00, y=100.00, z=29999999.00](JoeyPlayzTV at 2.9999999E7,100.0,2.9999999E7)]
	Chunk stats: ServerChunkCache: 1115 Drop: 0
	Level seed: -8353568499786466953
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 0.00,65.00,0.00 - World: (0,65,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4964763 game time, 11504 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 15970 (now: false), thunder time: 112001 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Linux (amd64) version 3.16.0-4-amd64
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 378643992 bytes (361 MB) / 841482240 bytes (802 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -Xms128M -Xmx2G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	CraftBukkit Information: 
   Running: CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) true
   Plugins: { PlotSquaredSG v2.0.0 com.empcraft.psg.Main [Empire92, Citymonstret], FastAsyncWorldEdit v19.03.02-14f3b91-1254-22.0.11 com.boydti.fawe.bukkit.BukkitMain [Empire92], VoxelSniper v5.170.0-SNAPSHOT-jnks317-gitfcb8fe1 com.thevoxelbox.voxelsniper.VoxelSniper [przerwap, MikeMatrix, Gavjenks, giltwist, psanker, Deamon5550, DivineRage], WorldEdit v6.1.7;dd00bb1 com.sk89q.worldedit.bukkit.WorldEditPlugin [], PlotSquared v19.03.12-2f882b5-724 com.plotsquared.bukkit.BukkitMain [Citymonstret, Empire92, MattBDev], Multiverse-Core v2.5.0-b727 com.onarandombox.MultiverseCore.MultiverseCore [Rigby, fernferret, lithium3141, main--, dumptruckman], ArmorStandEditor v1.8-0.1.5BETA io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin [RypoFalem], goBrush v2.0 gc.arcaniax.gobrush.Main [],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Craft Scheduler Thread - 2: [java.net.PlainSocketImpl.socketConnect(Native Method), java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350), java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206), java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188), java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392), java.net.Socket.connect(Socket.java:589), java.net.Socket.connect(Socket.java:538), sun.net.NetworkClient.doConnect(NetworkClient.java:180), sun.net.www.http.HttpClient.openServer(HttpClient.java:463), sun.net.www.http.HttpClient.openServer(HttpClient.java:558), sun.net.www.http.HttpClient.<init>(HttpClient.java:242), sun.net.www.http.HttpClient.New(HttpClient.java:339), sun.net.www.http.HttpClient.New(HttpClient.java:357), sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220), sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156), sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050), sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984), sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334), sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309), org.mcstats.multiverse.Metrics.postPlugin(Metrics.java:475), org.mcstats.multiverse.Metrics.access$400(Metrics.java:61), org.mcstats.multiverse.Metrics$1.run(Metrics.java:227), org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71), org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], RUNNABLE Craft Scheduler Thread - 6: [java.net.PlainSocketImpl.socketConnect(Native Method), java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350), java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206), java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188), java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392), java.net.Socket.connect(Socket.java:589), java.net.Socket.connect(Socket.java:538), sun.net.NetworkClient.doConnect(NetworkClient.java:180), sun.net.www.http.HttpClient.openServer(HttpClient.java:463), sun.net.www.http.HttpClient.openServer(HttpClient.java:558), sun.net.www.http.HttpClient.<init>(HttpClient.java:242), sun.net.www.http.HttpClient.New(HttpClient.java:339), sun.net.www.http.HttpClient.New(HttpClient.java:357), sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220), sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156), sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050), sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984), sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334), sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309), org.mcstats.Metrics.postPlugin(Metrics.java:449), org.mcstats.Metrics.access$400(Metrics.java:57), org.mcstats.Metrics$1.run(Metrics.java:223), org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71), org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], RUNNABLE Netty Epoll Server IO #1: [sun.misc.Unsafe.allocateMemory(Native Method), java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127), java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311), io.netty.buffer.UnpooledUnsafeDirectByteBuf.allocateDirect(UnpooledUnsafeDirectByteBuf.java:108), io.netty.buffer.UnpooledUnsafeDirectByteBuf.capacity(UnpooledUnsafeDirectByteBuf.java:157), io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:251), io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:817), io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:825), net.minecraft.server.v1_8_R3.PacketDataSerializer.writeBytes(PacketDataSerializer.java:655), net.minecraft.server.v1_8_R3.PacketPlayOutMapChunkBulk.b(PacketPlayOutMapChunkBulk.java:74), net.minecraft.server.v1_8_R3.PacketEncoder.a(SourceFile:46), net.minecraft.server.v1_8_R3.PacketEncoder.encode(SourceFile:16), io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107), io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658), io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716), io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706), io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741), io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895), io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240), net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198), io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Craft Scheduler Thread - 1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1610), org.bukkit.craftbukkit.v1_8_R3.CraftCrashReport.call(CraftCrashReport.java:29), net.minecraft.server.v1_8_R3.CrashReportSystemDetails.a(SourceFile:78), net.minecraft.server.v1_8_R3.CrashReport.h(CrashReport.java:127), net.minecraft.server.v1_8_R3.CrashReport.<init>(CrashReport.java:34), net.minecraft.server.v1_8_R3.CrashReport.a(CrashReport.java:312), net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1428), net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597), net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786), net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374), net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654), net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:212)], RUNNABLE Spigot Metrics Thread: [java.net.PlainSocketImpl.socketConnect(Native Method), java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350), java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206), java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188), java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392), java.net.Socket.connect(Socket.java:589), java.net.Socket.connect(Socket.java:538), sun.net.NetworkClient.doConnect(NetworkClient.java:180), sun.net.www.http.HttpClient.openServer(HttpClient.java:463), sun.net.www.http.HttpClient.openServer(HttpClient.java:558), sun.net.www.http.HttpClient.<init>(HttpClient.java:242), sun.net.www.http.HttpClient.New(HttpClient.java:339), sun.net.www.http.HttpClient.New(HttpClient.java:357), sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220), sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156), sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050), sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984), sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334), sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309), org.spigotmc.Metrics.postPlugin(Metrics.java:430), org.spigotmc.Metrics.access$4(Metrics.java:345), org.spigotmc.Metrics$1.run(Metrics.java:240), java.util.TimerThread.mainLoop(Timer.java:555), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING pool-6-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING Keep-Alive-Timer: [java.lang.Thread.sleep(Native Method), sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:172), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Timer-2: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_8_R3.FileIOThread.c(FileIOThread.java:52), net.minecraft.server.v1_8_R3.FileIOThread.run(FileIOThread.java:28), java.lang.Thread.run(Thread.java:748)], WAITING Java2D Disposer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164), sun.java2d.Disposer.run(Disposer.java:148), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING process reaper: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING Thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77), org.bukkit.craftbukkit.v1_8_R3.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:25), java.lang.Thread.run(Thread.java:748)], RUNNABLE Signal Dispatcher: [], RUNNABLE Craft Scheduler Thread - 3: [java.net.PlainSocketImpl.socketConnect(Native Method), java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350), java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206), java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188), java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392), java.net.Socket.connect(Socket.java:589), java.net.Socket.connect(Socket.java:538), sun.net.NetworkClient.doConnect(NetworkClient.java:180), sun.net.www.http.HttpClient.openServer(HttpClient.java:463), sun.net.www.http.HttpClient.openServer(HttpClient.java:558), sun.net.www.http.HttpClient.<init>(HttpClient.java:242), sun.net.www.http.HttpClient.New(HttpClient.java:339), sun.net.www.http.HttpClient.New(HttpClient.java:357), sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220), sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156), sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050), sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984), sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334), sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309), com.boydti.fawe.bukkit.Metrics.postPlugin(Metrics.java:393), com.boydti.fawe.bukkit.Metrics.access$100(Metrics.java:21), com.boydti.fawe.bukkit.Metrics$1.run(Metrics.java:231), org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71), org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], RUNNABLE Craft Scheduler Thread - 4: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.socketRead(SocketInputStream.java:116), java.net.SocketInputStream.read(SocketInputStream.java:171), java.net.SocketInputStream.read(SocketInputStream.java:141), sun.security.ssl.InputRecord.readFully(InputRecord.java:465), sun.security.ssl.InputRecord.read(InputRecord.java:503), sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983), sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385), sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413), sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397), sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559), sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185), sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564), sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492), sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263), java.net.URL.openStream(URL.java:1045), com.boydti.fawe.util.Updater.getUpdate(Updater.java:80), com.boydti.fawe.Fawe.update(Fawe.java:306), com.boydti.fawe.Fawe.lambda$new$2(Fawe.java:293), com.boydti.fawe.Fawe$$Lambda$11/704643778.run(Unknown Source), org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71), org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Craft Scheduler Thread - 5: [java.lang.Thread.sleep(Native Method), com.intellectualcrafters.plot.database.SQLManager$1.run(SQLManager.java:163), org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71), org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Craft Scheduler Thread - 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING Timer-1: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.util.TimerThread.mainLoop(Timer.java:526), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_8_R3.DedicatedServer$1.run(DedicatedServer.java:54)], RUNNABLE DestroyJavaVM: [], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.lang.ref.Reference.tryHandlePending(Reference.java:191), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)], RUNNABLE Server console handler: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(FileInputStream.java:255), java.io.BufferedInputStream.fill(BufferedInputStream.java:246), java.io.BufferedInputStream.read(BufferedInputStream.java:265), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2349), net.minecraft.server.v1_8_R3.DedicatedServer$2.run(DedicatedServer.java:79)], WAITING NonBlockingInputStreamThread: [java.lang.Object.wait(Native Method), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:278), java.lang.Thread.run(Thread.java:748)], RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:92)],}
   Recent tasks from 280-310{PlotSquared:com.intellectualcrafters.plot.database.SQLManager$52$1@322,}
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayer['JoeyPlayzTV'/342, l='plotjungle', x=29999999.00, y=100.00, z=29999999.00](JoeyPlayzTV at 2.9999999E7,100.0,2.9999999E7)]
	Is Modded: Definitely; Server brand changed to 'Spigot'
	Type: Dedicated Server (map_server.txt)

```

Please Fix it. The Error occurs when you Build your PlotRoad with Coca, Stairs and all block that can change thier Direction

**Comment by MattBDev** [comment]
> Please Fix it.

This is a server crash report which we can't do much with. Legacy PlotSquared is receiving limited support at the moment but you are using an plugin for plotsquared "PlotSquaredSG" that hasn't been updated since 2015 and isn't even supported.  
Also, don't delete the bug report template. It's there for a reason! 😠
