### ISSUE TITLE
No commands work but on /pl PlotSquared is green?

### ISSUE THREAD

**Issue by georgemuffinnz** [IntellectualSites/PlotSquared#2311]
Hi, I just installed PlotSquared and this happened. It is green in /pl and I have no idea why it is not working. From what I can read it's obviously something to do with worldedit but I can't understand what it means and was hoping to get some help :) 

Thank you,
George

[09:17:16] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to PlotSquared v4.189
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
at com.github.intellectualsites.plotsquared.plot.object.Location.<init>(Location.java:26) ~[?:?]
at com.github.intellectualsites.plotsquared.bukkit.util.BukkitUtil.getLocationFull(BukkitUtil.java:232) ~[?:?]
at com.github.intellectualsites.plotsquared.bukkit.object.BukkitPlayer.getLocationFull(BukkitPlayer.java:190) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.object.PlotPlayer.getLocation(PlotPlayer.java:306) ~[?:?]
at com.github.intellectualsites.plotsquared.bukkit.object.BukkitPlayer.getLocation(BukkitPlayer.java:53) ~[?:?]
at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.playerCommand(PlayerEvents.java:521) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor70.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[spigot.jar:git-Paper-572]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[spigot.jar:git-Paper-572]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot.jar:git-Paper-572]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[spigot.jar:git-Paper-572]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1774) ~[spigot.jar:git-Paper-572]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1590) ~[spigot.jar:git-Paper-572]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Paper-572]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[spigot.jar:git-Paper-572]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[spigot.jar:git-Paper-572]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[spigot.jar:git-Paper-572]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[spigot.jar:git-Paper-572]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[spigot.jar:git-Paper-572]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[spigot.jar:git-Paper-572]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[spigot.jar:git-Paper-572]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[09:17:36] [Timer-3/INFO]: [WorldGuard] Region data changes made in 'random' have been background saved
[09:17:39] [Server thread/ERROR]: Could not pass event ItemSpawnEvent to PlotSquared v4.189
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
at com.github.intellectualsites.plotsquared.plot.object.Location.<init>(Location.java:26) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.object.Location.<init>(Location.java:34) ~[?:?]
at com.github.intellectualsites.plotsquared.bukkit.util.BukkitUtil.getLocation(BukkitUtil.java:200) ~[?:?]
at com.github.intellectualsites.plotsquared.bukkit.listeners.EntitySpawnListener.creatureSpawnEvent(EntitySpawnListener.java:66) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor74.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[spigot.jar:git-Paper-572]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[spigot.jar:git-Paper-572]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot.jar:git-Paper-572]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[spigot.jar:git-Paper-572]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:507) ~[spigot.jar:git-Paper-572]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:401) ~[spigot.jar:git-Paper-572]

**Comment by MattBDev** [comment]
You need to use WorldEdit 7 beta 5.  Other versions of worldedit do not work and FAWE is incompatible at the moment
