### ISSUE TITLE
PlotSquared Loading Issue

### ISSUE THREAD

**Issue by musicjaxx** [IntellectualSites/PlotSquared#2321]
Hello,

I am totally new to GitHub. When I put PlotSquared-Bukkit-4.226 into my server and loaded it, I received the following error:

`Could not load 'plugins\PlotSquared-Bukkit-4.226.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WorldEdit
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:220) [spigot.jar:git-Spigot-f09662d-7c395d4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:325) [spigot.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot.jar:git-Spigot-f09662d-7c395d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]`

I have tried many versions of it and still somehow get the same error. This worked the other day but now it isn't. I'm using BuildTools' Spigot 1.13.2.

- Jaxx.

**Comment by N0tMyFaultOG** [comment]
Install/Update WorldEdit/Fawe; whatever you are using

**Comment by musicjaxx** [comment]
Thank you, I will try this :).

**Comment by musicjaxx** [comment]
Tried, results.

- Got a whole massive large list of errors.
- Really annoyed me and crashed the cmd prompt.

1 of the errors:
`[20:56:02 INFO]: Version is PlotSquared-19.4.11-b0b328e-228
[20:56:07 INFO]: Creating tables
[20:56:12 INFO]: [P2] Metrics enabled.
[20:56:12 INFO]: [P2]  PlotSquared is using online UUIDs
[20:56:26 INFO]: PlotSquared Scripting Test

[20:56:26 WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.object.Location.<init>(Location.java:26)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.object.Location.<init>(Location.java:34)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.object.ConsolePlayer.<init>(ConsolePlayer.java:24)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.object.ConsolePlayer.getConsole(ConsolePlayer.java:31)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.DebugExec.init(DebugExec.java:111)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.DebugExec.<init>(DebugExec.java:34)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.getInstance(MainCommand.java:80)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.<init>(SubCommand.java:18)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.<init>(SubCommand.java:22)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.commands.DebugUUID.<init>(DebugUUID.java:36)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.<init>(BukkitCommand.java:18)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.registerCommands(BukkitMain.java:302)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.PlotSquared.<init>(PlotSquared.java:198)
[20:56:26 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:143)
[20:56:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[20:56:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[20:56:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[20:56:26 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[20:56:26 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[20:56:26 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[20:56:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[20:56:26 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:56:26 WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.math.BlockVector3
[20:56:26 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[20:56:26 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136)
[20:56:26 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82)
[20:56:26 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[20:56:26 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)`

**Comment by N0tMyFaultOG** [comment]
>[20:56:26 WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3

Indicates that you are using an outdated version of WorldEdit, please use the latest from devbukkit

**Comment by musicjaxx** [comment]
That was the latest file apparently. I'll try FAWE.

**Comment by MattBDev** [comment]
You need to use worldedit 7 beta 5 or use FAWE Breaking from this download portal: https://incendo.org/download

**Comment by AeSix** [comment]
And @musicjaxx make sure you are NOT using PlotSquared 19.anything. That is *only* for 1.12 and older servers. Make sure the only PlotSquared jar you have in your plugins folder is the one marked release, on https://incendo.org/download 

Your second log paste shows you using 19.4.11, unless someone changed the versioning scheme again, it should be PlotSquared-Bukkit-4.2xx,
