### ISSUE TITLE
Error running script addsigns.js

### ISSUE THREAD

**Issue by steve4744** [IntellectualSites/PlotSquared#2322]
**Debug paste link:** 
https://incendo.org/paste/view/27caedb4c7f9442b9063c574f8b8a6ad

**Description of the problem:** 
Running `addsigns.js` script on console to replace signs on claimed plots:
```
>plot debugexec run addsigns.js
[23:51:49 INFO]: > /*
This script will fix all signs in the world.
*/
var plots = PS.sortPlots(PS.getPlots());
for (var i = 0; i < plots.size(); i++) {
    var plot = plots.get(i);
    if (!plot.isMerged() || !plot.getMerged(0)) {
        plot.setSign();
        PS.class.static.log('Setting sign for: ' + plot);
    }
    java.lang.Thread.sleep(10);
}
[23:51:49 WARN]: javax.script.ScriptException: TypeError: Can not invoke method [jdk.internal.dynalink.beans.SimpleDynamicMethod ArrayList com.github.intellectualsites.plotsquared.plot.PlotSquared.sortPlots(Collection,SortType,PlotArea)] with the passed arguments; they do not match any of its method signatures. in <eval> at line number 4
[23:51:49 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
[23:51:49 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
[23:51:49 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
[23:51:49 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
[23:51:49 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
[23:51:49 WARN]:        at javax.script.AbstractScriptEngine.eval(Unknown Source)
[23:51:49 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.DebugExec.onCommand(DebugExec.java:430)
[23:51:49 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.execute(SubCommand.java:29)
[23:51:49 WARN]:        at com.github.intellectualsites.plotsquared.commands.Command.execute(Command.java:323)
[23:51:49 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.execute(MainCommand.java:254)
[23:51:49 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.onCommand(MainCommand.java:133)
[23:51:49 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
[23:51:49 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[23:51:49 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:51:49 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)
[23:51:49 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:689)
[23:51:49 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459)
[23:51:49 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418)
[23:51:49 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[23:51:49 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[23:51:49 WARN]:        at java.lang.Thread.run(Unknown Source)
[23:51:49 WARN]: Caused by: <eval>:4 TypeError: Can not invoke method [jdk.internal.dynalink.beans.SimpleDynamicMethod ArrayList com.github.intellectualsites.plotsquared.plot.PlotSquared.sortPlots(Collection,SortType,PlotArea)] with the passed arguments; they do not match any of its method signatures.
[23:51:49 WARN]:        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
[23:51:49 WARN]:        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
[23:51:49 WARN]:        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
[23:51:49 WARN]:        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
[23:51:49 WARN]:        at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkBean(NashornBottomLinker.java:103)
[23:51:49 WARN]:        at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:73)
[23:51:49 WARN]:        at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
[23:51:49 WARN]:        at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
[23:51:49 WARN]:        at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
[23:51:49 WARN]:        at jdk.nashorn.internal.scripts.Script$3$\^eval\_.:program(<eval>:4)
[23:51:49 WARN]:        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
[23:51:49 WARN]:        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
[23:51:49 WARN]:        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
[23:51:49 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
[23:51:49 WARN]:        ... 19 more
```
 

**How to replicate:** 
Run `plot debugexec run addsigns.js` on the console

**Checklist**:
- [x] I included a `/plot debugpaste` link
- x[] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Jesse, wanna fix scripts?

**Comment by steve4744** [comment]
Thanks - works perfectly now.
