### ISSUE TITLE
can't Plot Delete / Clear (1.13.2)

### ISSUE THREAD

**Issue by MerlinK11** [IntellectualSites/PlotSquared#2329]
whem i will type in chat /p del or /p clear
it is not work and whem i type in again coms that:

A timer was tied to the plot or to you. Please wait until the time runs out.

i use version:
PlotSquared-19.4.18-7282ffe-750

**Comment by MerlinK11** [comment]
[03:51:23] [Server thread/INFO]: MerlinK11 issued server command: /p del
[03:51:23] [Server thread/WARN]: [PlotSquared] Task #1473894 for PlotSquared v19.04.18-7282ffe-750 generated an exception
java.lang.NullPointerException: null
	at com.intellectualcrafters.plot.util.block.LocalBlockQueue.setBlock(LocalBlockQueue.java:48) ~[?:?]
	at com.intellectualcrafters.plot.util.block.LocalBlockQueue.setCuboid(LocalBlockQueue.java:109) ~[?:?]
	at com.intellectualcrafters.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:201) ~[?:?]
	at com.intellectualcrafters.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:182) ~[?:?]
	at com.intellectualcrafters.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.intellectualcrafters.plot.util.ChunkManager$3.run(ChunkManager.java:182) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:888) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by N0tMyFaultOG** [comment]
Update plotsquared

**Comment by MerlinK11** [comment]
which version?
do you have a link?

**Comment by N0tMyFaultOG** [comment]
Get it here https://ci.athion.net/job/PlotSquared-Breaking/

**Comment by MerlinK11** [comment]
okay now is the plot world for example world: Plots
not more a plotsquared world

**Comment by N0tMyFaultOG** [comment]
Pastebin your startup log

**Comment by MerlinK11** [comment]
http://www.mediafire.com/file/22l3lqvwb2zl2z6/latest.log

**Comment by N0tMyFaultOG** [comment]
- Remove `PlotsquaredRaender`, it's outdated and breaks P2
- Update WorldGuard: https://dev.bukkit.org/projects/worldguard/files/2663455/download
- Update WorldEdit: https://dev.bukkit.org/projects/worldedit/files/2663452/download

**Comment by MerlinK11** [comment]
`
[22:02:53] [Server thread/INFO]: ﴾PlotMe﴿ Detected world load for 'Plots'
[22:02:53] [Server thread/INFO]: ﴾PlotMe﴿  - generator: PlotSquared>PlotSquared
[22:02:53] [Server thread/INFO]: ﴾PlotMe﴿  - plotworld: com.github.intellectualsites.plotsquared.plot.generator.HybridPlotWorld
[22:02:53] [Server thread/INFO]: ﴾PlotMe﴿  - plotAreaManager: com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager
[22:02:53] [Server thread/WARN]: com.github.intellectualsites.plotsquared.plot.config.Configuration$UnsafeBlockException: oak_leaves is not a valid block
[22:02:53] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.config.Configuration$4.parseString(Configuration.java:85)
[22:02:53] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.config.Configuration$4.parseString(Configuration.java:59)
[22:02:53] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.generator.ClassicPlotWorld.loadConfiguration(ClassicPlotWorld.java:85)
[22:02:53] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotWorld.loadConfiguration(HybridPlotWorld.java:109)
[22:02:53] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.PlotArea.loadDefaultConfiguration(PlotArea.java:339)
[22:02:53] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.PlotSquared.loadWorld(PlotSquared.java:1104)
[22:02:53] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.generator.BukkitPlotGenerator.getDefaultPopulators(BukkitPlotGenerator.java:80)
[22:02:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldServer.i_(WorldServer.java:115)
[22:02:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createWorld(CraftServer.java:949)
[22:02:53] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:458)
[22:02:53] [Server thread/WARN]: 	at multiworld.data.WorldManager.loadWorld(WorldManager.java:347)
[22:02:53] [Server thread/WARN]: 	at multiworld.data.WorldManager.loadWorlds(WorldManager.java:658)
[22:02:53] [Server thread/WARN]: 	at multiworld.data.DataHandler.load(DataHandler.java:242)
[22:02:53] [Server thread/WARN]: 	at multiworld.data.DataHandler.<init>(DataHandler.java:61)
[22:02:53] [Server thread/WARN]: 	at multiworld.MultiWorldPlugin.onEnable(MultiWorldPlugin.java:256)
[22:02:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[22:02:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[22:02:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[22:02:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434)
[22:02:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348)
[22:02:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579)
[22:02:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541)
[22:02:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419)
[22:02:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[22:02:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697)
[22:02:53] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:02:53] [Server thread/INFO]: ﴾PlotMe﴿ Detected world load for 'Plots'
[22:02:53] [Server thread/INFO]: ﴾PlotMe﴿  - generator: PlotSquared>PlotSquared
[22:02:53] [Server thread/INFO]: ﴾PlotMe﴿  - plotworld: com.github.intellectualsites.plotsquared.plot.generator.HybridPlotWorld
[22:02:53] [Server thread/INFO]: ﴾PlotMe﴿  - plotAreaManager: com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager
[22:02:53] [Server thread/ERROR]: Could not pass event WorldInitEvent to PlotSquared v4.244
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createWorld(CraftServer.java:965) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:458) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at multiworld.data.WorldManager.loadWorld(WorldManager.java:347) [multiworld.jar:?]
	at multiworld.data.WorldManager.loadWorlds(WorldManager.java:658) [multiworld.jar:?]
	at multiworld.data.DataHandler.load(DataHandler.java:242) [multiworld.jar:?]
	at multiworld.data.DataHandler.<init>(DataHandler.java:61) [multiworld.jar:?]
	at multiworld.MultiWorldPlugin.onEnable(MultiWorldPlugin.java:256) [multiworld.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.github.intellectualsites.plotsquared.plot.config.Configuration$UnsafeBlockException: oak_leaves is not a valid block
	at com.github.intellectualsites.plotsquared.plot.config.Configuration$4.parseString(Configuration.java:85) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.config.Configuration$4.parseString(Configuration.java:59) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.ClassicPlotWorld.loadConfiguration(ClassicPlotWorld.java:85) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotWorld.loadConfiguration(HybridPlotWorld.java:109) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.PlotArea.loadDefaultConfiguration(PlotArea.java:339) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.PlotSquared.loadWorld(PlotSquared.java:1104) ~[?:?]
	at com.github.intellectualsites.plotsquared.bukkit.listeners.WorldEvents.onWorldInit(WorldEvents.java:31) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	... 21 more`

**Comment by MerlinK11** [comment]
i am in the world: Plots and to do /p i and cams
You are Not in a Plotworld!

**Comment by MattBDev** [comment]
Totally different issue. For help with that you should join the discord.

**Comment by dordsor21** [comment]
There are no bugs with P2 here.
