### ISSUE TITLE
/p debugpaste causes java.net.ConnectException

### ISSUE THREAD

**Issue by burdoto** [IntellectualSites/PlotSquared#2332]
As seen in issues #2330 and #2331 (also opened by me), I am unable to use `/p debugpaste`.
The command causes the following stacktrace into console when issued both from client and server side:
```
> plot debugpaste
[10:46:34 WARN]: java.net.ConnectException: Connection timed out (Connection timed out)
[10:46:34 WARN]:        at java.net.PlainSocketImpl.socketConnect(Native Method)
[10:46:34 WARN]:        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[10:46:34 WARN]:        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[10:46:34 WARN]:        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[10:46:34 WARN]:        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[10:46:34 WARN]:        at java.net.Socket.connect(Socket.java:589)
[10:46:34 WARN]:        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
[10:46:34 WARN]:        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[10:46:34 WARN]:        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[10:46:34 WARN]:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[10:46:34 WARN]:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[10:46:34 WARN]:        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[10:46:34 WARN]:        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[10:46:34 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[10:46:34 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[10:46:34 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
[10:46:34 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[10:46:34 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
[10:46:34 WARN]:        at com.github.intellectualsites.plotsquared.plot.util.IncendoPaster.upload(IncendoPaster.java:123)
[10:46:34 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.DebugPaste.lambda$onCommand$0(DebugPaste.java:118)
[10:46:34 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[10:46:34 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[10:46:34 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:46:34 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:46:34 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:46:34 WARN]:        at java.lang.Thread.run(Thread.java:748)
[10:47:13 WARN]: java.net.ConnectException: Connection timed out (Connection timed out)
[10:47:13 WARN]:        at java.net.PlainSocketImpl.socketConnect(Native Method)
[10:47:13 WARN]:        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[10:47:13 WARN]:        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[10:47:13 WARN]:        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[10:47:13 WARN]:        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[10:47:13 WARN]:        at java.net.Socket.connect(Socket.java:589)
[10:47:13 WARN]:        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
[10:47:13 WARN]:        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[10:47:13 WARN]:        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[10:47:13 WARN]:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[10:47:13 WARN]:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[10:47:13 WARN]:        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[10:47:13 WARN]:        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[10:47:13 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[10:47:13 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[10:47:13 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
[10:47:13 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[10:47:13 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
[10:47:13 WARN]:        at com.github.intellectualsites.plotsquared.plot.util.IncendoPaster.upload(IncendoPaster.java:123)
[10:47:13 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.DebugPaste.lambda$onCommand$0(DebugPaste.java:118)
[10:47:13 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[10:47:13 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[10:47:13 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:47:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:47:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:47:13 WARN]:        at java.lang.Thread.run(Thread.java:748)
[10:47:13 INFO]: [P2] Failed to create the debug paste: Connection timed out (Connection timed out)
```

**Comment by N0tMyFaultOG** [comment]
Not really an issue, the service is currently under maintenance.

**Comment by burdoto** [comment]
Alright, although it might be good to have handling or some message like "Maybe the service is on maintenance" for this case within the plugin 👍

**Comment by MattBDev** [comment]
@burdoto Agreed.
