### ISSUE TITLE
Bug BiomeGrids

### ISSUE THREAD

**Issue by andfont** [IntellectualSites/PlotSquared#2336]
my server: 1.13.2 spigot
version plotsquared: PlotSquared-Bukkit-19.04.20-347c6fd-753

generates this error and there is no way to eliminate it:
error:
[01:15:42 INFO]: Adding new expiry task!
[01:15:43 WARN]: [PlotSquared] Task #294 for PlotSquared v19.04.20-347c6fd-753 generated an exception
java.lang.NoSuchMethodError: org.bukkit.generator.ChunkGenerator.generateExtBlockSections(Lorg/bukkit/World;Ljava/util/Random;IILorg/bukkit/generator/ChunkGenerator$BiomeGrid;)[[S
        at com.plotsquared.bukkit.util.BukkitHybridUtils$1$2$1.run(BukkitHybridUtils.java:93) ~[?:?]
        at com.plotsquared.bukkit.util.BukkitHybridUtils$1$2$1.run(BukkitHybridUtils.java:87) ~[?:?]
        at com.intellectualcrafters.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
        at com.intellectualcrafters.plot.util.ChunkManager$3.run(ChunkManager.java:182) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-f09662d-3697519]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-f09662d-3697519]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by N0tMyFaultOG** [comment]
Update P2 https://ci.athion.net/job/PlotSquared-Breaking/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-4.244.jar

**Comment by andfont** [comment]
It is not possible with these versions I do not work the plotsquared only with PlotSquared-legacis, versions 4.2 etc. do not work on my server 1.13.2 only the jenkins. Greetings.

**Comment by N0tMyFaultOG** [comment]
If v4 doesn't work, you are using outdated dependencies. Try the version I sent you above, restart the server and pastebin your startup log please.

**Comment by andfont** [comment]
https://pastebin.com/98zY96Bt

**Comment by andfont** [comment]
Hello I have sent the full log of errors are many with the 4.2 and for that reason we use the jenkings that we are perfect except that error that I have commented, please only ask that you fix the error of the biomes. the 4.2 is a disaster for us it does not work! when you have fixed the error of plotsquared-legacies of jenkins to say thank you.

**Comment by N0tMyFaultOG** [comment]
> Hello I have sent the full log of errors are many with the 4.2 and for that reason we use the jenkings that we are perfect except that error that I have commented, please only ask that you fix the error of the biomes. the 4.2 is a disaster for us it does not work! when you have fixed the error of plotsquared-legacies of jenkins to say thank you.

We won't "fix" something that is not broken, but might break if you use the wrong version on your systems. Also, you are running several outdated software which are conflicting with each other
- Update Spigot/Paper to the latest build (Paper is recommended like you can see in the log)
- Remove Fawe/DummyFawe and give it an update: https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/lastSuccessfulBuild/artifact/target/FastAsyncWorldEdit-bukkit-1.13.88.jar
- Update WorldGuard https://dev.bukkit.org/projects/worldguard/files/2663455/download

`The conversion has finished. PlotSquared will now be disabled and the new configuration file will be used at next startup. Please review the new worlds.yml file. Please note that schematics will not be converted, as we are now using WorldEdit to handle schematics. You need to re-generate the schematics`
Like it's already written in your startup log, restart your server to so P2 can use the new files

**Comment by andfont** [comment]
- Nostro Spigot is updated.
- We can not update the FAWE or WG because many plugins STOP WORKING !, For that reason we use the PlotSquared-legacies because we work everything but that detail that should be easy to fix.
- We can not update the mentioned versions because other plugins do not work and it is a big problem for us. please fix that mistakes thank you! Greetings.

**Comment by N0tMyFaultOG** [comment]
Idc about other plugins not working, if they are outdated either get a rid of them or kindly remind the author to do so. We are not fixing issues in the legacy versions so they work with 1.13, this is not intended and if you really want to use it, you can go ahead to do so but won't receive and support for it.
To verify that you are running the latest version, run `/version` ingame. If it returns that you are running the latest version it's fine.
