### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by mctool** [IntellectualSites/PlotSquared#2338]
```
[20:14:52 INFO]: Angelove issued server command: /mv tp plotworld
[20:14:54 WARN]: java.lang.NullPointerException
[20:14:54 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.titles.TitleManager_1_11.getHandle(TitleManager_1_11.java:352)
[20:14:54 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:326)
[20:14:54 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:195)
[20:14:54 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:15)
[20:14:54 WARN]:        at com.github.intellectualsites.plotsquared.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[20:14:54 WARN]:        at com.github.intellectualsites.plotsquared.plot.listener.PlotListener.lambda$plotEntry$0(PlotListener.java:177)
[20:14:54 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[20:14:54 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:14:54 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:14:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:14:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:14:54 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:14:54 WARN]: java.lang.NullPointerException
[20:14:54 WARN]:        at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source)
[20:14:54 WARN]:        at sun.reflect.UnsafeObjectFieldAccessorImpl.get(Unknown Source)
[20:14:54 WARN]:        at java.lang.reflect.Field.get(Unknown Source)
[20:14:54 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.titles.TitleManager_1_11.resetTitle(TitleManager_1_11.java:327)
[20:14:54 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.titles.TitleManager_1_11.send(TitleManager_1_11.java:195)
[20:14:54 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.titles.DefaultTitle_111.sendTitle(DefaultTitle_111.java:15)
[20:14:54 WARN]:        at com.github.intellectualsites.plotsquared.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:14)
[20:14:54 WARN]:        at com.github.intellectualsites.plotsquared.plot.listener.PlotListener.lambda$plotEntry$0(PlotListener.java:177)
[20:14:54 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[20:14:54 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:14:54 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:14:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:14:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:14:54 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by N0tMyFaultOG** [comment]
Fill out the issue template to receive support

**Comment by MattBDev** [comment]
We need a plotsquared version spigot/paper version and a multiverse version in order to help.
