### ISSUE TITLE
No commands work

### ISSUE THREAD

**Issue by psrcek** [IntellectualSites/PlotSquared#2344]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** cannot run command, because nothing works, but console says Version is PlotSquared-19.4.17-8ac23b9-245 on startup. Also tried [this version](http://ci.athion.net/job/PlotSquared-Releases/4/artifact/target/PlotSquared-Bukkit-4.221.jar), same issue.

**[REQUIRED] Spigot/Paper Version Number:** tried both git-Spigot-82e117e-2b2d084 and git-Spigot-1a3504a-a46fdbc. Same issue.

**[REQUIRED] Minecraft Version Number:** 1.13.2

**[REQUIRED] Description of the problem:**
No commands work. I've tried replacing and removing multiple other plugins to no avail. Please fix this as soon as possible as this plugin is required for our server to exist.

**Any relevant console output or screenshots:**
```log
[04:01:46 INFO]: [P2]  PlotSquared is using online UUIDs
[04:01:46 WARN]: java.lang.NullPointerException
[04:01:46 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.DebugExec.init(DebugExec.java:77)
[04:01:46 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.DebugExec.<init>(DebugExec.java:34)
[04:01:46 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.getInstance(MainCommand.java:80)
[04:01:46 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.<init>(SubCommand.java:18)
[04:01:46 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.<init>(SubCommand.java:22)
[04:01:46 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.commands.DebugUUID.<init>(DebugUUID.java:36)
[04:01:46 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.<init>(BukkitCommand.java:18)
[04:01:46 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.registerCommands(BukkitMain.java:302)
[04:01:46 WARN]:        at com.github.intellectualsites.plotsquared.plot.PlotSquared.<init>(PlotSquared.java:198)
[04:01:46 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:143)
[04:01:46 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[04:01:46 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[04:01:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[04:01:46 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[04:01:46 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[04:01:46 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[04:01:46 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[04:01:46 WARN]:        at java.lang.Thread.run(Thread.java:748)
[04:01:46 INFO]: PlotSquared is now enabled
```

**Plugins being used on the server:**
LuckPerms, WorldEdit, RedstoneClockDetector, LogBlock, Vault, WorldGuard, ModuleLoader (custom plugin), Essentials, EssentialsChat, PlotSquared, EssentialsSpawn, Multiverse-Core, Multiverse-Inventories

**How to replicate:** 
Just start the server, don't know what causes it.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
1.13 requires P2 version 4.2+ 
You're using the 1.12.2 and older legacy version. Create a new debug paste with proper versions if still having issues.

**Comment by psrcek** [comment]
What do you mean by version 4.2? From what I can find on this repository it says to use [this](https://ci.athion.net/job/PlotSquared-Breaking/) and the latest on that is PlotSquared-19.4.27-b7909cc-263
You clearly state [here](https://github.com/IntellectualSites/PlotSquared/releases/tag/4.0-pre-breaking) that it is for 1.13, and the same issue persists here.

```log
[13:05:29 INFO]: Version is PlotSquared-19.4.27-b7909cc-263
[13:05:29 INFO]: [P2] KillAllEntities started.
[13:05:29 INFO]: Please enable metrics for PlotSquared. Using metrics improves plugin stability, performance, and features. Bug fixes and new features are influenced on metrics.
[13:05:29 INFO]: [P2]  PlotSquared is using online UUIDs
[13:05:30 WARN]: java.lang.NullPointerException
[13:05:30 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.DebugExec.init(DebugExec.java:77)
[13:05:30 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.DebugExec.<init>(DebugExec.java:34)
[13:05:30 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.getInstance(MainCommand.java:80)
[13:05:30 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.<init>(SubCommand.java:18)
[13:05:30 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.<init>(SubCommand.java:22)
[13:05:30 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.commands.DebugUUID.<init>(DebugUUID.java:36)
[13:05:30 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.<init>(BukkitCommand.java:18)
[13:05:30 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.registerCommands(BukkitMain.java:306)
[13:05:30 WARN]:        at com.github.intellectualsites.plotsquared.plot.PlotSquared.<init>(PlotSquared.java:198)
[13:05:30 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:142)
[13:05:30 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[13:05:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[13:05:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[13:05:30 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[13:05:30 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[13:05:30 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[13:05:30 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[13:05:30 WARN]:        at java.lang.Thread.run(Thread.java:748)
[13:05:30 INFO]: PlotSquared is now enabled

```

**Comment by AeSix** [comment]
https://www.spigotmc.org/resources/plotsquared.1177/

**Comment by psrcek** [comment]
Same error with the jar from the spigot page:
```log
[13:59:08 INFO]: Version is PlotSquared-19.4.6-5d515b3-221
[13:59:08 INFO]: [P2] KillAllEntities started.
[13:59:08 INFO]: Please enable metrics for PlotSquared. Using metrics improves plugin stability, performance, and features. Bug fixes and new features are influenced on metrics.
[13:59:08 INFO]: [P2]  PlotSquared is using online UUIDs
[13:59:08 WARN]: java.lang.NullPointerException
[13:59:08 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.DebugExec.init(DebugExec.java:77)
[13:59:08 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.DebugExec.<init>(DebugExec.java:34)
[13:59:08 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.getInstance(MainCommand.java:80)
[13:59:08 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.<init>(SubCommand.java:18)
[13:59:08 WARN]:        at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.<init>(SubCommand.java:22)
[13:59:08 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.commands.DebugUUID.<init>(DebugUUID.java:36)
[13:59:08 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.<init>(BukkitCommand.java:18)
[13:59:08 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.registerCommands(BukkitMain.java:301)
[13:59:08 WARN]:        at com.github.intellectualsites.plotsquared.plot.PlotSquared.<init>(PlotSquared.java:198)
[13:59:08 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:143)
[13:59:08 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[13:59:08 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[13:59:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[13:59:08 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[13:59:08 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[13:59:08 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[13:59:08 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[13:59:08 WARN]:        at java.lang.Thread.run(Thread.java:748)
[13:59:08 INFO]: PlotSquared is now enabled
```

**Comment by AeSix** [comment]
Good. Now, can you send a /plot debugpaste link please?

**Comment by psrcek** [comment]
Uh.. no. I care about my data thanks, that is the only relevant error that is printed in console by p2. [here](http://cloud.panic.tk/s/rzw4aYNqxnxBdaz) is the log tho if you want it.

**Comment by AeSix** [comment]
I'm not downloading a log file.  If you want to use https://paste.md-5.net to paste the log so i can read it without downloading, I will.

**Comment by psrcek** [comment]
https://paste.md-5.net/nenebebegi.md

**Comment by AeSix** [comment]
[14:08:41] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.0-beta01;01dfebe
WorldGuard 7 Beta 3 should be used. 

[14:08:41] [Server thread/INFO]: [ModuleLoader] Loading ModuleLoader v5.2.2
Cannot find information for this. Apparently a custom plugins-as-modules system? Perhaps interfering?

[14:08:41] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v2.6.0-b738
AFAIK anything under 3.0.0 does not work on 1.13+ servers.
```[14:08:48] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v2.6.0-b738 (Is it up to date?)
java.lang.NullPointerException: null
	at buscript.multiverse.ScriptManager.<init>(ScriptManager.java:31) ~[?:?]
	at buscript.multiverse.Buscript.<init>(Buscript.java:77) ~[?:?]
	at buscript.multiverse.Buscript.<init>(Buscript.java:65) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.initializeBuscript(MultiverseCore.java:357) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:346) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot.jar:git-Spigot-1a3504a-a46fdbc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot.jar:git-Spigot-1a3504a-a46fdbc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot.jar:git-Spigot-1a3504a-a46fdbc]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot.jar:git-Spigot-1a3504a-a46fdbc]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot.jar:git-Spigot-1a3504a-a46fdbc]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot.jar:git-Spigot-1a3504a-a46fdbc]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot.jar:git-Spigot-1a3504a-a46fdbc]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot.jar:git-Spigot-1a3504a-a46fdbc]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-1a3504a-a46fdbc]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot.jar:git-Spigot-1a3504a-a46fdbc]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]```
This punctuates my point above. 

```[14:08:49] [Server thread/INFO]: [0;30;1m([0;31;22m[21mFAWE[0;30;1m)[m[0;37;22m Plugin 'PlotSquared' found. Using it now.[m
[14:08:49] [Server thread/WARN]: java.lang.ClassNotFoundException: com.destroystokyo.paper.event.server.AsyncTabCompleteEvent
[14:08:49] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[14:08:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136)
[14:08:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82)
[14:08:49] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[14:08:49] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[14:08:49] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[14:08:49] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[14:08:49] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.lambda$new$0(FaweBukkit.java:138)
[14:08:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[14:08:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[14:08:49] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[14:08:49] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[14:08:49] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[14:08:49] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[14:08:49] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)```
This confuses me as it says you're using paper, however there's a "USE PAPER" message furthur up in the log... Perhaps another P2 issue?

Of course, that issue may already be resolved, as well as the issue you intially reported with a newer build:
```[14:08:49] [Server thread/INFO]: [PlotSquared] -------- PlotSquared Update Check --------
[14:08:49] [Server thread/INFO]: [PlotSquared] There appears to be a PlotSquared update available!
[14:08:49] [Server thread/INFO]: [PlotSquared] You are running version 4.221, the newest available version is 4.226
[14:08:49] [Server thread/INFO]: [PlotSquared] Update URL: https://ci.athion.net/job/PlotSquared-Releases/5/artifact/target/PlotSquared-Bukkit-4.226.jar
[14:08:49] [Server thread/INFO]: [PlotSquared] -------- PlotSquared Update Check --------```

**Comment by psrcek** [comment]
i already tried the newer build and a newer multiverse version, our plugins are not interfering because this exact setup literally worked before

**Comment by psrcek** [comment]
log with newer versions of both: https://paste.md-5.net/cuwupetite.md

**Comment by dordsor21** [comment]
You're most likely using an incorrect Java version. Please use Java 8 or 9 with anything Minecraft related.

**Comment by psrcek** [comment]
I am using the 1.8.0_202-b08 build of java.

**Comment by dordsor21** [comment]
Are you sure? The issue is that the nashorn engine cannot be found. implying you are not.

**Comment by psrcek** [comment]
uhh does this convince you?
![image](https://user-images.githubusercontent.com/13370323/56866650-fc1ca200-69db-11e9-8864-741748f8af07.png)

**Comment by dordsor21** [comment]
uhh this is a problem with your setup, not a bug with PlotSquared.
