### ISSUE TITLE
1.14 /p delete error

### ISSUE THREAD

**Issue by cdmvirt** [IntellectualSites/PlotSquared#2345]
Notice this is on 1.14 with updated Worldedit for 1.14

```[PlotSquared] Task #624 for PlotSquared v4.263 generated an exception
java.lang.UnsupportedOperationException: Not supported in this Minecraft version! Unless you can fix it, this is not a bug :)
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.regenerateChunk(CraftWorld.java:399) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at com.github.intellectualsites.plotsquared.bukkit.util.block.BukkitLocalQueue.regenChunk(BukkitLocalQueue.java:71) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:177) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:173) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.util.ChunkManager$3.run(ChunkManager.java:183) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1005) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:798) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]```

**Comment by MattBDev** [comment]
1.14 support is still being worked on. Please use code blocks in markdown or use a pastebin service instead of copy and pasting the error.

**Comment by MattBDev** [comment]
Also do not delete the template. It is there for a reason and I normally would have just closed this issue.

**Comment by cdmvirt** [comment]
Sorry about that

**Comment by dordsor21** [comment]
This is currently an issue due to the method in Spigot being removed. When FAWE is fixed, using it will stop this issue, however, without FAWE, we must find a different solution to the regeneration of the chunk using this method (World#regenerateChunk(x, z))

**Comment by Yukyxy** [comment]
hi please fix this :(
