### ISSUE TITLE
 Could not pass event BlockRedstoneEvent to PlotSquared v4.221 and  Could not pass event BlockPhysicsEvent to PlotSquared v4.221

### ISSUE THREAD

**Issue by lays24mc** [IntellectualSites/PlotSquared#2348]
**[REQUIRED] PlotSquared Version Number:** 4.221

**[REQUIRED] Spigot/Paper Version Number:** 1.13.2

**[REQUIRED] Minecraft Version Number:** 1.13.2

**[REQUIRED] Description of the problem:** 

Server start and spam console wirh Could not pass event BlockRedstoneEvent to PlotSquared v4.221 and  Could not pass event BlockPhysicsEvent to PlotSquared v4.221

```[14:34:52 ERROR]: Could not pass event BlockRedstoneEvent to PlotSquared v4.221 org.bukkit.event.EventException: null at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.BlockRedstoneWire.b(BlockRedstoneWire.java:224) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.BlockRedstoneWire.a(BlockRedstoneWire.java:158) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:353) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.IBlockData.doPhysics(SourceFile:241) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.World.a(World.java:541) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.BlockDiodeAbstract.d(BlockDiodeAbstract.java:171) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.BlockRedstoneComparator.f(BlockRedstoneComparator.java:138) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.BlockRedstoneComparator.a(BlockRedstoneComparator.java:144) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.IBlockData.a(SourceFile:261) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.WorldServer.b(WorldServer.java:659) ~[spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:77) [spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:641) [spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:283) [spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952) [spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-f56e2e7-4385562] at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-f56e2e7-4385562] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181] Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3 at com.github.intellectualsites.plotsquared.plot.object.Location.(Location.java:26) ~[?:?] at com.github.intellectualsites.plotsquared.plot.object.Location.(Location.java:34) ~[?:?] at com.github.intellectualsites.plotsquared.bukkit.util.BukkitUtil.getLocation(BukkitUtil.java:200) ~[?:?] at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onRedstoneEvent(PlayerEvents.java:311) ~[?:?] at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-f56e2e7-4385562] ... 21 more ```

**Comment by dordsor21** [comment]
What version of WorldEdit are you using?

**Comment by SeaLife** [comment]
Hey, got the same Problme.

My Stacktrace is:

```log
> [17:59:30] [Server thread/ERROR]: Could not pass event BlockIgniteEvent to PlotSquared v4.276
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[server.jar:git-Spigot-4d24e36-5193f76]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-4d24e36-5193f76]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[server.jar:git-Spigot-4d24e36-5193f76]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[server.jar:git-Spigot-4d24e36-5193f76]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callBlockIgniteEvent(CraftEventFactory.java:1152) ~[server.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.BlockFire.tick(BlockFire.java:180) ~[server.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.IBlockData.a(SourceFile:262) ~[server.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.WorldServer.b(WorldServer.java:553) ~[server.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.TickListServer.a(TickListServer.java:76) [server.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:270) [server.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1054) [server.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [server.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:953) [server.jar:git-Spigot-4d24e36-5193f76]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:798) [server.jar:git-Spigot-4d24e36-5193f76]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
at com.github.intellectualsites.plotsquared.plot.object.Location.<init>(Location.java:26) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.object.Location.<init>(Location.java:34) ~[?:?]
at com.github.intellectualsites.plotsquared.bukkit.util.BukkitUtil.getLocation(BukkitUtil.java:200) ~[?:?]
at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onBlockIgnite(PlayerEvents.java:2356) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-4d24e36-5193f76]
... 14 more
```

World-Edit Version: (current from bukkit.org) worldedit-bukkit-6.1.9.jar

Regards
SeaLife

**Comment by N0tMyFaultOG** [comment]
> Hey, got the same Problme.

No, you are running WorldEdit <=1.12.2 on a 1.14 server where the issue above is purely 1.13

**Comment by SeaLife** [comment]
Ok, installed the beta files for 1.13+ (clicked on "latest" - downloaded the old version, sorry for not checking this).

Working fine now.
