### ISSUE TITLE
Server crash in EntitySpawnListener

### ISSUE THREAD

**Issue by lagnat** [IntellectualSites/PlotSquared#2413]
Quick side note:  Should this code check that the ChunkLoadEvent is coming from the plot world before doing its work?

```    
    @EventHandler public void onChunkLoad(ChunkLoadEvent event) {
        @NotNull Chunk chunk = event.getChunk();
        for (Entity entity : chunk.getEntities()) {
            testCreate(entity);
        }
    }
```

Calling chunk.getEntities() calls CraftWorld.getChunkAt() which eventually creates a recursion in ChunkMapDistance.a(), and that results in a CME.  

I can reproduce this crash by spamming `/ps home`, `/spawn`, `/ps home`, `/spawn`, `/ps home`, `/spawn`, ... and it will eventually throw a CME.

I don't know bukkit well enough so I could be way off here, but I'd expect getting entities from a ChunkLoadEvent to be safe, however at present time it is not.  I asked the question at the bottom of https://hub.spigotmc.org/jira/browse/SPIGOT-5116.

**Comment by AeSix** [comment]
Please re-open with appropriate information as prescribed in the issue template which you have removed.

**Comment by lagnat** [comment]
The spigot folks have reopened their ticket after initially considering it a plug-in issue so chances are good that they consider this a spigot bug.  In the mean time your code is vulnerable and you’re free to disregard this ticket because of its format.

**Comment by Sauilitired** [comment]
This warrants an exception to the report format in my opinion.

**Comment by lagnat** [comment]
You can see a stack trace in the spigot ticket, however it doesn't do you any good because it doesn't show any plotsquared code in it which is why I didn't paste it here.  I'll get into a little more detail..

When chunks are loaded, your event handler is called.  It's vanilla code iterating a collection of chunks which eventually leads to some bukkit code that calls you on your event handler.  Your event handler calls `chunk.getEntities()`, which for reasons that I am not qualified to understand, has to re-load the chunk.  That causes the same vanilla code to start iterating and calling out again.  After the second iteration is complete, the vanilla code `clear()`s the collection and the stack continues to unwind.  Eventually we get back to the first iteration which is still in progress and now you've got the CME because the collection was cleared in the recursion.  

In order to catch this happening in the wild, I added some instrumentation to `ChunkMapDistance.a()` to detect the recursion and throw an exception.  Here is what that looks like:

```
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.Chunk.loadCallback(Chunk.java:522) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$11(PlayerChunk.java:358) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$10(PlayerChunk.java:356) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_191]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:669) ~[?:1.8.0_191]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:1997) ~[?:1.8.0_191]
        at net.minecraft.server.v1_14_R1.PlayerChunk.a(PlayerChunk.java:355) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.ChunkMapDistance.lambda$1(ChunkMapDistance.java:110) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_191]
        at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:109) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:202) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:142) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:89) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:212) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(SourceFile:106) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:207) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.World.getType(World.java:548) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getType(CraftBlock.java:211) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at com.github.intellectualsites.plotsquared.bukkit.util.BukkitUtil.getHighestBlock(BukkitUtil.java:274) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.object.Plot.getSide(Plot.java:1221) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.object.Plot.getDefaultHome(Plot.java:1304) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.object.Plot.getHome(Plot.java:1236) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.object.Plot.teleportPlayer(Plot.java:2741) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.commands.Visit.lambda$execute$1(Visit.java:137) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.commands.MainCommand$1.run(MainCommand.java:172) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.commands.MainCommand$1.run(MainCommand.java:133) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.commands.Visit.execute(Visit.java:136) ~[?:?]
        at com.github.intellectualsites.plotsquared.commands.Command.execute(Command.java:323) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.execute(MainCommand.java:253) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.onCommand(MainCommand.java:133) ~[?:?]
        at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:25) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:709) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:874) [spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IllegalStateException: Recursion a!
        at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:107) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:202) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:142) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:89) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at net.minecraft.server.v1_14_R1.IChunkProvider.getChunkAt(SourceFile:16) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getChunkAt(CraftWorld.java:321) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at org.bukkit.craftbukkit.v1_14_R1.CraftChunk.getEntities(CraftChunk.java:97) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        at com.github.intellectualsites.plotsquared.bukkit.listeners.EntitySpawnListener.onChunkLoad(EntitySpawnListener.java:138) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.3-R0.1-SNAPSHOT.jar:git-Spigot-935adb3-a0e4747]
        ... 53 more
```

At issue is loading chunks while in the ChunkLoadEvent handler, but you're not loading chunks, spigot is loading chunks on your behalf and how are you to know which bukkit calls might also decide to load chunks.  There is a link to a Paper patch in the Spigot ticket but it seems the Spigot people aren't satisfied with that fix.  There is a mention of that fix having side effects.

It seems to me that you'd be able to protect yourself by either testing the chunk to see if it's loaded before calling `getEntities()` or putting the whole thing into a scheduled task.  I also want to re-iterate my off-topic question.  Should this code check that the ChunkLoadEvent is coming from the plot world before doing its work?

**Comment by lagnat** [comment]
Latest spigot has a fix for this
