### ISSUE TITLE
Wichtig: Probleme mit /p setowner <player>

### ISSUE THREAD

**Issue by DueKay** [IntellectualSites/PlotSquared#2416]
** [ERFORDERLICH] PlotSquared-Versionsnummer: PlotSquared-19.6.25-12e5d2e-771
** [ERFORDERLICH] NukkitX Versionsnummer: Dieser Server läuft unter der Version Nukkit git-de9fecc 「」und nutzt die Version 1.0.8 der API für Minecraft:BE v1.11.0 (Protokoll Version 354) 
** [ERFORDERLICH] Minecraft-Versionsnummer: Minecraft:BE v1.11.0
** [ERFORDERLICH] Beschreibung des Problems: Seid wann genau das Problem vorliegt, kann ich nicht genau sagen. Aufgefallen ist es mir gestern, als ich ein Plot mit /p setowner <Player> auf jemanden umschreiben wollte. 
Ingame hat er mir Garnichts angezeigt. Werder das ein Befehl gesendet, ausgeführt oder angekommen ist. In der Konsole kam dann das, was ich in den nächsten Abschnitt rein kopiert habe.
Ich hoffe ihr könnt mir helfen, da ich echt nicht weiß wie ich das beheben kann und auf den Befehl angewiesen bin.
** Alle relevanten Konsolenausgaben oder Screenshots: [36m10:47:35[m [[m[5;1;31mFATAL[m[m] Exception while invoking run 
java.lang.IllegalArgumentException: getHandlers method in com.plotsquared.nukkit.events.PlotChangeOwnerEvent was not static! 
at cn.nukkit.plugin.PluginManager.getEventListeners(PluginManager.java:627) ~[nukkit.jar:?] 
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:540) ~[nukkit.jar:?] 
at com.plotsquared.nukkit.util.NukkitEventUtil.callEvent(NukkitEventUtil.java:39) ~[?:?] 
at com.plotsquared.nukkit.util.NukkitEventUtil.callOwnerChange(NukkitEventUtil.java:120) ~[?:?] 
at com.intellectualcrafters.plot.object.Plot.setOwner(Plot.java:792) ~[?:?] 
at com.intellectualcrafters.plot.commands.Owner$1.run(Owner.java:80) ~[?:?] 
at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) [nukkit.jar:?] 
at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) [nukkit.jar:?] 
at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [nukkit.jar:?] 
at cn.nukkit.Server.tick(Server.java:1131) [nukkit.jar:?] 
at cn.nukkit.Server.tickProcessor(Server.java:903) [nukkit.jar:?] 
at cn.nukkit.Server.start(Server.java:880) [nukkit.jar:?] 
at cn.nukkit.Server.<init>(Server.java:565) [nukkit.jar:?] 
at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?] 
** Auf dem Server verwendete Plugins: Plugins (21): RollBossBar v1.1.0, DiscordChat v1.1.5.2, XHud v2.0, AutoSpawn v1.0, EconomyAPI v2.0.1, TransferCommand v1.0, StaffChat v1.0, EssentialsNK v1.6.1, FastAsyncWorldEdit v19.06.12-f71043b-1275-22.2.1, PlotSquared v19.06.25-12e5d2e-771, LuckPerms v4.4.19, NPC v2.2.4, KotlinLib v1.1, LuckChat v1.8-Beta, DbLib v1.0.1, PocketVote v2.0.1-bDEV, MultiWorld v1.0, MobPlugin v1.9.0.3, PlaceholderAPI v1.3.1, ChestShop v1.0, Holograms v3.1 

** Checkliste **:
<! - Stellen Sie sicher, dass Sie die folgenden Schritte ausgeführt haben (setzen Sie ein "X" in Klammern): ->
- [X] Ich habe alle erforderlichen Informationen in die obigen Abschnitte aufgenommen
- [] Ich habe sichergestellt, dass es keine Duplikate dieses Berichts gibt. [(Suche verwenden)] (https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
--->> Ich hab geschaut, da aber alles auf englisch ist und selten fragen zu Nukkit kommen, ist es nicht so eicht für mich xD
- [X] Ich habe sichergestellt, dass ich eine aktuelle Version von PlotSquared verwende
- [X] Ich habe sichergestellt, dass der Fehler nicht durch ein anderes Plugin verursacht wird
--->>Ich kann mich auch irren, aber ich würde meinen, dass es an keinem der anderen Plugins liegt.

Danke schonmal und Lg,
Jenny | DueKay

-------------------------------------------------------------------------------

** [REQUIRED] PlotSquared version number: PlotSquared-19.6.25-12e5d2e-771
** [REQUIRED] NukkitX version number: This server runs under the version Nukkit git-de9fecc 「」 and uses version 1.0.8 of the API for Minecraft: BE v1.11.0 (protocol version 354)
** [REQUIRED] Minecraft version number: Minecraft: BE v1.11.0
** [REQUIRED] Description of the problem: When exactly the problem is, I can not say exactly. It struck me yesterday when I wanted to rewrite a plot with / p setowner <Player>.
Ingame he has shown me nothing. If a command was sent, executed or arrived. In the console came then what I have purely copied in the next section.
I hope you can help me, because I really do not know how I can fix it and rely on the command.
** All relevant console editions or screenshots: [36m10: 47: 35 [m [[m [5; 1; 31mFATAL [m [m] Exception while invoking run
java.lang.IllegalArgumentException: getHandlers method in com.plotsquared.nukkit.events.PlotChangeOwnerEvent was not static!
at cn.nukkit.plugin.PluginManager.getEventListeners (PluginManager.java:627) ~ [nukkit.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent (PluginManager.java:540) ~ [nukkit.jar:?]
at com.plotsquared.nukkit.util.NukkitEventUtil.callEvent (NukkitEventUtil.java:39) ~ [?:?]
at com.plotsquared.nukkit.util.NukkitEventUtil.callOwnerChange (NukkitEventUtil.java:120) ~ [?:?]
at com.intellectualcrafters.plot.object.Plot.setOwner (Plot.java:792) ~ [?:?]
at com.intellectualcrafters.plot.commands.Owner $ 1.run (Owner.java:80) ~ [?:?]
at cn.nukkit.scheduler.TaskHandler.run (TaskHandler.java:99) [nukkit.jar:?]
at cn.nukkit.scheduler.ServerScheduler.runTasks (ServerScheduler.java:296) [nukkit.jar:?]
at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat (ServerScheduler.java:277) [nukkit.jar:?]
at cn.nukkit.Server.tick (Server.java:1131) [nukkit.jar:?]
at cn.nukkit.Server.tickProcessor (Server.java:903) [nukkit.jar:?]
at cn.nukkit.Server.start (Server.java:880) [nukkit.jar :?]
at cn.nukkit.Server. <init> (Server.java:565) [nukkit.jar :?]
at cn.nukkit.Nukkit.main (Nukkit.java:112) [nukkit.jar :?]
** Plugins used on the server: Plugins (21): RollBossBar v1.1.0, DiscordChat v1.1.5.2, XHud v2.0, AutoSpawn v1.0, EconomyAPI v2.0.1, TransferCommand v1.0, StaffChat v1.0, EssentialsNK v1.6.1, FastAsyncWorldEdit v19.06.12-f71043b-1275-22.2.1, PlotSquared v19.06.25-12e5d2e-771, LuckPerms v4.4.19, NPC v2.2.4, KotlinLib v1.1, LuckChat v1.8 Beta, DbLib v1.0.1, PocketVote v2.0.1-bDEV, MultiWorld v1.0, MobPlugin v1.9.0.3, PlaceholderAPI v1.3.1, ChestShop v1.0, Holograms v3.1

** Checklist **:
<! - Make sure you have completed the following steps (put an "X" in parentheses): ->
- [X] I have included all necessary information in the sections above
- [] I have made sure that there are no duplicates of this report. [(Use Search)] (https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
--- >> I looked, but since everything is in English and rarely come to Nukkit, it is not so easy for me xD
- [X] I made sure I used a recent version of PlotSquared
- [X] I made sure that the bug is not caused by another plugin
--- >> I can be wrong too, but I would think that it is not on any of the other plugins.

Thanks in advance and Lg,
Jenny | DueKay

**Comment by DueKay** [comment]
Ich hoffe wirklich, dass mir jemand helfen kann.
Ohne den Befehl, können wir unseren Server nicht Releasen >.<
Eigentlich ging der Befehl immer. Ich weiß wirklich nicht woher der Fehler kommt. 

----------------------------------------------------


I really hope somebody can help me.
Without the command, we can not release our server>. <
Actually, the command always went. I really do not know where the mistake is coming from.


Lg Jenny | DueKay

**Comment by DueKay** [comment]
Ich hab nun auch versucht, eine alte Version von Plotsquared zu benutzen (die letzte, welche noch bei nukkitx.com drin ist) aber der Fehler bleibt der selbe in der Konsole...
Kann mir jemand sagen woran das liegen kann?

----------------------------------------------------------------


I've also tried using an old version of Plotsquared (the last one still on nukkitx.com) but the bug stays the same in the console ...
Can someone tell me why this may be?

**Comment by DueKay** [comment]
Abend zusammen,
ich hoffe das Sie sich meinem Problem annehmen können, da man wirklich auf den Befehl angewiesen ist. Ein anderes Plot System gibt es für Nukkit auch nicht und selbst wenn würde ich gerne bei Plotsquared bleiben.

Lg DueKay

---------------------------------------------------------------------------

Evening together,
I hope you can take care of my problem because you really need the command. Nukkit does not have another plot system and even if I would like to stay with Plotsquared.

Lg DueKay

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/pull/2419
