### ISSUE TITLE
They can place lava and water in other plots!!!

### ISSUE THREAD

**Issue by andfont** [IntellectualSites/PlotSquared#2435]
- plot version
[13:44:13] [Craft Scheduler Thread - 84/INFO]: [P2] >> PlotSquared (Version: PlotSquared-4.301)
[13:44:13] [Craft Scheduler Thread - 84/INFO]: [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21
[13:44:13] [Craft Scheduler Thread - 84/INFO]: [P2] >> Wiki: https://github.com/IntellectualCrafters/PlotSquared/wiki
[13:44:13] [Craft Scheduler Thread - 84/INFO]: [P2] >> Newest Version: development-builds
**[REQUIRED] Spigot/Paper Version Number:** 
- MC Version 1.14.3 Spigot

BUG, ERROR:
[13:27:41] [Server thread/ERROR]: Could not pass event PlayerBucketEmptyEvent to PlotSquared v4.301
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:380) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactory.java:353) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.ItemBucket.a(ItemBucket.java:134) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.ItemBucket.a(ItemBucket.java:70) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.ItemStack.a(ItemStack.java:301) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:387) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1328) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875) [spigot.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot.jar:git-Spigot-9a643a6-eb2e657]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: Cannot get ID of Modern Material
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at org.bukkit.Material.getId(Material.java:3302) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onBucketEmpty(PlayerEvents.java:2382) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-9a643a6-eb2e657]
        ... 23 more
>

**[REQUIRED] Minecraft Version Number:** 
**Links to worlds.yml file and settings.yml file:** 
Worlds:
https://pastebin.com/ETBupWpS
Settings:
https://pastebin.com/a1HwvN2J

**[REQUIRED] Description of the problem:** 
A player who does not have permits in a plot can fill it with LAVA AND WATER terrible! BUG!! we have left the creative miss a mess please fix this terrible bug!

**Comment by antiburen** [comment]
I have the same problem, 1.14.4 PaperMC

[17:49:57 ERROR]: Could not pass event PlayerBucketEmptyEvent to PlotSquared v4.301
java.lang.IllegalArgumentException: Cannot get ID of Modern Material
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.14.4.jar:git-Paper-135]
        at org.bukkit.Material.getId(Material.java:3319) ~[patched_1.14.4.jar:git-Paper-135]
        at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onBucketEmpty(PlayerEvents.java:2382) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor34.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-135]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-135]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-135]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:396) ~[patched_1.14.4.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactory.java:368) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.ItemBucket.a(ItemBucket.java:140) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.ItemBucket.a(ItemBucket.java:70) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.ItemStack.a(ItemStack.java:330) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:392) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1416) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:991) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-135]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by AeSix** [comment]
Woo! Someone who didn't open a duplicate ticket. Thank you for your contribution @antiburen 
I'm sure the devs will be seeing this sooner or later.

**Comment by andfont** [comment]
but is it or not solved? I do not understand the answer is solved?Why do you close the ticket?

**Comment by andfont** [comment]
sorry and I think it's solved thank you very much! xDD good work xD
