### ISSUE TITLE
road plot schematic creation error

### ISSUE THREAD

**Issue by AeSix** [IntellectualSites/PlotSquared#2459]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 
PlotSquared 4.318

**[REQUIRED] Spigot/Paper Version Number:** 

[11:55:23 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[11:55:23 INFO]: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.

**[REQUIRED] Minecraft Version Number:** 
1.13.2

**Links to worlds.yml file and settings.yml file:** 

**[REQUIRED] Description of the problem:** 
/plot createroadschematic 
errors and does not perform.

**Any relevant console output or screenshots:**
The only output after immediately doing this command:
```
[11:54:26 WARN]: java.lang.NullPointerException
[11:54:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.generator.HybridUtils.regenerateRoad(HybridUtils.java:367)
[11:54:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.generator.HybridUtils$2$1.run(HybridUtils.java:201)
[11:54:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14)
[11:54:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.util.TaskManager$2.run(TaskManager.java:126)
[11:54:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.util.TaskManager$2.run(TaskManager.java:123)
[11:54:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14)
[11:54:26 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[11:54:26 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[11:54:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[11:54:26 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[11:54:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[11:54:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[11:54:26 WARN]:        at java.lang.Thread.run(Thread.java:748)
```
This is replicated continuously until interupted by the next command: (debugroadregen)

However, after attempting /plot debugroadregen:
```
[11:57:53 WARN]: java.lang.NullPointerException
[11:57:54 WARN]: java.lang.NullPointerException
[11:57:55 WARN]: java.lang.NullPointerException
[11:57:56 WARN]: java.lang.NullPointerException
[11:57:57 WARN]: java.lang.NullPointerException
[11:57:58 WARN]: java.lang.NullPointerException
[11:57:59 WARN]: java.lang.NullPointerException
[11:58:00 WARN]: java.lang.NullPointerException
```
Also continually spewing like niagra falls of NPEs.

**Plugins being used on the server:**

P2 4.318, WorldEdit 7 release, WorldGuard 7 release, a bunch of others which shouldn't have an affect on schemtics, plots, or chunk generation.

**How to replicate:** 

I started by doing "plot regenallroads newworld" - which gave me an informative message about it doing nothing if no road schematic was found.  (Shouldn't this actually regen the roads with the config settings if there's no schematic?)  I waited several minutes 
modify the roads around a plot.
/plot createroadschematic
(first error occurs)
/plot debugroadregen
(NPE flood)

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Closing, adding to https://github.com/IntellectualSites/PlotSquared/issues/2349 as a duplicate.

It appears plot/road schematic functions as a whole are not working properly.
