### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to PlotSquared

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#2463]
Paper dev 167 (Spigot 1.14.4)
PlotSquared-Breaking dev 326
WorldEdit dev 4623

Error occurs when chatting outside a plot region. 

Broke here? https://github.com/IntellectualSites/PlotSquared/commit/96427777500a0fdb48680ad657bf1077062f2f5a#diff-8a5f276e6afea474493ff275a6f82afeR935

```
[10:15:00] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to PlotSquared v4.326
java.lang.NullPointerException: null
	at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onChat(PlayerEvents.java:934) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor103.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1713) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by mibby** [comment]
Downgrading to dev 323 seems to fix the issue.

**Comment by MattBDev** [comment]
Looks like I unintentionally broke something. I'll fix it in a few hours.
