### ISSUE TITLE
Chunk worker exception on latest

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/PlotSquared#2464]
#Bug report template 
**[REQUIRED] PlotSquared Version Number:** Version 4 Build 326

**[REQUIRED] Spigot/Paper Version Number:** 
Paper 639

**[REQUIRED] Minecraft Version Number:** 
1.13.2

**Links to worlds.yml file and settings.yml file:** 
[worlds.yml](https://hastebin.com/dalaweyegi.sql)
[settings.yml](https://hastebin.com/abolopajog.bash)

**[REQUIRED] Description of the problem:** 
plot delete, setbiome make exception
**Any relevant console output or screenshots:**
```
[22:43:33] [Server thread/INFO]: There are 2 of a max 100 players online: probes13, jewome62
[22:44:01] [Server thread/INFO]: jewome62 issued server command: /plot info
[22:44:06] [Server thread/INFO]: There are 2 of a max 100 players online: probes13, jewome62
[22:44:12] [Server thread/INFO]: jewome62 issued server command: /plot delete
[22:44:12] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[22:44:12] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:44:12] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[22:44:12] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:44:12] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.util.block.QueueProvider$1.getNewQueue(QueueProvider.java:13)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.util.block.GlobalBlockQueue.getNewQueue(GlobalBlockQueue.java:64)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.PlotArea.getQueue(PlotArea.java:108)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager.clearPlot(HybridPlotManager.java:180)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.Plot$1.run(Plot.java:882)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.Plot.clear(Plot.java:885)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.Plot.deletePlot(Plot.java:1097)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.Delete$1.run(Delete.java:51)
[22:44:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[22:44:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[22:44:12] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010)
[22:44:12] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[22:44:12] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[22:44:12] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[22:44:12] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:44:12] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: com.github.intellectualsites.plotsquared.plot.util.block.LocalBlockQueue.<init>(Ljava/lang/String;)V
[22:44:12] [Server thread/WARN]: 	at com.boydti.fawe.regions.general.plot.FaweLocalBlockQueue.<init>(FaweLocalBlockQueue.java:32)
[22:44:12] [Server thread/WARN]: 	... 19 more
[22:44:12] [Server thread/WARN]: java.lang.NullPointerException
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.util.block.QueueProvider$1.getNewQueue(QueueProvider.java:20)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.util.block.GlobalBlockQueue.getNewQueue(GlobalBlockQueue.java:64)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.PlotArea.getQueue(PlotArea.java:108)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager.clearPlot(HybridPlotManager.java:180)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.Plot$1.run(Plot.java:882)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.Plot.clear(Plot.java:885)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.Plot.deletePlot(Plot.java:1097)
[22:44:12] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.Delete$1.run(Delete.java:51)
[22:44:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[22:44:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[22:44:12] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010)
[22:44:12] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[22:44:12] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServœer.a(MinecraftServer.java:940)
[22:44:12] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[22:44:12] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:44:12] [Server thread/WARN]: [PlotSquared] Task #8103 for PlotSquared v4.326 generated an exception
java.lang.NullPointerException: null
	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:194) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:181) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.ChunkManager$3.run(ChunkManager.java:191) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-641]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-641]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-641]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-641]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-641]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-641]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Plugins being used on the server:**

**How to replicate:** 
make plot delete command
**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Just confirmed like I already assumed, it's an issue with Fawe, Matt will push some changes later

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/3473f5dc851a06baab01049e832a7f6312ba20eb, update PlotSquared
