### ISSUE TITLE
Lot of error im my console..

### ISSUE THREAD

**Issue by Goodfun-Fr** [IntellectualSites/PlotSquared#2489]
Hello, can u help me plz ? :/

[K[31;1m[09:10:01 ERROR]: Could not pass event WorldInitEvent to PlotSquared v4.298
java.lang.NumberFormatException: For input string: "0]"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.config.Configuration$4.parseString(Configuration.java:73) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.config.Configuration$4.parseString(Configuration.java:59) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.ClassicPlotWorld.loadConfiguration(ClassicPlotWorld.java:85) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotWorld.loadConfiguration(HybridPlotWorld.java:116) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.PlotArea.loadDefaultConfiguration(PlotArea.java:332) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.PlotSquared.loadWorld(PlotSquared.java:1101) ~[?:?]
	at com.github.intellectualsites.plotsquared.bukkit.listeners.WorldEvents.onWorldInit(WorldEvents.java:32) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor79.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-175]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.createWorld(CraftServer.java:1018) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:492) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:284) ~[patched_1.14.4.jar:git-Paper-175]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:315) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-175]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[patched_1.14.4.jar:git-Paper-175]
	at java.lang.Thread.run(Thread.java:834) [?:?]

THX

**Comment by SirYwell** [comment]
You misconfigured something. Check your `worlds.yml`, there must be a value containing a `]`. Try to remove it, save the file and reload PlotSquared with `/plot reload`.

**Comment by MattBDev** [comment]
Don't delete the template.
