### ISSUE TITLE
Teleport Lag

### ISSUE THREAD

**Issue by RealH0peLess** [IntellectualSites/PlotSquared#2540]
https://athion.net/ISPaster/paste/view/dc0d74f440d449e9ba262e97a9cf4721
https://i.imgur.com/gtdZD9h.png

Minecraft Version Number: 1.13.2

I updated from 1.8 to 1.13.2 and now i have huge teleportation lags. for example by typing /plot home <offline player>, the server is lagging.
i unloaded every plugin and the lag is still happening. im using the newest build of PlotSquared (369)

Timings: https://timings.aikar.co/?id=7cf287f6d7b44ccf83610c59dab5acd4

**Comment by AeSix** [comment]
Yes, it appears as though PlotSquared is causing issues.  This may be due to FAWE or WorldGuard, however. 

Please ensure you are using WorldGuard 7.0.0 from https://dev.bukkit.org/projects/worldguard/files

If you're using Redis, you probably know what you're doing.  As such, you should fix your server instead of using clearlag.  It causes other issues, and may be interfering with PS.

**Comment by MattBDev** [comment]
2,000% of the tick seems highly unlikely. It looks like you have some UUID issues going on in your console.

**Comment by RealH0peLess** [comment]
Hello, thanks for the quick answers. 
I got this error in my console on every startup:

`[03:45:37] [Craft Scheduler Thread - 21/WARN]: java.io.EOFException
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.fromStream(NbtFactory.java:165)
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.uuid.FileUUIDHandler.lambda$cache$0(FileUUIDHandler.java:98)
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[03:45:37] [Craft Scheduler Thread - 21/WARN]: 	at java.lang.Thread.run(Thread.java:748)
`

**Comment by MattBDev** [comment]
We've determined there is nothing we can do on our end to fix this. It's not a PlotSquared issue
