### ISSUE TITLE
P list top don't work

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#2552]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**Debug paste link:** 

**[REQUIRED] Spigot/Paper Version Number:** 

https://athion.net/ISPaster/paste/view/fc288fd7e48c40bbbd3ca59d46a5e662

**[REQUIRED] Minecraft Version Number:** 
1.13.2  Paper
**[REQUIRED] Description of the problem:** 
When doing p list top don't work

**Any relevant console output or screenshots:**
ttps://athion.net/ISPaster/paste/view/fc288fd7e48c40bbbd3ca59d46a5e662

**Plugins being used on the server:**
nah

**[REQUIRED] How to replicate:** 
do /p list top

**[REQUIRED] Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
This is working in PlotSquared 4.340.  I know this is old, but at least it's a place to start looking for where this broke.  This works both in-game and in console. 

@xion87 is it broken in console as well as in-game, and does using ```/plot list top``` work?  I'm currently not ready to update P2, so cannot test it myself.

**Comment by xion87** [comment]
Yep same message when executed from console

**Comment by AeSix** [comment]
This may have something to do with the issue, or may be a separate issue:
```
[05:01:32] [Server thread/INFO]: [PlotSquared] Enabling PlotSquared v4.363
[05:01:33] [Server thread/INFO]: Version is PlotSquared-4.363
[05:01:38] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[05:01:38] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.database.SQLManager.getPlots(SQLManager.java:1843)
[05:01:38] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.database.DBFunc.getPlots(DBFunc.java:295)
[05:01:38] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.PlotSquared.setupDatabase(PlotSquared.java:1536)
[05:01:38] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.PlotSquared.<init>(PlotSquared.java:148)
[05:01:38] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:120)
[05:01:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[05:01:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
[05:01:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[05:01:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[05:01:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[05:01:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236)
[05:01:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[05:01:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[05:01:38] [Server thread/INFO]: Plot #240530(null;168;14) | null;168;14 had an invalid flag. A fix has been attempted.
[05:01:38] [Server thread/INFO]: use:,time:10000
```

**Comment by xion87** [comment]
I noticed another thing, i see two tables "ratings" and "rating", the rating one contain few values and the other one a lot of values, maybe p list top is looking the wrong table?

**Comment by xion87** [comment]
> This may have something to do with the issue, or may be a separate issue:
> 
> ```
> [05:01:32] [Server thread/INFO]: [PlotSquared] Enabling PlotSquared v4.363
> [05:01:33] [Server thread/INFO]: Version is PlotSquared-4.363
> [05:01:38] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
> [05:01:38] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.database.SQLManager.getPlots(SQLManager.java:1843)
> [05:01:38] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.database.DBFunc.getPlots(DBFunc.java:295)
> [05:01:38] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.PlotSquared.setupDatabase(PlotSquared.java:1536)
> [05:01:38] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.PlotSquared.<init>(PlotSquared.java:148)
> [05:01:38] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:120)
> [05:01:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
> [05:01:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
> [05:01:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
> [05:01:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
> [05:01:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
> [05:01:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236)
> [05:01:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
> [05:01:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
> [05:01:38] [Server thread/INFO]: Plot #240530(null;168;14) | null;168;14 had an invalid flag. A fix has been attempted.
> [05:01:38] [Server thread/INFO]: use:,time:10000
> ```

Yeah that is the flag fixer, i see that evertime there are some plots with wrong flags at startup

**Comment by xion87** [comment]
The same thing happen with 378

**Comment by AeSix** [comment]
I pulled that error blob from the log file you posted... 
I suggest building a fresh server for testing, because it sounds like either your sql server, the connection to your sql server, or your minecraft server / plugin configs are faulty.
