### ISSUE TITLE
/plot music throwing NPE

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquared#2571]
# NOTICE: 
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```

**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!

# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

PlotSquared version v4.391

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [ ] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [ ] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [ ] Minecraft 1.13.2
- [ ] Minecraft Java Edition *other versions, please specify*:
- [ ] Minecraft Bedrock Edition *speicify version*:

### Server build info: 

Previous version: git-Paper-213 (MC: 1.14.4)
You are 3 version(s) behind

### WorldEdit/FAWE versions:

- [ ] FAWE *version*:
- [X] WorldEdit *version*: 7.1.0

### How to replicate:

/plot music

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

```
[21:30:54] [Server thread/INFO]: NotMyFault issued server command: /p music
[21:30:54] [Server thread/WARN]: java.lang.NullPointerException
[21:30:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.PlotItemStack.getBlockState(PlotItemStack.java:48)
[21:30:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.BukkitInventoryUtil.getItem(BukkitInventoryUtil.java:59)
[21:30:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.BukkitInventoryUtil.open(BukkitInventoryUtil.java:31)
[21:30:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.object.PlotInventory.openInventory(PlotInventory.java:61)
[21:30:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.Music.onCommand(Music.java:71)
[21:30:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.execute(SubCommand.java:36)
[21:30:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.commands.Command.execute(Command.java:343)
[21:30:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.execute(MainCommand.java:258)
[21:30:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.onCommand(MainCommand.java:141)
[21:30:54] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:31)
[21:30:54] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:30:54] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[21:30:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006)
[21:30:54] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929)
[21:30:54] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

### Other plugins being used on the server:

/
### Relevant console output, log lines, and/or screenshots:

/
### Additional relevant comments/remarks:

/
# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
If you attempt to select a music disc on the music gui, you run into that issue: http://haste.athion.net/ejocosodor.bash
The flag is set like that rather than the name, like it was in the past
![](https://i.imgur.com/cwu5gpB.png)
It also does not work and throws this issue if a player enters the plot: http://haste.athion.net/omuferabax.sql
