### ISSUE TITLE
Plot2Dynmap - NoSuchMethodError: com.github.intellectualsites.plotsquared.plot.object.Plot.getRegions

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#2572]
Purpur dev 319 (Paper dev 225 / Spigot 1.14.4)
PlotSquared-Breaking dev 395
Plot2Dynmap v3.2.0
Dynmap v3.0-beta-6-220

```
[02:11:07] [Server thread/WARN]: [Plot2Dynmap] Task #103 for Plot2Dynmap v3.2.0 generated an exception
java.lang.NoSuchMethodError: com.github.intellectualsites.plotsquared.plot.object.Plot.getRegions()Ljava/util/HashSet;
	at com.empcraft.plot2dynmap.Main.handlePlot(Main.java:143) ~[?:?]
	at com.empcraft.plot2dynmap.Main.updatePlots(Main.java:263) ~[?:?]
	at com.empcraft.plot2dynmap.Main.access$200(Main.java:38) ~[?:?]
	at com.empcraft.plot2dynmap.Main$Plot2Update.run(Main.java:413) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[paperclip.jar:git-Purpur-319]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[paperclip.jar:git-Purpur-319]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1178) ~[paperclip.jar:git-Purpur-319]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:426) ~[paperclip.jar:git-Purpur-319]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1105) ~[paperclip.jar:git-Purpur-319]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:932) ~[paperclip.jar:git-Purpur-319]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

Edit: It's actually Plot2Dynmap v2.1 found here https://github.com/IntellectualSites/plot2dynmap/releases but the plugin.yml specifies the version as  v3.2.0.

**Comment by mibby** [comment]
Breaking change here.
https://github.com/IntellectualSites/PlotSquared/commit/88732bb88cd2f066654fdc17786cf9e9fe4f0c4a#diff-fda8e3c0aa4ed5b1695cefbe278b9022
