### ISSUE TITLE
plot auto <size> not working

### ISSUE THREAD

**Issue by Resi23** [IntellectualSites/PlotSquared#2609]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):
Debugpaste: https://athion.net/ISPaster/paste/view/9228504d562c4a39bd529046c1c0ca4d

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
Paper-230 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*: Bukkit-Official (7.1.0-SNAPSHOT;4738-89bc664)

### Description of the problem:

```/plot auto <size> not working```

### How to replicate:

try /p auto 2 or bigger size /p auto 25

### Relevant console output, log lines, and/or screenshots:

```[13:17:27] [Server thread/INFO]: ResistantX issued server command: /p auto 25
[13:17:27] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[13:17:27] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.Auto.onCommand(Auto.java:180)
[13:17:27] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.execute(SubCommand.java:36)
[13:17:27] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.commands.Command.execute(Command.java:343)
[13:17:27] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.execute(MainCommand.java:258)
[13:17:27] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.onCommand(MainCommand.java:141)
[13:17:27] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:31)
[13:17:27] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[13:17:27] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[13:17:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1158)
[13:17:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[13:17:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)```

```[13:17:30] [Server thread/INFO]: ResistantX issued server command: /p auto 2
[13:17:30] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[13:17:30] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.Auto.onCommand(Auto.java:180)
[13:17:30] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.execute(SubCommand.java:36)
[13:17:30] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.commands.Command.execute(Command.java:343)
[13:17:30] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.execute(MainCommand.java:258)
[13:17:30] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.onCommand(MainCommand.java:141)
[13:17:30] [Server thread/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:31)
[13:17:30] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[13:17:30] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[13:17:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1158)
[13:17:30] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[13:17:30] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)```

### Additional relevant comments/remarks:
<!--- Use this space to give us any additional information which may be relevant to this issue, such as: if you are using a Minecraft hosting provider; unusual installation environment; etc -->

# AFFIRMATION OF COMPLETION:
<!-- Make sure you have completed the following steps (put an "X" between of brackets): -->
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by DevJoey** [comment]
Yea i have the same Problem.

**Comment by MattBDev** [comment]
@Resi23 @DevJoey Maybe it's because you are also using the command wrong. From the wiki: 
> /plot auto [length,width]
Anyways I'm dummy proofing the command by setting the length and width to 1.

**Comment by Resi23** [comment]
yes, of course, that's how it works. I've read it somewhere else. sry

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/7e58f4341eeb8e00cd36d8df3aa36d4853686418

**Comment by TheReverend403** [comment]
I'm having this problem on the 27-Jan-2020 dev build.

![img](https://dev.pste.pw/f/cTe.png)
