### ISSUE TITLE
player building denied / weird error in console

### ISSUE THREAD

**Issue by AeSix** [IntellectualSites/PlotSquared#2624]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [x] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
[23:18:19] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-56f8471-eafd742 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[23:18:19] [Server thread/INFO]: You are 5 version(s) behind
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*: 

### Description of the problem:

I'm having a player test for me, while testing, this error appeared in console twice.

### How to replicate:

Ain't got the foggiest!

## Additional Information:

I may be dealing with a permissions issue, but felt the need to report everything that is out of the ordinary.

### Relevant console output, log lines, and/or screenshots:

```
[23:14:27] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to PlotSquared v4.422
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-server.jar:git-Spigot-56f8471-eafd742]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-server.jar:git-Spigot-56f8471-eafd742]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-server.jar:git-Spigot-56f8471-eafd742]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2289) ~[spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) ~[spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) ~[spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-server.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-server.jar:git-Spigot-56f8471-eafd742]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NoSuchFieldError: Legacy field ordinal: LEGACY_BANNER
        at org.bukkit.craftbukkit.v1_14_R1.util.CraftLegacy.modern_ordinal(CraftLegacy.java:254) ~[spigot-server.jar:git-Spigot-56f8471-eafd742]
        at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onInventoryClick(PlayerEvents.java:1715) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor246.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-server.jar:git-Spigot-56f8471-eafd742]
        ... 17 more
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
> Caused by: java.lang.NoSuchFieldError: Legacy field ordinal: LEGACY_BANNER
🤔

**Comment by Resi23** [comment]
I have a similar problem with 4.422. After the error, the plot owners could no longer build on their plots.
`[12:54:03] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to PlotSquared v4.422
java.lang.NullPointerException: null
	at com.github.intellectualsites.plotsquared.plot.util.EventUtil.checkPlayerBlockEvent(EventUtil.java:113) ~[?:?]
	at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onInteract(PlayerEvents.java:2028) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor48.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-235]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-235]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-235]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-235]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:443) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1158) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-235]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[12:54:03] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to PlotSquared v4.422
java.lang.NullPointerException: null
	at com.github.intellectualsites.plotsquared.plot.util.EventUtil.checkPlayerBlockEvent(EventUtil.java:113) ~[?:?]
	at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onInteract(PlayerEvents.java:2028) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor48.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-235]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-235]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-235]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-235]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:443) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-235]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-235]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]`

**Comment by MattBDev** [comment]
@Resi23 The latest dev builds are meant to be very buggy. I'm already aware of your issue.

**Comment by AeSix** [comment]
I turned on pex debugging (havn't migrated to LP ont his server yet)
The output for someone placing one block on their own plot:  (name and uuid redacted)
```
[09:20:22] [Server thread/INFO]: [Global-CX] [Owner] AeSix: place one block and do nothing else please
[09:20:25] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:20:25] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:20:25] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:20:25] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:20:26] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:20:26] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:20:26] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'simpleapi.lightdetector.use', regex-matched a value of undefined from cache.
[09:20:26] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'simpleapi.texturefinder.use', regex-matched a value of undefined from cache.
[09:20:26] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "worldguard.override.infinite-stack", no permission found
[09:20:26] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'creativeminecats.allowed.newworld', regex-matched a value of true from cache.
[09:20:26] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "worldguard.region.bypass.newworld", no permission found
[09:20:26] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'lockettepro.admin.interfere', regex-matched a value of undefined from cache.
[09:20:27] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:20:27] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:20:27] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:20:27] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:20:29] [Async Chat Thread - #2/INFO]: [PermissionsEx] User username checked for permission 'catchat.channel.use.general', regex-matched a value of true from cache.
[09:20:29] [Async Chat Thread - #2/INFO]: [PermissionsEx] User username checked for permission 'catchat.color', regex-matched a value of undefined from cache.
[09:20:29] [Async Chat Thread - #2/INFO]: [PermissionsEx] User username checked for permission 'irc.message.gamechat', regex-matched a value of true from cache.
[09:20:29] [Server thread/INFO]: [Global-CX] [Cub] username (*) : done
```

The "creativeminecats.allowed.newworld" is a plugin to help control gamemode changes. 

What I'm /not/ seeing is any check against PlotSquared.

**Comment by AeSix** [comment]
I reverted back to PlotSquared 4.400 - for testing, and to allow players to actually use the server.
Here's the pex debug - also missing any PlotSquared checks, but players are able to build:
```
[09:38:11] [Server thread/INFO]: [Global-CX] [Owner] AeSix: ok now
[09:38:13] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:38:13] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:38:13] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'simpleapi.lightdetector.use', regex-matched a value of undefined from cache.
[09:38:13] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'simpleapi.texturefinder.use', regex-matched a value of undefined from cache.
[09:38:13] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "worldguard.override.infinite-stack", no permission found
[09:38:13] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'creativeminecats.allowed.newworld', regex-matched a value of true from cache.
[09:38:13] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "worldguard.region.bypass.newworld", no permission found
[09:38:13] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'lockettepro.admin.interfere', regex-matched a value of undefined from cache.
[09:38:13] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'lockettepro.lock', regex-matched a value of true from cache.
[09:38:14] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:38:14] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:38:14] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:38:14] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:38:14] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:38:14] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:38:14] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:38:14] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:38:15] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:38:15] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:38:15] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:38:15] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:38:16] [Server thread/INFO]: [PermissionsEx] User uuid-uuid-uuid checked for "ontime.track", no permission found
[09:38:16] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'ontime.track', regex-matched a value of true from cache.
[09:38:16] [Server thread/INFO]: [PermissionsEx] User username checked for permission 'announcer.receiver', regex-matched a value of true from announcer.receiver (CACHE MISS)
[09:38:16] [Server thread/INFO]: [PermissionsEx] User AeSix checked for permission 'announcer.receiver', regex-matched a value of true from * (CACHE MISS)
[09:38:16] [Craft Scheduler Thread - 8/INFO]: [PermissionsEx] User username checked for permission 'stoppushing.allow', regex-matched a value of undefined from cache.
[09:38:16] [Craft Scheduler Thread - 8/INFO]: [PermissionsEx] User AeSix checked for permission 'stoppushing.allow', regex-matched a value of true from cache.
[09:38:22] [Server thread/INFO]: AeSix issued server command: /pex toggle debug
```

**Comment by MattBDev** [comment]
I blame pex for this because I tested the code without any permission manager and all plotsquared permissions were being checked.

**Comment by dordsor21** [comment]
Is this still an issue on v5?

**Comment by RedstoneFuture** [comment]
If you have still this problem, reopen it on https://issues.intellectualsites.com/issues?q=project:%20PlotSquared ,please.
