### ISSUE TITLE
Unable to find method createTag ([byte]) | Removed in 1.15

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquared#2629]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

https://athion.net/ISPaster/paste/view/2972d7a84ac24a61a1a74e9ac8f18635

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [x] Minecraft 1.15
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-8 (MC: 1.15) (Implementing API version 1.15-R0.1-SNAPSHOT)
[17:37:43 INFO]: Checking version, please wait...
[17:37:44 INFO]: You are running the latest version
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*: 7.1.0-SNAPSHOT;4787-aeb8935

### Description of the problem:

Answered below.

### How to replicate:

Setup a paper 1.15 server and use the latest p2 builds.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

The method named in the stacktrace below has been removed on 1.15. therefore it will error on startup. 

### Other plugins being used on the server:

PlotSquared, WorldEdit

### Relevant console output, log lines, and/or screenshots:

```
[17:36:52] [Craft Scheduler Thread - 0/WARN]: java.lang.IllegalStateException: Unable to find method createTag ([byte]).
[17:36:52] [Craft Scheduler Thread - 0/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.getMethod(NbtFactory.java:371)
[17:36:52] [Craft Scheduler Thread - 0/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.<init>(NbtFactory.java:86)
[17:36:52] [Craft Scheduler Thread - 0/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.get(NbtFactory.java:120)
[17:36:52] [Craft Scheduler Thread - 0/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.fromStream(NbtFactory.java:189)
[17:36:52] [Craft Scheduler Thread - 0/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.uuid.FileUUIDHandler.lambda$cache$0(FileUUIDHandler.java:98)
[17:36:52] [Craft Scheduler Thread - 0/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[17:36:52] [Craft Scheduler Thread - 0/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:36:52] [Craft Scheduler Thread - 0/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:36:52] [Craft Scheduler Thread - 0/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:36:52] [Craft Scheduler Thread - 0/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:36:52] [Craft Scheduler Thread - 0/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by Resi23** [comment]
I can confirm
PS 4.424
WorldEdit 7.1.0-SNAPSHOT;4787-aeb8935
Paper version git-Paper-8 (MC: 1.15)

**Comment by mibby** [comment]
Also able to confirm on 1.15.1 with PlotSquared-Breaking dev 427. Error seems to spam endlessly at start-up (600+ hits), or at least for every plot in existence.

```
[03:50:54] [Craft Scheduler Thread - 161/WARN]: java.lang.IllegalStateException: Unable to find method createTag ([byte]).
[03:50:54] [Craft Scheduler Thread - 161/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.getMethod(NbtFactory.java:371)
[03:50:54] [Craft Scheduler Thread - 161/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.<init>(NbtFactory.java:86)
[03:50:54] [Craft Scheduler Thread - 161/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.get(NbtFactory.java:120)
[03:50:54] [Craft Scheduler Thread - 161/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.fromStream(NbtFactory.java:189)
[03:50:54] [Craft Scheduler Thread - 161/WARN]: 	at com.github.intellectualsites.plotsquared.bukkit.uuid.FileUUIDHandler.lambda$cache$0(FileUUIDHandler.java:98)
[03:50:54] [Craft Scheduler Thread - 161/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[03:50:54] [Craft Scheduler Thread - 161/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[03:50:54] [Craft Scheduler Thread - 161/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[03:50:54] [Craft Scheduler Thread - 161/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[03:50:54] [Craft Scheduler Thread - 161/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[03:50:54] [Craft Scheduler Thread - 161/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by AeSix** [comment]
This is a paper issue.  This issue does not occur in spigot.

**Comment by electronicboy** [comment]
Before somebody else sees this and hops in our discord, not a paper issue; Even replicated proof coz I totally value my time; #BlameMojang

![image](https://user-images.githubusercontent.com/1228900/71304228-ba51c900-23bb-11ea-93be-509ba7e3d296.png)

**Comment by AeSix** [comment]
I may had spoke out of turn.  I don't see the issue on my server.  However, as this may be a situational issue, my server may not be in that situation.   I apologize I got so many people in an uproar, and for spreading wrong information.

**Comment by psrcek** [comment]
I have a server with this situation too, I'm a developer & stuff and if anyone wants me to do some testing, I'd like to help.  I'm running PlotSquared-4.432, Paper-26 (1.15.1-R0.1-SNAPSHOT), WorldEdit 7.1.0-SNAPSHOT;4799-79c11c5, java build 1.8.0_232-b09 I also got [this](https://hastebin.com/ukixapexip.md) next to the error in this thread.

**Comment by traksag** [comment]
The only actual use of NbtFactory I could find is in FileUUIDHandler to read information from player data files. Is there any reason this cannot be swapped out by, say, com.sk89q.jnbt, which is already used elsewhere? If so, this should be quite easy to fix and wouldn't require digging through Mojang's refactored NBT code.

**Comment by Sauilitired** [comment]
It has probably been left behind from earlier versions. WorldEdit wasn't a hard dependency until last year. If someone wants to swap out the implementation for a WorldEdit equivalent, then I'd happily merge the PR.
