### ISSUE TITLE
World is not correctly generated with custom roads in Paper 26

### ISSUE THREAD

**Issue by psrcek** [IntellectualSites/PlotSquared#2643]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

worlds.yml: https://hastebin.com/xezuhezoru.cs

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [ ] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [ ] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15
- [ ] Minecraft 1.14.4
- [ ] Minecraft 1.13.2
- [ ] Minecraft Java Edition *other versions, please specify*:
- [ ] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-26 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [ ] FAWE *version*:
- [X] WorldEdit *version*: WorldEdit 7.1.0-SNAPSHOT;4799-79c11c5

### Description of the problem:

Worlds don't generate correctly.

### How to replicate:

1. Create road templates.
2. Generate world with them

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

- PlotSquared-4.432
- java build 1.8.0_232-b09
- WorldGuard 7.0.1;f2118aa

### Other plugins being used on the server:

```
dynmap, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, HolographicDisplays, HoloPlots, LogBlock, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, OpenInv, Plot2Dynmap, PlotSquared, PlugMan, ProtocolLib, Vault, WorldEdit, WorldGuard
```

### Relevant console output, log lines, and/or screenshots:
![2019-12-23_01 28 32](https://user-images.githubusercontent.com/13370323/71375119-6f9f9f00-25bd-11ea-9d7c-2655c3318bb8.png)
```
[01:28:26 WARN]: java.lang.NullPointerException                                                                                                                                                                    
[01:28:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.util.world.PatternUtil.apply(PatternUtil.java:28)                                                                                         
[01:28:26 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.util.block.GenChunk.setBlock(GenChunk.java:111)                                                                                         
[01:28:26 WARN]:        at com.github.intellectualsites.plotsquared.plot.generator.HybridGen.generateChunk(HybridGen.java:150)                                                                                     
[01:28:26 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.generator.BukkitPlotGenerator.generate(BukkitPlotGenerator.java:173)                                                                    
[01:28:26 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.generator.BukkitPlotGenerator.generateChunkData(BukkitPlotGenerator.java:151)                                                           
[01:28:26 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:102)                                                                                 
[01:28:26 WARN]:        at net.minecraft.server.v1_15_R1.ChunkStatus.lambda$static$6(ChunkStatus.java:51)                                                                                                          
[01:28:26 WARN]:        at net.minecraft.server.v1_15_R1.ChunkStatus$d.doWork(ChunkStatus.java:240)                                                                                                                
[01:28:26 WARN]:        at net.minecraft.server.v1_15_R1.ChunkStatus.a(ChunkStatus.java:186)                                                                                                                       
[01:28:26 WARN]:        at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$null$20(PlayerChunkMap.java:672)                                                                                                    
[01:28:26 WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)                                                                                                                              
[01:28:26 WARN]:        at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$b$22(PlayerChunkMap.java:670)                                                                                                       
[01:28:26 WARN]:        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)                                                                                                           
[01:28:26 WARN]:        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)                                                                                                   
[01:28:26 WARN]:        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)                                                                                                       
[01:28:26 WARN]:        at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58)                                                                                                                     
[01:28:26 WARN]:        at net.minecraft.server.v1_15_R1.ThreadedMailbox.e(SourceFile:83)                                                                                                                          
[01:28:26 WARN]:        at net.minecraft.server.v1_15_R1.ThreadedMailbox.a(SourceFile:123)                                                                                                                         
[01:28:26 WARN]:        at net.minecraft.server.v1_15_R1.ThreadedMailbox.run(SourceFile:91)                                                                                                                        
[01:28:26 WARN]:        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)                                                                                                    
[01:28:26 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)                                                                                                                         
[01:28:26 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)                                                                                                             
[01:28:26 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)                                                                                                                     
[01:28:26 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [ ] I didn't read but checked everything above.

**Comment by AeSix** [comment]
Does this happen with earlier builds of PS?

**Comment by psrcek** [comment]
It happens with 4.400 aswell.

**Comment by traksag** [comment]
What happens if you replace
```yaml
floor:
- quartz_block
filling:
- quartz_block
```
with
```yaml
floor: quartz_block
filling: quartz_block
```

**Comment by psrcek** [comment]
That looks like it worked. Thanks! You must have changed the config format at some point because the config was directly copied from a 1.13 server. Welp I guess all that panic was for nothing.

**Comment by MattBDev** [comment]
@psrcek I'm reopening this issue because either a documentation change needs to be made or the code needs to be fixed to support the old format.

**Comment by Sauilitired** [comment]
The configuration has been updated: https://github.com/IntellectualSites/PlotSquared/wiki/worlds.yml
Going from v3 to v4 will attempt to correct the configuration. It worked with the old BlockBucket code, but I'm not sure if it works anymore after Jesse's changes (to add patterns).

**Comment by psrcek** [comment]
Well that's where the error is, in the pattern code: [link](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/util/world/PatternUtil.java#L28)

**Comment by BeerMC** [comment]
I met the same issue in Paper-93  with PlotSquared-455 when using old template.

**Comment by Sauilitired** [comment]
This was caused due to the legacy converter being broken. It has been fixed.
