### ISSUE TITLE
Interacting with Block having no Item representative throws IllegalArgumentException

### ISSUE THREAD

**Issue by yannicklamprecht** [IntellectualSites/PlotSquared#2644]
https://github.com/IntellectualSites/PlotSquared/blob/breaking/Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/object/BukkitBlockUtil.java#L15

Passing Material.REDSTONE_WALL_TORCH throws an IllegalArgumentException cause the Item representive ist REDSTONE_TORCH.

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [ ] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [ ] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [ ] Minecraft 1.15
- [x] Minecraft 1.14.4
- [ ] Minecraft 1.13.2
- [ ] Minecraft Java Edition *other versions, please specify*:
- [ ] Minecraft Bedrock Edition *specify version*:

### WorldEdit/FAWE versions:

- [ ] FAWE *version*:
- [x] WorldEdit *version*: WorldEdit version 7.0.1-rc1;edb2e91

### How to replicate:

Interacting with redstone_torches (REDSTONE_WALL_TORCH) on a Plot.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Relevant console output, log lines, and/or screenshots:

```

[14:06:51 ERROR]: Could not pass event PlayerInteractEvent to PlotSquared v4.400 java.lang.IllegalArgumentException: minecraft:redstone_wall_torch is not an item! at com.sk89q.worldedit.bukkit.BukkitAdapter.asItemType(BukkitAdapter.java:375) ~[?:?] at com.github.intellectualsites.plotsquared.bukkit.object.BukkitBlockUtil.lambda$supplyItem$0(BukkitBlockUtil.java:13) ~[?:?] at com.github.intellectualsites.plotsquared.plot.util.EventUtil.checkPlayerBlockEvent(EventUtil.java:231) ~[?:?] at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onInteract(PlayerEvents.java:2229) ~[?:?] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor50.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-237] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-237] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-237] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-237] at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:443) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-237] at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-237] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared (4.400) latest stable
- [x] I made sure the bug/error is not caused by any other plugin
- [ ] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
We already know this. Were you trying to use the API or did you just encounter it when running the plugin. We need to know these things.

**Comment by yannicklamprecht** [comment]
@MattBDev edit the post. It is just interacting with a REDSTONE_WALL_TORCH.

**Comment by MattBDev** [comment]
This should be fixed in the latest dev build where I modified a big chunk of the player interaction code.
