### ISSUE TITLE
Broken Partial augmented world 

### ISSUE THREAD

**Issue by jordi2010** [IntellectualSites/PlotSquared#2650]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-31 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*:  7.1.0

### Description of the problem:

I want a partial plot area like in the documentation.(https://github.com/IntellectualSites/PlotSquared/wiki/Augmented-Plot-Worlds).

/plot area world:area type=2 size=25 creates the area and remove all blocks inside this area. I'm not able to reproduce in an appropriate way. 
/plot area regen doesn't do anything.

### How to replicate:

/plot area world:area type=2 size=25
/plot area create pos1
/plot area create pos2

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

I tested on several versions in Spigot & Paper.

### Other plugins being used on the server:

Multiverse core
Worldedit

### Relevant console output, log lines, and/or screenshots:

https://athion.net/ISPaster/paste/view/a5afedfdbb0d4501a1c6fb602999042b

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
Augmented world's need to be retested. It seems the migration to worldedit api broke a lot of it unintentionally.

**Comment by gjerm** [comment]
Also seeing issues with this, on newest PaperMC/PlotSquared/WorldEdit. Getting these errors in the console, and the world is never changed (although the plot area is created):

```
[20:38:56] [Craft Scheduler Thread - 17/WARN]: [PlotSquared] Plugin PlotSquared v4.453 generated an exception while executing task 257
java.lang.IllegalStateException: Asynchronous getLoadedChunks!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.15.2.jar:git-Paper-164]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getLoadedChunks(CraftWorld.java:437) ~[patched_1.15.2.jar:git-Paper-164]
	at com.github.intellectualsites.plotsquared.bukkit.util.BukkitChunkManager.getChunkChunks(BukkitChunkManager.java:117) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.ChunkManager.lambda$largeRegionTask$0(ChunkManager.java:87) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-164]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-164]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-164]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_171]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

**Comment by Sauilitired** [comment]
@gjerm Revert to an older paper build until PlotSquared v5 is released.

**Comment by Sauilitired** [comment]
@gjerm Nevermind, I decided to actually fix it on our side in v4. The latest development builds will contain a fix.
