### ISSUE TITLE
Console Error [1.15.1]

### ISSUE THREAD

**Issue by JamesBach93** [IntellectualSites/PlotSquared#2655]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-33 (MC:1.15.1)
(Implementing API version 1.15.1-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-23 (MC: 1.15.1)
You are running the latest version
```

### WorldEdit/FAWE versions:

- [x] FAWE *version*:
- [] WorldEdit *version*: 

### Description of the problem:

After an Start i get some Errors in my Console.
[14:50:21 WARN]: java.lang.IllegalStateException: Unable to find method createTag ([byte]).
[14:50:21 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.getMethod(NbtFactory.java:371)
[14:50:21 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.<init>(NbtFactory.java:86)
[14:50:21 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.get(NbtFactory.java:120)
[14:50:21 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.util.NbtFactory.fromStream(NbtFactory.java:189)
[14:50:21 WARN]:        at com.github.intellectualsites.plotsquared.bukkit.uuid.FileUUIDHandler.lambda$cache$0(FileUUIDHandler.java:98)
[14:50:21 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[14:50:21 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[14:50:21 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:50:21 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:50:21 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:50:21 WARN]:        at java.lang.Thread.run(Unknown Source)

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

AdvancedHelp, AdvancedRegionMarket, BackToBlock, BeeHivesTrees, BKCommonLib, BottledExp, BukkitCompat*, Citizens, ColoredAnvils*, Confiscate, CoreProtect, CrateReloaded, CropChecker, dynmap*, Elevator, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, FastLeafDecay, HeadDatabase*, Holograms*, InventorySaver, KixsAutoAnnouncerPremium, Lands, LangUtils, LimitPillagers, LWC, mcMMO, Minepacks, Multiverse-Core, NametagEdit*, PermissionsEx*, PerWorldInventory, PetMaster, PictureLogin*, PlaceholderAPI, Playtimes*, PlayerListPlus, Plot2Dynmap, PlotBorder, PlotSquared, PluginConstructorAPI, ProtocolLib, QuickShop, Referral, RFChairs, ServerListPlus*, Shopkeepers, SkQuery, Skript, skript-yaml, skUtilities*, TimeVote, TreeAssist, UberEnchant, Vault, Votifier, VotingPlugin, WarpSystem, WeatherVote, Wild, WorldEdit, WorldGuard, WorldResetPlus*, XCoupons*

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
Fixed in latest dev builds, to download them, click on "Experimental Builds".
https://intellectualsites.github.io/download/plots.html

**Comment by MattBDev** [comment]
No debug paste links were provided either. In the future please follow the template.
