### ISSUE TITLE
Error-Message birch_wall_sign

### ISSUE THREAD

**Issue by therealatsuga** [IntellectualSites/PlotSquared#2670]
Can someone help me getting away this error-message? 

[16:07:30 ERROR]: Could not pass event PlayerInteractEvent to PlotSquared v4.400
java.lang.IllegalArgumentException: minecraft:birch_wall_sign is not an item!
at com.sk89q.worldedit.bukkit.BukkitAdapter.asItemType(BukkitAdapter.java:375) ~[?:?]
at com.github.intellectualsites.plotsquared.bukkit.object.BukkitBlockUtil.lambda$supplyItem$0(BukkitBlockUtil.java:13) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.util.EventUtil.checkPlayerBlockEvent(EventUtil.java:231) ~[?:?]
at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onInteract(PlayerEvents.java:2229) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-238]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-238]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-238]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-238]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:443) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-238]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**[REQUIRED] Spigot/Paper Version Number:** 
Spigot 1.14.4 ver 238

**[REQUIRED] Description of the problem:** 
Console is getting spammed with the error message above

**Plugins being used on the server:**
WorldEdit and WorldGuard are installed. There is a bunch of other plugins too, but I don't think they're causing the error

**How to replicate:** 
The message ist often shown when a player is re-joining the server. I haven't figured out how to reproduce

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [not sure] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Do not delete the template.
