### ISSUE TITLE
Expiry task not working if use-sqluuidhandler is enabled

### ISSUE THREAD

**Issue by Myszku** [IntellectualSites/PlotSquared#2674]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):
on use-sqluuidhandler: false https://athion.net/ISPaster/paste/view/5ef9ec6cb6e046218eefdbc4eae02d2e
on use-sqluuidhandler: true https://athion.net/ISPaster/paste/view/5081d3f39b0642ccb36173358177ac07

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-800b93f-a81f6ed (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit 7.1.0 RC1: 

### Description of the problem:

Few days ago I configured PlotSquared 4.400 on spigot 1.15.2 and yesterday I saw that expiry task not working. I've updated PS to 4.453 and nothing has changed. After many tries I noticed that when I set use-sqluuidhandler to false expiry task is running, but I can't disable sqluuidhandler, because often players lose their plots (it's display unknown in owner). Also expiry task displays an error on server startup when I disable use-sqluuidhandler.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Relevant console output, log lines, and/or screenshots:

```
[13:08:46] [Craft Scheduler Thread - 2/INFO]: Adding new expiry task!
[13:08:46] [Craft Scheduler Thread - 2/WARN]: [PlotSquared] Plugin PlotSquared v4.453 generated an exception while executing task 55
java.lang.IllegalStateException: PlotDeleteEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511) ~[spigot.jar:git-Spigot-800b93f-a81f6ed]
        at com.github.intellectualsites.plotsquared.bukkit.util.BukkitEventUtil.callEvent(BukkitEventUtil.java:54) ~[?:?]
        at com.github.intellectualsites.plotsquared.bukkit.util.BukkitEventUtil.callDelete(BukkitEventUtil.java:75) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.object.Plot.clear(Plot.java:868) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.object.Plot.deletePlot(Plot.java:1139) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.util.expiry.ExpireManager.deleteWithMessage(ExpireManager.java:384) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.util.expiry.ExpireManager$1.run(ExpireManager.java:164) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.util.expiry.ExpireManager$1.run(ExpireManager.java:155) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.util.expiry.ExpireManager$2.run(ExpireManager.java:294) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-800b93f-a81f6ed]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-800b93f-a81f6ed]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by AeSix** [comment]
Closing until debugpaste or prescribed files are added.

**Comment by Myszku** [comment]
I've added two debugpaste to main post.

**Comment by AeSix** [comment]
You're allowing cracked clients to connect?  Offline UUIDs?

**Comment by Myszku** [comment]
Yes, server is running in offline mode.

**Comment by AeSix** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/UUID-conversion

If this don't work, I don't know what to say.  I *personally* will help no further as allowing cracked clients on is a violation of the EULA and ToS. 

I will leave this open, and the developers can choose what to do.

**Comment by Myszku** [comment]
I don't know what converting "uuid" and not removing expired plots have in common. I didn't switch settings to online mode. Also the command you provided doesn't work. I've been using latest PlotSquared and I choose this plugin, because on spigot site you support offline mode servers. Plugin has the option which when enabled doesn't activate the removal of player plots. In addition, even if it's turned off, delete expired plots still doesn't work. You sent me yesterday to read the wiki again, but in PS-wiki there are two pages about delete expired plots and they both say something completely different.

It's a bug not only on offline mode servers.
```PlotDeleteEvent cannot be triggered asynchronously from another thread.```

**Comment by MattBDev** [comment]
This is a valid bug.

**Comment by N0tMyFaultOG** [comment]
Please retest the issue on v5.

**Comment by RedstoneFuture** [comment]
If you have still this problem, reopen it on https://issues.intellectualsites.com/issues?q=project:%20PlotSquared ,please.
