### ISSUE TITLE
auto-clear

### ISSUE THREAD

**Issue by zz2423257** [IntellectualSites/PlotSquared#2763]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

git-Paper-163 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHO

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: 

### Description of the problem:

The expired territory will not be automatically cleared when the server is opened
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Relevant console output, log lines, and/or screenshots:

 [PlotSquared] Plugin PlotSquared v4.493 generated an exception while executing task 1623
java.lang.IllegalStateException: PlotDeleteEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.15.2.jar:git-Paper-163]
        at com.github.intellectualsites.plotsquared.bukkit.util.BukkitEventUtil.callEvent(BukkitEventUtil.java:54) ~[?:?]
        at com.github.intellectualsites.plotsquared.bukkit.util.BukkitEventUtil.callDelete(BukkitEventUtil.java:75) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.object.Plot.clear(Plot.java:868) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.object.Plot.deletePlot(Plot.java:1139) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.util.expiry.ExpireManager.deleteWithMessage(ExpireManager.java:384) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.util.expiry.ExpireManager$1.run(ExpireManager.java:164) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.util.expiry.ExpireManager$1.run(ExpireManager.java:155) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.util.expiry.ExpireManager$2.run(ExpireManager.java:294) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-163]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-163]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-163]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
# AFFIRMATION OF COMPLETION:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by dordsor21** [comment]
This will be fixed in v5 from the new event system
