### ISSUE TITLE
Can't delete Plots on v5

### ISSUE THREAD

**Issue by 4Cris** [IntellectualSites/PlotSquared#2772]
[09:39:01 INFO]: 4Cris issued server command: /p del
[09:39:01 WARN]: [PlotSquared] Task #1783 for PlotSquared v5.1 generated an exception
java.lang.NullPointerException: Pattern may not be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.15.2.jar:git-Paper-193]
        at com.plotsquared.core.util.PatternUtil.apply(PatternUtil.java:49) ~[?:?]
        at com.plotsquared.core.queue.BasicLocalBlockQueue.setBlock(BasicLocalBlockQueue.java:118) ~[?:?]
        at com.plotsquared.core.queue.LocalBlockQueue.setCuboid(LocalBlockQueue.java:169) ~[?:?]
        at com.plotsquared.core.generator.HybridPlotManager$1.run(HybridPlotManager.java:239) ~[?:?]
        at com.plotsquared.core.generator.HybridPlotManager$1.run(HybridPlotManager.java:222) ~[?:?]
        at com.plotsquared.core.util.task.RunnableVal.run(RunnableVal.java:39) ~[?:?]
        at com.plotsquared.core.util.ChunkManager$3.run(ChunkManager.java:223) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-193]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-193]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1246) ~[patched_1.15.2.jar:git-Paper-193]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-193]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1164) ~[patched_1.15.2.jar:git-Paper-193]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-193]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by Sauilitired** [comment]
Your worlds.yml is broken. This would in most cases be caused by having updated to v4 while it was still broken.

If you've updated from v3, then you should have a worlds.yml backup (worlds.yml.old), try using that one. Note, however, that this will trigger the flag conversion again.

**Comment by 4Cris** [comment]
Thnks. The filling and floor blocks were somehow missing.
