### ISSUE TITLE
Web interface not working.

### ISSUE THREAD

**Issue by Connorcivi** [IntellectualSites/PlotSquared#2805]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
[16:28:19 INFO]: [P2] >> PlotSquared (Version: PlotSquared-4.453)
[16:28:19 INFO]: [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21
[16:28:19 INFO]: [P2] >> Wiki: https://github.com/IntellectualSites/PlotSquared/wiki

I couldn't get the latest version due to some plugins only allowing 1.12.2
```

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [X] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
[16:19:38 INFO]: This server is running Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[16:19:38 INFO]: Checking version, please wait...
[16:19:38 INFO]: Previous version: git-Paper-1616 (MC: 1
```

### WorldEdit/FAWE versions:

- [X] FAWE version:
- [] WorldEdit version: 

### Description of the problem:
So the problem is that when I have the web interface installed on a webserver and when I went to do /p download, also yes I did change the URL in config. So I've wait for 5 seconds and it returns an error saying that it failed to make a url. But I looked in console and it said 403 but I could connect to it fine. So I've been confused on why it won't work for anyone but all of my players said they can connect to the website without issues.

### Relevant console output, log lines, and/or screenshots:

```

[16:16:50 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://plotupload.xxxxxxxx.com/upload.php?20654e8a-971c-4fcf-ae63-d23f0d18c84c
[16:16:50 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[16:16:50 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[16:16:50 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[16:16:50 WARN]:        at com.github.intellectualsites.plotsquared.plot.util.MainUtil.lambda$upload$0(MainUtil.java:184)
[16:16:50 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[16:16:50 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[16:16:50 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:16:50 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:16:50 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:16:50 WARN]:        at java.lang.Thread.run(Unknown Source)

```

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by dordsor21** [comment]
well if you don't put a website that exists then it won't work.

**Comment by Connorcivi** [comment]
Here's the website that works. Also I blurred it out to not show it but here. https://plotupload.colizzycraft.com

**Comment by dordsor21** [comment]
check your webserver configuration. This isn't an issue with P2

**Comment by Connorcivi** [comment]
Could it be the permissions for the server?

**Comment by Connorcivi** [comment]
Because this is all on cpanel the interface is.

**Comment by dordsor21** [comment]
yep

**Comment by Connorcivi** [comment]
Permission is 755 so I don't see an issue on the webserver. I can post the Plotupload config?
