### ISSUE TITLE
Cannot use plot expiry feature

### ISSUE THREAD

**Issue by MegaNarwhal** [IntellectualSites/PlotSquared#2820]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/c886b4ed8b0e4e849a12f3630249580b

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
[13:08:37 INFO]: P2> >> PlotSquared (Version: PlotSquared-4.494)
[13:08:37 INFO]: P2> >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault
[13:08:37 INFO]: P2> >> Wiki: https://github.com/IntellectualSites/PlotSquared/wiki

```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-280 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: 7.1.0;8e55131

### Description of the problem:

Plot expiry task at server startup throws an exception. `/plot debugexec analyze` also fails with an exception. I have tested without AsyncWorldEdit installed and the error still occurs.

### How to replicate:

Start the server with plot expiry enabled or run `/plot debugexec analyze` and look in console.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Relevant console output, log lines, and/or screenshots:

```
[13:06:11 WARN]: [PlotSquared] Plugin PlotSquared v4.494 generated an exception while executing task 86
java.lang.NullPointerException: null
        at com.github.intellectualsites.plotsquared.plot.util.block.DelegateLocalBlockQueue.setBlock(DelegateLocalBlockQueue.java:64) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.generator.HybridGen.generateChunk(HybridGen.java:150) ~[?:?]
        at com.github.intellectualsites.plotsquared.plot.generator.HybridUtils.lambda$analyzeRegion$3(HybridUtils.java:93) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-280]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-280]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-280]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by dordsor21** [comment]
Not v5
