### ISSUE TITLE
"a timer is set to you or you plot"

### ISSUE THREAD

**Issue by LeWeeky** [IntellectualSites/PlotSquared#2829]
**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/KxkjDVg)**
-->

# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*

### PlotSquared version:

```
Paste the output here, between the tick marks, replacing this text
```

### Minecraft Version:
- [] Minecraft 1.14.4

- [] Minecraft Java Edition

### WorldEdit/FAWE versions:

- [] WorldEdit version: 7.1.0 (the latest)

### Description of the problem:
Bonjour ! J'ai un problème avec votre plugin ! Le /plot delete, /plot unclaim ne fonctionnent pas "Un minuteur est lié au plot ou à vous." 

## Additional Information:
J'ai personnalisé les plots, peut-être qie ça vient de là? 

### Other plugins being used on the server:
AntiFireworks*, BetterChairs*, ChestCommands, ClappyPlugin*, ClappyQuetes*, ClearLag, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, HeadDatabase*, HolographicDisplays, MinewebBridge*, Multiverse-Core, OnlyProxyJoin*, PermissionsEx*, PetBlocks*, PlotSquared, ProtocolLib*, SkinsRestorer, Vault, ViaVersion*, WorldEdit

### Relevant console output, log lines, and/or screenshots:

```
>.... [14:25:19 WARN]: [PlotSquared] Task #158 for PlotSquared v4.4.495 generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.setBiome(IIILorg/bukkit/block/Biome;)V
at com.github.intellectualsites.plotsquared.bukkit.util.BukkitUtil.setBiomes(BukkitUtil.java:441) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.util.MainUtil.setBiome(MainUtil.java:575) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:197) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:188) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
at com.github.intellectualsites.plotsquared.plot.util.ChunkManager$3.run(ChunkManager.java:192) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-237]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-237]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-237]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-237]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-237]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-237]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```
for short (20 lines or less) text blobs, or a paste service for large blobs -->

### Additional relevant comments/remarks:
J'ai pris le même plugin/le même paper que j'utilisais sur un autre serveur où cela marchait (mais les plots n'étaient pas personnalisé 

# PS : 
Je suis francophone, veuillez m'excuser pour ma maîtrise "douteuse" de l'anglais :p

**Comment by N0tMyFaultOG** [comment]
Fixed in v5. You can update here: https://www.spigotmc.org/resources/plotsquared-v5.77506/

**Comment by LeWeeky** [comment]
ah d'accord, je ne risque pas de corrompre la map ou autre ? j'y ai pensé mais j'avais peur de faire une bêtise :3
