### ISSUE TITLE
Many NullPointerExpections

### ISSUE THREAD

**Issue by DieProgrammIDE** [IntellectualSites/PlotSquared#2842]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/8496d7d880694b0dbea46a30da0e684d

**/plot debugpaste:** 

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
> p plugin
[20:13:32 INFO]: [P2] >> PlotSquared (Version: PlotSquared-5.11.2)
[20:13:32 INFO]: [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault & SirYwell
[20:13:32 INFO]: [P2] >> Wiki: https://wiki.intellectualsites.com/plotsquared/home
[20:13:32 INFO]: [P2] >> Premium: false
```
Built via ./gradlew build with Local Repo-Version of [this (latest) commit](https://github.com/IntellectualSites/PlotSquared/commit/c58309b3853359af9323bc4813b9c720a2e33cd8)
### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
> version
[20:16:09 INFO]: This server is running Paper version git-Paper-284 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[20:16:09 INFO]: Previous version: git-Paper-261 (MC: 1.15.2)
[20:16:09 INFO]: You are 16 version(s) behind
```

### WorldEdit/FAWE versions:

- [X] FAWE version:
- [] WorldEdit version: 
Build 235

### Description of the problem:

I always get NullPointerExpections in the Console, very fast and always, everythign execpt Aliases works
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

```
[20:10:27 WARN]: [PlotSquared] Task #15 for PlotSquared v5.11.2 generated an exception
java.lang.NullPointerException: null
        at com.plotsquared.bukkit.util.BukkitUtil.getHealth(BukkitUtil.java:550) ~[?:?]
        at com.plotsquared.core.listener.PlotListener.lambda$startRunnable$0(PlotListener.java:95) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-284]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-284]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1253) ~[patched_1.15.2.jar:git-Paper-284]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-284]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1170) ~[patched_1.15.2.jar:git-Paper-284]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:959) ~[patched_1.15.2.jar:git-Paper-284]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by SirYwell** [comment]
Please provide a `/plot debugpaste` or at least a full log file.

**Comment by DieProgrammIDE** [comment]
I added it

**Comment by RedstoneFuture** [comment]
moved to: https://issues.intellectualsites.com/issue/PS-8
