### ISSUE TITLE
Console startup error

### ISSUE THREAD

**Issue by osum54** [IntellectualSites/PlotSquared#2885]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

[02:01:44 INFO]: [P2] Debug Information
>> PlotArea
>> Plot Worlds: plots

>> Owned Plots: 4

>> Messages
>> Total Messages: 617

>> View all captions: /plot debug msg
>>https://pastebin.com/iCskjSrr

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
[02:01:20 INFO]: [P2] >> PlotSquared (Version: PlotSquared-5.13.0-Premium)
[02:01:20 INFO]: [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault & SirYwell
[02:01:20 INFO]: [P2] >> Wiki: https://wiki.intellectualsites.com/plotsquared/home
[02:01:20 INFO]: [P2] >> Premium: true
```

### Minecraft Version:
**Select one**

- [x] Minecraft 1.16.1
- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
[02:00:55 INFO]: This server is running Paper version git-Paper-100 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [x] WorldEdit version: 
[02:02:10 INFO]: WorldEdit version 7.2.0-beta-01
[02:02:10 INFO]: https://github.com/EngineHub/WorldEdit/
[02:02:10 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(7.2.0-beta-01+0eb9ac7)

[02:02:10 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

### Description of the problem:

On startup it produces error below.

### How to replicate:

Had a older version and put a newer version in: old version was 5.10.4

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

AdvancedChests v5.5
AdvancedNMotd v8.0.0
AntiVoid v1.0
BuycraftX v12.0.6
Chairs v5.1
ClearChat v3.2.4
CommandSigns v2.2.0
CoreProtect v19.1-RC1
CPCameraStudioReborn v1.4.2
DiscordSRV v1.19.1
dynmap v3.1-beta-1-367
Dynmap-HeroChat v0.50
Essentials v2.18.0.0
EssentialsSpawn v2.18.0.0
floodgate-bukkit v1.0-SNAPSHOT
GhostBlockKiller v4.0
GriefPrevention v16.13.0
GriefPreventionFlags v5.9.0
Herochat v6.0.1-SNAPSHOT-bb34
HorseTpWithMe v7.4.0.2
InventoryRollback v1.3.8
Item2Chat v4.4.5
Matrix v5.0.2
Multiverse-Core v4.1.0-b775
Multiverse-Inventories v3.0.0-b459
Multiverse-NetherPortals v4.1.0-b763
NexelWilderness v0.8-pre7
OpenInv v4.1.2
PermissionsEx v1.23.4
PlaceholderAPI v2.10.6
PlayerParticles v7.15
PlotSquared v5.13.0-Premium
PlugMan v2.1.7
ProtocolLib v4.6.0-SNAPSHOT-b472
PvPToggle v1.7
RChest v1.0
Shop v1.8.1
SignSell v1.0
SkEmail v1.7
SkQuery v3.6.5
Skript v2.5-alpha4
SkriptJSON v1.0.0
TAB v2.8.2
TCPShield v2.2
TreeFeller v1.13.4
Vault v1.7.3-b131
ViaBackwards v3.0.1
ViaRewind v1.5.0
ViaVersion v3.0.1
Vote v2.0.1
Votifier v2.7.1
WayPoints v1.0.0
WorldBorder v1.9.10 (beta)
WorldEdit v7.2.0-beta-01+0eb9ac7
WorldEditSelectionVisualizer v2.0.4
WorldGuard v7.0.4-beta1;bc551da

### Relevant console output, log lines, and/or screenshots:

```
[01:58:07 WARN]: java.sql.SQLException: no such column: 'flags'
[01:58:07 WARN]:        at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
[01:58:07 WARN]:        at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:452)
[01:58:07 WARN]:        at com.plotsquared.core.database.SQLManager.convertFlags(SQLManager.java:1637)
[01:58:07 WARN]:        at com.plotsquared.core.PlotSquared.<init>(PlotSquared.java:247)
[01:58:07 WARN]:        at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:219)
[01:58:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[01:58:07 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[01:58:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[01:58:07 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500)
[01:58:07 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414)
[01:58:07 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:209)
[01:58:07 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940)
[01:58:07 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[01:58:07 WARN]:        at java.lang.Thread.run(Unknown Source)
```
for short (20 lines or less) text blobs, or a paste service for large blobs -->

### Additional relevant comments/remarks:

It doesn't really effect the plugin from what i've seen but it is there in console and concerns me.

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by osum54** [comment]
Why was this closed with no answer?

**Comment by Sauilitired** [comment]
Wrong issue tracker.
