### ISSUE TITLE
option to replace invalid (offline) UUIDs

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2959]
**PlotSquared Feature Suggestion:**

Can we add an option to delete / override invalid UUID's in the database? Or a function to hide this old UUIDs from the UUID cache on the startup?

`[21:40:48] [Craft Scheduler Thread - 94/INFO]: [PS]: (UUID) Request for 030de5ae-a083-3581-9129-d0bb4e98da7b timed out`

`[21:46:06] [pool-16-thread-585/INFO]: [ParzellenSystem]: (UUID) Found invalid UUID: 030de5ae-a083-3581-9129-d0bb4e98da7b`

Otherwise, this invalid UUID's will check with every startup. In this way this feature can get a performance improvement on servers with this problem.

**How should it be implemented?**
Which kind of solutions are valid? Maybe a replacement from `invalid UUID` to `null`?
Maybe a problem is the check in which table the UUID stand on.

**Additional context**
I have my server since over 8 years. So, I have an amount of old / invalid users registered in my PS database. I think it's a good feature to help people with the same problem without to delete all old plot.

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
Is it possible to add an option to set the invalid UUID to a specified valid dummy ID like "3206ba4c-968d-424c-877d-1547fa974d60"? 

If I use `/p list all` I get many warning because of invalid players. And I wouldn't like to delete the plots. A manually set of the plot-owner needing much time.

```
[14:47:36 WARN]: java.util.concurrent.TimeoutException
[14:47:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1956)
[14:47:36 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2091)
[14:47:36 WARN]:        at PlotSquared.jar//com.plotsquared.core.util.PlayerManager.getPlayerList(PlayerManager.java:141)
[14:47:36 WARN]:        at PlotSquared.jar//com.plotsquared.core.command.ListCmd$1.run(ListCmd.java:435)
[14:47:36 WARN]:        at PlotSquared.jar//com.plotsquared.core.command.ListCmd$1.run(ListCmd.java:414)
[14:47:36 WARN]:        at PlotSquared.jar//com.plotsquared.core.command.Command.paginate(Command.java:276)
[14:47:36 WARN]:        at PlotSquared.jar//com.plotsquared.core.command.ListCmd.displayPlots(ListCmd.java:414)
[14:47:36 WARN]:        at PlotSquared.jar//com.plotsquared.core.command.ListCmd.lambda$onCommand$0(ListCmd.java:191)
[14:47:36 WARN]:        at PlotSquared.jar//com.plotsquared.core.command.ListCmd.onCommand(ListCmd.java:283)
[14:47:36 WARN]:        at PlotSquared.jar//com.plotsquared.core.command.SubCommand.execute(SubCommand.java:57)
[14:47:36 WARN]:        at PlotSquared.jar//com.plotsquared.core.command.Command.execute(Command.java:365)
[14:47:36 WARN]:        at PlotSquared.jar//com.plotsquared.core.command.MainCommand.execute(MainCommand.java:312)
[14:47:36 WARN]:        at PlotSquared.jar//com.plotsquared.core.command.MainCommand.onCommand(MainCommand.java:187)
[14:47:36 WARN]:        at PlotSquared.jar//com.plotsquared.bukkit.BukkitCommand.onCommand(BukkitCommand.java:54)
[14:47:36 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:47:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:47:36 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838)
[14:47:36 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2257)
[14:47:36 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2068)
[14:47:36 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2049)
[14:47:36 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:47:36 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[14:47:36 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[14:47:36 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:47:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[14:47:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[14:47:36 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418)
[14:47:36 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[14:47:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[14:47:36 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396)
[14:47:36 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389)
[14:47:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[14:47:36 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367)
[14:47:36 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278)
[14:47:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[14:47:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```
