### ISSUE TITLE
Plot Delete Exception

### ISSUE THREAD

**Issue by AgentSlim** [IntellectualSites/PlotSquared#3080]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When a player user /plot delete come an Exception

*Player* issued server command: /p delete
[PlotSquared] Task #9 for PlotSquared v5.13.12 generated an exception
com.plotsquared.core.command.Command$CommandException: null
        at com.plotsquared.core.util.PatternUtil.parse(PatternUtil.java:91) ~[?:?]
        at com.plotsquared.core.util.PatternUtil.parse(PatternUtil.java:62) ~[?:?]
        at com.plotsquared.core.plot.BlockBucket.compile(BlockBucket.java:168) ~[?:?]
        at com.plotsquared.core.plot.BlockBucket.toPattern(BlockBucket.java:176) ~[?:?]
        at com.plotsquared.core.generator.ClassicPlotManager.unClaimPlot(ClassicPlotManager.java:86) ~[?:?]
        at com.plotsquared.core.plot.Plot$1.run(Plot.java:947) ~[?:?]
        at com.plotsquared.core.queue.GlobalBlockQueue.runEmptyTasks(GlobalBlockQueue.java:342) ~[?:?]
        at com.plotsquared.core.queue.GlobalBlockQueue.access$400(GlobalBlockQueue.java:39) ~[?:?]
        at com.plotsquared.core.queue.GlobalBlockQueue$2.run(GlobalBlockQueue.java:119) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:829) [?:?]

### To Reproduce

1. Go on plot
2. user /plot delete

### Expected behaviour

The plot will resete/delete

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fc9da1a9a233487ca5f05fd76eb43fc5

### PlotSquared Version

PlotSquared version 5.13.12

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
You have an invalid entry in your worlds.yml
