### ISSUE TITLE
P2 conflicts with the front plug-in CS-CoreLib2 in slimfun, and the content is as follows:

### ISSUE THREAD

**Issue by shiqutong** [IntellectualSites/PlotSquared#3083]
### What feature do you want to see added?

[16:37:21] [Server thread/WARN]: [Slimefun] Loaded class com.bekvon.bukkit.residence.Residence from Residence v4.9.3.10 which is not a depend, softdepend or loadbefore of this plugin.
[16:37:21] [Server thread/ERROR]: [CS-CoreLib2] An Error occured while querying the Protection Module: "PlotSquared v6.0.0-SNAPSHOT"
java.lang.NoSuchMethodError: 'void com.plotsquared.core.location.Location.<init>(java.lang.String, int, int, int)'
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.modules.PlotSquared5ProtectionModule.hasPermission(PlotSquared5ProtectionModule.java:39) ~[?:?]
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.ProtectionManager.hasPermission(ProtectionManager.java:181) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.tools.PickaxeOfVeinMining.breakBlocks(PickaxeOfVeinMining.java:57) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.tools.PickaxeOfVeinMining.lambda$getItemHandler$1(PickaxeOfVeinMining.java:49) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callToolHandler$1(BlockListener.java:137) ~[?:?]
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem.callItemHandler(SlimefunItem.java:918) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callToolHandler(BlockListener.java:137) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:121) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor416.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-752]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-752]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-752]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:359) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:284) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1395) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-752]
	at java.lang.Thread.run(Thread.java:831) [?:?]

### Are there any alternatives?

[16:37:21] [Server thread/WARN]: [Slimefun] Loaded class com.bekvon.bukkit.residence.Residence from Residence v4.9.3.10 which is not a depend, softdepend or loadbefore of this plugin.
[16:37:21] [Server thread/ERROR]: [CS-CoreLib2] An Error occured while querying the Protection Module: "PlotSquared v6.0.0-SNAPSHOT"
java.lang.NoSuchMethodError: 'void com.plotsquared.core.location.Location.<init>(java.lang.String, int, int, int)'
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.modules.PlotSquared5ProtectionModule.hasPermission(PlotSquared5ProtectionModule.java:39) ~[?:?]
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.ProtectionManager.hasPermission(ProtectionManager.java:181) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.tools.PickaxeOfVeinMining.breakBlocks(PickaxeOfVeinMining.java:57) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.tools.PickaxeOfVeinMining.lambda$getItemHandler$1(PickaxeOfVeinMining.java:49) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callToolHandler$1(BlockListener.java:137) ~[?:?]
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem.callItemHandler(SlimefunItem.java:918) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callToolHandler(BlockListener.java:137) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:121) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor416.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-752]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-752]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-752]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:359) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:284) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1395) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-752]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-752]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by NotMyFault** [comment]
Report that to SlimeFun. They fail to load their "PlotSquared5ProtectionModule".
