### ISSUE TITLE
Failed to initialize the preset system after Java 16 installation

### ISSUE THREAD

**Issue by Thefirstalpha** [IntellectualSites/PlotSquared#3094]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Just after pushing my java version from 14 to 16, the plugins show this warn in the terminal

> [09:49:20 INFO]: [P2] Failed to initialize the preset system
[09:49:20 WARN]: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "this.engine" is null
[09:49:20 WARN]:        at com.plotsquared.core.command.DebugExec.init(DebugExec.java:133)
[09:49:20 WARN]:        at com.plotsquared.core.command.DebugExec.<init>(DebugExec.java:88)
[09:49:20 WARN]:        at com.plotsquared.core.command.MainCommand.getInstance(MainCommand.java:143)
[09:49:20 WARN]:        at com.plotsquared.core.components.ComponentPresetManager.<init>(ComponentPresetManager.java:114)
[09:49:20 WARN]:        at com.plotsquared.core.PlotSquared.<init>(PlotSquared.java:321)
[09:49:20 WARN]:        at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:221)
[09:49:20 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[09:49:20 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[09:49:20 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[09:49:20 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[09:49:20 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[09:49:20 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270)
[09:49:20 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[09:49:20 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[09:49:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

From what I've tested, everything seem to work fine

### To Reproduce

Just switch from Java 14 to Java 16

### Expected behaviour

Nothing special, just reporting this warning x)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/44e43ea03b744f3b90acf070ffd86a64

### PlotSquared Version

5.13.12

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Disable the nashorn scripting engine in your settings.yml. This has been resolved in v6.
