### ISSUE TITLE
No caption with the key 'plotsquared:flag.no_flags' exists in the map

### ISSUE THREAD

**Issue by TheIntelloBox** [IntellectualSites/PlotSquared#3121]
### Server Implementation

Spigot

### Server Version

1.17.1

### Describe the bug

[02:15:31] [Server thread/INFO]: Detected world load for 'creatif'
[02:15:31] [Server thread/INFO]: - generator: PlotSquared>PlotSquared
[02:15:31] [Server thread/INFO]: - plot world: com.plotsquared.core.generator.HybridPlotWorld
[02:15:31] [Server thread/INFO]: - plot area manager: com.plotsquared.core.generator.HybridPlotManager
[02:15:31] [Server thread/WARN]: com.plotsquared.core.configuration.caption.CaptionMap$NoSuchCaptionException: No caption with the key 'plotsquared:flag.no_flags' exists in the map
[02:15:31] [Server thread/WARN]: 	at com.plotsquared.core.configuration.caption.DummyCaptionMap.getMessage(DummyCaptionMap.java:50)
[02:15:31] [Server thread/WARN]: 	at com.plotsquared.core.configuration.caption.TranslatableCaption.getComponent(TranslatableCaption.java:96)
[02:15:31] [Server thread/WARN]: 	at com.plotsquared.core.plot.PlotArea.getFlagsComponent(PlotArea.java:450)
[02:15:31] [Server thread/WARN]: 	at com.plotsquared.core.plot.PlotArea.loadDefaultConfiguration(PlotArea.java:414)
[02:15:31] [Server thread/WARN]: 	at com.plotsquared.core.PlotSquared.loadWorld(PlotSquared.java:844)
[02:15:31] [Server thread/WARN]: 	at com.plotsquared.bukkit.generator.BukkitPlotGenerator.getDefaultPopulators(BukkitPlotGenerator.java:116)
[02:15:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:621)
[02:15:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:592)
[02:15:31] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
[02:15:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987)
[02:15:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[02:15:31] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[02:15:31] [Server thread/INFO]: Detected world load for 'creatif'
[02:15:31] [Server thread/INFO]: - generator: PlotSquared>PlotSquared
[02:15:31] [Server thread/INFO]: - plot world: com.plotsquared.core.generator.HybridPlotWorld
[02:15:31] [Server thread/INFO]: - plot area manager: com.plotsquared.core.generator.HybridPlotManager
[02:15:31] [Server thread/ERROR]: Could not pass event WorldInitEvent to PlotSquared v6.0.4-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:626) ~[spigot-1.17.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:592) ~[spigot-1.17.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[spigot-1.17.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[spigot-1.17.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3147-Spigot-9472b09-d7ef1e9]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: com.plotsquared.core.configuration.caption.CaptionMap$NoSuchCaptionException: No caption with the key 'plotsquared:flag.no_flags' exists in the map
	at com.plotsquared.core.configuration.caption.DummyCaptionMap.getMessage(DummyCaptionMap.java:50) ~[?:?]
	at com.plotsquared.core.configuration.caption.TranslatableCaption.getComponent(TranslatableCaption.java:96) ~[?:?]
	at com.plotsquared.core.plot.PlotArea.getFlagsComponent(PlotArea.java:450) ~[?:?]
	at com.plotsquared.core.plot.PlotArea.loadDefaultConfiguration(PlotArea.java:414) ~[?:?]
	at com.plotsquared.core.PlotSquared.loadWorld(PlotSquared.java:844) ~[?:?]
	at com.plotsquared.bukkit.listener.WorldEvents.onWorldInit(WorldEvents.java:64) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.jar:3147-Spigot-9472b09-d7ef1e9]
	... 9 more

### To Reproduce

Start of the server.

### Expected behaviour

No error in the console.

### Plot Debugpaste

There is an error.

### PlotSquared Version

PlotSquared v6.0.4-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
You have an invalid entry in your lang file. PlotSquared uses a dot as delimiter from captions to sub categories, not a colon.

**Comment by TheIntelloBox** [comment]
@NotMyFault I still have the error after deleting the lang file.

**Comment by NotMyFault** [comment]
Provide your full startup log https://paste.gg/

**Comment by TheIntelloBox** [comment]
https://paste.gg/p/anonymous/1198e7b1853040a3aaeeb016cfbde5e1

**Comment by NotMyFault** [comment]
> java.nio.file.NoSuchFileException: plugins/PlotSquared/lang/messages_fr.json

You attempt to load a file that does not exist. Either change it bac k to _en or create named file.

**Comment by TheIntelloBox** [comment]
Where can I find the French translation ?

**Comment by NotMyFault** [comment]
https://intellectualsites.crowdin.com/plotsquared
