### ISSUE TITLE
Error by /p download world - Reflections & Java 16

### ISSUE THREAD

**Issue by JaTiTV** [IntellectualSites/PlotSquared#3127]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

when I use /p downlod this error comes but nothing more happens

### To Reproduce

Command /p downlod on a plot

### Expected behaviour

that i get a link to download the plot

### Error log (if applicable)

https://paste.gg/p/anonymous/5893d84cd695451a8f6c04978855d1d4

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/2c2a639d10d7428e921ebf83355b4d4f

### PlotSquared Version

PlotSquared-6.0.5-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Super plugin, thank you that you exist

**Comment by NotMyFault** [comment]
This appears to be old NMS. A quick look over our ReflectionUtils revealed that we still use pre-1.17 initialization with versioned packages which is no longer used on version equal to or newer than 1.17.

**Comment by JaTiTV** [comment]
i just rebooted ps with a brand new world. Have there the building with worldedit copied in and there comes this error
`[22:12:58 INFO]: JaTiTV issued server command: /p download schem
[22:13:00 ERROR]: [PlotSquared/PlotUploader] Failed to upload schematic
java.util.concurrent.CompletionException: com.plotsquared.core.arkitektonika.exceptions.InvalidFormatException: Failed to upload '/upload'. Code: 400 (Bad Request). Reason: Uploaded file is not of valid NBT format
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: com.plotsquared.core.arkitektonika.exceptions.InvalidFormatException: Failed to upload '/upload'. Code: 400 (Bad Request). Reason: Uploaded file is not of valid NBT format
        at com.plotsquared.core.arkitektonika.v1.ApiClient.lambda$upload$4(ApiClient.java:85) ~[?:?]
        at com.plotsquared.core.http.HttpClient$WrappedRequestBuilder.execute(HttpClient.java:333) ~[?:?]
        at com.plotsquared.core.arkitektonika.v1.ApiClient.lambda$upload$7(ApiClient.java:90) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        ... 3 more
[22:13:03 INFO]: JaTiTV issued server command: /p download world
[22:13:03 WARN]: java.lang.NoSuchFieldException: m
[22:13:03 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[22:13:03 WARN]:        at com.plotsquared.core.util.ReflectionUtils.getMap(ReflectionUtils.java:58)
[22:13:03 WARN]:        at com.plotsquared.core.util.WorldUtil$1.run(WorldUtil.java:255)
[22:13:03 WARN]:        at com.plotsquared.core.util.WorldUtil$1.run(WorldUtil.java:243)
[22:13:03 WARN]:        at com.plotsquared.core.util.task.RunnableVal.run(RunnableVal.java:41)
[22:13:03 WARN]:        at com.plotsquared.core.util.SchematicHandler.lambda$upload$0(SchematicHandler.java:185)
[22:13:03 WARN]:        at com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:46)
[22:13:03 WARN]:        at com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:51)
[22:13:03 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[22:13:03 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[22:13:03 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:13:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[22:13:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[22:13:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[22:13:03 WARN]: [PlotSquared] Plugin PlotSquared v6.0.5-Premium generated an exception while executing task 6631138
java.lang.UnsupportedOperationException: null
        at com.google.common.collect.ImmutableMap.put(ImmutableMap.java:473) ~[patched_1.17.jar:git-Paper-63]
        at com.plotsquared.core.util.WorldUtil$1.run(WorldUtil.java:256) ~[?:?]
        at com.plotsquared.core.util.WorldUtil$1.run(WorldUtil.java:243) ~[?:?]
        at com.plotsquared.core.util.task.RunnableVal.run(RunnableVal.java:41) ~[?:?]
        at com.plotsquared.core.util.SchematicHandler.lambda$upload$0(SchematicHandler.java:185) ~[?:?]
        at com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:46) ~[?:?]
        at com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:51) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-63]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-63]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-63]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by JaTiTV** [comment]
can you fix this with the next update?

**Comment by JaTiTV** [comment]
Here again the error since it is no longer readable at Paste.gg [https://paste.gg/p/JaTiTV/b8c0389e2a844cf695a9b05293fd5d51](https://paste.gg/p/JaTiTV/b8c0389e2a844cf695a9b05293fd5d51)

PS: /p download and /p download schem work it only comes an error at /p download world

**Comment by NotMyFault** [comment]
Addressing reflections is always fun
```
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.plotsquared.core.util.ReflectionUtils (file:/K:/serversOnK/1.17.1/plugins/PlotSquared-Bukkit-6.0.10-SNAPSHOT.jar) to field java.util.Collections$UnmodifiableMap.m
WARNING: Please consider reporting this to the maintainers of com.plotsquared.core.util.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[14:14:59 INFO]: private final java.util.Map java.util.Collections$UnmodifiableMap.m
```
