### ISSUE TITLE
Doesn't support 1.16.5 Spigot.

### ISSUE THREAD

**Issue by ElektrodemonNl** [IntellectualSites/PlotSquared#3128]
### What feature do you want to see added?

Support for 1.16.5

I tried to install and this error came: 

[20:18:59] [Server thread/ERROR]: Could not load 'plugins/PlotSquared-Bukkit-4.494(1).jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency WorldEdit. Please download and install WorldEdit to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:269) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:381) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:224) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]

### Are there any alternatives?

tried to install other vesions of PlotSquared. I got v6 and v4.

**Comment by SirYwell** [comment]
Read the stacktrace.
