### ISSUE TITLE
 A legacy configuration file was detected. Conversion will be attempted. Failed

### ISSUE THREAD

**Issue by xazes** [IntellectualSites/PlotSquared#3149]
### Server Implementation

Spigot

### Server Version

1.17.1

### Describe the bug

Hi
When i start my Server i become this:
```
[10:55:24] [Server thread/INFO]: A legacy configuration file was detected. Conversion will be attempted.
[10:55:24] [Server thread/INFO]: A copy of worlds.yml has been saved in the file worlds.yml.old
[10:55:24] [Server thread/ERROR]: Failed to convert the legacy configuration file. See stack trace for information.
java.lang.NullPointerException: Cannot invoke "com.plotsquared.google.Injector.getInstance(java.lang.Class)" because the return value of "com.plotsquared.core.PlotPlatform.injector()" is null
        at com.plotsquared.core.PlotPlatform.worldUtil(PlotPlatform.java:214) ~[?:?]
        at com.plotsquared.core.util.LegacyConverter.blockToBucket(LegacyConverter.java:70) ~[?:?]
        at com.plotsquared.core.util.LegacyConverter.convertBlock(LegacyConverter.java:118) ~[?:?]
        at com.plotsquared.core.util.LegacyConverter.convert(LegacyConverter.java:160) ~[?:?]
        at com.plotsquared.core.PlotSquared.setupConfigs(PlotSquared.java:1393) ~[?:?]
        at com.plotsquared.core.PlotSquared.<init>(PlotSquared.java:184) ~[?:?]
        at com.plotsquared.bukkit.BukkitPlatform.onEnable(BukkitPlatform.java:260) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:233) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[10:55:24] [Server thread/INFO]: [PlotSquared] Disabling PlotSquared v6.0.5-Premium
```
I update plotsquard from old free version to premium v6 version. 
I dont know why he cant convert my old worlds.yml

### To Reproduce

1.Copy new jar to server
2.start the server

### Expected behaviour

I have expected that old would convert succesfully

### Plot Debugpaste

Cannot execute command 'plot' in plugin PlotSquared v6.0.5-Premium - plugin is disabled.

### PlotSquared Version

PlotSquared v6.0.5-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Provide both files.

**Comment by xazes** [comment]
which worlds.yml?

**Comment by NotMyFault** [comment]
> which worlds.yml?



> Provide both files.

Both, like mentioned.

**Comment by xazes** [comment]
[worlds.zip](https://github.com/IntellectualSites/PlotSquared/files/6795012/worlds.zip)

**Comment by NotMyFault** [comment]
You can't upgrade from v3 to v6 in one step. See [here](https://github.com/IntellectualSites/PlotSquared-Documentation/wiki/Migrating-from-an-older-major-release#migrating-from-plotsquared-v3) how to do so and go thru all steps.
PlotSquared will attempt several, but different, conversion steps.

**Comment by xazes** [comment]
thx
