### ISSUE TITLE
Chunk failed to load

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#3152]
### Server Implementation

Tuinity

### Server Version

1.17.1

### Describe the bug

I created a new world on 1.17.1 but after claiming a plot I get an error in console:
```
[13:47:31 WARN]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Chunk failed to load: Unloaded [-62, -35] Unloaded [-56, -29] Unloaded ticket level [-64, -37]
[13:47:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[13:47:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[13:47:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155)
[13:47:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[13:47:31 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[13:47:31 WARN]:        at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1219)
[13:47:31 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[13:47:31 WARN]:        at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1234)
[13:47:31 WARN]:        at net.minecraft.server.level.ChunkProviderServer.runTasks(ChunkProviderServer.java:835)
[13:47:31 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1395)
[13:47:31 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1378)
[13:47:31 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[13:47:31 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1354)
[13:47:31 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1265)
[13:47:31 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[13:47:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[13:47:31 WARN]: Caused by: java.lang.IllegalStateException: Chunk failed to load: Unloaded [-62, -35] Unloaded [-56, -29] Unloaded ticket level [-64, -37]
[13:47:31 WARN]:        at net.minecraft.server.level.ChunkProviderServer.lambda$bringToStatusAsync$10(ChunkProviderServer.java:595)
[13:47:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
[13:47:31 WARN]:        ... 13 more
```

### To Reproduce

1. Create a new world
2. Do /plot auto

### Expected behaviour

No errors should appear after claiming a plot

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/99f86b654a3947359e894a909170a066

### PlotSquared Version

PlotSquared-Bukkit-6.0.5-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
When using such oversized plots, it's easier to pregenerate the world. Elsewise chunks are generated when the player teleports to the plot e.g. by running commands like `/plot auto`.

**Comment by L4BORG** [comment]
BTW The same exception would pop up when regenerating roads...

on latest P2

```
> ver
[16:45:34 INFO]: Checking version, please wait...
> ver PlotSquared
[16:45:35 INFO]: PlotSquared version 6.9.2-Premium
[16:45:35 INFO]: Easy, yet powerful Plot World generation and management.
[16:45:35 INFO]: Website: https://www.spigotmc.org/resources/77506/
[16:45:35 INFO]: Authors: Citymonstret, Empire92, MattBDev, dordsor21, NotMyFault and SirYwell
[16:45:36 INFO]: This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are running the latest version
Previous version: git-Paper-386 (MC: 1.18.2)
```
