### ISSUE TITLE
Economy injection fails if no consumer plugin is used

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3189]
```
[12:10:26 INFO]: NotMyFault issued server command: /p auto
[12:10:26 WARN]: java.lang.NullPointerException: Cannot invoke "net.milkbowl.vault.economy.Economy.getBalance(org.bukkit.OfflinePlayer)" because "this.econ" is null
[12:10:26 WARN]:        at com.plotsquared.bukkit.util.BukkitEconHandler.getBalance(BukkitEconHandler.java:110)
[12:10:26 WARN]:        at com.plotsquared.core.util.EconHandler.getMoney(EconHandler.java:58)
[12:10:26 WARN]:        at com.plotsquared.bukkit.util.BukkitEconHandler.getMoney(BukkitEconHandler.java:71)
[12:10:26 WARN]:        at com.plotsquared.core.command.Auto.onCommand(Auto.java:320)
[12:10:26 WARN]:        at com.plotsquared.core.command.SubCommand.execute(SubCommand.java:57)
[12:10:26 WARN]:        at com.plotsquared.core.command.Command.execute(Command.java:365)
[12:10:26 WARN]:        at com.plotsquared.core.command.MainCommand.execute(MainCommand.java:312)
[12:10:26 WARN]:        at com.plotsquared.core.command.MainCommand.onCommand(MainCommand.java:187)
[12:10:26 WARN]:        at com.plotsquared.bukkit.BukkitCommand.onCommand(BukkitCommand.java:54)
[12:10:26 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:10:26 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:10:26 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:830)
[12:10:26 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
[12:10:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[12:10:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[12:10:26 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:10:26 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:10:26 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[12:10:26 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:10:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:10:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[12:10:26 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[12:10:26 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[12:10:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:10:26 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[12:10:26 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[12:10:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[12:10:26 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[12:10:26 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[12:10:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[12:10:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by mrfloris** [comment]
Yep, I am getting this as well. Using CMI economy. and vault 1.7.3
