### ISSUE TITLE
CPU usage stuck at over 100% because of PlotSquared

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#3235]
### Server Implementation

Tuinity

### Server Version

1.17.1

### Describe the bug

After leaving my server online for a couple of hours I noticed that my CPU usage was stuck at over 100% so I used VisualVM to see what was going on and this seems to be the problem:

![Untitled](https://user-images.githubusercontent.com/10485646/132258010-30b5df2f-3c27-4381-a03f-4e520c779f2b.png)

```
"Craft Scheduler Thread - 5 - PlotSquared" - Thread t@115
   java.lang.Thread.State: RUNNABLE
        at app//org.sqlite.core.NativeDB.step(Native Method)
        - locked <505b55ae> (a org.sqlite.core.NativeDB)
        at app//org.sqlite.core.DB.execute(DB.java:851)
        at app//org.sqlite.core.DB.executeUpdate(DB.java:904)
        - locked <505b55ae> (a org.sqlite.core.NativeDB)
        at app//org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
        at PlotSquared-Bukkit-6.0.9-Premium.jar//com.plotsquared.core.database.SQLManager$8.addBatch(SQLManager.java:1082)
        at PlotSquared-Bukkit-6.0.9-Premium.jar//com.plotsquared.core.database.SQLManager.sendBatch(SQLManager.java:430)
        at PlotSquared-Bukkit-6.0.9-Premium.jar//com.plotsquared.core.database.SQLManager.lambda$new$0(SQLManager.java:210)
        at PlotSquared-Bukkit-6.0.9-Premium.jar//com.plotsquared.core.database.SQLManager$$Lambda$5760/0x0000000801d6e380.run(Unknown Source)
        at PlotSquared-Bukkit-6.0.9-Premium.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:46)
        at PlotSquared-Bukkit-6.0.9-Premium.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:51)
        at app//org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
        at app//org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at app//com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base@16.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base@16.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base@16.0.2/java.lang.Thread.run(Thread.java:831)
```

![Untitled](https://user-images.githubusercontent.com/10485646/132258741-e38fb842-b523-4521-8c0c-f8230d0ae980.png)

Here is the entire thread dump if it helps: https://pastebin.com/DDHetRPT

When shutting down the server I received this error: https://pastebin.com/DJzr7L2z

### To Reproduce

I'm not sure how to reproduce this

### Expected behaviour

CPU usage should not get stuck at a high percentage

### Plot Debugpaste

I had to restart my server because of the CPU usage being very high: https://athion.net/ISPaster/paste/view/48550f965c68413a8ff4ee6bed05aa6c

### PlotSquared Version

PlotSquared-Bukkit-6.0.9-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by SirYwell** [comment]
Could you share your log from before the restart?

**Comment by SecretlyJealous** [comment]
> Could you share your log from before the restart?

Sure, here's the log: https://pastebin.com/iLSpyf3y

**Comment by OneLiteFeather** [comment]
Can't be replicated and the logs are empty as well
