### ISSUE TITLE
An Error occured while querying the Protection Module: "PlotSquared v6.0.10-SNAPSHOT"

### ISSUE THREAD

**Issue by mclk623** [IntellectualSites/PlotSquared#3243]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

[14:40:44 ERROR]: An Error occured while querying the Protection Module: "PlotSquared v6.0.10-SNAPSHOT"
java.lang.NoSuchMethodError: 'void com.plotsquared.core.location.Location.<init>(java.lang.String, int, int, int)'
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.modules.PlotSquared5ProtectionModule.hasPermission(PlotSquared5ProtectionModule.java:39) ~[Slimefun-v4.9-canary-338f154.jar:?]
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.ProtectionManager.hasPermission(ProtectionManager.java:181) ~[Slimefun-v4.9-canary-338f154.jar:?]
	at io.github.thebusybiscuit.exoticgarden.listeners.PlantsListener.onHarvest(PlantsListener.java:302) ~[ExoticGarden - DEV 76 (git d148a).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor836.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-259]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-259]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-259]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:402) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:356) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:316) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1734) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-259]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-259]
	at java.lang.Thread.run(Thread.java:831) [?:?]

### To Reproduce

1.Install Slimefun-v4.9-canary-338f154.jar
2.Running server

### Expected behaviour

No this error

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/0d3406ecfc6245ec990d6128c51970ff

### PlotSquared Version

6.0.10-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Not a plotsquared issue, repprt it to slimefun.
