### ISSUE TITLE
[API] PlayerAutoPlotsChosenEvent issue with plot.addTrusted()

### ISSUE THREAD

**Issue by AerWyn81** [IntellectualSites/PlotSquared#3271]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When using the PlayerAutoPlotsChosenEvent event, method `plot.addTrusted()` throw an SQL exception : 
```
[14:05:37 INFO]: AerWyn81 issued server command: /plot auto
[14:05:37 WARN]: java.sql.SQLException: Plot does not exist in database
[14:05:37 WARN]: 	at PlotSquared-Bukkit-6.1.2-Premium.jar//com.plotsquared.core.database.SQLManager.getId(SQLManager.java:1571)
[14:05:37 WARN]: 	at PlotSquared-Bukkit-6.1.2-Premium.jar//com.plotsquared.core.database.SQLManager$32.set(SQLManager.java:2584)
[14:05:37 WARN]: 	at PlotSquared-Bukkit-6.1.2-Premium.jar//com.plotsquared.core.database.SQLManager.sendBatch(SQLManager.java:429)
[14:05:37 WARN]: 	at PlotSquared-Bukkit-6.1.2-Premium.jar//com.plotsquared.core.database.SQLManager.lambda$new$0(SQLManager.java:210)
[14:05:37 WARN]: 	at PlotSquared-Bukkit-6.1.2-Premium.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:46)
[14:05:37 WARN]: 	at PlotSquared-Bukkit-6.1.2-Premium.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:51)
[14:05:37 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:05:37 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:05:37 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:05:37 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[14:05:37 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:05:37 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

However, the player is added to the plot : 
![](https://i.imgur.com/2fJFu7Z.png)

### To Reproduce

- Create a class and register the PS API. 
- Subscribe to the event PlayerAutoPlotsChosenEvent.
- Get the event plot object and try to add a trusted player in the plot with the plot.addTrusted();
- See console exception

### Expected behaviour

No exception

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/bb568cc53c1c46ecb27c38fadfb39275

### PlotSquared Version

6.1.2-Premium

### Checklist

- [x] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
The event is fired when the plot is chosen, not claimed. Use `PlotClaimedNotifyEvent`

**Comment by AerWyn81** [comment]
So I need to handle the player management on my side ? Because `PlotClaimedNotifyEvent` does not contains any information of player who claimed auto while `PlayerAutoPlotsChosenEvent` does ? Or is it possible to add the user who has claim in the notify?

**Comment by dordsor21** [comment]
The player is the owner of the plot..?

**Comment by AerWyn81** [comment]
It's incredibly clever.

Ook, i'm a bit tired. You're right, ty 😂
