### ISSUE TITLE
Failed to parse default flag with key 'use' and value '#doors'

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#3352]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

In worlds.yml when I set #doors as a use flag it prints an error in console:
```
[15:04:34 WARN]: [PlotSquared/PlotArea] Failed to parse default flag with key 'use' and value '#doors'. Reason: com.plotsquared.core.configuration.caption.TranslatableCaption@6ebec81d. This flag will not be added as a default flag.
[15:04:34 WARN]: com.plotsquared.core.plot.flag.FlagParseException: Failed to parse flag of type 'use'. Value '#doors' was not accepted.
[15:04:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.flag.types.BlockTypeListFlag.getCategory(BlockTypeListFlag.java:102)
[15:04:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.flag.types.BlockTypeListFlag.parse(BlockTypeListFlag.java:63)
[15:04:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.flag.types.BlockTypeListFlag.parse(BlockTypeListFlag.java:42)
[15:04:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.PlotArea.parseFlags(PlotArea.java:201)
[15:04:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.PlotArea.loadDefaultConfiguration(PlotArea.java:411)
[15:04:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.PlotSquared.loadWorld(PlotSquared.java:844)
[15:04:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.bukkit.generator.BukkitPlotGenerator.getDefaultPopulators(BukkitPlotGenerator.java:116)
[15:04:34 WARN]:        at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:746)
[15:04:34 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:702)
[15:04:34 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[15:04:34 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[15:04:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:04:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### To Reproduce

1. Go to worlds.yml and set the use flag to `#doors`

### Expected behaviour

1. There should be no error printed to console

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/591bc8d7600249738145f33d58f874b3

### PlotSquared Version

PlotSquared-Bukkit-6.1.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I was not able to replicate that. Looking at your log, it doesn't appear on startup either, can you leave some steps to replicate that?

**Comment by SecretlyJealous** [comment]
> I was not able to replicate that. Looking at your log, it doesn't appear on startup either, can you leave some steps to replicate that?

In my worlds.yml I am manually editing the file to add a use flag for minecraft:#doors

```
    flags:
      use: minecraft:#doors
```

![Untitled](https://user-images.githubusercontent.com/10485646/144704955-1fb9097d-374f-40ce-ba9e-50c98c14e2c5.png)

On startup it gives this error in latest.log:
```
[09:39:34 WARN]: [PlotSquared/PlotArea] Failed to parse default flag with key 'use' and value 'minecraft:#doors'. Reason: com.plotsquared.core.configuration.caption.TranslatableCaption@6ebec81d. This flag will not be added as a default flag.
[09:39:34 WARN]: com.plotsquared.core.plot.flag.FlagParseException: Failed to parse flag of type 'use'. Value 'minecraft:#doors' was not accepted.
[09:39:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.flag.types.BlockTypeListFlag.getCategory(BlockTypeListFlag.java:93)
[09:39:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.flag.types.BlockTypeListFlag.parse(BlockTypeListFlag.java:63)
[09:39:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.flag.types.BlockTypeListFlag.parse(BlockTypeListFlag.java:42)
[09:39:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.PlotArea.parseFlags(PlotArea.java:201)
[09:39:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.PlotArea.loadDefaultConfiguration(PlotArea.java:411)
[09:39:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.PlotSquared.loadWorld(PlotSquared.java:844)
[09:39:34 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.bukkit.generator.BukkitPlotGenerator.getDefaultPopulators(BukkitPlotGenerator.java:116)
[09:39:34 WARN]:        at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:746)
[09:39:34 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:702)
[09:39:34 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[09:39:34 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[09:39:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[09:39:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[09:39:34 INFO]: [P2] Area flags: [use;minecraft:#doors]
[09:39:34 INFO]: [P2] Road flags: []
```

PS Debugpaste: https://athion.net/ISPaster/paste/view/7c2d0bc9180b4dc2ae0eeaa74f99d45a

**Comment by SirYwell** [comment]
The correct syntax for that would be `#minecraft:doors`. In YAML, you need to add enclosing `'`, otherwise it's interpreted as a comment.

**Comment by SecretlyJealous** [comment]
> The correct syntax for that would be `#minecraft:doors`. In YAML, you need to add enclosing `'`, otherwise it's interpreted as a comment.

I've adjusted it but it still doesn't work unless I've still written it wrong?

    flags:
      use: '#minecraft:doors'

```
[15:14:46 WARN]: [PlotSquared/PlotArea] Failed to parse default flag with key 'use' and value '#minecraft:doors'. Reason: com.plotsquared.core.configuration.caption.TranslatableCaption@6ebec81d. This flag will not be added as a default flag.
[15:14:46 WARN]: com.plotsquared.core.plot.flag.FlagParseException: Failed to parse flag of type 'use'. Value '#minecraft:doors' was not accepted.
[15:14:46 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.flag.types.BlockTypeListFlag.getCategory(BlockTypeListFlag.java:102)
[15:14:46 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.flag.types.BlockTypeListFlag.parse(BlockTypeListFlag.java:63)
[15:14:46 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.flag.types.BlockTypeListFlag.parse(BlockTypeListFlag.java:42)
[15:14:46 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.PlotArea.parseFlags(PlotArea.java:201)
[15:14:46 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.plot.PlotArea.loadDefaultConfiguration(PlotArea.java:411)
[15:14:46 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.core.PlotSquared.loadWorld(PlotSquared.java:844)
[15:14:46 WARN]:        at PlotSquared-Bukkit-6.1.4-Premium.jar//com.plotsquared.bukkit.generator.BukkitPlotGenerator.getDefaultPopulators(BukkitPlotGenerator.java:116)
[15:14:46 WARN]:        at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:746)
[15:14:46 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:702)
[15:14:46 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[15:14:46 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[15:14:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:14:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:14:46 INFO]: [P2] Area flags: [use;#minecraft:doors]
[15:14:46 INFO]: [P2] Road flags: []
```
