### ISSUE TITLE
java.lang.NullPointerException when a portal is created by something other than a player

### ISSUE THREAD

**Issue by quiquelhappy** [IntellectualSites/PlotSquared#3367]
### Server Implementation

Paper

### Server Version

1.18

### Describe the bug

```
[12:10:51 ERROR]: Could not pass event PortalCreateEvent to PlotSquared v6.1.4-Premium
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getLocation()" because the return value of "org.bukkit.event.world.PortalCreateEvent.getEntity()" is null
        at com.plotsquared.bukkit.listener.PlayerEventListener.onPortalCreation(PlayerEventListener.java:1758) ~[PlotSquared-Bukkit-6.1.4-Premium.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor41.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-73]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.portal.PortalShape.createPortalBlocks(PortalShape.java:203) ~[?:?]
        at net.minecraft.world.level.block.BaseFireBlock.onPlace(BaseFireBlock.java:154) ~[?:?]
        at net.minecraft.world.level.block.FireBlock.onPlace(FireBlock.java:364) ~[?:?]
        at net.minecraft.world.level.block.BaseFireBlock.onPlace(BaseFireBlock.java:145) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onPlace(BlockBehaviour.java:950) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk.setBlockState(LevelChunk.java:555) ~[?:?]
        at net.minecraft.world.level.Level.setBlock(Level.java:581) ~[?:?]
        at net.minecraft.world.level.Level.setBlock(Level.java:543) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:201) ~[paper-1.18.1.jar:git-Paper-73]
        at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:186) ~[paper-1.18.1.jar:git-Paper-73]
        at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.setBlockData(CraftBlock.java:182) ~[paper-1.18.1.jar:git-Paper-73]
        at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.setType(CraftBlock.java:171) ~[paper-1.18.1.jar:git-Paper-73]
        at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.setType(CraftBlock.java:165) ~[paper-1.18.1.jar:git-Paper-73]
        at me.IIIKILLAIII.AntiPortalTrapping.Main.onPortalLeave(Main.java:196) ~[AntiPortalTrapping.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor154.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-73]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1482) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Rot.handle(ServerboundMovePlayerPacket.java:64) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-73]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-73]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-73]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-73]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-73]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-73]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-73]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-73]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

is being generated when a portal that creates nether portals creates em, of course, since the plugin created the portal, the entity creating the portal is null, therefore dropping an error in the process. please, just ignore portal creation events for null entities.

### To Reproduce

1. install plotsquared and antiportaltrapping
2. enter a portal (may need to be created on the plot, not sure)

### Expected behaviour

ignore events for null entities for portal creation

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/4d924ccddc794553aa574e7aa5e1194b

### PlotSquared Version

6.1.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
> Expected behaviour
ignore events for null entities for portal creation

That may leads to more unexpected results, preferably nullability should be treated properly.
