### ISSUE TITLE
loader constraint violation for class com.fastasyncworldedit.bukkit.regions.plotsquared.FaweQueueCoordinator

### ISSUE THREAD

**Issue by PappoYT** [IntellectualSites/PlotSquared#3462]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

After installing FastAsyncWorldEdit I get errors on startup:

```
[06:05:29] [Server thread/ERROR]: Error occurred while enabling PlotSquared v6.3.0-Premium (Is it up to date?)
java.lang.LinkageError: loader constraint violation for class com.fastasyncworldedit.bukkit.regions.plotsquared.FaweQueueCoordinator: when selecting overriding method 'com.sk89q.worldedit.world.World com.fastasyncworldedit.bukkit.regions.plotsquared.FaweQueueCoordinator.getWorld()' the class loader 'FastAsyncWorldEdit-Bukkit-2.0.1-SNAPSHOT-72.jar' @12cbf967 of the selected method's type com.fastasyncworldedit.bukkit.regions.plotsquared.FaweQueueCoordinator, and the class loader 'PlotSquared-Bukkit-6.3.0-Premium.jar' @1bb057db for its super type com.plotsquared.core.queue.QueueCoordinator have different Class objects for the type com.sk89q.worldedit.world.World used in the signature (com.fastasyncworldedit.bukkit.regions.plotsquared.FaweQueueCoordinator is in unnamed module of loader 'FastAsyncWorldEdit-Bukkit-2.0.1-SNAPSHOT-72.jar' @12cbf967, parent loader 'app'; com.plotsquared.core.queue.QueueCoordinator is in unnamed module of loader 'PlotSquared-Bukkit-6.3.0-Premium.jar' @1bb057db, parent loader 'app')
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:375) ~[?:?]
at com.plotsquared.bukkit.BukkitPlatform.onEnable(BukkitPlatform.java:267) ~[PlotSquared-Bukkit-6.3.0-Premium.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-408]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-408]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-408]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-408]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-408]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[patched_1.17.1.jar:git-Paper-408]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-408]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### To Reproduce

Install build #72 https://ci.athion.net/job/FastAsyncWorldEdit/
startup server

### Expected behaviour

no errors

### Error log (if applicable)

https://mclo.gs/fstYjJW

### Plot Debugpaste

Sorry, taht command is disabled (it is shown after I type the command)

### PlotSquared Version

PlotSquared v6.3.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

20.01 07:13:59 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'plot' in plugin PlotSquared v6.3.0-Premium - plugin is disabled.

**Comment by SirYwell** [comment]
https://mclo.gs/fstYjJW#L79 your log file already tells you what's wrong.
