### ISSUE TITLE
Async catcher prevents plot clear

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3667]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

Async catcher prevents plot clearing on 1.19

### To Reproduce

- Create a server on 1.19 using the newest Paper, WorldEdit and P2 build (specific version information can be obtained from the debugpaste below)
- Create a plot world
- Run `/plot clear`

### Expected behaviour

Proceed fine

### Error log (if applicable)

https://gist.github.com/NotMyFault/e78359794d04f904e38a7af8cb3cb768

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/355edd9b906d4cc9bba7d87ed6b562e0

### PlotSquared Version

6.8.1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
Fixed by #3657

**Comment by NotMyFault** [comment]
> Fixed by #3657

Nice to see, though I'm not able to launch that (on 1.19):
```
[13:53:59 ERROR]: Error occurred while enabling PlotSquared v6.8.2-SNAPSHOT (Is it up to date?)
com.plotsquared.google.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingImplementation]: No implementation for Boolean annotated with @Assisted("forceSync") was bound.

Did you mean?
    Boolean annotated with @Assisted("") bound at ChunkCoordinatorFactory.create(ChunkCoordinatorFactory.java:56)

Requested by:
1  : BukkitChunkCoordinator.<init>(BukkitChunkCoordinator.java:117)
      \_ for 10th parameter
     at ChunkCoordinatorFactory.create(ChunkCoordinatorFactory.java:56)
     at FactoryProvider2.initialize(FactoryProvider2.java:785)
     at PlotSquared-Bukkit-6.8.2-SNAPSHOT.jar//BukkitModule.configure(BukkitModule.java:129)
      \_ installed by: BukkitModule -> FactoryModuleBuilder$1

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

2) [Guice/MissingImplementation]: No implementation for Boolean annotated with @Assisted("unloadAfter") was bound.

Did you mean?
    Boolean annotated with @Assisted("") bound at ChunkCoordinatorFactory.create(ChunkCoordinatorFactory.java:56)

Requested by:
1  : BukkitChunkCoordinator.<init>(BukkitChunkCoordinator.java:117)
      \_ for 8th parameter
     at ChunkCoordinatorFactory.create(ChunkCoordinatorFactory.java:56)
     at FactoryProvider2.initialize(FactoryProvider2.java:785)
     at PlotSquared-Bukkit-6.8.2-SNAPSHOT.jar//BukkitModule.configure(BukkitModule.java:129)
      \_ installed by: BukkitModule -> FactoryModuleBuilder$1

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

2 errors

======================
Full classname legend:
======================
Assisted:                "com.plotsquared.google.assistedinject.Assisted"
BukkitChunkCoordinator:  "com.plotsquared.bukkit.queue.BukkitChunkCoordinator"
BukkitModule:            "com.plotsquared.bukkit.inject.BukkitModule"
ChunkCoordinatorFactory: "com.plotsquared.core.inject.factory.ChunkCoordinatorFactory"
FactoryModuleBuilder$1:  "com.plotsquared.google.assistedinject.FactoryModuleBuilder$1"
FactoryProvider2:        "com.plotsquared.google.assistedinject.FactoryProvider2"
========================
End of classname legend:
========================

	at com.plotsquared.google.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:576) ~[PlotSquared-Bukkit-6.8.2-SNAPSHOT.jar:?]
	at com.plotsquared.google.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182) ~[PlotSquared-Bukkit-6.8.2-SNAPSHOT.jar:?]
	at com.plotsquared.google.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113) ~[PlotSquared-Bukkit-6.8.2-SNAPSHOT.jar:?]
	at com.plotsquared.google.Guice.createInjector(Guice.java:87) ~[PlotSquared-Bukkit-6.8.2-SNAPSHOT.jar:?]
	at com.plotsquared.google.Guice.createInjector(Guice.java:78) ~[PlotSquared-Bukkit-6.8.2-SNAPSHOT.jar:?]
	at com.plotsquared.bukkit.BukkitPlatform.onEnable(BukkitPlatform.java:290) ~[PlotSquared-Bukkit-6.8.2-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554) ~[paper-1.19.jar:git-Paper-"02b5ec4"]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468) ~[paper-1.19.jar:git-Paper-"02b5ec4"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.jar:git-Paper-"02b5ec4"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-"02b5ec4"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-"02b5ec4"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by dordsor21** [comment]
Are you merging the PR locally and testing or using the PR branch directly?

**Comment by NotMyFault** [comment]
> Are you merging the PR locally and testing or using the PR branch directly?

I checkout out the PR via `gh pr checkout 3657`.

**Comment by dordsor21** [comment]
Either we remove the deprecated create method, or we implement two custom classes specifically to handle instances such as this, based on https://github.com/google/guice/pull/1347

**Comment by NotMyFault** [comment]
> #3657

Should be good to remove it I guess, it's sunset anyway.

**Comment by NotMyFault** [comment]
I can confirm this resolves the issue 👍🏻
