### ISSUE TITLE
Claiming a new plot displays unloaded chunks that refuse to load

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#3753]
### Server Implementation

Paper

### Server Version

1.19.1

### Describe the bug

I've been getting complaints ever since I updated to 1.19 about new players claiming plots but chunks not loading correctly, there is no error in console but I'm able to reproduce this behaviour on my test server by claiming a new plot. Reloading the chunks with F3 + A doesn't seem to fix the issue either and I wasn't able to get the chunk to load by placing a block on it.
Here's a video of the problem: https://gfycat.com/commoncaninefrilledlizard

### To Reproduce

1. Claim a new plot

### Expected behaviour

Claiming a new plot shouldn't have unloaded chunks which refuse to load

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9deef19851414314b269d0ca3bfea0b5

### PlotSquared Version

6.9.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Is the attached debug paste from your test server?
We'd need the debug paste of the server, when the issue happens

**Comment by SecretlyJealous** [comment]
> Is the attached debug paste from your test server? We'd need the debug paste of the server, when the issue happens

The debug paste is from the test server and the video is also from the test server, I recreated the problem on a test server by claiming a new plot

**Comment by PierreSchwang** [comment]
I'm unable to reproduce that with the latest builds (Paper 1.19.2-113 and PS 9.6.4-SNAPSHOT)
Can you try to reproduce that on latest paper again?

**Comment by SecretlyJealous** [comment]
> I'm unable to reproduce that with the latest builds (Paper 1.19.2-113 and PS 9.6.4-SNAPSHOT) Can you try to reproduce that on latest paper again?

I reproduced it on the latest paper: https://gfycat.com/grizzledignorantbarbet
Here is my debug paste: https://athion.net/ISPaster/paste/view/28d3109f56704dabb7777df068b482e5
It could be because of my plot size? Can you try to reproduce it using my worlds.yml file with `size: 505` I'm also using the default preload chunk count in fawe: `preload-chunk-count: 512`

**Comment by PierreSchwang** [comment]
Relates to https://github.com/IntellectualSites/PlotSquared/issues/3152 - Basically, yes. This plot size is enormous and can't be handled to generate in time. Basically, pregenerate the whole plotworld and you should be good to go

**Comment by SecretlyJealous** [comment]
> Relates to #3152 - Basically, yes. This plot size is enormous and can't be handled to generate in time. Basically, pregenerate the whole plotworld and you should be good to go

https://github.com/IntellectualSites/PlotSquared/issues/3152 is a different issue though, I get that error in console sometimes but it is different from the behaviour that I'm reporting now. The issue right now with the chunks not loading is that it should eventually load but that's not what is happening, I have to leave the server and join back just to get the chunks to show up on my screen. When I claim a new plot and the chunks are unloaded I can still build on those chunks but visually the chunk does not appear to load, I think there's some sort of packet related issue going on which is causing this visual behaviour. I don't really want to progenerate my world, it's not really feasible given due to size. I've been able to run the server for years without any issues with claiming large plots. I did some more tests now and I can confirm that this is a visual bug, I claimed a plot and quickly rejoined the server and all the chunks showed up correctly. I'm really hoping you can figure out if it's a timing issue with packets? I didn't have this problem on 1.18 if that helps.

**Comment by PierreSchwang** [comment]
Yes, you don't have the error (tho I had it once) but PS does nothing then teleporting the player to the plot location. It's the server softwares tasks to teleport and load the chunks. If the server is not capable of doing that (or just doesn't want to), we can't change anything about that.
Did a little bit of testing by loading the chunk manually, but that didn't work either

**Comment by SecretlyJealous** [comment]
The problem is that the server is actually loading the chunks, I visually cannot see them until I rejoin the server which is why I believe this is a packet related issue. I didn't have this problem in 1.18 so something has changed in paper I'm assuming

**Comment by PierreSchwang** [comment]
I did a bit of testing, but that does not seem to be fixable on PS's side.
And here for example, I get the name error of the linked issue:
```[22:53:25 INFO]: PierreV2 issued server command: /plot auto
[22:53:32 WARN]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Chunk failed to load: Unloaded [-33, -28] Unloaded [-27, -20] Unloaded ticket level [-35, -28]
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[22:53:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:53:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer$b.d(ChunkProviderServer.java:1243)
[22:53:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[22:53:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer$b.y(ChunkProviderServer.java:1256)
[22:53:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer.d(ChunkProviderServer.java:820)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1388)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[22:53:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1348)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1230)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[22:53:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:53:32 WARN]: Caused by: java.lang.IllegalStateException: Chunk failed to load: Unloaded [-33, -28] Unloaded [-27, -20] Unloaded ticket level [-35, -28]
[22:53:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer.lambda$bringToStatusAsync$10(ChunkProviderServer.java:587)
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
[22:53:32 WARN]:        ... 13 more
[22:53:32 WARN]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Chunk failed to load: Unloaded [-33, -28] Unloaded [-27, -20] Unloaded ticket level [-35, -28]
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[22:53:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:53:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer$b.d(ChunkProviderServer.java:1243)
[22:53:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[22:53:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer$b.y(ChunkProviderServer.java:1256)
[22:53:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer.d(ChunkProviderServer.java:820)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1388)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[22:53:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1348)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1230)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[22:53:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:53:32 WARN]: Caused by: java.lang.IllegalStateException: Chunk failed to load: Unloaded [-33, -28] Unloaded [-27, -20] Unloaded ticket level [-35, -28]
[22:53:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer.lambda$bringToStatusAsync$10(ChunkProviderServer.java:587)
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
[22:53:32 WARN]:        ... 13 more
[22:53:32 WARN]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Chunk failed to load: Unloaded [-33, -28] Unloaded [-27, -20] Unloaded ticket level [-35, -28]
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[22:53:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:53:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer$b.d(ChunkProviderServer.java:1243)
[22:53:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[22:53:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer$b.y(ChunkProviderServer.java:1256)
[22:53:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer.d(ChunkProviderServer.java:820)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1388)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[22:53:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1348)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1230)
[22:53:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[22:53:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:53:32 WARN]: Caused by: java.lang.IllegalStateException: Chunk failed to load: Unloaded [-33, -28] Unloaded [-27, -20] Unloaded ticket level [-35, -28]
[22:53:32 WARN]:        at net.minecraft.server.level.ChunkProviderServer.lambda$bringToStatusAsync$10(ChunkProviderServer.java:587)
[22:53:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
[22:53:32 WARN]:        ... 13 more```

We can't do anything about the way minecraft handles the sending of packets
