### ISSUE TITLE
Carnt delete plots

### ISSUE THREAD

**Issue by Josh-65** [IntellectualSites/PlotSquared#3754]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

When i try using /plot delete or /plot dispose it doesnt do anything in game and creates an error in the console

`[19:11:19 WARN]: [PlotSquared] Task #46068 for PlotSquared v6.9.4-SNAPSHOT generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 24 out of bounds for length 24
        at com.plotsquared.core.queue.LocalChunk.setBiome(LocalChunk.java:91) ~[PlotSquared-Bukkit-6.9.4-SNAPSHOT.jar:?]
        at com.plotsquared.core.queue.BasicQueueCoordinator.setBiome(BasicQueueCoordinator.java:136) ~[PlotSquared-Bukkit-6.9.4-SNAPSHOT.jar:?]
        at com.plotsquared.core.queue.QueueCoordinator.setBiomeCuboid(QueueCoordinator.java:497) ~[PlotSquared-Bukkit-6.9.4-SNAPSHOT.jar:?]
        at com.plotsquared.core.queue.BasicQueueCoordinator.setBiomeCuboid(BasicQueueCoordinator.java:346) ~[PlotSquared-Bukkit-6.9.4-SNAPSHOT.jar:?]
        at com.plotsquared.core.generator.HybridPlotManager.clearPlot(HybridPlotManager.java:293) ~[PlotSquared-Bukkit-6.9.4-SNAPSHOT.jar:?]
        at com.plotsquared.core.plot.PlotModificationManager$2.run(PlotModificationManager.java:280) ~[PlotSquared-Bukkit-6.9.4-SNAPSHOT.jar:?]
        at com.plotsquared.core.plot.PlotModificationManager.clear(PlotModificationManager.java:283) ~[PlotSquared-Bukkit-6.9.4-SNAPSHOT.jar:?]
        at com.plotsquared.core.plot.PlotModificationManager.deletePlot(PlotModificationManager.java:855) ~[PlotSquared-Bukkit-6.9.4-SNAPSHOT.jar:?]
        at com.plotsquared.core.command.Delete.lambda$onCommand$3(Delete.java:108) ~[PlotSquared-Bukkit-6.9.4-SNAPSHOT.jar:?]
        at com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39) ~[PlotSquared-Bukkit-6.9.4-SNAPSHOT.jar:?]
        at com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44) ~[PlotSquared-Bukkit-6.9.4-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### To Reproduce

1. Claim plot /plot claim
2. Go into plot
3. Using /plot delete

### Expected behaviour

The plot should using the plot.schmatic to reset the plot and allow it to be claimable again.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d052077ea13444c4b3a35064d8cacc9c

### PlotSquared Version

6.9.4 Snapshot

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Im using the github build version https://github.com/IntellectualSites/PlotSquared/pull/3750 since it doesnt let me download from spigot

**Comment by PierreSchwang** [comment]
Try updating WorldEdit to 7.2.10 and see, if the issue persists.

**Comment by Josh-65** [comment]
Im using 7.2.11 of the plugin doesnt change anything

**Comment by PierreSchwang** [comment]
Relates to https://github.com/IntellectualSites/PlotSquared/issues/3755 and should be solved with that

**Comment by Josh-65** [comment]
With the new configs it still has the same issue.

**Comment by Josh-65** [comment]
Issue still exsits with new config file you send

**Comment by Josh-65** [comment]
This is still an issue and is not a duplicate of 3755
