### ISSUE TITLE
i need help with the mod

### ISSUE THREAD

**Issue by elpalomomlg** [IntellectualSites/PlotSquared#3797]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

[22:19:09 WARN]: com.plotsquared.google.ProvisionException: Unable to provision, see the following errors:
[22:19:09 WARN]: 
[22:19:09 WARN]: 1) [Guice/NullInjectedIntoNonNullable]: null returned by binding at HybridPlotWorldFactory.create()
[22:19:09 WARN]:  but the 2nd parameter of HybridPlotWorld.<init>(HybridPlotWorld.java:101) is not @Nullable
[22:19:09 WARN]:   at HybridPlotWorldFactory.create(HybridPlotWorldFactory.java:1)
[22:19:09 WARN]:   at HybridPlotWorld.<init>(HybridPlotWorld.java:101)
[22:19:09 WARN]:       \_ for 2nd parameter
[22:19:09 WARN]:   while locating HybridPlotWorld annotated with @UniqueAnnotations$Internal(1)
[22:19:09 WARN]: 
[22:19:09 WARN]: Learn more:
[22:19:09 WARN]:   https://github.com/google/guice/wiki/NULL_INJECTED_INTO_NON_NULLABLE
[22:19:09 WARN]: 
[22:19:09 WARN]: 1 error
[22:19:09 WARN]: 
[22:19:09 WARN]: ======================
[22:19:09 WARN]: Full classname legend:
[22:19:09 WARN]: ======================
[22:19:09 WARN]: HybridPlotWorld:            "com.plotsquared.core.generator.HybridPlotWorld"
[22:19:09 WARN]: HybridPlotWorldFactory:     "com.plotsquared.core.inject.factory.HybridPlotWorldFactory"
[22:19:09 WARN]: UniqueAnnotations$Internal: "com.plotsquared.google.internal.UniqueAnnotations$Internal"
[22:19:09 WARN]: ========================
[22:19:09 WARN]: End of classname legend:
[22:19:09 WARN]: ========================
[22:19:09 WARN]: 
[22:19:09 WARN]:        at com.plotsquared.google.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
[22:19:09 WARN]:        at com.plotsquared.google.internal.InjectorImpl$1.get(InjectorImpl.java:1104)
[22:19:09 WARN]:        at com.plotsquared.google.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:906)
[22:19:09 WARN]:        at jdk.proxy7/jdk.proxy7.$Proxy93.create(Unknown Source)
[22:19:09 WARN]:        at com.plotsquared.core.generator.HybridGen.getNewPlotArea(HybridGen.java:372)
[22:19:09 WARN]:        at com.plotsquared.core.setup.CommonSetupSteps.wrap(CommonSetupSteps.java:270)
[22:19:09 WARN]:        at com.plotsquared.core.setup.CommonSetupSteps$2.handleInput(CommonSetupSteps.java:82)
[22:19:09 WARN]:        at com.plotsquared.core.setup.SetupProcess.handleInput(SetupProcess.java:47)
[22:19:09 WARN]:        at com.plotsquared.core.command.Setup.onCommand(Setup.java:101)
[22:19:09 WARN]:        at com.plotsquared.core.command.SubCommand.execute(SubCommand.java:50)
[22:19:09 WARN]:        at com.plotsquared.core.command.Command.execute(Command.java:358)
[22:19:09 WARN]:        at com.plotsquared.core.command.MainCommand.execute(MainCommand.java:305)
[22:19:09 WARN]:        at com.plotsquared.core.command.MainCommand.onCommand(MainCommand.java:180)
[22:19:09 WARN]:        at com.plotsquared.bukkit.BukkitCommand.onCommand(BukkitCommand.java:54)
[22:19:09 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:19:09 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169)
[22:19:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:773)
[22:19:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:757)
[22:19:09 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:367)
[22:19:09 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:339)
[22:19:09 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1003)
[22:19:09 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:818)
[22:19:09 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
[22:19:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:19:09 INFO]: [P2] An error occurred: Unable to provision, see the following errors:
[22:19:09 INFO]: 
[22:19:09 INFO]: 1) [Guice/NullInjectedIntoNonNullable]: null returned by binding at HybridPlotWorldFactory.create()
[22:19:09 INFO]:  but the 2nd parameter of HybridPlotWorld.<init>(HybridPlotWorld.java:101) is not @Nullable
[22:19:09 INFO]:   at HybridPlotWorldFactory.create(HybridPlotWorldFactory.java:1)
[22:19:09 INFO]:   at HybridPlotWorld.<init>(HybridPlotWorld.java:101)
[22:19:09 INFO]:       \_ for 2nd parameter
[22:19:09 INFO]:   while locating HybridPlotWorld annotated with @UniqueAnnotations$Internal(1)
[22:19:09 INFO]: 
[22:19:09 INFO]: Learn more:
[22:19:09 INFO]:   https://github.com/google/guice/wiki/NULL_INJECTED_INTO_NON_NULLABLE
[22:19:09 INFO]: 
[22:19:09 INFO]: 1 error
[22:19:09 INFO]: 
[22:19:09 INFO]: ======================
[22:19:09 INFO]: Full classname legend:
[22:19:09 INFO]: ======================
[22:19:09 INFO]: HybridPlotWorld:            "com.plotsquared.core.generator.HybridPlotWorld"
[22:19:09 INFO]: HybridPlotWorldFactory:     "com.plotsquared.core.inject.factory.HybridPlotWorldFactory"
[22:19:09 INFO]: UniqueAnnotations$Internal: "com.plotsquared.google.internal.UniqueAnnotations$Internal"
[22:19:09 INFO]: ========================
[22:19:09 INFO]: End of classname legend:
[22:19:09 INFO]: ========================
[22:19:09 INFO]: 

### To Reproduce

see error

### Expected behaviour

i cant create a plot world

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a24a265f4fec41b3a40762dada9071a8

### PlotSquared Version

PlotSquared v6 6.9.4

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by SirYwell** [comment]
You are using an unsupported server platform.
