### ISSUE TITLE
entity tile error

### ISSUE THREAD

**Issue by Wastinqs** [IntellectualSites/PlotSquared#3901]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

```
31.12 18:39:20 [Server] WARN IllegalStateException attempting to populate tile entity into the world at location 110,51,109. Possibly on <=1.17.1, switching to secondary method.
31.12 18:39:20 [Server] INFO java.lang.IllegalStateException: The blockState must be placed to call this method
31.12 18:39:20 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.requirePlaced(CraftBlockState.java:324) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:187) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:24) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at com.plotsquared.bukkit.queue.LimitedRegionWrapperQueue.setBlock(LimitedRegionWrapperQueue.java:72) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 18:39:20 [Server] INFO at com.plotsquared.core.queue.DelegateQueueCoordinator.setBlock(DelegateQueueCoordinator.java:87) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 18:39:20 [Server] INFO at com.plotsquared.core.queue.ScopedQueueCoordinator.setBlock(ScopedQueueCoordinator.java:89) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 18:39:20 [Server] INFO at com.plotsquared.core.generator.HybridGen.placeSchem(HybridGen.java:81) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 18:39:20 [Server] INFO at com.plotsquared.core.generator.HybridGen.populateChunk(HybridGen.java:316) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 18:39:20 [Server] INFO at com.plotsquared.bukkit.generator.BlockStatePopulator.populate(BlockStatePopulator.java:84) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 18:39:20 [Server] INFO at net.minecraft.world.level.chunk.ChunkGenerator.addDecorations(ChunkGenerator.java:274) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.generator.CustomChunkGenerator.applyBiomeDecoration(CustomChunkGenerator.java:272) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$10(ChunkStatus.java:93) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:212) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$38(ChunkMap.java:1326) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$40(ChunkMap.java:1324) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
31.12 18:39:20 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
31.12 18:39:20 [Server] INFO at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[app:?]
31.12 18:39:20 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91) ~[app:?]
31.12 18:39:20 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146) ~[app:?]
31.12 18:39:20 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[app:?]
31.12 18:39:20 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
31.12 18:39:20 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
31.12 18:39:20 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
31.12 18:39:20 [Server] WARN IllegalStateException attempting to populate tile entity into the world at location 110,53,110. Possibly on <=1.17.1, switching to secondary method.
31.12 18:39:20 [Server] INFO java.lang.IllegalStateException: The blockState must be placed to call this method
31.12 18:39:20 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.requirePlaced(CraftBlockState.java:324) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:187) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:24) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at com.plotsquared.bukkit.queue.LimitedRegionWrapperQueue.setBlock(LimitedRegionWrapperQueue.java:72) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 18:39:20 [Server] INFO at com.plotsquared.core.queue.DelegateQueueCoordinator.setBlock(DelegateQueueCoordinator.java:87) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 18:39:20 [Server] INFO at com.plotsquared.core.queue.ScopedQueueCoordinator.setBlock(ScopedQueueCoordinator.java:89) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 18:39:20 [Server] INFO at com.plotsquared.core.generator.HybridGen.placeSchem(HybridGen.java:81) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 18:39:20 [Server] INFO at com.plotsquared.core.generator.HybridGen.populateChunk(HybridGen.java:316) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 18:39:20 [Server] INFO at com.plotsquared.bukkit.generator.BlockStatePopulator.populate(BlockStatePopulator.java:84) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 18:39:20 [Server] INFO at net.minecraft.world.level.chunk.ChunkGenerator.addDecorations(ChunkGenerator.java:274) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.generator.CustomChunkGenerator.applyBiomeDecoration(CustomChunkGenerator.java:272) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$10(ChunkStatus.java:93) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:212) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$38(ChunkMap.java:1326) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$40(ChunkMap.java:1324) ~[patched_1.17.1.jar:git-Paper-411]
31.12 18:39:20 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
31.12 18:39:20 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
31.12 18:39:20 [Server] INFO at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[app:?]
31.12 18:39:20 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91) ~[app:?]
31.12 18:39:20 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146) ~[app:?]
31.12 18:39:20 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[app:?]
31.12 18:39:20 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
31.12 18:39:20 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
31.12 18:39:20 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
31.12 18:39:48 [Server] INFO Fetching all due players...
```

Just when I generated a new plot world with a template. Now when ever I run into a new chunk this error occures. How to fix it?

### To Reproduce

I've put the .template files into the templates directory and the world and the schematics perfectly loaded up. I even have the feeling that everything works but I'm still unsure what to do about the console error, since its really spamming me out.

### Expected behaviour

Not throwing errors.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f335e6794bb0423cb4a3c24ba9f1e7ec

### PlotSquared Version

6.10.5 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
I believe this is tracked by IntellectualSites/FastAsyncWorldEdit#1371
