### ISSUE TITLE
issue column 'flags' not found

### ISSUE THREAD

**Issue by Wastinqs** [IntellectualSites/PlotSquared#3902]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

```
31.12 22:25:14 [Server] INFO java.sql.SQLException: Column 'flags' not found.
31.12 22:25:14 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:575) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at com.mysql.cj.jdbc.result.ResultSetImpl.getString(ResultSetImpl.java:882) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at com.plotsquared.core.database.SQLManager.convertFlags(SQLManager.java:1714) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 22:25:14 [Server] INFO at com.plotsquared.bukkit.BukkitPlatform.onEnable(BukkitPlatform.java:317) ~[PlotSquared-Bukkit-6.10.5-Premium.jar:?]
31.12 22:25:14 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
31.12 22:25:14 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### To Reproduce

I just restarted my server.

### Expected behaviour

no errors.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f1a76d739c0740b1960d26945e54cfc4

### PlotSquared Version

6.10.5 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Please attach your full `latest.log`: https://gist.github.com/

**Comment by NotMyFault** [comment]
No response, closing.
