### ISSUE TITLE
[v7] `/plot list all` errors if a plot with `server-plot` flag set is part of the output

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3910]
![Screenshot 2023-01-08 at 13 09 24](https://user-images.githubusercontent.com/13383509/211195267-395a3aa3-bf19-42b4-bb68-a24e2c640280.png)

```
[13:08:47 INFO]: NotMyFault issued server command: /p list all
[13:08:47 WARN]: java.lang.IllegalArgumentException: Tag name must match pattern [!?#]?[a-z0-9_-]*, was info.server
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.configuration.adventure.text.minimessage.internal.TagInternals.assertValidTagName(TagInternals.java:53)
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.configuration.adventure.text.minimessage.tag.resolver.TagResolver.resolver(TagResolver.java:95)
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.ListCmd$1.run(ListCmd.java:468)
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.ListCmd$1.run(ListCmd.java:417)
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.Command.paginate(Command.java:275)
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.ListCmd.displayPlots(ListCmd.java:417)
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.ListCmd.lambda$onCommand$0(ListCmd.java:190)
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.ListCmd.onCommand(ListCmd.java:282)
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.SubCommand.execute(SubCommand.java:50)
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.Command.execute(Command.java:375)
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.MainCommand.execute(MainCommand.java:306)
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.MainCommand.onCommand(MainCommand.java:181)
[13:08:47 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.bukkit.BukkitCommand.onCommand(BukkitCommand.java:49)
[13:08:47 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[13:08:47 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[13:08:47 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929)
[13:08:47 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[13:08:47 WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[13:08:47 WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:313)
[13:08:47 WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:297)
[13:08:47 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
[13:08:47 WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[13:08:47 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[13:08:47 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[13:08:47 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:08:47 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:08:47 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:08:47 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[13:08:47 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[13:08:47 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:08:47 WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[13:08:47 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[13:08:47 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:08:47 WARN]: 	at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[13:08:47 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[13:08:47 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:08:47 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
> 
```

**Comment by NotMyFault** [comment]
After checking my DB, I have a plot owned by `00000001-0001-0003-0003-000000000007`, I'd assume that's what we assign server plots, hence it returns `info.server` as key.
