### ISSUE TITLE
Unable to create single plot worlds on 1.19.3

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3940]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

I'm unable to create a single plot world using the build in generator.

### To Reproduce

[09:15:22] [Server thread/INFO]: NotMyFault issued server command: /plot setup
[09:15:26] [Server thread/INFO]: NotMyFault issued server command: /plot setup PlotSquared:single
[09:15:31] [Server thread/INFO]: NotMyFault issued server command: /plot setup normal
[09:15:37] [Server thread/INFO]: NotMyFault issued server command: /plot setup false
[09:15:42] [Server thread/INFO]: NotMyFault issued server command: /plot setup flatworld

### Expected behaviour

The world should be generated as expected.

### Error log (if applicable)

https://gist.github.com/NotMyFault/5c68ef0f84e8a3bbaade6cb85b6ed689

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/06e630d0dba04096bd9c3bfcf6df5d0d

### PlotSquared Version

6.10.9

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Loading in 1.20 using b7, yields:
```
[10:08:51 WARN]: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_20_R1.CraftChunk.getHandle()
[10:08:51 WARN]: 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2772)
[10:08:51 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.util.ReflectionUtils$RefClass.getMethod(ReflectionUtils.java:130)
[10:08:51 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.bukkit.listener.SingleWorldListener.<init>(SingleWorldListener.java:46)
[10:08:51 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.bukkit.inject.BukkitModule.configure(BukkitModule.java:114)
[10:08:51 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.AbstractModule.configure(AbstractModule.java:64)
[10:08:51 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.spi.Elements$RecordingBinder.install(Elements.java:426)
[10:08:51 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.spi.Elements.getElements(Elements.java:113)
[10:08:51 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.internal.InjectorShell$Builder.build(InjectorShell.java:160)
[10:08:51 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
[10:08:51 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.Guice.createInjector(Guice.java:87)
[10:08:51 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.Guice.createInjector(Guice.java:78)
[10:08:51 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.bukkit.BukkitPlatform.onEnable(BukkitPlatform.java:288)
[10:08:51 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[10:08:51 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[10:08:51 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[10:08:51 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[10:08:51 WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:562)
[10:08:51 WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:473)
[10:08:51 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
[10:08:51 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[10:08:51 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[10:08:51 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
```
and
```
[10:08:52 WARN]: com.plotsquared.google.ProvisionException: Unable to provision, see the following errors:
[10:08:52 WARN]: 
[10:08:52 WARN]: 1) [Guice/ErrorInjectingConstructor]: NoSuchMethodException: org.bukkit.craftbukkit.v1_20_R1.CraftChunk.getHandle()
[10:08:52 WARN]:   at SingleWorldListener.<init>(SingleWorldListener.java:44)
[10:08:52 WARN]:   while locating SingleWorldListener
[10:08:52 WARN]: 
[10:08:52 WARN]: Learn more:
[10:08:52 WARN]:   https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
[10:08:52 WARN]: 
[10:08:52 WARN]: 1 error
[10:08:52 WARN]: 
[10:08:52 WARN]: ======================
[10:08:52 WARN]: Full classname legend:
[10:08:52 WARN]: ======================
[10:08:52 WARN]: SingleWorldListener:   "com.plotsquared.bukkit.listener.SingleWorldListener"
[10:08:52 WARN]: ========================
[10:08:52 WARN]: End of classname legend:
[10:08:52 WARN]: ========================
[10:08:52 WARN]: 
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.internal.InjectorImpl$1.get(InjectorImpl.java:1151)
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.internal.InjectorImpl.getInstance(InjectorImpl.java:1186)
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.bukkit.BukkitPlatform.onEnable(BukkitPlatform.java:555)
[10:08:52 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[10:08:52 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[10:08:52 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[10:08:52 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[10:08:52 WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:562)
[10:08:52 WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:473)
[10:08:52 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
[10:08:52 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[10:08:52 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[10:08:52 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[10:08:52 WARN]: Caused by: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_20_R1.CraftChunk.getHandle()
[10:08:52 WARN]: 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2772)
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.util.ReflectionUtils$RefClass.getMethod(ReflectionUtils.java:130)
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.bukkit.listener.SingleWorldListener.<init>(SingleWorldListener.java:46)
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.bukkit.listener.SingleWorldListener$$FastClassByGuice$$305278.GUICE$TRAMPOLINE(<generated>)
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.bukkit.listener.SingleWorldListener$$FastClassByGuice$$305278.apply(<generated>)
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
[10:08:52 WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.google.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
[10:08:52 WARN]: 	... 12 more
```
when the `worlds` is set to true, without creating any world at all.
