### ISSUE TITLE
Error on /p2 reload

### ISSUE THREAD

**Issue by JasonHorkles** [IntellectualSites/PlotSquared#4064]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

When using `/p2 reload`, a bunch of errors are thrown into console. It may be linked to the chunk processor but I can't say for sure 

### To Reproduce

1. Run `/p2 reload` (potentially with the chunk processor enabled)
2. Move around so chunks unload
3. See the errors in console

### Expected behaviour

There shouldn't be any errors

### Error log (if applicable)

https://paste.gg/p/JasonHorkles/c2a192877982488cb41ca23064cf583c

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/490722ff2c904438a17407ebbe8efaa9

### PlotSquared Version

6.11.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
There are no error in the debug paste

**Comment by JasonHorkles** [comment]
That's why there's an error log link...

**Comment by JasonHorkles** [comment]
Looks like this guy is null for some reason https://github.com/IntellectualSites/PlotSquared/blob/444ccda807106dd89a0dee2ba44654e095fccd16/Bukkit/src/main/java/com/plotsquared/bukkit/listener/ChunkListener.java#LL170C8-L170C63

**Comment by JasonHorkles** [comment]
This seems to be happening again:
```
Could not pass event ChunkUnloadEvent to PlotSquared v7.5.4-Premium
java.lang.NullPointerException: Cannot invoke "com.plotsquared.core.util.ReflectionUtils$RefMethod.of(Object)" because "this.methodGetHandleChunk" is null
        at PlotSquared.jar/com.plotsquared.bukkit.listener.ChunkListener.unloadChunk(ChunkListener.java:179) ~[PlotSquared.jar:?]
        at PlotSquared.jar/com.plotsquared.bukkit.listener.ChunkListener.onChunkUnload(ChunkListener.java:249) ~[PlotSquared.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.7-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:71) ~[paper-api-1.21.7-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.7-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk.unloadCallback(LevelChunk.java:680) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at ca.spottedleaf.moonrise.paper.util.BaseChunkSystemHooks.onChunkNotBorder(BaseChunkSystemHooks.java:108) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1311) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1497) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1462) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:922) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at net.minecraft.world.level.TicketStorage.purgeStaleTickets(TicketStorage.java:254) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:492) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:770) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1530) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1252) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.7.jar:1.21.7-17-b4466ec]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

https://athion.net/ISPaster/paste/view/35e06e15deee43f0b71939283c4a56fe
