### ISSUE TITLE
P7 exception error during startup (on update checker?)

### ISSUE THREAD

**Issue by mrfloris** [IntellectualSites/PlotSquared#4079]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

I noticed this error during startup, on the first run of p7 with fawe 7 for p7 on paper 1.20.1 build 22, using p6 1.19.4 world. 
```
[23:31:59 INFO]: [com.fastasyncworldedit.bukkit.FaweBukkit] Plugin 'PlotSquared' v7 found. Using it now.
[23:31:59 WARN]: [PlotSquared] Plugin PlotSquared v7.0.0-RC.1-Premium generated an exception while executing task 35
java.lang.NumberFormatException: For input string: "0 RC"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:665) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:781) ~[?:?]
	at com.plotsquared.core.PlotVersion.isLaterVersion(PlotVersion.java:126) ~[plotsquared-bukkit-7.0.0-RC.1-Premium.jar:?]
	at com.plotsquared.bukkit.util.UpdateUtility.lambda$updateChecker$0(UpdateUtility.java:75) ~[plotsquared-bukkit-7.0.0-RC.1-Premium.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-22]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-22]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

### To Reproduce

'be my server', with p6 world on 1.19.4, upgrading to 1.20.1, get spigot rc1 p7 jar and jenkins fawe7 for p7 jar, and start the server.

### Expected behaviour

i expect no errors, .. sorry, never know what to write here.

### Screenshots / Videos

<img width="1401" alt="Screen-Shot 2023-06-15 at 23 42 19" src="https://github.com/IntellectualSites/PlotSquared/assets/28841349/0f97ccb9-3b55-4879-af05-8702ede63b15">

### Error log (if applicable)

https://paste.md-5.net/ecesikegig.php

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fbd0c0a23ca243f29a9a90945e6e0beb

### PlotSquared Version

PlotSquared version 7.0.0-RC.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I've tried my best to read and understand the changelog and go through it all in order to make sure I can upgrade properly. I have no idea what I might be doing wrong. If it's not a bug, then please tell me what I forgot to do.

**Comment by NotMyFault** [comment]
This can be ignored, the current version pattern isn't made for RCs. They'll be gone once a stable release drops.

**Comment by mrfloris** [comment]
I see this went from Not-Planned to Fixed; https://www.spigotmc.org/resources/plotsquared-v6.77506/update?update=505548

`- The update checker does no longer throw an exception caused by "RC"`

**Comment by NotMyFault** [comment]
> I see this went from Not-Planned to Fixed; https://www.spigotmc.org/resources/plotsquared-v6.77506/update?update=505548
> 
> `- The update checker does no longer throw an exception caused by "RC"`

Not actually fixed, I just disabled it rather than fixing it. Will be re-enabled once released to GA.

**Comment by mrfloris** [comment]
> Not actually fixed, I just disabled it rather than fixing it. Will be re-enabled once released to GA.

Thank you for the clarification.
