### ISSUE TITLE
Plugin startup warning

### ISSUE THREAD

**Issue by aml2023529** [IntellectualSites/PlotSquared#4082]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

I'm a newbie I don't know what to do

### To Reproduce

[12:26:00 WARN]: [PlotSquared] Plugin PlotSquared v7.0.0-RC.1-Premium generated an exception while executing task 33
java.lang.NumberFormatException: For input string: "0 RC"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:665) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:781) ~[?:?]
        at com.plotsquared.core.PlotVersion.isLaterVersion(PlotVersion.java:126) ~[[地皮]plotsquared-bukkit-7.0.0-RC.1-Premium.jar:?]
        at com.plotsquared.bukkit.util.UpdateUtility.lambda$updateChecker$0(UpdateUtility.java:75) ~[[地皮]plotsquared-bukkit-7.0.0-RC.1-Premium.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-39]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-39]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[12:26:03 INFO]: [Vault] No new version available
[12:26:04 INFO]: [Matrix] Premium license detected, enabling premium features.
[12:26:04 INFO]: [Matrix] Successfully fetched your license.

### Expected behaviour

I don't know how I should solve the plugin download is complete into the load he warned me

### Screenshots / Videos

![QQ截图20230620123432](https://github.com/IntellectualSites/PlotSquared/assets/134866994/466c06eb-9cb0-4570-9564-7bda255c96aa)

### Error log (if applicable)

[12:26:00 WARN]: [PlotSquared] Plugin PlotSquared v7.0.0-RC.1-Premium generated an exception while executing task 33 java.lang.NumberFormatException: For input string: "0 RC"         at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]         at java.lang.Integer.parseInt(Integer.java:665) ~[?:?]         at java.lang.Integer.parseInt(Integer.java:781) ~[?:?]         at com.plotsquared.core.PlotVersion.isLaterVersion(PlotVersion.java:126) ~[[地皮]plotsquared-bukkit-7.0.0-RC.1-Premium.jar:?]         at com.plotsquared.bukkit.util.UpdateUtility.lambda$updateChecker$0(UpdateUtility.java:75) ~[[地皮]plotsquared-bukkit-7.0.0-RC.1-Premium.jar:?]         at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-39]         at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-39]         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]         at java.lang.Thread.run(Thread.java:1623) ~[?:?]

### Plot Debugpaste

> plot debugpaste [12:33:07 INFO]: 跳过 Multiverse多世界插件的 worlds.yml ,因为它没有被使用 [12:33:11 INFO]: [P2] 上传了完整的debug调试报告至: https://athion.net/ISPaster/paste/view/7818a1cd74234c948947c38c12d5cc06

### PlotSquared Version

> version PlotSquared [12:32:37 INFO]: PlotSquared version 7.0.0-RC.1-Premium [12:32:37 INFO]: Easy, yet powerful Plot World generation and management. [12:32:37 INFO]: Website: https://www.spigotmc.org/resources/77506/ [12:32:37 INFO]: Authors: Citymonstret, Empire92, MattBDev, dordsor21, NotMyFault and SirYwell >

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

![QQ截图20230620123432](https://github.com/IntellectualSites/PlotSquared/assets/134866994/690ddd2b-b9f1-4be6-8dc2-ae8185ad2373)

**Comment by mrfloris** [comment]
Basically duplicate of https://github.com/IntellectualSites/PlotSquared/issues/4079
