### ISSUE TITLE
Player enters plot

### ISSUE THREAD

**Issue by Insom96** [IntellectualSites/PlotSquared#4087]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Bug appears after a player uses /p v <name>

### To Reproduce

Just do /p v <name>

### Expected behaviour

No bug

### Error log (if applicable)

[19:15:58] [Server thread/ERROR]: [com.google.common.eventbus.EventBus.PlotSquaredEvents] Exception thrown by subscriber method onPlotEnter(com.plotsquared.core.events.PlayerEnterPlotEvent) on subscriber de.worldslegacy.citybuild.system.systems.perks.PerksListener@731aff89 when dispatching event: com.plotsquared.core.events.PlayerEnterPlotEvent@3fe36f16 java.lang.IllegalStateException: zip file closed 	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?] 	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?] 	at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?] 	at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 	at de.worldslegacy.citybuild.system.systems.perks.FlyPerk.update(FlyPerk.java:66) ~[CityBuild.jar:?] 	at de.worldslegacy.citybuild.system.systems.perks.PerksListener.onPlotEnter(PerksListener.java:316) ~[CityBuild.jar:?] 	at jdk.internal.reflect.GeneratedMethodAccessor197.invoke(Unknown Source) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85) ~[guava-31.1-jre.jar:?] 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142) ~[guava-31.1-jre.jar:?] 	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71) ~[guava-31.1-jre.jar:?] 	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-31.1-jre.jar:?] 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68) ~[guava-31.1-jre.jar:?] 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:109) ~[guava-31.1-jre.jar:?] 	at com.google.common.eventbus.EventBus.post(EventBus.java:267) ~[guava-31.1-jre.jar:?] 	at com.plotsquared.core.util.EventDispatcher.callEvent(EventDispatcher.java:121) ~[plotsquared-bukkit-7.0.0-RC.1-Premium.jar:?] 	at com.plotsquared.core.util.EventDispatcher.callEntry(EventDispatcher.java:238) ~[plotsquared-bukkit-7.0.0-RC.1-Premium.jar:?] 	at com.plotsquared.core.listener.PlotListener.plotEntry(PlotListener.java:171) ~[plotsquared-bukkit-7.0.0-RC.1-Premium.jar:?] 	at com.plotsquared.bukkit.listener.PlayerEventListener.playerMove(PlayerEventListener.java:597) ~[plotsquared-bukkit-7.0.0-RC.1-Premium.jar:?] 	at com.plotsquared.bukkit.listener.PlayerEventListener.onTeleport(PlayerEventListener.java:469) ~[plotsquared-bukkit-7.0.0-RC.1-Premium.jar:?] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor38.execute(Unknown Source) ~[?:?] 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-45] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?] 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-45] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-45] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?] 	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1347) ~[paper-1.20.1.jar:git-Paper-45] 	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1245) ~[paper-1.20.1.jar:git-Paper-45] 	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftEntity.lambda$teleportAsync$1(CraftEntity.java:1331) ~[paper-1.20.1.jar:git-Paper-45] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-45] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-45] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-45] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-45] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-45] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-45] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-45] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-45] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Plot Debugpaste

g

### PlotSquared Version

7.0.0 Release Candidate 1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
> de.worldslegacy.citybuild.system.systems.perks.FlyPerk.update(FlyPerk.java:66) ~[CityBuild.jar:?] at de.worldslegacy.citybuild.system.systems.perks.PerksListener.onPlotEnter(PerksListener.java:316) ~[CityBuild.jar:?] at

This plugin needs to adapt v7 changes. Not something we can control.
A more profound analysis isn't possible without a debugpaste.
