### ISSUE TITLE
Generation problems with road height / Schematic generation

### ISSUE THREAD

**Issue by iCrashMix0** [IntellectualSites/PlotSquared#4108]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

I have performed Schematic generation setup and created Custom road and it turns out that the road generation is generated in Wrong height. Take a look at the video: https://youtu.be/p6bMsbihl-s

### To Reproduce

-

### Expected behaviour

-

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fea5a459a7d94b0d9556b46225e11666

### PlotSquared Version

PlotSquared 7.0.0-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
You have `paste-road-on-top` set to `false` in settings.yml. Did you create the road schematic with `/plot createroadschematic` with paste on top set to true or false?

**Comment by iCrashMix0** [comment]
I first ran Schematic generation setup and set 'paste-road-on-top' to 'false' and then I created road.

**Comment by iCrashMix0** [comment]
I just tested again and it doesn't matter if I have 'paste-road-on-top' set to 'false' or 'true' or if I entered /plot createroadschematic before or after, because it gets the same result on all directions as you can see in the video.

**Comment by dordsor21** [comment]
Createroadschematic should always be called after changing any settings. You should also always restart the server or run `/ps reload` before creating road schematics. I think it likely #4102 will have fixed this

**Comment by iCrashMix0** [comment]
Have they tried themselves? So for me it does not work I have tried so: https://youtu.be/lY_iuxYXKmk

**Comment by iCrashMix0** [comment]
I tried plot first and then street or the other way around and whether I set before or after in settings from paste-on-top: and always ran /ps reload did nothing in all directions. It always came the same result.

**Comment by OneLiteFeather** [comment]
I know that is the plot schematic, but I might thought this was not considered to be a problem yet, so let's write about this:

`PlotSquared/HybridPlotWorld]` - plot schematic: plugins\PlotSquared\schematics\GEN_ROAD_SCHEMATIC\Test7165783\plot.schem
[00:57:03] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 384
[00:57:03] [Server thread/WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.generator.HybridPlotWorld.addOverlayBlock(HybridPlotWorld.java:503)
[00:57:03] [Server thread/WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.generator.HybridPlotWorld.setupSchematics(HybridPlotWorld.java:414)
[00:57:03] [Server thread/WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.generator.HybridPlotWorld.loadConfiguration(HybridPlotWorld.java:176)
[00:57:03] [Server thread/WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.plot.PlotArea.loadDefaultConfiguration(PlotArea.java:436)
[00:57:03] [Server thread/WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.Reload.lambda$onCommand$0(Reload.java:76)
[00:57:03] [Server thread/WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.plot.world.PlotAreaManager.forEachPlotArea(PlotAreaManager.java:223)
[00:57:03] [Server thread/WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.Reload.onCommand(Reload.java:68)
[00:57:03] [Server thread/WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.SubCommand.execute(SubCommand.java:50)
[00:57:03] [Server thread/WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.Command.execute(Command.java:374)
[00:57:03] [Server thread/WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.MainCommand.execute(MainCommand.java:305)
[00:57:03] [Server thread/WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.command.MainCommand.onCommand(MainCommand.java:180)
[00:57:03] [Server thread/WARN]: 	at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.bukkit.BukkitCommand.onCommand(BukkitCommand.java:54)
[00:57:03] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:57:03] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[00:57:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1003)
[00:57:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:966)
[00:57:03] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:501)
[00:57:03] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:448)
[00:57:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[00:57:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[00:57:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[00:57:03] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)`

Do you have a picture how the road and the plot schematic should look like? I saw the video but we don't have the schematic as a picture, it might help understanding what is going on as well.

**Comment by iCrashMix0** [comment]
![image](https://github.com/IntellectualSites/PlotSquared/assets/110557043/0d52e301-8260-47f9-9952-076610feefaa)

**Comment by iCrashMix0** [comment]
So I didn't get that with the error up there. I have checked when creating if there could be any errors in the console, because have not discovered any yet.

**Comment by OneLiteFeather** [comment]
Can we by chance add a unit test for the plot height; this case (and maybe more where it might be useful) and look where it can fail @dordsor21 ?
I am not really sure if we can reproduce it in the wild, my imagination of what went wrong is limited right now.

What do you think we can do next?

**Comment by iCrashMix0** [comment]
> Can we by chance add a unit test for the plot height; this case (and maybe more where it might be useful) and look where it can fail @dordsor21 ? I am not really sure if we can reproduce it in the wild, my imagination of what went wrong is limited right now.
> 
> What do you think we can do next?

Is that meant for me?

**Comment by OneLiteFeather** [comment]
> 

not directly, it's for the maintainer I pinged but it would help if we know how to adress what happened and fix it if it is fixable.

**Comment by dordsor21** [comment]
Forgot to link this i  #4113
