### ISSUE TITLE
Failed to parse flag 'mob-cap' error upon 1.20 upgrade

### ISSUE THREAD

**Issue by DaMarine** [IntellectualSites/PlotSquared#4119]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Upon upgrading our servers to 1.20, we're now seeing the following errors in the console: 
```[12:40:41 WARN]: com.plotsquared.core.plot.flag.FlagParseException: Failed to parse flag of type 'mob-cap'. Value '-2147483619' was not accepted.
[12:40:41 WARN]:        at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.plot.flag.types.NumberFlag.parse(NumberFlag.java:50)
[12:40:41 WARN]:        at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.database.SQLManager.getPlots(SQLManager.java:2041)
[12:40:41 WARN]:        at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.database.DBFunc.getPlots(DBFunc.java:320)
[12:40:41 WARN]:        at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.core.PlotSquared.setupDatabase(PlotSquared.java:1311)
[12:40:41 WARN]:        at plotsquared-bukkit-7.0.0-SNAPSHOT.jar//com.plotsquared.bukkit.BukkitPlatform.onEnable(BukkitPlatform.java:321)
[12:40:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[12:40:41 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[12:40:41 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[12:40:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[12:40:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:639)
[12:40:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:550)
[12:40:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
[12:40:41 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[12:40:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[12:40:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:40:41 ERROR]: [PlotSquared/SQLManager] Plot with ID 437 has an invalid value:
[12:40:41 ERROR]: [PlotSquared/SQLManager] Failed to parse flag 'mob-cap', value '-2147483619': com.plotsquared.core.configuration.caption.TranslatableCaption@6efb76d6```

Afaik there's no way in PlotSquared to just visit a plot by an ID, and without knowing who or what this plot corresponds to are unaware of the impact this may be having.

### To Reproduce

1. Have a server with a large number of plots/IDs
2. Update server to 1.20.1 and PlotSquared Version 7.0.0-Snapshot
3. See error in the console upon startup and shutdown and be unable to diagnose further without knowing what plot to visit.

### Expected behaviour

Expect this error to be handled correctly and the plot converted to a value that is allowed.

### Screenshots / Videos

![image](https://github.com/IntellectualSites/PlotSquared/assets/10583568/66b50380-316d-4b44-ad9e-92d6d7313bac)


### Error log (if applicable)

_No response_

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/ced5b59686f248149f065b971042ff91

### PlotSquared Version

PlotSquared Version 7.0.0-Snapshot

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

**Comment by NotMyFault** [comment]
> [12:40:41 ERROR]: [PlotSquared/SQLManager] Failed to parse flag 'mob-cap', value '-2147483619': com.plotsquared.core.configuration.caption.TranslatableCaption@6efb76d6```

-2147483619 Is an invalid value to enter, as the error tells you. Remove the value manually from your database.
