### ISSUE TITLE
[SimpleProviderStorage] Circular plugin loading

### ISSUE THREAD

**Issue by Banexplain** [IntellectualSites/PlotSquared#4129]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Hello there - the newest Build of PlotSquared v 7.0.0 RC.3 
don't let my 1.20.1 Server start.

It gives me this error:

"[05:05:16] [Server thread/ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[05:05:16] [Server thread/ERROR]: [SimpleProviderStorage] Circular load order:
[05:05:16] [Server thread/ERROR]: [SimpleProviderStorage]   PlotSquared -> Essentials -> CustomJoinAndQuitMessages -> DiscordSRV -> Multiverse-Core -> PlotSquared
[05:05:16] [Server thread/ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[05:05:16] [Server thread/ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[05:05:16] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins PlotSquared
    at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[paper-1.20.1.jar:git-Paper-100]
    at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:43) ~[paper-1.20.1.jar:git-Paper-100]
    at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-100]
    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.1.jar:git-Paper-100]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.1.jar:git-Paper-100]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-100]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-100]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]"

### To Reproduce

I only have these Plugins installed and start up the server.

PlotSquared, EssentialsX, CustomJoinAndQuitMessages, DiscordSRV, Multiverse-Core

### Expected behaviour

The Server Crashes.

### Plot Debugpaste

not possible

### PlotSquared Version

7.0.0 RC.3

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Assuming CustomJoinAndQuitMessages is https://github.com/jonagamerpro1234/CustomJoinAndQuitMessages, then that's influenced by https://github.com/jonagamerpro1234/CustomJoinAndQuitMessages/blob/f5e5378024b3cd1437835a6fde355aac136a7a09/bukkit/src/main/resources/plugin.yml#L6-L12

softdepend declares the plugin will load _after_ the one's specified, loadbefore declares the plugin will load _before_ the one's specified.
You can't add a plugin to both entries without causing damage downstream.

Best to report that to the plugin maintainer, specifying invalid loading scopes.
