### ISSUE TITLE
Beacon error spam

### ISSUE THREAD

**Issue by Woeben** [IntellectualSites/PlotSquared#4138]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Whenever players are around beacons, the console get spammed with the following error:

```
[11:50:52 ERROR]: Could not pass event BeaconEffectEvent to PlotSquared v7.0.0-rc.4-Premium
com.plotsquared.core.util.PlayerManager$NoSuchPlayerException: There is no online player with UUID '239721a8-a88d-4d46-a9e2-b1da1f8fb3b1'
        at com.plotsquared.bukkit.player.BukkitPlayerManager.getPlayer(BukkitPlayerManager.java:62) ~[plotsquared-bukkit-7.0.0-rc.4-Premium.jar:?]
        at com.plotsquared.bukkit.util.BukkitUtil.adapt(BukkitUtil.java:123) ~[plotsquared-bukkit-7.0.0-rc.4-Premium.jar:?]
        at com.plotsquared.bukkit.listener.PaperListener.onBeaconEffect(PaperListener.java:417) ~[plotsquared-bukkit-7.0.0-rc.4-Premium.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor105.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:248) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.world.level.block.entity.BeaconBlockEntity.applyEffect(BeaconBlockEntity.java:331) ~[?:?]
        at net.minecraft.world.level.block.entity.BeaconBlockEntity.applyEffects(BeaconBlockEntity.java:361) ~[?:?]
        at net.minecraft.world.level.block.entity.BeaconBlockEntity.tick(BeaconBlockEntity.java:203) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1208) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1160) ~[?:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:917) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:683) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1593) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### To Reproduce

Place a beacon.

### Expected behaviour

Expected no errors.

### Error log (if applicable)

https://paste.gg/p/anonymous/fe58ee135343479bac44b7600b19c14f

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/41e6d8964e9c4502a8db2e40de0b08a7

### PlotSquared Version

7.0.0-rc.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Could you please upload your latest.log additionally - as the debugpaste truncated the log due to the amount of errors. 

If you encounter a file limit, just truncate the exceptions yourself (but only those of the beacon, not for quitevents or other errors)

**Comment by Woeben** [comment]
[latest (2).log](https://github.com/IntellectualSites/PlotSquared/files/12313372/latest.2.log)
Trimmed it down quite a bit. These errors are super annoying..

**Comment by OneLiteFeather** [comment]
> ![image](https://user-images.githubusercontent.com/49917554/259840041-080f33a1-7a12-45dd-a2ea-f5902651bf78.png) Somehow this happened? No idea how it's caused.

As I looked into it, I found many database errors and this enabled: 
[12:03:18] [Server thread/INFO]: [PlotSquared/PlotSquared] Key: disable-beacon-effect-overflow | Value: true
Also an outdated NBT Plugin, you should update and fix the odd ones out.

Also your server is localhost and online mode and not a network? It is important because you need a good firewall and the error with the not existing players are quite weird. Maybe fixing your database errors and look for other plugins errors to fix might solve your problem.
Keep us updated! :)

**Comment by Woeben** [comment]
Hi, I fixed both the disable-beacon-effect-overflow and NBT plugin. The error is still being spammed.

Also, I'm not sure what you mean by localhost, online mode and not being in a network. The server is not on a local host, nor is it in online mode and is in a network ;). (sorry for late reply)

**Comment by OneLiteFeather** [comment]
@Woeben 
https://github.com/IntellectualSites/PlotSquared/blob/11fac3f060ed36b96a4a8ce838fcf3a2b7dcd369/Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitPlayerManager.java#L57
This is where the check fails because there is something that is a player but not a real one, I might suggest trying without WildLoaders https://github.com/BG-Software-LLC/WildLoaders/blob/c64e6b234297f54a692a985c9e3303624a251357/src/main/java/com/bgsoftware/wildloaders/nms/NMSAdapter.java#L23 as it might interfere because it is an NPC based chunk loader.

Tell us if it works without WildLoaders!

**Comment by OneLiteFeather** [comment]
I forgot to mention that the UUID in the error does not exist somehow when I searched for it. Could be an edge case

**Comment by OneLiteFeather** [comment]
Actually I was able to replicate the error with your WildLoaders Plugin as it is a beacon with a UUID. Please tell the developer to do it differently.
![grafik](https://github.com/IntellectualSites/PlotSquared/assets/77929075/ab878273-22a2-42d8-950c-8b3e921b5ec8)
It even happens on outdated versions
