### ISSUE TITLE
`/plot debug loadedchunks` fails when executed on console

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#4140]
Using `/plot debug loadedchunks` fails with the following error, when executed on console:
```
> plot debug loadedchunks
[19:36:19 INFO]: [P2] Fetching loaded chunks...
[19:36:19 WARN]: [PlotSquared] Plugin PlotSquared v7.0.0-SNAPSHOT generated an exception while executing task 32
java.lang.RuntimeException: Could not find worlds folder: ./region ? (no read access?)
	at com.plotsquared.core.util.WorldUtil.getChunkChunks(WorldUtil.java:344) ~[plotsquared-bukkit-7.0.0-SNAPSHOT.jar:?]
	at com.plotsquared.bukkit.util.BukkitUtil.getChunkChunks(BukkitUtil.java:556) ~[plotsquared-bukkit-7.0.0-SNAPSHOT.jar:?]
	at com.plotsquared.core.command.Debug.lambda$onCommand$0(Debug.java:93) ~[plotsquared-bukkit-7.0.0-SNAPSHOT.jar:?]
	at com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39) ~[plotsquared-bukkit-7.0.0-SNAPSHOT.jar:?]
	at com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44) ~[plotsquared-bukkit-7.0.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-117]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-117]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```
Using the command ingame words as intended and returns the proper results.

**Comment by dordsor21** [comment]
The command is completely wrong tbh, and the same (but correct) functionality exists in other plugins (e.g. essentials) so I suggest we simply remove the command
