### ISSUE TITLE
Could not pass event InventoryCloseEvent to PlotSquared

### ISSUE THREAD

**Issue by Dweezy750** [IntellectualSites/PlotSquared#4169]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Hi,
we just simple kick a player from a server with:  player.kickPlayer("lobby");

Server: PupurMC 1.20.1 Version 2058

This results in follwing error:

> [08:03:48] [Server thread/INFO]: FooBar is kicked by AFK-Tool.
[08:03:48] [Server thread/INFO]: FooBar lost connection: lobby
[08:03:48] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to PlotSquared v7.0.0-Premium
com.plotsquared.core.util.PlayerManager$NoSuchPlayerException: There is no online player with UUID '********-****-****-****-************'
	at com.plotsquared.bukkit.player.BukkitPlayerManager.getPlayer(BukkitPlayerManager.java:62) ~[plotsquared-bukkit-7.0.0-Premium.jar:?]
	at com.plotsquared.bukkit.util.BukkitUtil.adapt(BukkitUtil.java:123) ~[plotsquared-bukkit-7.0.0-Premium.jar:?]
	at com.plotsquared.bukkit.listener.PlayerEventListener.onInventoryClose(PlayerEventListener.java:1319) ~[plotsquared-bukkit-7.0.0-Premium.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor9.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2058]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1638) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3119) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3112) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1313) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2058]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]<

### To Reproduce

Kick a player with follwing code:
player.kickPlayer("lobby");

### Expected behaviour

No Error message :)

### Plot Debugpaste

http://write.me.ifneeded

### PlotSquared Version

PlotSquared v7.0.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Please open a valid issue with a plot debugpaste and paper. Also take sure no other plugin is interacting / influencing with your issue
