### ISSUE TITLE
Players can open doors on others plots

### ISSUE THREAD

**Issue by masterhacka** [IntellectualSites/PlotSquared#4270]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Players can visit other plots and can open any doors.

### To Reproduce

Visit a plot which you aren't owning and open a door.

### Expected behaviour

Doors should only open through the plot owners and members.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fd0d1940be1646cfa617f080f4bc66d0

### PlotSquared Version

PlotSquared-7.2.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I don't know if this has to do with this issue, but this is shown in the logs on startup:

`[11:31:34 ERROR]: [PlotSquared/SQLManager] Failed to load old flag values
java.sql.SQLException: no such column: 'flags'
        at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:51) ~[sqlite-jdbc-3.42.0.1.jar:?]
        at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:366) ~[sqlite-jdbc-3.42.0.1.jar:?]
        at com.plotsquared.core.database.SQLManager.convertFlags(SQLManager.java:1736) ~[plotsquared-bukkit-7.2.1-Premium.jar:?]
        at com.plotsquared.bukkit.BukkitPlatform.onEnable(BukkitPlatform.java:330) ~[plotsquared-bukkit-7.2.1-Premium.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]`

**Comment by PierreSchwang** [comment]
I rather feel like the issue is related to the failed database migration. From what version did you upgrade from?

**Comment by masterhacka** [comment]
v6

**Comment by masterhacka** [comment]
So I did a reset of the whole database. Now the log issue is gone. But the door issue persists in a different way. For now only Bedrock players via Geyser can open doors. But only when hitting the top part of the door. Any suggestions?

**Comment by dordsor21** [comment]
Definitely a bug in geyser or your server software. I would report to them

**Comment by masterhacka** [comment]
So it seems like there is an issue too for PlotSquared:
[https://github.com/GeyserMC/Geyser/issues/4358#issuecomment-1868276781](https://github.com/GeyserMC/Geyser/issues/4358#issuecomment-1868276781
)
