### ISSUE TITLE
Cannot invoke "org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason.name()" because the return value of "org.bukkit.entity.Entity.getEntitySpawnReason()" is null

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#4312]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

I have this error but am not sure what causes it, I thought maybe it would go away but it seems common so I thought it would be best to report it. There is a lot of spam and the error eventually just becomes "java.lang.NullPointerException" without any other info:
```
[16:09:57] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason.name()" because the return value of "org.bukkit.entity.Entity.getEntitySpawnReason()" is null
[16:09:57] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$5(BukkitPlatform.java:782)
[16:09:57] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.core.plot.world.PlotAreaManager.forEachPlotArea(PlotAreaManager.java:223)
[16:09:57] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$6(BukkitPlatform.java:772)
[16:09:57] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39)
[16:09:57] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44)
[16:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[16:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[16:09:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636)
[16:09:57] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[16:09:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1515)
[16:09:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1216)
[16:09:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[16:09:57] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[16:09:58] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason.name()" because the return value of "org.bukkit.entity.Entity.getEntitySpawnReason()" is null
[16:09:58] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$5(BukkitPlatform.java:782)
[16:09:58] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.core.plot.world.PlotAreaManager.forEachPlotArea(PlotAreaManager.java:223)
[16:09:58] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$6(BukkitPlatform.java:772)
[16:09:58] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39)
[16:09:58] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44)
[16:09:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[16:09:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[16:09:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636)
[16:09:58] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[16:09:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1515)
[16:09:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1216)
[16:09:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[16:09:58] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[16:09:59] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason.name()" because the return value of "org.bukkit.entity.Entity.getEntitySpawnReason()" is null
[16:09:59] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$5(BukkitPlatform.java:782)
[16:09:59] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.core.plot.world.PlotAreaManager.forEachPlotArea(PlotAreaManager.java:223)
[16:09:59] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$6(BukkitPlatform.java:772)
[16:09:59] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39)
[16:09:59] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44)
[16:09:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[16:09:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[16:09:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636)
[16:09:59] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[16:09:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1515)
[16:09:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1216)
[16:09:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[16:09:59] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[16:10:00] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason.name()" because the return value of "org.bukkit.entity.Entity.getEntitySpawnReason()" is null
[16:10:00] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$5(BukkitPlatform.java:782)
[16:10:00] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.core.plot.world.PlotAreaManager.forEachPlotArea(PlotAreaManager.java:223)
[16:10:00] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$6(BukkitPlatform.java:772)
[16:10:00] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39)
[16:10:00] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.2-Premium.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44)
[16:10:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[16:10:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[16:10:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636)
[16:10:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[16:10:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1515)
[16:10:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1216)
[16:10:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[16:10:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[16:10:01] [Server thread/WARN]: java.lang.NullPointerException
[16:10:02] [Server thread/WARN]: java.lang.NullPointerException
[16:10:03] [Server thread/WARN]: java.lang.NullPointerException
[16:10:04] [Server thread/WARN]: java.lang.NullPointerException
[16:10:05] [Server thread/WARN]: java.lang.NullPointerException
[16:10:06] [Server thread/WARN]: java.lang.NullPointerException
[16:10:07] [Server thread/WARN]: java.lang.NullPointerException
[16:10:08] [Server thread/WARN]: java.lang.NullPointerException
[16:10:09] [Server thread/WARN]: java.lang.NullPointerException
[16:10:10] [Server thread/WARN]: java.lang.NullPointerException
[16:10:11] [Server thread/WARN]: java.lang.NullPointerException
[16:10:12] [Server thread/WARN]: java.lang.NullPointerException
[16:10:13] [Server thread/WARN]: java.lang.NullPointerException
[16:10:14] [Server thread/WARN]: java.lang.NullPointerException
[16:10:15] [Server thread/WARN]: java.lang.NullPointerException
[16:10:16] [Server thread/WARN]: java.lang.NullPointerException
[16:10:17] [Server thread/WARN]: java.lang.NullPointerException
[16:10:18] [Server thread/WARN]: java.lang.NullPointerException
[16:10:19] [Server thread/WARN]: java.lang.NullPointerException
[16:10:20] [Server thread/WARN]: java.lang.NullPointerException
[16:10:21] [Server thread/WARN]: java.lang.NullPointerException
```

### To Reproduce

1. Not sure

### Expected behaviour

No errors in console

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/15ebe6517dd1450fb47f1cb5de036d59

### PlotSquared Version

PlotSquared (Version: PlotSquared-7.3.2-Premium)

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
This is already adressed by
#4305

**Comment by SirYwell** [comment]
#4305 addresses incompatibility with Spigot, but this is Paper.

It seems like `Entity#getEntitySpawnReason` returns null although specifying to be not null... that would be a Paper issue then I guess.

**Comment by OneLiteFeather** [comment]
Please retry without your disguise plugin

**Comment by ofunny** [comment]
Can confirm this bug in 7.3.3 on Paper 1.20.4 build 409, removing LibsDisguises what is the only disguise plugin I use on this server, did not fix the issue.

**Comment by SirYwell** [comment]
Do you have any other plugins spawning entities? Try removing them too.

**Comment by IAISI** [comment]
We're having the exact same issues on our Creative server:

```
> ver
[10:34:39 INFO]: Checking version, please wait...
[10:34:39 INFO]: This server is running Paper version git-Paper-"9e171ef" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9e171ef)
You are running the latest version
Previous version: git-Paper-"c5d168c" (MC: 1.20.4)
> ver plo
[10:34:43 INFO]: PlotSquared version 7.3.3-Premium
[10:34:43 INFO]: Easy, yet powerful Plot World generation and management.
[10:34:43 INFO]: Website: https://www.spigotmc.org/resources/77506/
[10:34:43 INFO]: Authors: Citymonstret, Empire92, MattBDev, dordsor21, NotMyFault and SirYwell
[10:34:43 INFO]: PlotSquaredPlus version 1.20
[10:34:43 INFO]: PlotSquared Plus
```

I've checked EchoPet which does spawn pets with spawn reason, also HD plugin. We're not using any disguises plugins.

I'm starting to suspect this is somehow caused by Hacked Minecraft clients spawning entities but was unable to find or replicate. Or by the fact that we use old world (generated from in 1.8 but upgraded to latest ver so the players didn't lose plots).

> Can confirm this bug in 7.3.3 on Paper 1.20.4 build 409, removing LibsDisguises what is the only disguise plugin I use on this server, did not fix the issue.

You were able to replicate without *any* other plugins? Just paper and p2?

I suspect the issue might be related to wither skulls but not sure. Couldn't really find any entities...

**Comment by ofunny** [comment]
> Do you have any other plugins spawning entities? Try removing them too.
If you wan me to test, to remove other plugins until its gone, I can to so, but not on the production server.
On the given server are no other plugins what spawn animal, but maybe some who use this event.

**Comment by PierreSchwang** [comment]
> Do you have any other plugins spawning entities? Try removing them too.

I guess even if the plugins were removed, the issue persists due to the timer task removing entities. The already spawned entities should continue having no spawn reason attached. 

The most sane approach would be handling null values and just handling those as any other entity with no CUSTOM spawn reason.

**Comment by OneLiteFeather** [comment]
> We're having the exact same issues on our Creative server:
> 
> ```
> > ver
> [10:34:39 INFO]: Checking version, please wait...
> [10:34:39 INFO]: This server is running Paper version git-Paper-"9e171ef" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9e171ef)
> You are running the latest version
> Previous version: git-Paper-"c5d168c" (MC: 1.20.4)
> > ver plo
> [10:34:43 INFO]: PlotSquared version 7.3.3-Premium
> [10:34:43 INFO]: Easy, yet powerful Plot World generation and management.
> [10:34:43 INFO]: Website: https://www.spigotmc.org/resources/77506/
> [10:34:43 INFO]: Authors: Citymonstret, Empire92, MattBDev, dordsor21, NotMyFault and SirYwell
> [10:34:43 INFO]: PlotSquaredPlus version 1.20
> [10:34:43 INFO]: PlotSquared Plus
> ```
> 
> I've checked EchoPet which does spawn pets with spawn reason, also HD plugin. We're not using any disguises plugins.
> 
> I'm starting to suspect this is somehow caused by Hacked Minecraft clients spawning entities but was unable to find or replicate. Or by the fact that we use old world (generated from in 1.8 but upgraded to latest ver so the players didn't lose plots).
> 
> > Can confirm this bug in 7.3.3 on Paper 1.20.4 build 409, removing LibsDisguises what is the only disguise plugin I use on this server, did not fix the issue.
> 
> You were able to replicate without _any_ other plugins? Just paper and p2?
> 
> I suspect the issue might be related to wither skulls but not sure. Couldn't really find any entities...

well there is something off your plotsquared version, there is no "Plotsquared Plus" in Plotsquared

**Comment by SecretlyJealous** [comment]
Unfortunately I'm not able to remove disguises and pets on my live server since they are donator perks, but updating to 7.3.3 still causes this:

debugpaste: https://athion.net/ISPaster/paste/view/c309452143db4fe5998d93b1ba40caae

```
[09:29:45] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason.name()" because the return value of "org.bukkit.entity.Entity.getEntitySpawnReason()" is null
[09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$5(BukkitPlatform.java:782)
[09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.core.plot.world.PlotAreaManager.forEachPlotArea(PlotAreaManager.java:223)
[09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$6(BukkitPlatform.java:772)
[09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39)
[09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44)
[09:29:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[09:29:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[09:29:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636)
[09:29:45] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[09:29:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1515)
[09:29:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1216)
[09:29:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[09:29:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by OneLiteFeather** [comment]
> Unfortunately I'm not able to remove disguises and pets on my live server since they are donator perks, but updating to 7.3.3 still causes this error spam:
> 
> debugpaste: https://athion.net/ISPaster/paste/view/c309452143db4fe5998d93b1ba40caae
> 
> ```
> [09:29:45] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason.name()" because the return value of "org.bukkit.entity.Entity.getEntitySpawnReason()" is null
> [09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$5(BukkitPlatform.java:782)
> [09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.core.plot.world.PlotAreaManager.forEachPlotArea(PlotAreaManager.java:223)
> [09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$6(BukkitPlatform.java:772)
> [09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39)
> [09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44)
> [09:29:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
> [09:29:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
> [09:29:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636)
> [09:29:45] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
> [09:29:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1515)
> [09:29:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1216)
> [09:29:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
> [09:29:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
> ```

can you send us a startup log? The startup is missing due to the NPE spam

**Comment by SecretlyJealous** [comment]
> > Unfortunately I'm not able to remove disguises and pets on my live server since they are donator perks, but updating to 7.3.3 still causes this error spam:
> > debugpaste: https://athion.net/ISPaster/paste/view/c309452143db4fe5998d93b1ba40caae
> > ```
> > [09:29:45] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason.name()" because the return value of "org.bukkit.entity.Entity.getEntitySpawnReason()" is null
> > [09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$5(BukkitPlatform.java:782)
> > [09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.core.plot.world.PlotAreaManager.forEachPlotArea(PlotAreaManager.java:223)
> > [09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$runEntityTask$6(BukkitPlatform.java:772)
> > [09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39)
> > [09:29:45] [Server thread/WARN]: 	at plotsquared-bukkit-7.3.3-Premium.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44)
> > [09:29:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
> > [09:29:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
> > [09:29:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636)
> > [09:29:45] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
> > [09:29:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1515)
> > [09:29:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1216)
> > [09:29:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
> > [09:29:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
> > ```
> 
> can you send us a startup log? The startup is missing due to the NPE spam

Sure
Startup log: https://pastebin.com/9g3vHRcZ
