### ISSUE TITLE
java.util.concurrent.TimeoutException (getChunkAtAsync)

### ISSUE THREAD

**Issue by IAISI** [IntellectualSites/PlotSquared#4324]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

```
[12:05:32] [Server thread/WARN]: java.util.concurrent.TimeoutException
[12:05:32] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
[12:05:32] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
[12:05:32] [Server thread/WARN]: 	at PlotSquared-Bukkit.jar//com.plotsquared.core.util.PlayerManager.getPlayerList(PlayerManager.java:141)
[12:05:32] [Server thread/WARN]: 	at PlotSquared-Bukkit.jar//com.plotsquared.core.plot.Plot.lambda$format$13(Plot.java:2789)
[12:05:32] [Server thread/WARN]: 	at PlotSquared-Bukkit.jar//com.plotsquared.bukkit.util.BukkitUtil.lambda$getBiome$3(BukkitUtil.java:227)
[12:05:32] [Server thread/WARN]: 	at PlotSquared-Bukkit.jar//com.plotsquared.bukkit.util.BukkitUtil.ensureMainThread(BukkitUtil.java:204)
[12:05:32] [Server thread/WARN]: 	at PlotSquared-Bukkit.jar//com.plotsquared.bukkit.util.BukkitUtil.lambda$ensureLoaded$0(BukkitUtil.java:195)
[12:05:32] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[12:05:32] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[12:05:32] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[12:05:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.lambda$getChunkAtAsync$15(CraftWorld.java:2445)
[12:05:32] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:05:32] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:05:32] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:05:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1456)
[12:05:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:195)
[12:05:32] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[12:05:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1433)
[12:05:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1356)
[12:05:32] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:05:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1334)
[12:05:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1223)
[12:05:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[12:05:32] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[12:05:33] [Server thread/WARN]: java.util.concurrent.TimeoutException
[12:05:33] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
[12:05:33] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
[12:05:33] [Server thread/WARN]: 	at PlotSquared-Bukkit.jar//com.plotsquared.core.util.PlayerManager.getPlayerList(PlayerManager.java:141)
[12:05:33] [Server thread/WARN]: 	at PlotSquared-Bukkit.jar//com.plotsquared.core.plot.Plot.lambda$format$13(Plot.java:2790)
[12:05:33] [Server thread/WARN]: 	at PlotSquared-Bukkit.jar//com.plotsquared.bukkit.util.BukkitUtil.lambda$getBiome$3(BukkitUtil.java:227)
[12:05:33] [Server thread/WARN]: 	at PlotSquared-Bukkit.jar//com.plotsquared.bukkit.util.BukkitUtil.ensureMainThread(BukkitUtil.java:204)
[12:05:33] [Server thread/WARN]: 	at PlotSquared-Bukkit.jar//com.plotsquared.bukkit.util.BukkitUtil.lambda$ensureLoaded$0(BukkitUtil.java:195)
[12:05:33] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[12:05:33] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[12:05:33] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[12:05:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.lambda$getChunkAtAsync$15(CraftWorld.java:2445)
[12:05:33] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:05:33] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:05:33] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:05:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1456)
[12:05:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:195)
[12:05:33] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[12:05:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1433)
[12:05:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1356)
[12:05:33] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:05:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1334)
[12:05:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1223)
[12:05:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[12:05:33] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

```

> ver
[10:58:36 INFO]: Checking version, please wait...
[10:58:36 INFO]: This server is running Paper version git-Paper-"9e171ef" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9e171ef)
You are running the latest version
Previous version: git-Paper-"c5d168c" (MC: 1.20.4)
```

### To Reproduce

Not sure, randomly seeing those exceptions.

### Expected behaviour

Not sure.

### Plot Debugpaste

Would prefer to keep it private, please DM me if needed.

### PlotSquared Version

PlotSquared version 7.3.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
we need a debugpaste here unfortunately, in the debugpaste the sensitive information is cut out for example the ip adress of players. You can create one without player messages, just restart the server and do some plotsquared related fawe operations like clearing a bigger plot. Also on your stacktrace is there a part saying "caused by" ?

**Comment by IAISI** [comment]
I can replicate on testing server tho, it would pop up kinda randomly, also there is no caused by part of exception...

**Comment by NotMyFault** [comment]
Please raise a new issue once you include clear steps to replicate the issue and a debugpaste.

**Comment by IAISI** [comment]
I don't think it's an issue since we've updated to 7.3.5, it always seemed followed by players logging on the server to TPing to their plot with /p tp

**Comment by OneLiteFeather** [comment]
there is no /p tp in plotsquared itsself, just /p v <player> and /p h, check your plugins and possibily retry without plotaddons

**Comment by OneLiteFeather** [comment]
My bad, it exists but it is not tabcompleted which is awkward. I am going to open an issue for that
