### ISSUE TITLE
Could not pass event PotionSplashEvent to PlotSquared v7.3.8-Premium

### ISSUE THREAD

**Issue by IAISI** [IntellectualSites/PlotSquared#4421]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

```
com.destroystokyo.paper.exception.ServerEventException: Could not pass event PotionSplashEvent to PlotSquared v7.3.8-Premium
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:72)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:865)
	at net.minecraft.world.entity.projectile.EntityPotion.applySplash(EntityPotion.java:235)
	at net.minecraft.world.entity.projectile.EntityPotion.splash(EntityPotion.java:141)
	at net.minecraft.world.entity.projectile.EntityPotion.a(EntityPotion.java:124)
	at net.minecraft.world.entity.projectile.IProjectile.preOnHit(IProjectile.java:202)
	at net.minecraft.world.entity.projectile.EntityProjectile.l(EntityProjectile.java:77)
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:1419)
	at net.minecraft.world.level.World.a(World.java:1576)
	at net.minecraft.server.level.WorldServer.lambda$tick$9(WorldServer.java:926)
	at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:48)
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:897)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1733)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:452)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1534)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1234)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.plotsquared.core.util.PlayerManager$NoSuchPlayerException: There is no online player with UUID 'ab9b4774-99de-3151-a151-c666c3bcaa69'
	at PlotSquared-Bukkit.jar//com.plotsquared.bukkit.player.BukkitPlayerManager.getPlayer(BukkitPlayerManager.java:62)
	at PlotSquared-Bukkit.jar//com.plotsquared.bukkit.util.BukkitUtil.adapt(BukkitUtil.java:123)
	at PlotSquared-Bukkit.jar//com.plotsquared.bukkit.util.BukkitEntityUtil.entityDamage(BukkitEntityUtil.java:157)
	at PlotSquared-Bukkit.jar//com.plotsquared.bukkit.util.BukkitEntityUtil.entityDamage(BukkitEntityUtil.java:66)
	at PlotSquared-Bukkit.jar//com.plotsquared.bukkit.listener.ProjectileEventListener.onPotionSplash(ProjectileEventListener.java:80)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor90.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:865)
	at net.minecraft.world.entity.projectile.ThrownPotion.applySplash(ThrownPotion.java:235)
	at net.minecraft.world.entity.projectile.ThrownPotion.splash(ThrownPotion.java:141)
	at net.minecraft.world.entity.projectile.ThrownPotion.onHit(ThrownPotion.java:124)
	at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:202)
	at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:77)
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1419)
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1576)
	at net.minecraft.server.level.ServerLevel.lambda$tick$9(ServerLevel.java:926)
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:48)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:897)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1733)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:452)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1534)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234)
	... 2 more
```

### To Reproduce

Unable to replicate. happens randomly on our Creative server

### Expected behaviour

Not sure.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/10fe84a3a3af48dc954d71d19090553b

### PlotSquared Version

PlotSquared version 7.3.8-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
You using a unsupported fork
