### ISSUE TITLE
bukkitWorldRef is null

### ISSUE THREAD

**Issue by 1470429149** [IntellectualSites/PlotSquared#4442]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

```
[09:16:41 ERROR]: Could not pass event PlayerNaturallySpawnCreaturesEvent to PlotSquared v7.3.9-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "java.lang.ref.WeakReference.get()" because "bukkitWorldRef" is null
        at com.plotsquared.bukkit.util.BukkitWorld.of(BukkitWorld.java:78) ~[plotsquared-bukkit-7.3.9-SNAPSHOT.jar:?]
        at com.plotsquared.bukkit.util.BukkitUtil.adapt(BukkitUtil.java:136) ~[plotsquared-bukkit-7.3.9-SNAPSHOT.jar:?]
        at com.plotsquared.bukkit.listener.PaperListener.onPlayerNaturallySpawnCreaturesEvent(PaperListener.java:271) ~[plotsquared-bukkit-7.3.9-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor95.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:567) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:488) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:868) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[09:16:41 ERROR]: Could not pass event PlayerNaturallySpawnCreaturesEvent to PlotSquared v7.3.9-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "java.lang.ref.WeakReference.get()" because "bukkitWorldRef" is null
        at com.plotsquared.bukkit.util.BukkitWorld.of(BukkitWorld.java:78) ~[plotsquared-bukkit-7.3.9-SNAPSHOT.jar:?]
        at com.plotsquared.bukkit.util.BukkitUtil.adapt(BukkitUtil.java:136) ~[plotsquared-bukkit-7.3.9-SNAPSHOT.jar:?]
        at com.plotsquared.bukkit.listener.PaperListener.onPlayerNaturallySpawnCreaturesEvent(PaperListener.java:271) ~[plotsquared-bukkit-7.3.9-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor95.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:567) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:488) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:868) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### To Reproduce

on join server

### Expected behaviour

null

### Plot Debugpaste

null

### PlotSquared Version

PlotSquared-7.3.9-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by 1470429149** [comment]
#4435 
Although the memory leak problem has been optimized, new problems have emerged
