### ISSUE TITLE
Plot debugpaste broken

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#452]
``` java
[03:50:55 WARN]: java.io.IOException: Server returned HTTP response code: 400 for URL: http://hastebin.com/documents
[03:50:55 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[03:50:55 WARN]:        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:28)
[03:50:55 WARN]:        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:53)
[03:50:55 WARN]:        at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29)
[03:50:55 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[03:50:55 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[03:50:55 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[03:50:55 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[03:50:55 WARN]:        at java.lang.Thread.run(Unknown Source)
```

I have the same error.

**Comment by Sauilitired** [comment]
Is might be the file size of the log? That's what I suspect.

**Comment by Sauilitired** [comment]
This happens when latest.log is too big to be pasted. I'll make it ignore it if it fails.
