### ISSUE TITLE
UUID caching

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#456]
``` java
[03:04:28 ERROR]: Could not pass event PlayerMoveEvent to PlotSquared v2.12.16
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:269) [spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-f94fe8f-2642f9b]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NullPointerException
        at com.intellectualcrafters.plot.util.bukkit.uuid.SQLUUIDHandler.getUUID(SQLUUIDHandler.java:491) ~[?:?]
        at com.intellectualcrafters.plot.util.bukkit.UUIDHandler.getUUID(UUIDHandler.java:113) ~[?:?]
        at com.intellectualcrafters.plot.object.BukkitPlayer.getUUID(BukkitPlayer.java:52) ~[?:?]
        at com.intellectualcrafters.plot.listeners.PlotListener.plotEntry(PlotListener.java:104) ~[?:?]
        at com.intellectualcrafters.plot.listeners.PlayerEvents.PlayerMove(PlayerEvents.java:499) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f94fe8f-2642f9b]
        ... 15 more
```
@Sauilitired

**Comment by Sauilitired** [comment]
@boy0001 This can only be null when there is no uuid wrapper s:

**Comment by boy0001** [comment]
It's not setting a wrapper then.

**Comment by Sauilitired** [comment]
It's using the same code as the other uuid handler, does that one throw errors? :3

**Comment by Sauilitired** [comment]
This has been fixed in the restructuring. @boy0001 may reopen this is there are still issues, but I am 90% sure there isn't :dancer:
