### ISSUE TITLE
Error on /plot unclaim

### ISSUE THREAD

**Issue by diecode** [IntellectualSites/PlotSquared#486]
I get this when I type on /plot unclaim

I am using the latest build #139 - PlotSquared-Bukkit.jar, Spigot 1.8.x

```
[14:08:00 WARN]: java.lang.IncompatibleClassChangeError: Found class com.intellectualcrafters.plot.object.PlotPlayer, but interface was expected
[14:08:00 WARN]:        at com.intellectualcrafters.plot.commands.Unclaim.onCommand(Unclaim.java:46)
[14:08:00 WARN]:        at com.intellectualcrafters.plot.commands.Unclaim.onCommand(Unclaim.java:34)
[14:08:00 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.handle(MainCommand.java:376)
[14:08:00 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:308)
[14:08:00 WARN]:        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:40)
[14:08:00 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:08:00 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:08:00 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[14:08:00 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[14:08:00 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[14:08:00 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[14:08:00 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[14:08:00 WARN]:        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[14:08:00 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:08:00 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:08:00 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[14:08:00 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[14:08:00 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[14:08:00 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[14:08:00 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by boy0001** [comment]
The dev builds aren't stable, and not always compiled correctly. Please refer to spigot for releases.
