### ISSUE TITLE
MySQL Exception after update

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#494]
Just updated from 2.9.something to 3.0.6 and got this in console and I'm not sure if I have to worry about ^^

```
[08:14:45] [Server thread/INFO]: BACKING UP: plot_helpers
[08:14:45] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown table 'psq_plot_helpers_tmp'
[08:14:45] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:14:45] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:14:45] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:14:45] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[08:14:45] [Server thread/WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[08:14:45] [Server thread/WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[08:14:45] [Server thread/WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[08:14:45] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[08:14:45] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[08:14:45] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[08:14:45] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[08:14:45] [Server thread/WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[08:14:45] [Server thread/WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1662)
[08:14:45] [Server thread/WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1581)
[08:14:45] [Server thread/WARN]:        at com.intellectualcrafters.plot.database.SQLManager.updateTables(SQLManager.java:887)
[08:14:45] [Server thread/WARN]:        at com.intellectualcrafters.plot.database.SQLManager.<init>(SQLManager.java:105)
[08:14:45] [Server thread/WARN]:        at com.intellectualcrafters.plot.PS.setupDatabase(PS.java:1194)
[08:14:45] [Server thread/WARN]:        at com.intellectualcrafters.plot.PS.<init>(PS.java:168)
[08:14:45] [Server thread/WARN]:        at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:116)
[08:14:45] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[08:14:45] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[08:14:45] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[08:14:45] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[08:14:45] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[08:14:45] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[08:14:45] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524)
[08:14:45] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)
[08:14:45] [Server thread/INFO]: Creating tables
```

**Comment by boy0001** [comment]
This has been fixed
