### ISSUE TITLE
BiomeGenerator - jungle

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#500]
```
[15:43:43] [Server thread/INFO]: Log1xx issued server command: /p gb jungle
[15:44:06] [Server thread/WARN]: [BiomeGenerator] Task #5333 for BiomeGenerator v3.0.3 generated an exception
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.BiomeJungle.a(SourceFile:72) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-0febdc8-880a532]
	at com.empcraft.biomes.generators.BiomeGenerator_18R3$1$1$1.run(BiomeGenerator_18R3.java:163) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-0febdc8-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-0febdc8-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:779) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-0febdc8-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-0febdc8-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-0febdc8-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-0febdc8-880a532]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

```

**Comment by Log1x** [comment]
This is still very present, and not just with Jungle.

Biome's also generate into the road slightly (mainly leaves from tree's)

**Comment by MattBDev** [comment]
Ticket closed since it is super old.
