### ISSUE TITLE
plot unlink

### ISSUE THREAD

**Issue by donbubu** [IntellectualSites/PlotSquared#501]
hi and thanks for the eco fix, but now we can't unlink plot. PlotSquared version 3.0.7 #148 and #149
The error on console is:

[20:02:17] [Server thread/WARN]: java.lang.IncompatibleClassChangeError: Found class com.intellectualcrafters.plot.object.PlotPlayer, but interface was expected
[20:02:17] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.Unlink.onCommand(Unlink.java:48)
[20:02:17] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.Unlink.onCommand(Unlink.java:34)
[20:02:17] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.handle(MainCommand.java:380)
[20:02:17] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:312)
[20:02:17] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:37)
[20:02:17] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:02:17] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[20:02:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646)
[20:02:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135)
[20:02:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970)
[20:02:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:02:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[20:02:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[20:02:17] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:02:17] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:02:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
[20:02:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718)
[20:02:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
[20:02:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
[20:02:17] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[20:02:17] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by boy0001** [comment]
The file didn't compile properly.. I'll upload to spigot soon

**Comment by donbubu** [comment]
ok and many thanks for your fast reply :)
