### ISSUE TITLE
/plot list is not listing

### ISSUE THREAD

**Issue by diecode** [IntellectualSites/PlotSquared#506]
Hi,

When I am using the ```/plot list <all | mine | etc>``` command, then it is not listing the entries only the pages.

https://gyazo.com/e6c33087d4c427ff67a868680d0375d7

I am using the latest version: 3.0.7 of PlotSquared and latest Spigot 1.8.8

```
/plot list all
[18:43:10] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/google/gson/JsonParser
[18:43:10] [Server thread/WARN]: 	at com.plotsquared.bukkit.chat.FancyMessage.<clinit>(FancyMessage.java:773)
[18:43:10] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.list.displayPlots(list.java:357)
[18:43:10] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.list.onCommand(list.java:300)
[18:43:10] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.list.onCommand(list.java:1)
[18:43:10] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.handle(MainCommand.java:380)
[18:43:10] [Server thread/WARN]: 	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:312)
[18:43:10] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:37)
[18:43:10] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:43:10] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:43:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[18:43:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[18:43:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[18:43:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[18:43:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[18:43:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[18:43:10] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:43:10] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[18:43:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
[18:43:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[18:43:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[18:43:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[18:43:10] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[18:43:10] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonParser
[18:43:10] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[18:43:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[18:43:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[18:43:10] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:43:10] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:43:10] [Server thread/WARN]: 	... 22 more
```

**Comment by boy0001** [comment]
Disable fancy chat in the settings.yml for now.

**Comment by boy0001** [comment]
Fixed
