### ISSUE TITLE
Startup error message

### ISSUE THREAD

**Issue by diecode** [IntellectualSites/PlotSquared#507]
```
[PlotSquared] Enabling PlotSquared v3.0.7
[18:42:52] [Server thread/INFO]: $1PlotSquared is now enabled
[18:42:52] [Server thread/INFO]: $3[$1P2$3] $2&6Debug Mode Enabled (Default). Edit the config to turn this off.
[18:42:52] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 2
[18:42:52] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.getServerVersion(BukkitMain.java:108)
[18:42:52] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.setupConfig(PS.java:1780)
[18:42:52] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.setupConfigs(PS.java:1822)
[18:42:52] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:164)
[18:42:52] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:123)
[18:42:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[18:42:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[18:42:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[18:42:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
[18:42:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
[18:42:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:153)
[18:42:52] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494)
[18:42:52] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[18:42:52] [Server thread/INFO]: 1.8-R0.1-SNAPSHOT
[18:42:52] [Server thread/INFO]: ( 1,8 )
```

**Comment by boy0001** [comment]
Low / no risk.
