### ISSUE TITLE
NPE at plot swap

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#512]
Plot owner and probably other stuff has not been swapped with.
Target plot was empty and unclaimed

```
[18:29:37] [Server thread/INFO]: Olaf issued server command: /plot swap 7;-1
[18:29:38] [Server thread/WARN]: java.lang.NullPointerException
[18:29:38] [Server thread/WARN]:        at com.intellectualcrafters.plot.util.MainUtil.moveData(MainUtil.java:1374)
[18:29:38] [Server thread/WARN]:        at com.intellectualcrafters.plot.util.MainUtil.swapData(MainUtil.java:1343)
[18:29:38] [Server thread/WARN]:        at com.intellectualcrafters.plot.commands.Swap.onCommand(Swap.java:124)
[18:29:38] [Server thread/WARN]:        at com.intellectualcrafters.plot.commands.Swap.onCommand(Swap.java:1)
[18:29:38] [Server thread/WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.handle(MainCommand.java:380)
[18:29:38] [Server thread/WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:312)
[18:29:38] [Server thread/WARN]:        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:37)
[18:29:38] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:29:38] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:29:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[18:29:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[18:29:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1078)
[18:29:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:237)
[18:29:38] [Server thread/WARN]:        at it.mri.mycommand.execute.DispatchCommands.ExecuteCommands(DispatchCommands.java:635)
[18:29:38] [Server thread/WARN]:        at it.mri.mycommand.execute.DispatchCommands.PerformMycmdCommands(DispatchCommands.java:514)
[18:29:38] [Server thread/WARN]:        at it.mri.mycommand.execute.DispatchCommands.ExecuteMyCommandCommands(DispatchCommands.java:202)
[18:29:38] [Server thread/WARN]:        at it.mri.mycommand.listener.PreprocessEvent.onPlayerCommandPreprocess(PreprocessEvent.java:110)
[18:29:38] [Server thread/WARN]:        at sun.reflect.GeneratedMethodAccessor409.invoke(Unknown Source)
[18:29:38] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:29:38] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[18:29:38] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[18:29:38] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:29:38] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[18:29:38] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[18:29:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[18:29:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[18:29:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:29:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:29:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[18:29:38] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:29:38] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:29:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[18:29:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
[18:29:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:29:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[18:29:38] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[18:29:38] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)
```

3.0.7

**Comment by boy0001** [comment]
TODO forward to `/plot move` if other plot is not occupied.

**Comment by EvilOlaf** [comment]
What happen is  the target plot is unclaimed but there is a building or stuff on it for any reason? Shift the risk to the person who executes the swap/move?
