### ISSUE TITLE
various invalid flags

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#515]
3.0.7

http://pastebin.com/kfZaKKqZ

**Comment by c0wg0d** [comment]
I'm getting the same bug on 3.0.8.

<pre>
[12:42:02 INFO]: Plot 7418 had an invalid flag. A fix has been attempted.
[12:42:02 INFO]: weather:CLEAR
[12:42:02 WARN]: java.lang.IllegalArgumentException: Flag value must be weather type: 'clear' or 'rain'
[12:42:02 WARN]:        at com.intellectualcrafters.plot.flag.Flag.<init>(Flag.java:48)
[12:42:02 WARN]:        at com.intellectualcrafters.plot.database.SQLManager.getPlots(SQLManager.java:1138)
[12:42:02 WARN]:        at com.intellectualcrafters.plot.database.SQLManager.validateAllPlots(SQLManager.java:2310)
[12:42:02 WARN]:        at com.intellectualcrafters.plot.database.DBFunc.validatePlots(DBFunc.java:66)
[12:42:02 WARN]:        at com.intellectualcrafters.plot.PS.disable(PS.java:1481)
[12:42:02 WARN]:        at com.plotsquared.bukkit.BukkitMain.onDisable(BukkitMain.java:129)
[12:42:02 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
[12:42:02 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
[12:42:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[12:42:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[12:42:02 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336)
[12:42:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460)
[12:42:02 WARN]:        at org.spigotmc.RestartCommand.restart(RestartCommand.java:81)
[12:42:02 WARN]:        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40)
[12:42:02 WARN]:        at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31)
[12:42:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:728)
[12:42:02 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[12:42:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[12:42:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[12:42:02 WARN]:        at java.lang.Thread.run(Thread.java:745)

</pre>

**Comment by PhanaticD** [comment]
here is output with 3.1.0

http://pastebin.com/jeDKdRWg

**Comment by c0wg0d** [comment]
I sincerely hope that bad language is never shown in game and only goes to the logs.  Otherwise I'm going to have to stop using PlotSquared.  Can't have that.

**Comment by boy0001** [comment]
@c0wg0d The bad language was from players...?

**Comment by PhanaticD** [comment]
yea lol it was from something a player set.. relax..

**Comment by c0wg0d** [comment]
My apologies.  Carry on.

**Comment by MattBDev** [comment]
Flags have been completely changed in 3.4.0. This should be fixed. If it is not, it is recommended to file a new bug report.
