### ISSUE TITLE
Can't call commit when autocommit=true

### ISSUE THREAD

**Issue by Zenexer** [IntellectualSites/PlotSquared#524]
Getting this every 10 seconds:

```
[05:01:15 WARN]: java.sql.SQLException: Can't call commit when autocommit=true
[05:01:15 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
[05:01:15 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
[05:01:15 WARN]:        at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1655)
[05:01:15 WARN]:        at com.intellectualcrafters.plot.database.SQLManager$1.run(SQLManager.java:92)
[05:01:15 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[05:01:15 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[05:01:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
[05:01:15 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[05:01:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[05:01:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[05:01:15 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

Looking at the relevant code, it's not a good idea to run commits every 10 seconds like that.  Let server owners tune consistency on their own.  The way you're doing it isn't going to be any more efficient on a properly tuned InnoDB database, and it decreases both consistency and atomicity.  Autocommit exists for a reason: either use proper transactions, or let autocommit do its job.  Note that just because autocommit is enabled doesn't necessarily mean data is going to be written to the main database files every time there's a write operation.  It's up to the server owner to adjust that.

**Comment by boy0001** [comment]
The latest version should remove the stacktrace:
https://www.spigotmc.org/resources/plotsquared.1177/download?version=38551

```Looking at the relevant code, it's not a good idea to run commits every 10 seconds like that.```
Most information is cached on the server, to reduce the reliance on the database and constant queries. There is no reason it would need to be committed more often. On shutdown, the database is also checked against the servers copy, and changes are made if necessary.

```Let server owners tune consistency on their own```
Server owners usually don't tune their database, and of those that do, it is usually for generic usage, rather than tuned for specific applications. Therefore in the majority of cases, it is ideal for the application to choose the settings for it's own connection.

```The way you're doing it isn't going to be any more efficient on a properly tuned InnoDB database, and it decreases both consistency and atomicity.```
It is more efficient in the majority of cases, I can't comment on your specific configuration.

```Autocommit exists for a reason```
Disabling it also exists for a reason. You could also say that the reload command in bukkit exists for a reason - yet existence isn't proof of good practice.

```either use proper transactions, or let autocommit do its job```
Using autocommit for every query would make things like mass changing plot flags take a very long time if you have enough plots. 

The question is really how the logic should handle these. Having "proper transactions" is an option, but requires me to explicitly state when I want to do any mass changes. This is undesirable if someone wants to write a script, or another plugin that involves such changes, as then they also need to explicitly state that they want to do some mass updates. Having updates at a consistent interval means that everything can go through the same channels without worrying about the number of changes.

It may not be considered best practice, but it does what it needs, it's faster in most cases, and means the specific database implementation doesn't need to be exposed at the API level.
