### ISSUE TITLE
Regenallroads + plot offset

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#547]
```java
[02:50:58 WARN]: [PlotSquared] Task #72747 for PlotSquared v3.1.0 generated an exception
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_51]
        at com.intellectualcrafters.plot.PS.getPlot(PS.java:1097) ~[?:?]
        at com.intellectualcrafters.plot.generator.SquarePlotManager.getPlotId(SquarePlotManager.java:154) ~[?:?]
        at com.intellectualcrafters.plot.generator.HybridUtils.regenerateRoad(HybridUtils.java:269) ~[?:?]
        at com.intellectualcrafters.plot.generator.HybridUtils$3$1$2.run(HybridUtils.java:170) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-ea179b3-6e0120a]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-ea179b3-6e0120a]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot.jar:git-Spigot-ea179b3-6e0120a]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-ea179b3-6e0120a]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-ea179b3-6e0120a]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-ea179b3-6e0120a]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by boy0001** [comment]
Fixed
