### ISSUE TITLE
/plot continue bug

### ISSUE THREAD

**Issue by diecode** [IntellectualSites/PlotSquared#553]
When I type ```/plot continue``` I get this:

```
[23:39:10 INFO]: cmd: /plot continue
[23:39:10 WARN]: java.lang.Error: Unresolved compilation problems:
        TODO cannot be resolved to a type
        Syntax error on token "plot", ; expected
        limit cannot be resolved to a type
        Syntax error on token ".", ; expected
        The method removePlotFlag(Plot, String) is undefined for the type Continue

[23:39:10 WARN]:        at com.intellectualcrafters.plot.commands.Continue.onCommand(Continue.java:68)
[23:39:10 WARN]:        at com.intellectualcrafters.plot.commands.Continue.onCommand(Continue.java:1)
[23:39:10 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.handle(MainCommand.java:448)
[23:39:10 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:333)
[23:39:10 WARN]:        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:36)
[23:39:10 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:39:10 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:39:10 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[23:39:10 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[23:39:10 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[23:39:10 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:39:10 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:39:10 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[23:39:10 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:39:10 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[23:39:10 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[23:39:10 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
[23:39:10 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[23:39:10 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[23:39:10 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[23:39:10 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by boy0001** [comment]
```
TODO cannot be resolved to a type
```
You're using a build that I hadn't fully implemented the continue command. Did I post that to spigot? Anyway, it has since been implemented.
