### ISSUE TITLE
org.apache.commons.lang.UnhandledException || java.lang.IllegalArgumentException: The permission plotsquared_user_attributes.disabletitles is already defined!

### ISSUE THREAD

**Issue by L4BORG** [IntellectualSites/PlotSquared#621]
```
[03:08:06] [Craft Scheduler Thread - 15/WARN]: Exception in thread "Craft Scheduler Thread - 15" 
[03:08:06] [Craft Scheduler Thread - 15/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.1.9 generated an exception while executing task 67
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: The permission plotsquared_user_attributes.disabletitles is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599)
	at com.plotsquared.bukkit.object.BukkitPlayer.getAttribute(BukkitPlayer.java:181)
	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:13)
	at com.plotsquared.listener.PlotListener$1.run(PlotListener.java:162)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[03:08:06] [Craft Scheduler Thread - 6/WARN]: Exception in thread "Craft Scheduler Thread - 6" 
[03:08:06] [Craft Scheduler Thread - 6/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.1.9 generated an exception while executing task 87
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: The permission plotsquared_user_attributes.disabletitles is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599)
	at com.plotsquared.bukkit.object.BukkitPlayer.getAttribute(BukkitPlayer.java:181)
	at com.intellectualcrafters.plot.util.AbstractTitle.sendTitle(AbstractTitle.java:13)
	at com.plotsquared.listener.PlotListener$1.run(PlotListener.java:162)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

```
>ver
[03:10:37 INFO]: This server is running CraftBukkit version git-PaperSpigot-88826e0-9cd1111 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[03:10:37 INFO]: Checking version, please wait...
```

**Comment by MattBDev** [comment]
This issue should be fixed now.
