### ISSUE TITLE
NPEs at plot setowner

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#657]
```
[12:10:53] [Server thread/INFO]: Olaf issued server command: /plot setowner aUser
[12:10:53] [Server thread/WARN]: java.lang.NullPointerException
[12:10:53] [Server thread/WARN]:        at com.intellectualcrafters.plot.object.PlotHandler.setOwner(PlotHandler.java:70)
[12:10:53] [Server thread/WARN]:        at com.intellectualcrafters.plot.object.Plot.setOwner(Plot.java:574)
[12:10:53] [Server thread/WARN]:        at com.intellectualcrafters.plot.commands.SetOwner.onCommand(SetOwner.java:95)
[12:10:53] [Server thread/WARN]:        at com.intellectualcrafters.plot.commands.SetOwner.onCommand(SetOwner.java:1)
[12:10:53] [Server thread/WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.handle(MainCommand.java:429)
[12:10:53] [Server thread/WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:316)
[12:10:53] [Server thread/WARN]:        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:36)
[12:10:53] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:10:53] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:10:53] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[12:10:53] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[12:10:53] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1078)
[12:10:53] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:237)
[12:10:53] [Server thread/WARN]:        at it.mri.mycommand.execute.DispatchCommands.ExecuteCommands(DispatchCommands.java:635)
[12:10:53] [Server thread/WARN]:        at it.mri.mycommand.execute.DispatchCommands.PerformMycmdCommands(DispatchCommands.java:514)
[12:10:53] [Server thread/WARN]:        at it.mri.mycommand.execute.DispatchCommands.ExecuteMyCommandCommands(DispatchCommands.java:202)
[12:10:53] [Server thread/WARN]:        at it.mri.mycommand.listener.PreprocessEvent.onPlayerCommandPreprocess(PreprocessEvent.java:110)
[12:10:53] [Server thread/WARN]:        at sun.reflect.GeneratedMethodAccessor434.invoke(Unknown Source)
[12:10:53] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:10:53] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[12:10:53] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[12:10:53] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:10:53] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[12:10:53] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[12:10:53] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[12:10:53] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[12:10:53] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:10:53] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:10:53] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[12:10:53] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:10:53] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:10:53] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[12:10:53] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[12:10:53] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[12:10:53] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[12:10:53] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[12:10:53] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)
```

Another try:
```
[12:11:00] [Server thread/INFO]: Olaf issued server command: /plot setowner aUser
[12:11:00] [Server thread/WARN]: java.lang.NullPointerException
[12:11:00] [Server thread/WARN]:        at com.intellectualcrafters.plot.object.PlotHandler.setOwner(PlotHandler.java:70)
[12:11:00] [Server thread/WARN]:        at com.intellectualcrafters.plot.object.Plot.setOwner(Plot.java:574)
[12:11:00] [Server thread/WARN]:        at com.intellectualcrafters.plot.commands.SetOwner.onCommand(SetOwner.java:95)
[12:11:00] [Server thread/WARN]:        at com.intellectualcrafters.plot.commands.SetOwner.onCommand(SetOwner.java:1)
[12:11:00] [Server thread/WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.handle(MainCommand.java:429)
[12:11:00] [Server thread/WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:316)
[12:11:00] [Server thread/WARN]:        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:36)
[12:11:00] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:11:00] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:11:00] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[12:11:00] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[12:11:00] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[12:11:00] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:11:00] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:11:00] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[12:11:00] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:11:00] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:11:00] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[12:11:00] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[12:11:00] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[12:11:00] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[12:11:00] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[12:11:00] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)
```

Spigot 1.8.8
Tested with 3.2.6. Will test with 3.2.7 tomorrow.
If this has been fixed already, never mind :)

**Comment by EvilOlaf** [comment]
Epic.
