### ISSUE TITLE
java.lang.ArithmeticException

### ISSUE THREAD

**Issue by Quicksteve** [IntellectualSites/PlotSquared#658]
When plot commands are used, this happens in console:

```
[08:10:30 INFO]: Quicksteve issued server command: /plot list mine 4
[08:10:30 WARN]: java.lang.ArithmeticException
[08:10:30 WARN]: java.lang.ArithmeticException
[08:10:30 WARN]: java.lang.ArithmeticException
[08:10:30 WARN]: java.lang.ArithmeticException
[08:10:30 WARN]: java.lang.ArithmeticException
```

We've used P2 for a long time and we have a lot of plots (a little less than 19000), so I am assuming something in the database got corrupted. This error did occur with stack traces (which I can't find at the moment) and it is happening [here](https://github.com/IntellectualSites/PlotSquared/blob/master/src/main/java/com/intellectualcrafters/plot/database/SQLManager.java#L1301), which seems to be a hard-coded division by 0 error. I am unsure of why this is happening or why a hard-coded division by 0 error is implemented in the code, but I would appreciate any help.

Version:
```
>p2 version
[08:23:49 INFO]: [P2] >> PlotSquared (Version: 3.2.7)
[08:23:49 INFO]: [P2] >> Authors: Citymonstret & Empire92
[08:23:49 INFO]: [P2] >> Wiki: https://github.com/IntellectualCrafters/PlotSquared/wiki
[08:23:49 INFO]: [P2] >> Website: http://plotsquared.com
[08:23:49 INFO]: [P2] >> Newest Version: 3.2.7
```

If needed, I can supply more data.

**Comment by boy0001** [comment]
The full log might be useful (with stacktrace). I forgot about the divide by 0 thing, I had meant to change that to a throw clause. It would occur when the plugin is trying to make changes to a plot that doesn't exist in the database.

The real problem is why listing the plots is causing changes to occur for a plot that doesn't exist in the database. My best guess is some invalid property (plot merging) that the plugin is attempting to fix, but it should print a message when that occurs.

What I can do in the meantime:
 - Make changes to some code that could be related so it checks if the plot exists
 - Catch the exception and don't have the whole command fail.

**Comment by Quicksteve** [comment]
I managed to find a stack trace:

```
[12:27:18 WARN]: java.lang.ArithmeticException: / by zero
[12:27:18 WARN]:        at com.intellectualcrafters.plot.database.SQLManager.getId(SQLManager.java:1301)
[12:27:18 WARN]:        at com.intellectualcrafters.plot.database.SQLManager$21.set(SQLManager.java:1656)
[12:27:18 WARN]:        at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:275)
[12:27:18 WARN]:        at com.intellectualcrafters.plot.database.SQLManager$2.run(SQLManager.java:203)
[12:27:18 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[12:27:18 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[12:27:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:27:18 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[12:27:18 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Quicksteve** [comment]
This is actually getting worse with each minute, console is spamming this error. Would appreciate a quick fix!

**Comment by boy0001** [comment]
the dev build would be here:
https://github.com/IntellectualSites/PlotSquared/blob/master/target/PlotSquared-Bukkit.jar

**Comment by Quicksteve** [comment]
Doesn't fix it.

Our current server log looks like this:

```
[12:17:59 INFO]: Player issued server command: //set 9
[12:17:59 WARN]: java.lang.ArithmeticException
[12:17:59 WARN]: java.lang.ArithmeticException
[12:17:59 WARN]: java.lang.ArithmeticException
[12:17:59 WARN]: java.lang.ArithmeticException
[12:17:59 WARN]: java.lang.ArithmeticException
[12:17:59 WARN]: java.lang.ArithmeticException
[12:17:59 WARN]: java.lang.ArithmeticException
[12:17:59 WARN]: java.lang.ArithmeticException
[12:18:01 INFO]: Player issued server command: //set 1
[12:18:01 WARN]: java.lang.ArithmeticException
[12:18:01 WARN]: java.lang.ArithmeticException
[12:18:01 WARN]: java.lang.ArithmeticException
[12:18:02 WARN]: java.lang.ArithmeticException
[12:18:02 WARN]: java.lang.ArithmeticException
[12:18:02 WARN]: java.lang.ArithmeticException
[12:18:02 WARN]: java.lang.ArithmeticException
[12:18:02 WARN]: java.lang.ArithmeticException
[12:18:02 WARN]: java.lang.ArithmeticException
[12:18:02 WARN]: java.lang.ArithmeticException
[12:18:02 WARN]: java.lang.ArithmeticException
[12:18:02 WARN]: java.lang.ArithmeticException
[12:18:02 WARN]: java.lang.ArithmeticException
[12:18:02 WARN]: java.lang.ArithmeticException
[12:18:05 INFO]: Player issued server command: /pet hide
[12:18:16 INFO]: Player issued server command: /p h 3
[12:18:16 INFO]: Player issued server command: /plot h 3
[12:18:16 WARN]: java.lang.ArithmeticException
[12:18:16 WARN]: java.lang.ArithmeticException
[12:18:16 WARN]: java.lang.ArithmeticException
[12:18:16 WARN]: java.lang.ArithmeticException
[12:18:16 WARN]: java.lang.ArithmeticException
[12:18:19 INFO]: Player issued server command: //set
[12:18:19 WARN]: java.lang.ArithmeticException
[12:18:19 WARN]: java.lang.ArithmeticException
[12:18:19 WARN]: java.lang.ArithmeticException
[12:18:19 WARN]: java.lang.ArithmeticException
[12:18:19 WARN]: java.lang.ArithmeticException
[12:18:19 WARN]: java.lang.ArithmeticException
[12:18:19 WARN]: java.lang.ArithmeticException
[12:18:19 WARN]: java.lang.ArithmeticException
```

I desperately need a fix for this (very desperately)!

**Comment by Quicksteve** [comment]
I uploaded your latest development build and so far I see no exceptions.
