### ISSUE TITLE
Plot Reports not clearing/working properly

### ISSUE THREAD

**Issue by Quicksteve** [IntellectualSites/PlotSquared#668]
Doing /plot inbox:

![](http://i.imgur.com/drJrWIh.png)

1/0... strange.

/plot inbox report:

![](http://i.imgur.com/QmAKrJF.png)

But doing /plot inbox report delete 0:

![](http://i.imgur.com/V151MU3.png)

/plot inbox report delete 1:

![](http://i.imgur.com/5Q3YL2p.png)

/plot inbox report delete 2:

![](http://i.imgur.com/yLY0AF8.png)

However, in console:

```
[07:22:02 WARN]: [PlotSquared] Task #3901910 for PlotSquared v3.2.9 generated an exception
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_66-internal]
        at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_66-internal]
        at com.intellectualcrafters.plot.commands.Inbox$2.run(Inbox.java:159) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-f928e7a-e91aed8]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [server.jar:git-Spigot-f928e7a-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [server.jar:git-Spigot-f928e7a-e91aed8]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
```

After doing any of these, the comment stays in the report inbox and is not removed. /plot inbox report clear reports success, but it didn't actually clear it:

![](http://i.imgur.com/PW3m3Ya.png)

Database:
```
mysql> select * from plot_comments;
+----------+----------+---------+--------+------------+----------------+
| world    | hashcode | comment | inbox  | timestamp  | sender         |
+----------+----------+---------+--------+------------+----------------+
| creative |     9776 | fun     | report | 1444445557 | kittenlover1O1 |
+----------+----------+---------+--------+------------+----------------+
1 row in set (0.00 sec)
```
According to the /plugin version command, I am using version 3.2.9, I downloaded this version from GitHub yesterday though (sha256sum is `3596d2a04bc7c6b5e55aab7e84b44e6953bc21b81232252b8f6301aa91863080`).

**Comment by Quicksteve** [comment]
Not fixed, the /plot inbox report shows the wrong IDs (they start with 0 and are off-by-one).

**Comment by boy0001** [comment]
That was the previous issue. I just checked and it all starts with 1... Are you sure you were using the right version?
