### ISSUE TITLE
UUIDCONVERT ERRORS

### ISSUE THREAD

**Issue by ScuroK** [IntellectualSites/PlotSquared#704]
Send command: p uuidconvert online

[22:34:40 WARN]: Unexpected exception while parsing console command "p uuidconvert online"
org.bukkit.command.CommandException: Unhandled exception executing command 'p' in plugin PlotSquared v3.2.16
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[craftbukkit.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [craftbukkit.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [craftbukkit.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [craftbukkit.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-5f38d38-18fbb24]
at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.ArithmeticException: / by zero
at com.intellectualcrafters.plot.generator.SquarePlotManager.getPlotId(SquarePlotManager.java:124) ~[?:?]
at com.intellectualcrafters.plot.util.MainUtil.getPlotId(MainUtil.java:2321) ~[?:?]
at com.intellectualcrafters.plot.util.MainUtil.getPlotAbs(MainUtil.java:2341) ~[?:?]
at com.intellectualcrafters.plot.util.MainUtil.getPlot(MainUtil.java:651) ~[?:?]
at com.intellectualcrafters.plot.object.ConsolePlayer.teleport(ConsolePlayer.java:86) ~[?:?]
at com.intellectualcrafters.plot.object.ConsolePlayer.getConsole(ConsolePlayer.java:24) ~[?:?]
at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:40) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-5f38d38-18fbb24]
... 8 more

**Comment by boy0001** [comment]
The plot width is 0. Check your settings.yml and correct the value.
