### ISSUE TITLE
[Bug Report] Version 16u2 with plotme 0.16.3

### ISSUE THREAD

**Issue by Narimm** [IntellectualSites/PlotSquared#711]
I am recording this as a Bug because based on the stacktrace I cant see how it isnt (or atleast doesnt get handled) 

we are converting a plotme world to plotsq, it will convert with no errors using sqlite as the db layer but with mysql turned on you get the following stacktrace in the log
```java
PlotMe->PlotSquared: Creating plot DB
21:43:35 [INFO]: PlotMe->PlotSquared: Saving configuration...
21:43:35 [INFO]: ERROR 1:  | com.intellectualcrafters.plot.object.Plot
21:43:35 [INFO]: Batch 2: 1039 | com.intellectualcrafters.plot.object.Plot
21:43:35 [INFO]: PlotMe->PlotSquared: Reloading generator for world: 'plotworld'...
java.sql.SQLException: No value specified for parameter 8
21:43:35 [WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
21:43:35 [WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
21:43:35 [WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
21:43:35 [WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
21:43:35 [WARN]:        at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2558)
21:43:35 [WARN]:        at com.mysql.jdbc.PreparedStatement.addBatch(PreparedStatement.java:1013)
21:43:35 [WARN]:        at com.intellectualcrafters.plot.database.SQLManager.setBulk(SQLManager.java:656)
21:43:35 [WARN]:        at com.intellectualcrafters.plot.database.SQLManager.createPlots(SQLManager.java:611)
21:43:35 [WARN]:        at com.intellectualcrafters.plot.database.SQLManager$5.run(SQLManager.java:414)
21:43:35 [WARN]:        at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:260)
21:43:35 [WARN]:        at com.intellectualcrafters.plot.database.SQLManager$3.run(SQLManager.java:221)
21:43:35 [WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
21:43:35 [WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
21:43:35 [WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
21:43:35 [WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
21:43:35 [WARN]:        at java.lang.Thread.run(Thread.java:745)
21:43:35 [INFO]: ERROR 1:  | com.intellectualcrafters.plot.object.Plot
21:43:35 [INFO]: Batch 2: 1039 | com.intellectualcrafters.plot.object.Plot
21:43:35 [INFO]: PlotMe->PlotSquared: Reloading generator for world: 'plotworld'...
```

**Comment by Narimm** [comment]
It appeared the createPlot prepared statement was causing this exception abased on a missing value....oddly enough I couldnt work out how it could have 8 parameters?

We are processing around 1300 plots.

**Comment by boy0001** [comment]
There are 5 parameters per plot. It does up to 5000 plots per statement, and potentially multiple statements per transaction. The third parameter of the second plot is null, i.e. the plot owner. I've made some changes that should fix this.

It does however look like the fallback method executed, are you able to check if the plots were inserted?
