### ISSUE TITLE
How do you remove/add all from a plot?

### ISSUE THREAD

**Issue by c0wg0d** [IntellectualSites/PlotSquared#721]
I was told in IRC at some point that you could use a star to denote "all" when trusting/untrusting/denying from a plot.  This does not appear to work.  I'm using PlotSquared 3.2.17 on Spigot 1.8.8.

`
[18:52:22 INFO]: MissNinjaCat issued server command: /plot trust *
[18:52:22 WARN]: java.util.ConcurrentModificationException
[18:52:22 WARN]:        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
[18:52:22 WARN]:        at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
[18:52:22 WARN]:        at com.intellectualcrafters.plot.object.Plot.removeMember(Plot.java:1050)
[18:52:22 WARN]:        at com.intellectualcrafters.plot.commands.Trust.onCommand(Trust.java:91)
[18:52:22 WARN]:        at com.intellectualcrafters.plot.commands.Trust.onCommand(Trust.java:1)
[18:52:22 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.handle(MainCommand.java:400)
[18:52:22 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:277)
[18:52:22 WARN]:        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:37)
[18:52:22 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:52:22 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:52:22 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[18:52:22 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[18:52:22 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[18:52:22 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:52:22 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:52:22 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[18:52:22 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:52:22 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:52:22 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[18:52:22 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[18:52:22 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:52:22 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:52:22 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:52:22 WARN]:        at java.lang.Thread.run(Thread.java:745)
`

**Comment by boy0001** [comment]
Already fixed.
