### ISSUE TITLE
Plot clear and delete crashes server

### ISSUE THREAD

**Issue by CaptnSisko** [IntellectualSites/PlotSquared#744]
I recently installed the plugin on my spigot server. When I use /plot clear or /plot delete, my server crashes. Crash error:

[14:56:13] [Server thread/INFO]: Captain_Sisko issued server command: /p clear
[14:56:13] [Server thread/WARN]: [PlotSquared] Task #11894 for PlotSquared v3.2.18 generated an exception
java.lang.NullPointerException
	at net.minecraft.server.v1_8_R2.Chunk.addEntities(Chunk.java:814) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.chunkLoadPostProcess(CraftWorld.java:271) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.regenerateChunk(CraftWorld.java:215) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at com.plotsquared.bukkit.util.BukkitChunkManager.regenerateChunk(BukkitChunkManager.java:84) ~[?:?]
	at com.intellectualcrafters.plot.generator.HybridPlotManager$1.run(HybridPlotManager.java:190) ~[?:?]
	at com.intellectualcrafters.plot.util.ChunkManager$1.run(ChunkManager.java:90) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[14:56:13] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R2.ReportedException: Exception ticking world entities
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:792) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NullPointerException
	at org.spigotmc.ActivationRange.activateChunkEntities(ActivationRange.java:146) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at org.spigotmc.ActivationRange.activateEntities(ActivationRange.java:129) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.World.tickEntities(World.java:1400) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.WorldServer.tickEntities(WorldServer.java:596) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:781) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	... 4 more
[14:56:13] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException
	at org.spigotmc.ActivationRange.activateChunkEntities(ActivationRange.java:146) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at org.spigotmc.ActivationRange.activateEntities(ActivationRange.java:129) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.World.tickEntities(World.java:1400) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.WorldServer.tickEntities(WorldServer.java:596) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:781) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) ~[craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit.jar:git-Spigot-c80bcce-22ee419]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

Plot debug paste: http://hastebin.com/iwuzipekak

Thanks in advance.

**Comment by boy0001** [comment]
Try updating spigot.
