### ISSUE TITLE
Error on startup PlotSquared 3.2.23

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#778]
[01:37:21 WARN]: java.lang.IllegalArgumentException: The permission plotsquared_user_attributes.worldedit is already defined!
[01:37:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:599)
[01:37:21 WARN]:        at com.plotsquared.bukkit.object.BukkitPlayer.getAttribute(BukkitPlayer.java:162)
[01:37:21 WARN]:        at com.plotsquared.bukkit.listeners.PlayerEvents$2.run(PlayerEvents.java:438)
[01:37:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[01:37:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[01:37:21 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[01:37:21 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[01:37:21 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by TheChampTF** [comment]
Can confirm this bug is still on 3.2.24

03.01 23:24:28 [Server] WARN at java.lang.Thread.run(Thread.java:745) 
03.01 23:24:28 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
03.01 23:24:28 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
03.01 23:24:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) 
03.01 23:24:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) 
03.01 23:24:28 [Server] WARN at com.plotsquared.bukkit.listeners.PlayerEvents$2.run(PlayerEvents.java:446) 
03.01 23:24:28 [Server] WARN at com.plotsquared.bukkit.object.BukkitPlayer.getAttribute(BukkitPlayer.java:162) 
03.01 23:24:28 [Server] WARN at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:598) 
03.01 23:24:28 [Server] WARN java.lang.IllegalArgumentException: The permission plotsquared_user_attributes.worldedit is already defined! 
03.01 23:24:28 [Server] WARN at java.lang.Thread.run(Thread.java:745)
03.01 23:24:28 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
03.01 23:24:28 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
03.01 23:24:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) 
03.01 23:24:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) 
03.01 23:24:28 [Server] WARN at com.plotsquared.bukkit.listeners.PlayerEvents$2.run(PlayerEvents.java:446) 
03.01 23:24:28 [Server] WARN at com.plotsquared.bukkit.object.BukkitPlayer.getAttribute(BukkitPlayer.java:162) 
03.01 23:24:28 [Server] WARN at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:598) 
03.01 23:24:28 [Server] WARN java.lang.IllegalArgumentException: The permission plotsquared_user_attributes.worldedit is already defined!

**Comment by manuelgu** [comment]
Open your permission file, search for `plotsquared_user_attributes.worldedit` and remove the permission node.

**Comment by TheChampTF** [comment]
Only one I could find is 'plotsquared_user_attributes.chat'

**Comment by PhanaticD** [comment]
no permission node for that in my file
