### ISSUE TITLE
Road not regenerating correctly

### ISSUE THREAD

**Issue by CaptnSisko** [IntellectualSites/PlotSquared#844]
http://hastebin.com/ayinibukut

I set up plots to be 45x45. I set the roads to have andesite in the middle and polished andesite on the side. I put slabs on the corners. As you can see in my config, I set the walls for both unclaimed and claimed plots to ''. Players cannot edit the polished andesite or the stone slabs. When I claim a plot, then do /plot delete, the polished andesite turns to stone. This also happens with /plot clear.

![Plots](http://i.imgur.com/5DgfacD.png)
This is an image of what I'm talking about. The plot on the left is working. The plot on the right is after /plot claim then /plot delete.

```
[16:42:31 INFO]: Captain_Sisko issued server command: /p claim
[16:42:31 WARN]: java.lang.NullPointerException
[16:42:31 WARN]: at com.intellectualcrafters.plot.generator.ClassicPlotManager.claimPlot(ClassicPlotManager.java:413)
[16:42:31 WARN]: at com.intellectualcrafters.plot.commands.Claim.claimPlot(Claim.java:90)
[16:42:31 WARN]: at com.intellectualcrafters.plot.commands.Claim.onCommand(Claim.java:134)
[16:42:31 WARN]: at com.intellectualcrafters.plot.commands.Claim.onCommand(Claim.java:1)
[16:42:31 WARN]: at com.intellectualcrafters.plot.commands.MainCommand.handle(MainCommand.java:438)
[16:42:31 WARN]: at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:304)
[16:42:31 WARN]: at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:37)
[16:42:31 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:42:31 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:42:31 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[16:42:31 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[16:42:31 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[16:42:31 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:42:31 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:42:31 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:42:31 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[16:42:31 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[16:42:31 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:42:31 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:42:31 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:42:31 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:42:31 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:42:31 WARN]: at java.lang.Thread.run(Thread.java:745)

```

I get this error when do /plot claim. It still works, though. I don't know if this is related.

**Comment by CaptnSisko** [comment]
I changed one of the settings so that the stone turns to polished andesite. Walls/slabs still not working. I would really appreciate a fix for this.
