### ISSUE TITLE
auto-purge issue

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#871]
For a quite long time I have the following messages in my log files:
```
[05:14:55] [Server thread/INFO]: PLOT 734 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 735 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 736 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 737 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 738 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 739 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 745 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 746 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 747 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 748 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 749 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 750 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 751 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 752 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 753 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 754 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 755 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 756 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 757 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 758 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 759 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 760 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 761 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 762 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: PLOT 763 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 744 in `plot_helpers` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 745 in `plot_helpers` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 743 in `plot_helpers` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 734 in `plot_helpers` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 742 in `plot_trusted` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 734 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 735 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 736 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 737 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 738 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 739 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 745 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 746 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 747 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 748 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 749 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 750 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 751 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 752 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 753 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 754 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 755 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 756 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 757 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 758 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 759 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 760 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 761 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 762 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
[05:14:55] [Server thread/INFO]: ENTRY 763 in `plot_settings` does not exist. Create this plot or set `auto-purge: true` in the settings.yml.
```

A while ago I tried to do that and simply added `auto-purge: true` somewhere at the `settings.yml`;
to be exact between `debug: true` and  `mob_pathfinding: true`.

Actually this does not work out very well. This is what I get:

```
[20:25:24] [Server thread/INFO]: Batch 1: 25 | java.lang.Integer
[20:25:24] [Server thread/WARN]: java.sql.BatchUpdateException: Table 'myplotdb.plot' doesn't exist
[20:25:24] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2018)
[20:25:24] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1449)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.setBulk(SQLManager.java:660)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.deleteRows(SQLManager.java:1508)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.getPlots(SQLManager.java:1624)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.DBFunc.getPlots(DBFunc.java:269)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.setupDatabase(PS.java:1559)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:163)
[20:25:24] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:126)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[20:25:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[20:25:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[20:25:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:25:24] [Server thread/INFO]: ERROR 1:  | java.lang.Integer
[20:25:24] [Server thread/INFO]: Batch 2: 25 | java.lang.Integer
[20:25:24] [Server thread/WARN]: java.sql.BatchUpdateException: Table 'myplotdb.plot' doesn't exist
[20:25:24] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2018)
[20:25:24] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1449)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.setBulk(SQLManager.java:703)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.deleteRows(SQLManager.java:1508)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.getPlots(SQLManager.java:1624)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.DBFunc.getPlots(DBFunc.java:269)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.setupDatabase(PS.java:1559)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:163)
[20:25:24] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:126)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[20:25:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[20:25:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[20:25:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:25:24] [Server thread/INFO]: ERROR 2:  | java.lang.Integer
[20:25:24] [Server thread/INFO]: [WARN] Could not bulk save!
[20:25:24] [Server thread/INFO]: Batch 3
[20:25:24] [Server thread/WARN]: java.sql.BatchUpdateException: Table 'myplotdb.plot' doesn't exist
[20:25:24] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2018)
[20:25:24] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1449)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.setBulk(SQLManager.java:723)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.deleteRows(SQLManager.java:1508)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.getPlots(SQLManager.java:1624)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.DBFunc.getPlots(DBFunc.java:269)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.setupDatabase(PS.java:1559)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:163)
[20:25:24] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:126)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[20:25:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[20:25:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[20:25:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:25:24] [Server thread/INFO]: [ERROR] Failed to save all!
[20:25:24] [Server thread/INFO]: Batch 1: 4 | java.lang.Integer
[20:25:24] [Server thread/WARN]: java.sql.BatchUpdateException: Table 'myplotdb.plot_helpers' doesn't exist
[20:25:24] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2018)
[20:25:24] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1449)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.setBulk(SQLManager.java:660)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.deleteRows(SQLManager.java:1508)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.getPlots(SQLManager.java:1675)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.database.DBFunc.getPlots(DBFunc.java:269)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.setupDatabase(PS.java:1559)
[20:25:24] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:163)
[20:25:24] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:126)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[20:25:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[20:25:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[20:25:24] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[20:25:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:25:24] [Server thread/INFO]: ERROR 1:  | java.lang.Integer

I cut the log here as it continous for all mentioned plots above.
``` 

No clue why this should be a database problem as the rest of P^2  works smoothly.
3.2.26

**Comment by MattBDev** [comment]
Can you confirm if it is still an issue in 3.3.1?

**Comment by boy0001** [comment]
Prefix is set in the database config but using SQLite which doesn't have a prefix. To fix this the SQLManager needs to ignore the prefix on SQLite for this method.
