### ISSUE TITLE
SQL error or missing database (Expression tree is too large (maximum depth 1000))

### ISSUE THREAD

**Issue by andris155** [IntellectualSites/PlotSquared#884]
[21:52:30] [Server thread/INFO]: [0;30;1m[[0;33;22mP2[0;30;1m] [0;37;22m/plot purge unknown [21m<world>[m
[21:52:33] [Craft Scheduler Thread - 6/INFO]: [0;30;1m[[0;33;22mP2[0;30;1m] [0;37;22m[0;36;22mSuccessfully purged 2531 plots[m
[21:52:34] [Craft Scheduler Thread - 7/WARN]: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (Expression tree is too large (maximum depth 1000))
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:383)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at org.sqlite.DB.newSQLException(DB.java:387)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at org.sqlite.DB.throwex(DB.java:374)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at org.sqlite.NativeDB.prepare(Native Method)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at org.sqlite.DB.prepare(DB.java:123)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:404)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:399)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at org.sqlite.Conn.prepareStatement(Conn.java:383)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$30.run(SQLManager.java:1962)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:261)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$3.run(SQLManager.java:222)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:52:34] [Craft Scheduler Thread - 7/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:52:34] [Craft Scheduler Thread - 7/INFO]: [0;31;1m[ERROR] FAILED TO PURGE WORLD 'plotworld'![m

**Comment by MattBDev** [comment]
How helpful. Just copy and paste an error and assume we know what version of PlotSquared or Bukkit you are running. :clap:
Please submit following the issue guidelines.
