### ISSUE TITLE
Plot does not exist in database

### ISSUE THREAD

**Issue by rErEaT** [IntellectualSites/PlotSquared#919]
[22:55:13] [Craft Scheduler Thread - 3/WARN]: java.sql.SQLException: Plot does not exist in database
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.getId(SQLManager.java:1415)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$15.set(SQLManager.java:1204)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:294)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$3.run(SQLManager.java:222)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: java.sql.SQLException: Plot does not exist in database
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.getId(SQLManager.java:1415)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$21.set(SQLManager.java:1318)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:294)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$3.run(SQLManager.java:222)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:55:13] [Craft Scheduler Thread - 3/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: java.sql.SQLException: Plot does not exist in database
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.getId(SQLManager.java:1415)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$15.set(SQLManager.java:1204)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:294)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$3.run(SQLManager.java:222)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: java.sql.SQLException: Plot does not exist in database
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.getId(SQLManager.java:1415)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$21.set(SQLManager.java:1318)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:294)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$3.run(SQLManager.java:222)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:57:13] [Craft Scheduler Thread - 3/WARN]: 	at java.lang.Thread.run(Thread.java:745)

This spam my console in version 3.2.26

**Comment by MattBDev** [comment]
@rErEaT if you do not follow the issue template, your future issues will be closed. Please provide a `/plot debugpaste`

**Comment by rErEaT** [comment]
http://hastebin.com/vinetatiju

**Comment by MattBDev** [comment]
PLease try 3.3.1 and let us know if it is happening on that version. If I don't hear from you then I am going to assume it is no longer an issue.
