### ISSUE TITLE
Economy is not working

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#922]
Economy is not working. I get "economy is not enabled" and plot claim does not take money from balance

possibly related to https://github.com/IntellectualSites/PlotSquared/issues/65

Vault 1.5.6
plotsquared 3.2.26 off spigot forums
EssentialsX build 288
CraftBukkit version git-PaperSpigot-440 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

settings: http://hastebin.com/xuxagacibi

notice:

    economy:
      prices:
        merge: 100.0
        sell: 75.0
        claim: 100.0
      use: true

**Comment by PhanaticD** [comment]
If I change Vault to be a hard depend in plugin.yml for plotsquared I get this error on startup

```
[19:58:49] [Server thread/ERROR]: Encountered an unexpected exception
org.bukkit.plugin.UnknownDependencyException: Vault
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:123) ~[patched.jar:git-PaperSpigot-440]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[patched.jar:git-PaperSpigot-440]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:275) ~[patched.jar:git-PaperSpigot-440]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) ~[patched.jar:git-PaperSpigot-440]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) ~[patched.jar:git-PaperSpigot-440]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-440]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

**Comment by PhanaticD** [comment]
If I add 
```
loadbefore: [PlotSquared]
```
to Vaults's plugin.yml the server starts up normally and economy works. 

Obviously this is not an idea solution

**Comment by boy0001** [comment]
```YAML
softdepend: [WorldEdit, BarAPI, CameraAPI, Vault]
```
Is supposed to load vault beforehand. Same behavior as `depend` except it doesn't stop the plugin from starting if it isn't present. I'm inclined to say this is a spigot bug since I see no reason why it would only work in the Vault plugin.yml

**Comment by boy0001** [comment]
Artificially delaying the economy hook should be a workaround.
