### ISSUE TITLE
Plotsquared crash with fastasyncworldedit

### ISSUE THREAD

**Issue by popcorn9499** [IntellectualSites/PlotSquared#927]
There is no debug info cuz the server crashed

The problem is that when i load my server with fastasyncworldedit and plotsquared i get a crash and the error log shows me this

fastayncworldedit crash log
```
[18:47:09] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v1.2.1
[18:47:09] [Server thread/WARN]: java.lang.NullPointerException
[18:47:09] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.getQueue(FaweBukkit.java:137)
[18:47:09] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.<init>(Fawe.java:110)
[18:47:09] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.set(Fawe.java:76)
[18:47:09] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.onEnable(FaweBukkit.java:57)
[18:47:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[18:47:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[18:47:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[18:47:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[18:47:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[18:47:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202)
[18:47:09] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522)
[18:47:09] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

```

plot squared
```
[18:47:14] [Server thread/INFO]: [0;30;1m[[0;33;22mP2[0;30;1m] [0;37;22m [0;33;22mPlotSquared is using online UUIDs[m
[18:47:14] [Server thread/WARN]: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.server.v1_9_R1.World.x(net.minecraft.server.v1_9_R1.BlockPosition)
[18:47:14] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getMethod(ReflectionUtils.java:320)
[18:47:14] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.block.FastQueue_1_8_3.<init>(FastQueue_1_8_3.java:68)
[18:47:14] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.initPlotQueue(BukkitMain.java:371)
[18:47:14] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:259)
[18:47:14] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:81)
[18:47:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[18:47:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[18:47:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[18:47:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[18:47:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[18:47:14] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202)
[18:47:14] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522)
[18:47:14] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[18:47:14] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_9_R1.World.x(net.minecraft.server.v1_9_R1.BlockPosition)
[18:47:14] [Server thread/WARN]: 	at java.lang.Class.getDeclaredMethod(Unknown Source)
[18:47:14] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getMethod(ReflectionUtils.java:317)
[18:47:14] [Server thread/WARN]: 	... 12 more

```

im running spigot version: version 1.9-R0.1-Snapshot
plotsquared version: 3.3.1
fastasyncworldedit version: 3.3.0

**Comment by boy0001** [comment]
> [18:47:09] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v1.2.1

I had the wrong file on spigot :/
Try this: https://www.spigotmc.org/resources/free-fast-async-worldedit-%CE%B2.13932/download?version=72711

**Comment by popcorn9499** [comment]
thx
