### ISSUE TITLE
Exception while running server

### ISSUE THREAD

**Issue by adiantek** [IntellectualSites/PlotSquared#958]
**Debug paste link**:
[15:11:57] [Server thread/INFO]: [P2] Metrics enabled.
[15:11:57] [Server thread/INFO]: [P2]  PlotSquared is using online UUIDs
[15:11:57] [Server thread/WARN]: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.server.v1_7_R4.PacketPlayOutMapChunk.<init>(net.minecraft.server.v1_7_R4.Chunk, boolean, int)
[15:11:57] [Server thread/WARN]:        at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getConstructor(ReflectionUtils.java:352)
[15:11:57] [Server thread/WARN]:        at com.plotsquared.bukkit.util.SendChunk.<init>(SendChunk.java:54)
[15:11:57] [Server thread/WARN]:        at com.plotsquared.bukkit.BukkitMain.initPlotQueue(BukkitMain.java:360)
[15:11:57] [Server thread/WARN]:        at com.intellectualcrafters.plot.PS.<init>(PS.java:207)
[15:11:57] [Server thread/WARN]:        at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:78)
[15:11:57] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[15:11:57] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[15:11:57] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[15:11:57] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[15:11:57] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[15:11:57] [Server thread/WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:170)
[15:11:57] [Server thread/WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494)
[15:11:57] [Server thread/WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[15:11:57] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_7_R4.PacketPlayOutMapChunk.<init>(net.minecraft.server.v1_7_R4.Chunk, boolean, int)
[15:11:57] [Server thread/WARN]:        at java.lang.Class.getConstructor0(Class.java:3082)
[15:11:57] [Server thread/WARN]:        at java.lang.Class.getDeclaredConstructor(Class.java:2178)
[15:11:57] [Server thread/WARN]:        at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getConstructor(ReflectionUtils.java:349)
[15:11:57] [Server thread/WARN]:        ... 12 more
[15:11:57] [Server thread/WARN]: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.server.v1_7_R4.PacketPlayOutMapChunk.<init>(net.minecraft.server.v1_7_R4.Chunk, boolean, int)
[15:11:57] [Server thread/WARN]:        at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getConstructor(ReflectionUtils.java:352)
[15:11:57] [Server thread/WARN]:        at com.plotsquared.bukkit.util.SendChunk.<init>(SendChunk.java:54)
[15:11:57] [Server thread/WARN]:        at com.plotsquared.bukkit.util.block.FastQueue_1_7.<init>(FastQueue_1_7.java:48)
[15:11:57] [Server thread/WARN]:        at com.plotsquared.bukkit.BukkitMain.initPlotQueue(BukkitMain.java:389)
[15:11:57] [Server thread/WARN]:        at com.intellectualcrafters.plot.PS.<init>(PS.java:207)
[15:11:57] [Server thread/WARN]:        at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:78)
[15:11:57] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[15:11:57] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[15:11:57] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[15:11:57] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[15:11:57] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[15:11:57] [Server thread/WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:170)
[15:11:57] [Server thread/WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494)
[15:11:57] [Server thread/WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[15:11:57] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_7_R4.PacketPlayOutMapChunk.<init>(net.minecraft.server.v1_7_R4.Chunk, boolean, int)
[15:11:57] [Server thread/WARN]:        at java.lang.Class.getConstructor0(Class.java:3082)
[15:11:57] [Server thread/WARN]:        at java.lang.Class.getDeclaredConstructor(Class.java:2178)
[15:11:57] [Server thread/WARN]:        at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getConstructor(ReflectionUtils.java:349)
[15:11:57] [Server thread/WARN]:        ... 13 more
[15:11:57] [Server thread/INFO]: [P2] Key: API Location, Value: http://www.intellectualsites.com/minecraft.php
[15:11:57] [Server thread/INFO]: [P2] Key: Kill Road Mobs, Value: false
[15:11:57] [Server thread/INFO]: [P2] Key: Use Metrics, Value: true
[15:11:57] [Server thread/INFO]: [P2] Key: Delete Plots On Ban, Value: false
[15:11:57] [Server thread/INFO]: [P2] Key: DB SQLite Enabled, Value: true
[15:11:57] [Server thread/INFO]: [P2] Key: DB Mysql Enabled, Value: false
[15:11:57] [Server thread/INFO]: [P2] Key: Auto Clear Enabled, Value: true
[15:11:57] [Server thread/INFO]: [P2] Key: Auto Clear Days, Value: 7
[15:11:57] [Server thread/INFO]: [P2] Key: Schematics Save Path, Value: schematics
[15:11:57] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!

**Description of the problem:** PlotSquared doesn't work 100% on PaperSpigot 1.7.10 build 43 (on spigotmc.org is: Tested Minecraft Versions: 1.7 1.8 1.9)

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`: http://hastebin.com/axoyevehoz
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared - yes, lastest version 3.3.1
- [X] Made sure the bug/error isn't caused by any other plugin - I've one pugin PlotSquared

**Comment by MattBDev** [comment]
A debug paste link means that you provide a **LINK** by using the command `/plots debugpaste`

**Comment by EvilOlaf** [comment]
It is included, just look down a bit ^^
Was also wondering that it is so short but it seems like that P^2 is the only plugin installed there.

**Comment by MattBDev** [comment]
I think I remember @boy0001 saying that this might be normal behavior?

**Comment by adiantek** [comment]
I think that exceptions in console is not normal behavior.

**Comment by boy0001** [comment]
No idea what I said in some other context. Anywho the stacktrace is still an error. It gets thrown when the NMS class for mass block changes can't load. Plugin will function, just slower for certain functions.

Need to fix the NMS stuff for 1.7.10.

**Comment by MattBDev** [comment]
@adiantek just because it says on spigotmc.org it was tested on a certain version, doesn't mean it was tested for Derivatives of Spigot. Tested means it is guaranteed to work on Spigot and CraftBukkit.
