### ISSUE TITLE
1.7.10 problem

### ISSUE THREAD

**Issue by AuthMe** [IntellectualSites/PlotSquared#963]
```
[22:26:01] [Server thread/WARN]: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.server.v1_7_R4.PacketPlayOutMapChunk.<init>(net.minecraft.server.v1_7_R4.Chunk, boolean, int)
[22:26:01] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getConstructor(ReflectionUtils.java:352)
[22:26:01] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.SendChunk.<init>(SendChunk.java:54)
[22:26:01] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.initPlotQueue(BukkitMain.java:360)
[22:26:01] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:207)
[22:26:01] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:78)
[22:26:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[22:26:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[22:26:01] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[22:26:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[22:26:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[22:26:01] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:170)
[22:26:01] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494)
[22:26:01] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[22:26:01] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_7_R4.PacketPlayOutMapChunk.<init>(net.minecraft.server.v1_7_R4.Chunk, boolean, int)
[22:26:01] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Unknown Source)
[22:26:01] [Server thread/WARN]: 	at java.lang.Class.getDeclaredConstructor(Unknown Source)
[22:26:01] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getConstructor(ReflectionUtils.java:349)
[22:26:01] [Server thread/WARN]: 	... 12 more
[22:26:01] [Server thread/WARN]: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.server.v1_7_R4.PacketPlayOutMapChunk.<init>(net.minecraft.server.v1_7_R4.Chunk, boolean, int)
[22:26:01] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getConstructor(ReflectionUtils.java:352)
[22:26:01] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.SendChunk.<init>(SendChunk.java:54)
[22:26:01] [Server thread/WARN]: 	at com.plotsquared.bukkit.util.block.FastQueue_1_7.<init>(FastQueue_1_7.java:48)
[22:26:01] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.initPlotQueue(BukkitMain.java:389)
[22:26:01] [Server thread/WARN]: 	at com.intellectualcrafters.plot.PS.<init>(PS.java:207)
[22:26:01] [Server thread/WARN]: 	at com.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:78)
[22:26:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[22:26:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[22:26:01] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[22:26:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[22:26:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[22:26:01] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:170)
[22:26:01] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494)
[22:26:01] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[22:26:01] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_7_R4.PacketPlayOutMapChunk.<init>(net.minecraft.server.v1_7_R4.Chunk, boolean, int)
[22:26:01] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Unknown Source)
[22:26:01] [Server thread/WARN]: 	at java.lang.Class.getDeclaredConstructor(Unknown Source)
[22:26:01] [Server thread/WARN]: 	at com.intellectualcrafters.plot.util.ReflectionUtils$RefClass.getConstructor(ReflectionUtils.java:349)
[22:26:01] [Server thread/WARN]: 	... 13 more
```

I use PlotSquared 3.3.1 on Spigot 1.7.10, a new server without any plugins.

**Comment by MattBDev** [comment]
Did not follow issue template.

**Comment by AuthMe** [comment]
@MattBDev Oh! I'm sorry I forgot this...Has been re-written.

**Comment by MattBDev** [comment]
It is a duplicate anyways. someone reported this earlier.

**Comment by AuthMe** [comment]
@MattBDev YES, I find it.
