### ISSUE TITLE
Plot clear deleting chunks in plots!

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#966]
I compiled the version off gihub march15

plot clear is resetting the chunks to be nothing, including neighbor plots!
screenshot: https://gyazo.com/107dfe46d41fa375ccddf85bccbc08d6

**Comment by PhanaticD** [comment]
this is most likely relevant:

```
[09:13:33] [Server thread/INFO]: [P2] Detected world load for 'plotme_member'
[09:13:33] [Server thread/INFO]: [P2]  - generator: PlotSquared>PlotSquared
[09:13:33] [Server thread/INFO]: [P2]  - plotworld: com.intellectualcrafters.plot.generator.HybridPlotWorld
[09:13:33] [Server thread/INFO]: [P2]  - manager: com.intellectualcrafters.plot.generator.HybridPlotManager
[09:13:33] [Server thread/INFO]: [P2]  - schematic: false
[09:13:33] [Server thread/INFO]: World possibly already loaded: plotme_member
[09:13:33] [Server thread/INFO]: Preparing start region for level 1 (Seed: 876265281970129172)
[09:13:34] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[09:13:34] [Server thread/WARN]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[09:13:34] [Server thread/WARN]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[09:13:34] [Server thread/WARN]:    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:13:34] [Server thread/WARN]:    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityTypes.a(SourceFile:232)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:466)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:415)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:370)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.createWorld(CraftServer.java:953)
[09:13:34] [Server thread/WARN]:    at org.bukkit.Bukkit.createWorld(Bukkit.java:485)
[09:13:34] [Server thread/WARN]:    at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:725)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:309)
[09:13:34] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[09:13:34] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319)
[09:13:34] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:355)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:315)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:405)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:370)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:325)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:564)
[09:13:34] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[09:13:34] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Duplicate id value for 15!
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DataWatcher.register(DataWatcher.java:63)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityOcelot.i(EntityOcelot.java:33)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.Entity.<init>(Entity.java:194)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityLiving.<init>(EntityLiving.java:120)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityInsentient.<init>(EntityInsentient.java:49)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityCreature.<init>(EntityCreature.java:20)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityAgeable.<init>(EntityAgeable.java:39)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityAnimal.<init>(EntityAnimal.java:10)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityTameableAnimal.<init>(SourceFile:30)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityOcelot.<init>(EntityOcelot.java:13)
[09:13:34] [Server thread/WARN]:    ... 34 more
[09:13:34] [Server thread/WARN]: Skipping Entity with id Ozelot
[09:13:34] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[09:13:34] [Server thread/WARN]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[09:13:34] [Server thread/WARN]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[09:13:34] [Server thread/WARN]:    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:13:34] [Server thread/WARN]:    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityTypes.a(SourceFile:232)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:466)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:415)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:370)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.createWorld(CraftServer.java:953)
[09:13:34] [Server thread/WARN]:    at org.bukkit.Bukkit.createWorld(Bukkit.java:485)
[09:13:34] [Server thread/WARN]:    at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:725)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:309)
[09:13:34] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)

```

**Comment by PhanaticD** [comment]
then the generator did not load right or something with this error (causing the issue in the screenshot)

```
[09:13:33] [Server thread/INFO]: [P2] Detected world load for 'plotme_member'
[09:13:33] [Server thread/INFO]: [P2]  - generator: PlotSquared>PlotSquared
[09:13:33] [Server thread/INFO]: [P2]  - plotworld: com.intellectualcrafters.plot.generator.HybridPlotWorld
[09:13:33] [Server thread/INFO]: [P2]  - manager: com.intellectualcrafters.plot.generator.HybridPlotManager
[09:13:33] [Server thread/INFO]: [P2]  - schematic: false
[09:13:33] [Server thread/INFO]: World possibly already loaded: plotme_member
[09:13:33] [Server thread/INFO]: Preparing start region for level 1 (Seed: 876265281970129172)
[09:13:34] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[09:13:34] [Server thread/WARN]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[09:13:34] [Server thread/WARN]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[09:13:34] [Server thread/WARN]:    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:13:34] [Server thread/WARN]:    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityTypes.a(SourceFile:232)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:466)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:415)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:370)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.createWorld(CraftServer.java:953)
[09:13:34] [Server thread/WARN]:    at org.bukkit.Bukkit.createWorld(Bukkit.java:485)
[09:13:34] [Server thread/WARN]:    at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:725)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:309)
[09:13:34] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[09:13:34] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319)
[09:13:34] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:355)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:315)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:405)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:370)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:325)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:564)
[09:13:34] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[09:13:34] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Duplicate id value for 15!
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DataWatcher.register(DataWatcher.java:63)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityOcelot.i(EntityOcelot.java:33)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.Entity.<init>(Entity.java:194)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityLiving.<init>(EntityLiving.java:120)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityInsentient.<init>(EntityInsentient.java:49)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityCreature.<init>(EntityCreature.java:20)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityAgeable.<init>(EntityAgeable.java:39)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityAnimal.<init>(EntityAnimal.java:10)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityTameableAnimal.<init>(SourceFile:30)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityOcelot.<init>(EntityOcelot.java:13)
[09:13:34] [Server thread/WARN]:    ... 34 more
[09:13:34] [Server thread/WARN]: Skipping Entity with id Ozelot
[09:13:34] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[09:13:34] [Server thread/WARN]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[09:13:34] [Server thread/WARN]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[09:13:34] [Server thread/WARN]:    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:13:34] [Server thread/WARN]:    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.EntityTypes.a(SourceFile:232)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:466)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:415)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:370)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[09:13:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125)
[09:13:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.createWorld(CraftServer.java:953)
[09:13:34] [Server thread/WARN]:    at org.bukkit.Bukkit.createWorld(Bukkit.java:485)
[09:13:34] [Server thread/WARN]:    at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:725)
[09:13:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:309)
[09:13:34] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)

```

**Comment by PhanaticD** [comment]
even when those error messages did not appear it is still happening, it was working one minute and then now it is not, no error message. One plot I could clear it and use //regen and the next one over I could not

**Comment by PhanaticD** [comment]
after disabling fast mode it appears to be working, for now at least

**Comment by MattBDev** [comment]
@PhanaticD Can you confirm that disabling fast mode fixed the issue? If you can, it helps  A LOT.

**Comment by PhanaticD** [comment]
okay no it is not fast mode, it works fine after a server restart then randomly breaks over time (thats why i thought that was the fix, because a restart momentarily fixed it)

**Comment by PhanaticD** [comment]
now it looks like this: https://gyazo.com/ed570ac4c09251acd9b39e6e3f3281e1

**Comment by EvilOlaf** [comment]
Seems like only chunk which are not connected to the road are affected?

**Comment by PhanaticD** [comment]
after changing to non-fast mode it looks like that

**Comment by L4BORG** [comment]
So it's the same issue as here https://github.com/IntellectualSites/PlotSquared/issues/953 ?

**Comment by L4BORG** [comment]
Also, do you think that this could be related: http://shrani.si/f/3m/NS/1loSpXZT/untitled.png ? Started happening at about the same time and "plot regenallroads world" just wouldn't fix it... (also I think plot regenallroads world could be bugged since it would say that it's still running... after hours and we're rocking MC-32 with SSDs).

**Comment by JKnetz** [comment]
Same issue here

**Comment by PhanaticD** [comment]
https://gyazo.com/93f848f113f718528d7a63dbb04eae94
this is version compiled off github march 25 right after you pushed that commit "forgot to push this"
with fast-mode false
