### ISSUE TITLE
issue with plot alias

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#967]
```
[01:45:23] [Server thread/INFO]: xIzzux issued server command: /plot alias Aye
[01:45:23] [Craft Scheduler Thread - 0/WARN]: java.sql.BatchUpdateException: Duplicate entry 'Aye' for key 'unique_alias'
[01:45:23] [Craft Scheduler Thread - 0/WARN]:   at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2018)
[01:45:23] [Craft Scheduler Thread - 0/WARN]:   at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1449)
[01:45:23] [Craft Scheduler Thread - 0/WARN]:   at com.intellectualcrafters.plot.database.SQLManager$UniqueStatement.execute(SQLManager.java:372)
[01:45:23] [Craft Scheduler Thread - 0/WARN]:   at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:300)
[01:45:23] [Craft Scheduler Thread - 0/WARN]:   at com.intellectualcrafters.plot.database.SQLManager$3.run(SQLManager.java:222)
[01:45:23] [Craft Scheduler Thread - 0/WARN]:   at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[01:45:23] [Craft Scheduler Thread - 0/WARN]:   at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[01:45:23] [Craft Scheduler Thread - 0/WARN]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[01:45:23] [Craft Scheduler Thread - 0/WARN]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[01:45:23] [Craft Scheduler Thread - 0/WARN]:   at java.lang.Thread.run(Thread.java:745)
```

**Comment by PhanaticD** [comment]
```
[01:45:52] [Craft Scheduler Thread - 0/WARN]: java.sql.BatchUpdateException: Duplicate entry '&c&lI&6&lz&e&lz&a&lu' for key 'unique_alias'
[01:45:52] [Craft Scheduler Thread - 0/WARN]:   at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2018)
[01:45:52] [Craft Scheduler Thread - 0/WARN]:   at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1449)
[01:45:52] [Craft Scheduler Thread - 0/WARN]:   at com.intellectualcrafters.plot.database.SQLManager$UniqueStatement.execute(SQLManager.java:372)
[01:45:52] [Craft Scheduler Thread - 0/WARN]:   at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:300)
[01:45:52] [Craft Scheduler Thread - 0/WARN]:   at com.intellectualcrafters.plot.database.SQLManager$3.run(SQLManager.java:222)
[01:45:52] [Craft Scheduler Thread - 0/WARN]:   at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[01:45:52] [Craft Scheduler Thread - 0/WARN]:   at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[01:45:52] [Craft Scheduler Thread - 0/WARN]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[01:45:52] [Craft Scheduler Thread - 0/WARN]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[01:45:52] [Craft Scheduler Thread - 0/WARN]:   at java.lang.Thread.run(Thread.java:745)

```

**Comment by boy0001** [comment]
Version?
`/plot debugpaste`

**Comment by PhanaticD** [comment]
uhh I compiled it off github March 15

**Comment by boy0001** [comment]
This error would be thrown if someone tries to set the plot to an alias that's already in use.

Fixed for future installations of the plugin. @PhanaticD You will need to modify the table `plot_settings` and remove `alias` as a unique key.
