### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [IntellectualSites/PlotSquared#992]
```
[22:15:53 WARN]: java.lang.NullPointerException
[22:15:53 WARN]:        at com.intellectualcrafters.plot.object.PlotArea.loadDefaultConfiguration(PlotArea.java:238)
[22:15:53 WARN]:        at com.intellectualcrafters.plot.PS.loadWorld(PS.java:1381)
[22:15:53 WARN]:        at com.plotsquared.bukkit.generator.BukkitPlotGenerator.getDefaultPopulators(BukkitPlotGenerator.java:201)
[22:15:53 WARN]:        at net.minecraft.server.v1_9_R1.WorldServer.b(WorldServer.java:112)
[22:15:53 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:268)
[22:15:53 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
[22:15:53 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522)
[22:15:53 WARN]:        at java.lang.Thread.run(Thread.java:745)
[22:15:53 INFO]: Preparing start region for level 0 (Seed: 6398182579961397048)
[22:15:53 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_9_R1.ReportedException: Exception generating new chunk
        at net.minecraft.server.v1_9_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:165) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:134) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:113) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:367) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-604e046-69e196f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ExceptionInInitializerError
        at com.plotsquared.bukkit.generator.BukkitPlotGenerator.generateChunkData(BukkitPlotGenerator.java:233) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:52) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:157) ~[spigot.jar:git-Spigot-604e046-69e196f]
        ... 7 more
Caused by: java.lang.IllegalArgumentException: disabled
        at com.intellectualcrafters.plot.util.TaskManager.runTaskRepeat(TaskManager.java:21) ~[?:?]
        at com.intellectualcrafters.plot.util.SetQueue.<init>(SetQueue.java:19) ~[?:?]
        at com.intellectualcrafters.plot.util.SetQueue.<clinit>(SetQueue.java:10) ~[?:?]
        at com.plotsquared.bukkit.generator.BukkitPlotGenerator.generateChunkData(BukkitPlotGenerator.java:233) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:52) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:157) ~[spigot.jar:git-Spigot-604e046-69e196f]
        ... 7 more
[22:15:53 ERROR]:       Cause of unexpected exception was
java.lang.ExceptionInInitializerError
        at com.plotsquared.bukkit.generator.BukkitPlotGenerator.generateChunkData(BukkitPlotGenerator.java:233) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:52) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:157) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:134) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:113) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:367) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) ~[spigot.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-604e046-69e196f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: disabled
        at com.intellectualcrafters.plot.util.TaskManager.runTaskRepeat(TaskManager.java:21) ~[?:?]
        at com.intellectualcrafters.plot.util.SetQueue.<init>(SetQueue.java:19) ~[?:?]
        at com.intellectualcrafters.plot.util.SetQueue.<clinit>(SetQueue.java:10) ~[?:?]
        ... 10 more
```

**Comment by EvilOlaf** [comment]
`at com.intellectualcrafters.plot.object.PlotArea.loadDefaultConfiguration(PlotArea.java:238)`
just guessing, but did you try to backup your current config (if any) and let P^2 create a new one?

**Comment by QUIQUELHAPPY** [comment]
It was because a mysql database error
